// File: /d/noden/house/pass4.c
// Generated by Roommaker Mon Dec  4 20:59:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("走廊盡頭");
	ob->set_long( @LONG_DESCRIPTION
你現在站在一條陰暗走廊的盡頭，這裡是古屋的二樓，一道木製的樓梯往下通
往一樓，北邊的牆上有一個圓形的窗戶(window)，你似乎聽到南邊有女人在唱歌的
聲音，不過你的理智告訴你這樣的鬼屋裡不會有女人在唱歌，你壯著膽子準備面對
任何奇形怪狀的鬼怪。
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"window" : @LONG_TEXT
從窗子向外望去，一片青翠茂密的森林，幾個孩子在屋後的空地上嘻嘻哈哈地
玩著遊戲....慢著，孩子？....你很快地轉過頭，不再去關心窗外的景色。
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"down" : "/d/noden/house/pass3", 
		"south" : "/d/noden/house/pass5", 
		"west" : "/d/noden/house/bedroom" ]) );
	ob->reset();
}
