// File: /d/noden/house/pass5.c
// Generated by Roommaker Mon Dec  4 21:00:00 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("陰暗走廊");
	ob->set_long( @LONG_DESCRIPTION
你現在走在一條陰暗的走廊中，北邊是走廊的盡頭，你從這裡可以看到一座
通往一樓的樓梯。這裡的地板有些潮溼，你仔細一看，上面竟然有幾個溼淋淋的
小孩子腳印(footprints)，南邊是一間黑黝黝的起居室，隱隱約約傳來一陣女人
輕柔的歌聲，像是在唱著搖籃曲哄孩子睡覺....
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"footprints" : @LONG_TEXT
這些腳印相當小，而且似乎是剛剛走過才留下的，不過這並不是最奇怪的，你
發現腳印的方向是從西邊走向東邊，而你的西邊和東邊都是牆壁....
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"north" : "/d/noden/house/pass4", 
		"south" : "/d/noden/house/living_room" ]) );
	ob->reset();
}
