// File: /d/noden/house/pass1.c
// Generated by Roommaker Mon Dec  4 20:59:19 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("陰暗走廊");
	ob->set_long( @LONG_DESCRIPTION
你現在走在一條陰暗的走廊上，腳下踩著的木板發出「吱嘎」的聲音，似乎只要
稍一用力就會陷下去，兩邊的牆上掛著一些發黃的人物肖像畫(painting)，你看到北
邊走廊的盡頭好像有燈光，不....也許是錯覺吧，這種陰森森的環境特別容易使人產
生不愉快的錯覺。
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"painting" : @LONG_TEXT
東邊的肖像畫是一位穿著華麗的貴婦人，當你注視這幅畫的時候，好像聽到背
後一聲冷笑，你回過頭來，除了西邊那幅威武騎士的肖像畫，什麼也沒有看見。
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"south" : "/d/noden/house/hall", 
		"north" : "/d/noden/house/pass2" ]) );
	ob->set( "objects", ([ 
		"wisp#1" : "/d/noden/house/monster/wisp", 
		"wisp#2" : "/d/noden/house/monster/wisp" ]) );
	ob->reset();
}
