// File: /d/noden/house/pass3.c
// Generated by Roommaker Mon Dec  4 20:59:38 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("走廊盡頭");
	ob->set_long( @LONG_DESCRIPTION
你現在站在一條陰暗走廊的盡頭，北邊是一扇圓形的窗戶(window)，一道木製
樓梯通往古屋的二樓，兩邊的牆上各有一個銅製的燭臺，上面的蠟燭是點著的，不
知道是什麼人留下來的？
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"window" : @LONG_TEXT
你往窗外望去，一片一望無際的碧藍色大海，和屋內陰森森的氣氛簡直有天壤之別
....慢著，你記得進來的時候，北邊應該是一片森林....，你感到一股涼意從腳底
升起....
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"up" : "/d/noden/house/pass4", 
		"south" : "/d/noden/house/pass2", 
		"west" : "/d/noden/house/kitchen" ]) );
	ob->reset();
}
