// File: /d/noden/house/attic.c
// Generated by Roommaker Thu Dec 23 08:06:37 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("閣樓");
	set_long( @LONG_DESCRIPTION
你現在正站在一間小小的閣樓裡，南邊是一個三角形的窗戶(window)，這裡的地上
零零散散地丟了滿地的玩具(toys)，看起來像是小孩子住的地方，不過很奇怪的是，你
看不到這個房間有任何出口，只有地上一個地方用木板(board)釘起來的洞。
LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "c_item_desc", ([ 
		"board" : @LONG_TEXT
這些木板釘得十分倉促，有些板子上釘了十幾根釘子，有些卻還沒有釘牢，似乎
釘這些木板的人受到了什麼驚嚇。
LONG_TEXT
, 
		"toys" : "這些玩具有玩具兵、小木偶、小木劍....你猜住在這裡的大概是位小男孩。\n", 
		"window" : @LONG_TEXT
你從窗戶看出去，只見灰濛濛地一片霧氣，不知道外面是什麼地方，窗戶並沒有
關著，如果你試著爬(climb)出去的話，也許可以離開這個詭異的地方。
LONG_TEXT
 ]) );
	set( "objects", ([ 
		"boy" : "/d/noden/house/monster/boy" ]) );
	reset();
}

void init()
{
   if( this_player() ) this_player()->set_explore("noden#25");
	add_action("do_climb", "climb");
}

int do_climb(string arg)
{
	if( !arg || arg!="window" ) return 0;
   write( "你爬過窗戶，往一片灰濛濛的霧中跳下去....。\n" );
	this_player()->move_player( "/d/noden/house/grave1", "SNEAK" );
    tell_room( this_object(),
       this_player()->query("c_cap_name")+ "爬出窗戶，消失在一片灰濛濛的霧中。\n",
		this_player() );
	return 1;
}
