// File: /d/noden/house/bedroom.c
// Generated by Roommaker Wed Dec 22 22:05:20 1993

#include <mudlib.h>

inherit ROOM;
int diary;

void create()
{
	::create();
   set_short("主臥室");
	set_long( @LONG_DESCRIPTION
你現在來到這棟古屋的主臥室，房間中央一張木製的大床(bed)，床邊有一面巨大
的鏡子(mirror)，北邊似乎原來有一扇窗戶，但是屋子的主人用磚塊把窗戶封死了
，你覺得這裡的氣氛和其他地方有點不同，但是到底哪裡不同一時也說不上來。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"bed" : @LONG_TEXT
這是一張看起來頗大的雙人床，床單上繡著一朵朵紅色的花....啊....是許多
血跡！
LONG_TEXT
, 
		"mirror" : "你注視這鏡子中自己的影子一會兒，並沒有看到任何預期中的可怕景象。\n" ]) );
	set( "exits", ([ 
		"east" : "/d/noden/house/pass4" ]) );
	set( "objects", ([
		"harold" : "/d/noden/house/monster/ghost_harold" ]) );
	set( "search_desc", ([
		"bed" : "@@search_bed" ]) );
	reset();
}

void reset()
{
        ::reset();
        diary = 1;
}

string search_bed()
{
	object obj;

   if( !diary ) return "你找了又找，並沒有發現任何東西。\n";
	obj = new( "/d/noden/house/obj/diary" );
	obj->move( this_object() );
	diary = 0;
   return  "你在床底下發現了一本老舊的日記！\n";
}
