// File: /d/noden/house/cellar1.c
// Generated by Roommaker Sat Dec 25 21:46:11 1993

#include <mudlib.h>

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
   set_short("地下室");
	set_long( @LONG_DESCRIPTION
你現在來到一個陰暗的地下室，潮溼的空氣中似乎還帶著一絲絲酒味，也許這
裡是屋子主人儲藏酒類的地窖，角落裡一個幾乎腐蝕斷裂的木梯通往一樓的客廳。
LONG_DESCRIPTION
	);

	set( "exits", ([ 
		"south" : "/d/noden/house/cellar2", 
		"up" : "/d/noden/house/hall" ]) );
	create_door( "south", "north", ([
		"keyword" : ({ "wooden door", "door" }),
		"name" : "wooden door",
		"c_name" : "木門",
		"c_desc" : "一扇很普通的木門",
		"status" : "locked",
		"lock" : "GHOST_HAROLD_CELLAR"
	]) );
	reset();
}
