// File: /d/noden/house/cellar2.c
// Generated by Roommaker Sat Dec 25 21:51:33 1993

#include <mudlib.h>

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
   set_short("酒窖");
	set_long( @LONG_DESCRIPTION
你現在正位於一間陰暗的酒窖中，這間酒窖堆滿了許多酒桶(barrels)和一箱箱
的酒瓶(bottles)，所有的酒類都按照年份分門別類堆放在架子上，這裡原來的主人
必定是位酒類的專家，這裡沒有任何窗戶，可是不知道從哪裡來的風一陣陣地吹得
你感覺涼颼颼的....
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"bottles" : @LONG_TEXT
這些酒瓶大部分都是空的，有些酒瓶裡面裝著的好像不是酒，是因為幾十年
來的溼氣所積的水。
LONG_TEXT
, 
		"barrels" : @LONG_TEXT
這些酒桶都用泥土封住，以免地下室的溼氣影響酒的品質，算一算這裡的酒桶
一共有將近三十個，裡面到底還有沒有酒從外面看不出來....
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/house/cellar1" ]) );
	set( "objects", ([
           "bravar" : "/d/noden/house/monster/bravar" ]) );
	create_door( "north", "south", ([
		"keyword" : ({ "wooden door", "door" }),
		"name" : "wooden door",
		"c_name" : "木門",
		"c_desc" : "一扇很普通的木門",
		"status" : "locked",
		"lock" : "GHOST_HAROLD_CELLAR"
	]) );
	reset();
}
