// File: /d/noden/house/grave.c
// Generated by Roommaker Wed Dec 22 22:11:10 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("墓園");
	set_long( @LONG_DESCRIPTION
你現在站在一大堆「一望無際」的墓碑(tombstone)中間，四周全是一片灰濛濛
的霧，一股莫名的恐懼襲上你的心頭，這裡是什麼地方？死後的世界？你聽到一陣
低沈的祈禱(pray)聲從四面八方傳來，不過也許是幻覺....
LONG_DESCRIPTION
	);
	set( "light", 1 );
	set( "item_func", ([
		"tombstone" : "look_tombstone" ]) );
	set( "objects", ([
		"variel": "/d/noden/house/monster/ghost_variel" ]) );
	set( "exits", ([
		"north": "/d/noden/house/grave1",
		"south": "/d/noden/house/grave1",
		"east": "/d/noden/house/grave1",
		"west": "/d/noden/house/grave1" ]) );
	reset();
}

void init()
{
	add_action( "do_pray", "pray" );
	add_action( "do_bury", "bury" );
}

void look_tombstone()
{
	write( "上面寫著: "+this_player()->query("c_cap_name") + " 171 年死因不明，葬於此地。\n");
}

int do_pray()
{
	write( 
		"你閉上眼睛開始祈禱....祈禱些什麼呢？....\n");
	tell_room( this_object(), 
		this_player()->query("c_cap_name") + "閉上眼睛開始祈禱....\n",
		this_player() );
	if( random(10)<5 ) {
		// Move silently
		this_player()->move( "/d/noden/house/hall" );
	}
	return 1;
}

int do_bury(string arg)
{
	object obj, ghost;

	if( !arg || arg=="" || !(obj= present( arg, this_player() )) )
		return notify_fail( "埋葬什麼？\n" );
	if( !obj->id("corpse") )
		return notify_fail( 
			"埋葬這種東西對這裡的死者有失尊敬 ....\n");

	write("你挖了一個洞穴，把屍體埋在裡面 ....\n");

	tell_room( this_object(), 
		this_player()->query("c_cap_name") + "挖了一個洞穴，然後把一具屍體埋在裡面。\n",
		this_player() );
	if( obj->id("corpse of Devil boy") ) {
		if ( !this_player()->query_temp("devil_killer")) 
		{ 
		write( @NOT_YET
當你剛把屍體埋好，一個奇怪的聲音從地底傳了出來：「哈哈哈 ～～你的力量
還壓制不住我，休想把我送回地獄去 !!」。一道漆黑的輕煙緩緩的從地底升起
慢慢的飄散在灰濛濛的霧中。你的直覺告訴你：事情並沒有結束。
NOT_YET
		      );
		obj->remove();
		return 1;
		}
		if( (int)this_player()->query_quest_level("cursed_house") < 1 ) {
			this_player()->finish_quest( "cursed_house", 1 );
			write( "[你完成了 Cursed_house 任務，得到 10,000 點經驗]\n");
			this_player()->gain_experience(10000);
		}
		if( ghost= present("ghost of Variel", this_object() ) )
			ghost->quest_finished( this_player() );
	}
	obj->remove();
	return 1;
}
