// File: /d/noden/house/hall.c
// Generated by Roommaker Thu Dec 23 14:40:19 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("大廳");
	set_long( @LONG_DESCRIPTION
你現在站在一間破舊的大廳，發黴的地毯和破爛不堪的傢俱是這個大廳僅剩下
的東西，北邊靠牆的地方有一座古老的掛鐘(clock)，掛鐘旁是一個火爐(fireplace)
，東倒西歪的椅子和散落地面的石塊顯示這裡曾經遭遇一場可怕的破壞，是什麼東西
造成這裡凌亂不堪的景象？
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"clock" : "這座掛鐘正指著十一點四十六分，不過很顯然的，它已經停了幾十年了。\n", 
		"fireplace" : @LONG_TEXT
這個火爐上面積滿了灰塵，不過你發現裡面有幾根燒過的木炭，竟然還是溫熱的
！難道這個地方還有人住嗎？
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/house/pass1", 
		"out" : "/d/noden/16,13.noden" ]) );
	set( "objects", ([ 
		"bill" : "/d/noden/house/monster/ghost_bill" ]) );
   set( "search_desc", ([
                 "fireplace" : "@@search_fireplace" ]) );
	reset();
}

string search_fireplace()
{
   add( "exits", ([
        "down" : "/d/noden/house/cellar1" ]) );
	set( "exit_suppress", ({ "down" }) );
     return "你仔細搜索火爐, 竟然發現一個往下的通道!\n";
}

void reset()
{
   delete( "exits/down" );
   ::reset();
}
