// File: /d/noden/house/kitchen.c
// Generated by Roommaker Wed Dec 22 23:04:53 1993

#include <mudlib.h>

inherit ROOM;
int cookie;

void create()
{
	::create();
   set_short("廚房");
	set_long( @LONG_DESCRIPTION
從這裡的佈置看起來，你大概可以猜出這裡是一間廚房，一些老舊不堪的櫥櫃
(cupboard)和廚房用具散置在房間中，牆角有一個金屬桶子(can)在黑暗中反射著
從你這邊照過去的光線，往東可以回到走廊上。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"cupboard" : @LONG_TEXT
這些櫥櫃有些已經積滿了灰塵，有些卻擦拭得一塵不染，其中一個櫥櫃甚至還
殘留著食物的香味....
LONG_TEXT
, 
		"can" : @LONG_TEXT
這大概是垃圾桶吧....你一邊這樣想著，一邊掀開蓋子，一股幾乎令人窒息的
屍臭味冒了出來，你立刻將蓋子蓋回去。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"east" : "/d/noden/house/pass3" ]) );
	set( "objects", ([ 
		"ham" : "/d/noden/house/monster/ham" ]) );
   set( "search_desc", ([
            "cupboard" :  "@@search_cupboard" ]) );
	reset();
}

void reset()
{
        ::reset();
        cookie = 1;
}

string search_cupboard()
{
        object obj;

   if( !cookie ) return
            "你找了又找，並沒有發現任何東西。\n";
   obj = new( "/d/noden/house/obj/cookie" );
   obj->move( this_object() );
   cookie = 0;
   return "你仔細搜索櫥櫃, 發現了一片餅乾！\n";
}
