// File: /d/noden/house/living_room.c
// Generated by Roommaker Thu Dec 23 07:45:55 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("起居室");
	set_long( @LONG_DESCRIPTION
你現在位於古屋二樓的起居室，這裡的傢俱和其他地方比起來，似乎比較新也
比較完整，一個磚砌的壁爐(fireplace)和幾張長長的沙發(sofa)構成這個房間的主
要裝潢，你腳下所站的地方鋪著一張淡紫色的地毯(carpet)，上面畫著許多詭異的
同心圓，女人唱著搖籃曲的聲音在你身邊回湯著，但是這裡一個人也沒有....。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"sofa" : @LONG_TEXT
形式很舊的沙發，上面積滿了厚厚的灰塵，沙發上似乎有一些血跡，很難想像
這裡曾經發生過什麼樣的慘劇。
LONG_TEXT
, 
		"carpet" : @LONG_TEXT
這張地毯是圓形的，上面畫著一、二、....共十三個同心圓(circle)，你光是看著這
張地毯就覺得一陣頭暈....
LONG_TEXT
, 
		"fireplace" : @LONG_TEXT
這個壁爐裡面打掃得很乾淨，如果是二流的偵探小說，在這樣的壁爐裡面一定會
有一個密道....
LONG_TEXT
, 
		"circle" : @LONG_TEXT
你看著這些同心圓，忽然有個聲音在你耳邊說道: 進去吧(enter)吧，孩子！
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/house/pass5" ]) );
	reset();
}


void init()
{
	add_action( "do_enter", "enter" );
}

int do_enter(string arg)
{
	if( !arg || arg!= "circle" ) return 0;
   write(
		"你一腳踏進同心圓的中心，立刻感到一陣昏昏欲睡的感覺，像是有人在\n"
            "你的耳邊唱著搖籃曲....\n" );
    tell_room( this_object(), 
        this_player()->query("c_cap_name") + "的身影突然變得模糊，然後消失了....\n",
		this_player() );
	this_player()->move_player( "/d/noden/house/attic", "SNEAK" );
	return 1;
}
