// File: /d/noden/house/pass2.c
// Generated by Roommaker Wed Dec 22 15:47:19 1993

#include <mudlib.h>

inherit ROOM;
int face = 1;

void create()
{
	::create();
   set_short("陰暗走廊");
	set_long( @LONG_DESCRIPTION
你現在走在一條陰暗的走廊上，北邊不遠處有一座木梯往上到二樓，兩邊的牆壁
上都有好幾道深深的抓痕(scratch)，走廊往南通往這棟建築的大廳。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"scratch" : @LONG_TEXT
這些抓痕共五條一組，似乎是人類用手抓出來的，但是人類可能有這麼大的力氣
在堅硬的磚牆上抓出這樣的痕跡嗎？你開始想起一些屬於原始恐懼的古老傳說，
狼人？吸血鬼？.....你開始覺得毛骨悚然....
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/house/pass3", 
		"south" : "/d/noden/house/pass1" ]) );
	set( "pre_exit_func", ([
		"north" : "loop_exit" ]) );
	set( "search_desc", ([
		"here" : "@@search_here" ]) );
	reset();
}

int loop_exit()
{
	if( face || present( "face", this_object() ) ) {
            write(
			"你向前走了幾步，一股奇怪的感覺告訴你: 地板在動！\n"
                    "莫名的恐懼使你停了下來。\n" );
		return 1;
	} else return 0;
}

string search_here()
{
	object obj;

    if( !face || present("face", this_object()) ) return
            "你找了又找，並沒有發現任何東西。\n";
	obj = new( "/d/noden/house/monster/face" );
	obj->move( this_object() );
	face = 0;
   return "你仔細搜索這裡的牆壁，猛然看到一張女人的臉從牆壁伸出來！\n";
}
