// File: /open/polo/noden/farwind/bazz4.c
// Generated by Roommaker Mon Nov  6 06:27:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("微風路");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在微風路上。廣場位於你的西方不遠處，微風路向東
一路延伸下去，北邊的建築物目前正在出租。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/cemetery", 
		"west" : "/d/noden/farwind/bazz3" ]) );
	ob->reset();
}
