// File: /open/polo/noden/farwind/bazz3.c
// Generated by Roommaker Mon Nov  6 06:27:47 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("微風路");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在微風路上。廣場位於你的西方不遠處，微風路向東
一路延伸下去，北邊的建築物是小頑皮茹比開的寵物店。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/bazz4", 
		"north" : "/d/noden/farwind/pet_shop", 
		"west" : "/d/noden/farwind/bazz2" ]) );
	ob->reset();
}
