// File: /open/polo/noden/farwind/bridge.c
// Generated by Roommaker Mon Nov  6 06:27:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石板橋上");
	ob->set_long( @LONG_DESCRIPTION
你現在站在一座石板橋上，橋下潺潺的流水聲伴隨著鵝群的叫聲，與眼前
的景色構成一幅鄉村田園的風景畫。在你的東邊是遠風鎮的西門，往西南走過
石板橋可以離開遠風鎮，西北邊一條沿著河邊的小路通往河流北岸的草原。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "exits", ([ 
		"northwest" : "/d/noden/13,5.noden", 
		"southwest" : "/d/noden/13,7.noden", 
		"east" : "/d/noden/farwind/w_gate" ]) );
	ob->reset();
}
