// File: /open/polo/noden/farwind/cellar5.c
// Generated by Roommaker Mon Nov  6 06:28:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞");
	ob->set_long( @LONG_DESCRIPTION
這的地洞相當窄小，東邊的出口似乎有微微的亮光。你可以聞到一陣腐臭的
味道來自西邊。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/cellar6.c", 
		"west" : "/d/noden/farwind/cellar4.c" ]) );
	ob->set( "objects", ([ 
		"grey rat" : "/d/noden/farwind/monster/grey_rat" ]) );
	ob->reset();
}
