// File: /open/polo/noden/farwind/cellar3.c
// Generated by Roommaker Mon Nov  6 06:28:22 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞");
	ob->set_long( @LONG_DESCRIPTION
這個地洞十分窄小，牆壁上有一條條的抓痕。往西邊的通路地勢稍微高了一點
，東南方傳來一陣陣腐臭的味道。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/noden/farwind/cellar2.c", 
		"southeast" : "/d/noden/farwind/cellar4.c" ]) );
	ob->reset();
}
