// File: /d/noden/farwind/cellar6.c
// Generated by Roommaker Sun Nov 19 20:22:37 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞");
	ob->set_long( @LONG_DESCRIPTION
你很驚訝地發現地洞中會有這樣的一個地方，牆壁上掛著一盞油燈(lamp)，
桌子、椅子、床鋪應有盡有，這裡的主人身材似乎不是很高，因為大部分的傢俱
都很小，你注意到地洞的一角有一個木箱(chest)。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/noden/farwind/cellar5.c" ]) );
	ob->set( "item_desc", ([ 
		"lamp" : "這盞油燈雖然看起來十分粗糙，但是它點亮了這整個房間。\n", 
		"chest" : @LONG_TEXT
 一個相當精緻的木箱子，雖然很髒，但仍然看得出來是裝貴重物品
的箱子。你走近一看，裡面是空的。
LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"giant rat" : "/d/noden/farwind/monster/giant_rat" ]) );
	ob->reset();
}
