// File: /open/polo/noden/farwind/cellar4.c
// Generated by Roommaker Mon Nov  6 06:28:28 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞");
	ob->set_long( @LONG_DESCRIPTION
你現在站在一個陰暗的地洞中，地洞中央有一個小小的水池(pool)，一些
食物的殘渣、碎屑散落在水池周圍。這些殘渣散發出一股腐敗發黴的味道，使
你不由自主地掩住鼻子。西北邊有一條通道。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"northwest" : "/d/noden/farwind/cellar3.c", 
		"east" : "/d/noden/farwind/cellar5.c", 
		"south" : "/d/noden/farwind/tunnel1.c" ]) );
	ob->set( "item_desc", ([ 
		"pool" : @LONG_TEXT
與其說這是個水池，不如說它是個水窪。水面上飄著一些吃剩的食物
殘渣，你發現水裡面好像有一些東西在遊動，不過水實在太髒了，你
無法確定是什麼東西。
LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"grey rat" : "/d/noden/farwind/monster/grey_rat", 
		"fat rat" : "/d/noden/farwind/monster/fat_rat" ]) );
	ob->reset();
}
