// File: /open/polo/noden/farwind/clearing.c
// Generated by Roommaker Mon Nov  6 06:28:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("河邊空地");
	ob->set_long( @LONG_DESCRIPTION
這裡是遠風鎮西南邊的一塊空地，你的南邊和北邊都是河水，西邊被一道
圍牆擋住，也許是東北邊那戶人家的院子，河邊有許多卵石(pebble)和雜草，
你看到西邊的圍牆邊好像有一堆魚網(net)。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/farwind/path1" ]) );
	ob->set( "item_desc", ([ 
		"net" : "一堆糾結在一起的魚網，看來大概不能用了。\n", 
		"pebble" : "這些石頭大部分是圓的，顯然是河流從上游衝下來的。\n" ]) );
	ob->set( "objects", ([ 
		"toad" : "/d/noden/farwind/monster/toad" ]) );
	ob->reset();
}
