// File: /open/polo/noden/farwind/ebazz.c
// Generated by Roommaker Mon Nov  6 06:28:58 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("微風路");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在微風路上。廣場位於你的東方不遠處，微風路向西
一路延伸下去, 北邊的建築物是本鎮的教堂, 南邊是一間結婚禮服用
品店。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/square", 
		"south" : "/d/noden/farwind/wedding_store", 
		"west" : "/d/noden/farwind/wbazz", 
		"north" : "/d/noden/farwind/church" ]) );
	ob->reset();
}
