// File: /open/polo/noden/farwind/nmain.c
// Generated by Roommaker Mon Nov  6 06:29:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遠風鎮大街");
	ob->set_long( @LONG_DESCRIPTION
這裡是遠風鎮大街的盡頭，從這裡往北出遠風鎮是一條鄉村小路，銜接鎮外
北方的田野，在你的東邊是遠風鎮的銀行。西邊的建築是法院，不過入口並不在
這邊。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/bank", 
		"north" : "/d/noden/14,5.noden", 
		"south" : "/d/noden/farwind/square" ]) );
	ob->set( "objects", ([ 
		"vendor" : "/obj/vendor" ]) );
	ob->reset();
}
