// File: /open/polo/noden/farwind/path1.c
// Generated by Roommaker Mon Nov  6 06:29:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小路");
	ob->set_long( @LONG_DESCRIPTION
這是一條鄉村中常見的小路，遠風鎮在冒險者公會成立之前，最多
的路就是像這樣的小路。在你的北邊不遠處是遠風鎮的西門，東邊一棟
房子看起來像是有錢人的住宅，門口還有一座小噴泉(fountain)，裡面
不知道住著哪位大人物。從這裡往南是河邊的一塊空地，往西似乎有一
條石階往下通往河床邊上。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/farwind/clearing", 
		"north" : "/d/noden/farwind/w_gate", 
		"west" : "/d/noden/farwind/steps" ]) );
	ob->set( "item_desc", ([ 
		"fountain" : @LONG_TEXT
這個噴泉造型相當優美，一個小天使的雕像站在池子中央，手中的瓶子不斷湧出清 涼的泉水，你發現水池中有一點一點亮晶晶的東西，莫非這噴泉是許願池？
LONG_TEXT
 ]) );
	ob->reset();
}
