// File: /open/polo/noden/farwind/riverbend.c
// Generated by Roommaker Mon Nov  6 06:29:27 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("河邊空地");
	ob->set_long( @LONG_DESCRIPTION
這裡是河邊的一塊空地，在你北邊的橋底下是一個養鵝場，養鵝的人用
圍籬圍出一小片空地關住鵝群，但是你發現圍籬似乎有破洞，因為你現在所
站的地方地上就掉了幾根鵝毛(feather)，還有一些鵝的腳印。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "exits", ([ 
		"south" : "/d/noden/farwind/steps" ]) );
	ob->set( "objects", ([ 
		"goose 3" : "/d/noden/farwind/monster/goose" ]) );
	ob->reset();
}
