// File: /d/noden/farwind/smain2.c
// Generated by Roommaker Sun Nov 19 20:19:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遠風鎮大街");
	ob->set_long( @LONG_DESCRIPTION
你現在走在遠風鎮的大街上。北邊不遠處是遠風鎮的中心廣場，在你
的東側有一間鐵匠鋪，西邊則是郵局。往南走你可以離開遠風鎮，進入諾
頓王國的野外區域。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/smithy", 
		"west" : "/d/noden/farwind/post_office", 
		"north" : "/d/noden/farwind/smain", 
		"south" : "/d/noden/14,7.noden" ]) );
	ob->reset();
}
