// File: /open/polo/noden/farwind/smain.c
// Generated by Roommaker Mon Nov  6 06:29:35 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遠風鎮大街");
	ob->set_long( @LONG_DESCRIPTION
你現在走在遠風鎮的大街上。北邊是遠風鎮的中心廣場，在你的東側有
一間商店，西邊的建築則是鼎鼎大名的冒險者公會。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "doors", ([ 
		"west" : ([ 
			"name" : "oak door", 
			"linked" : "east", 
			"keyword" : ({ 
				"oak door", 
				"door" }), 
			"c_desc" : "一扇結實厚重的橡木門", 
			"status" : "open", 
			"c_name" : "橡木門" ]) ]) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/shop", 
		"north" : "/d/noden/farwind/square", 
		"west" : "/d/adventurer/hall/adv_guild", 
		"south" : "/d/noden/farwind/smain2" ]) );
	ob->set( "item_desc", ([ 
		"west door" : "一扇結實厚重的橡木門，它現在是開著的。\n" ]) );
	ob->reset();
}
