// File: /open/polo/noden/farwind/steps.c
// Generated by Roommaker Mon Nov  6 06:29:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石階小道");
	ob->set_long( @LONG_DESCRIPTION
你走在一條由青石板所鋪成的石階小徑上，石階上佈滿青苔。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/path1", 
		"north" : "/d/noden/farwind/riverbend" ]) );
	ob->reset();
}
