// File: /open/polo/noden/farwind/tunnel2.c
// Generated by Roommaker Mon Nov  6 06:29:58 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞通道");
	ob->set_long( @LONG_DESCRIPTION
這裡是一條陰暗狹窄的地底通道，北邊傳來陣陣腐敗食物的臭味，你可以
感覺到這裡的空氣越來越潮溼，滴水的聲音自西南方傳來。除了滴水聲外，你
好像還可以聽到一些「咕咕 ... 」的低鳴，說不定那裡有什麼可怕的怪物。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"southwest" : "/d/noden/farwind/tunnel3.c", 
		"north" : "/d/noden/farwind/tunnel1.c" ]) );
	ob->reset();
}
