// File: /open/polo/noden/farwind/tunnel1.c
// Generated by Roommaker Mon Nov  6 06:29:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞通道");
	ob->set_long( @LONG_DESCRIPTION
這裡是一條陰暗狹窄的通道, 空氣中瀰漫著一股腐敗食物的臭味, 你
隱隱約約地聽到南邊的地洞傳來滴水的聲音。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/noden/farwind/tunnel2.c", 
		"north" : "/d/noden/farwind/cellar4.c" ]) );
	ob->reset();
}
