// File: /open/polo/noden/farwind/wbazz.c
// Generated by Roommaker Mon Nov  6 06:30:12 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("微風路");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在微風路上。往東走你可以到達遠風鎮的廣場，在你
的北邊是一家新開的藥材店，南邊的牆上似乎寫了一些字(writing)
，往西走是遠風鎮的西門。
LONG_DESCRIPTION
	);

	ob->set_outside( "farwind" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/farwind/ebazz", 
		"west" : "/d/noden/farwind/w_gate", 
		"north" : "/d/noden/farwind/apoth" ]) );
	ob->set( "item_desc", ([ 
		"writing" : "「住在這間屋子裡的人是大混蛋，生的兒子沒屁眼！」\n" ]) );
	ob->reset();
}
