// File: /d/noden/bluesand/alley1.c
// Generated by Roommaker Mon Dec  4 22:07:25 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小巷");
	ob->set_long( @LONG_DESCRIPTION
這裡是一條小巷子，左右的房屋雖然簡陋，但是都頗為整潔，在這裡
有一塊告示板(board)，上面貼了幾則啟事。
LONG_DESCRIPTION
	);

	ob->set_outside( "bluesand" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/bluesand/port_r0.c", 
		"south" : "/d/noden/bluesand/alley2.c" ]) );
	ob->reset();
}
