// File: /d/noden/bluesand/beach1.c
// Generated by Roommaker Mon Dec  4 22:08:46 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("白沙灘");
	ob->set_long( @LONG_DESCRIPTION
這裡是一片白色的沙灘，潔白的海沙中夾雜著一點點藍色的小石子，你走近
一看，發現它們都是透明的！也許這些石子是珍貴的寶石也不一定。沙灘向西方
繼續延伸，東邊是一些建築物，一望無際的大海就在你的北方。
LONG_DESCRIPTION
	);

	ob->set_outside( "bluesand" );
	ob->set( "exits", ([ 
		"west" : "/d/noden/bluesand/beach", 
		"south" : "/d/noden/bluesand/port_r2" ]) );
	ob->set( "objects", ([ 
		"crab#1" : "/d/noden/bluesand/monster/crab", 
		"crab#2" : "/d/noden/bluesand/monster/crab" ]) );
	ob->reset();
}
