// File: /d/noden/bluesand/office.c
// Generated by Roommaker Mon Dec  4 22:09:19 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("辦公室");
	ob->set_long( @LONG_DESCRIPTION
這裡是藍沙港警備隊長的辦公室，潔淨的窗戶映著窗外藍白夾雜的沙灘，使你
不得不羨慕起他們的工作環境，往北是一條建有許多倉庫的街道，警備隊常常在這
裡巡邏，以免小偷肆虐。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/noden/bluesand/street2" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"captain" : "/d/noden/bluesand/monster/captain" ]) );
	ob->reset();
}
