// File: /d/noden/bluesand/port_r0.c
// Generated by Roommaker Mon Dec  4 22:09:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("港灣路");
	ob->set_long( @LONG_DESCRIPTION
你現在走在藍沙港主要的街道，港灣路上。藍沙港是個很新的港
口城市，由於和東方大國的貿易，你可以看到不少帶有東方色彩的建
築物。往東你可以遠遠望見藍沙港的碼頭，北邊是一家商店，如果你
往西走，就可以離開藍沙港。
LONG_DESCRIPTION
	);

	ob->set_outside( "bluesand" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/bluesand/port_r1.c", 
		"west" : "/d/noden/16,10.noden", 
		"north" : "/d/noden/bluesand/shop.c", 
		"south" : "/d/noden/bluesand/alley1.c" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
