// File: /d/noden/bluesand/port_r2.c
// Generated by Roommaker Mon Dec  4 22:10:28 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("港灣路");
	ob->set_long( @LONG_DESCRIPTION
你現在走在藍沙港主要的街道，港灣路上。在你的北邊是一片白中帶
著淡藍色細點的沙灘，東邊是藍沙港的碼頭，往南走通往一條寬敞卻不熱
鬧的街道。
LONG_DESCRIPTION
	);

	ob->set_outside( "bluesand" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/bluesand/jetty", 
		"south" : "/d/noden/bluesand/street1.c", 
		"west" : "/d/noden/bluesand/port_r1.c", 
		"north" : "/d/noden/bluesand/beach1" ]) );
	ob->reset();
}
