// File: /d/noden/bluesand/port_r1.c
// Generated by Roommaker Mon Dec  4 22:09:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("港灣路");
	ob->set_long( @LONG_DESCRIPTION
你現在走在藍沙港主要的街道，港灣路上。在你的北邊是一片白中帶
著淡藍色細點的沙灘，碼頭在你的東方不遠處，南邊是藍沙港著名的水手
酒吧，順著港灣路向西可以離開藍沙港。
LONG_DESCRIPTION
	);

	ob->set_outside( "bluesand" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/bluesand/port_r2.c", 
		"south" : "/d/noden/bluesand/pub.c", 
		"west" : "/d/noden/bluesand/port_r0.c", 
		"north" : "/d/noden/bluesand/beach" ]) );
	ob->reset();
}
