// File: /d/noden/bluesand/pub.c
// Generated by Roommaker Mon Dec  4 22:10:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("水手酒吧");
	ob->set_long( @LONG_DESCRIPTION
這裡是藍沙港名聞遐邇的水手酒吧，據說來到藍沙港的人如果沒有到
水手酒吧喝一杯「血瑪莉」，就不算來過藍沙港。這裡的酒類種類之多足
以傲視整個諾頓王國，你可以「翻一翻」櫃檯上的酒單(menu)就知道。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"menu" : "酒單上寫著: 未成年不宜。\n" ]) );
	ob->set( "exits", ([ 
		"north" : "/d/noden/bluesand/port_r1.c" ]) );
	ob->set( "objects", ([ 
		"sailor 2" : "/d/noden/bluesand/monster/sailor", 
		"patrick" : "/d/noden/bluesand/monster/patrick" ]) );
	ob->reset();
}
