// File: /d/noden/bluesand/street2.c
// Generated by Roommaker Mon Dec  4 22:11:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("街道");
	ob->set_long( @LONG_DESCRIPTION
你走在一條寬敞的街道上，左右兩旁都是商人們存放貨物的倉庫。街道
上行人不多，但是每個人的衣飾看起來都頗為高貴。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/noden/bluesand/street1.c", 
		"south" : "/d/noden/bluesand/office" ]) );
	ob->reset();
}
