// File: /d/noden/bluesand/ship.c
// Generated by Roommaker Mon Dec  6 21:56:37 1993
// translation done 2-24-94 -Elon.

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("比亞藍號");
	set_long( @LONG_DESCRIPTION
你現在站在一艘老舊的船上，破舊的船體和處處可見的蛀蟲孔洞顯示這
艘船早已不適合再航行於波濤洶湧的海上了，你發現只要稍微動一動，船身
就會發出嘎嘎的聲音，碼頭就在你的西邊不遠處，趁著船還沒有解體之前趕
快遊(swim)回去吧。
LONG_DESCRIPTION
	);

	set( "objects", ([ "zombie": "/d/noden/bluesand/monster/zombie" ]) );
	reset();
}

void init()
{
	if( this_player() && present("zombie", this_object()) )
        this_player()->set_explore("noden#12");
	add_action( "do_swim", "swim" );
}

int do_swim(string arg)
{
	if( arg && arg!="back" )
            return notify_fail( "你想游到哪裡去？\n" );
    write( "你循原來上船的地方游回碼頭。\n" );
	this_player()->move_player("/d/noden/bluesand/jetty", "SNEAK" );
    tell_room( "/d/noden/bluesand/jetty",
            this_player()->query("c_cap_name") + "溼漉漉地從海中爬上碼頭。\n",
		this_player() );
	return 1;
}
