// File: /d/noden/bluesand/shop.c
// Generated by Roommaker Wed Nov 17 14:37:26 1993
 
#include <mudlib.h>
#include <money.h>
 
inherit SHOP;
 
void create()
{
	::create();
   set_short("商店");
	set_long( @LONG_DESCRIPTION
這裡是藍沙港的商店，由於貿易的發達，藍沙港常常充滿各種珍奇寶物
與各式商品，因此你可以用最低廉的價格買到其他地方難得一見的貨物，你
看到牆上貼了一張紙(paper)，上面寫著: 「貨真價實、童叟無欺」。
LONG_DESCRIPTION
);
 
	set( "exits", ([
		"south" : "/d/noden/bluesand/port_r0.c"
	]) );
	set( "c_item_desc", ([
		"paper" :
			"「貨真價實、童叟無欺」....旁邊一行小字: 貨物售出，蓋不退貨。\n",
	]) );
	set( "light", 1 );
	set( "objects", ([
		"trashcan": "/obj/trashcan",
		"shopkeeper": "/d/noden/bluesand/monster/shopkeeper" ]) );
	reset();
	replace_program(SHOP);
}
