// File: /d/noden/bluesand/temple.c
// Generated by Roommaker Thu Nov 11 12:45:35 1993
// translation done 2-24-94 -Elon ANOTHER hard one?!?! *sigh*

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("土地廟");
	set_long( @LONG_DESCRIPTION
這是一間土地公廟，土地公是東方大國的人們普遍信仰的地方性神明，他
會保佑虔誠的信徒們多福多壽，並且避免地方上受到妖魔鬼怪的侵擾。你可以
看到一尊泥塑的土地公雕像(statue)坐在檀木桌上，嫋嫋的香菸襯托初一種寧
靜祥和的氣氛。
LONG_DESCRIPTION
	);
    set("c_item_desc",(["statue":@C_LONG
這是一尊很和藹的土地公雕像，一位白髮蒼蒼的老公公，佇著長長的柺杖，
笑咪咪的好像正在看望的他的土地。或許土地公是東方大陸的普遍信仰，但
在諾頓卻很少見，你走上前去仔細打量他，卻發現他十分乾淨，好像有人每
天摸(touch)他似的。
C_LONG
		]) );
		
	set( "objects", ([
		"samurai": "/d/noden/bluesand/monster/samurai" ]) );
	set( "exits", ([
		"north" : "/d/noden/bluesand/alley2.c"
	]) );
	reset();
}
void init()
{
	add_action("do_touch","touch");
}

int do_touch(string arg)
{
	if ( !arg || arg != "statue" )
		return notify_fail("你要摸什麼？\n");
	if ( !query("exits/west") ) {
	write(@LONG
你伸出手摸摸土地公像，發現他有點搖晃，好像可以轉動，於是你順手
一轉，突然「拍」的一聲，西邊出現一道暗門。
LONG
	);
	tell_room(this_object(),this_player()->query("c_name")+
	"伸手摸摸土地公像，突然「拍」的一聲，西邊出現了一道暗門。\n",
	this_player() );
	set("exits/west","/d/thief/hall/thief_guild");
   this_player()->set_explore("noden#36");
	return 1;
	}
	write("你摸摸土地公像，順手轉了他一下，把暗門關起來。\n");
	delete("exits/west");
	return 1;
}

void reset()
{
	delete("exits/west");
	::reset();
}
