// File: /d/noden/moyada/mainrd7.c
// Generated by Roommaker Mon Dec  4 20:22:47 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("主要道路");
	ob->set_long( @LONG_DESCRIPTION
你現在站在摩亞達城的主要道路，它大多以破碎的磚石所鋪制而成
。往北就是城中心的著名的圓形廣場與「銀色之塔」。你可以看到一棟
很高且散發銀色光芒的圓形建築物。西邊有一片沙地。
LONG_DESCRIPTION
	);

	ob->set_outside( "moyada" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/moyada/rndplza.c", 
		"west" : "/d/noden/moyada/sand_square.c", 
		"south" : "/d/noden/moyada/mainrd3.c" ]) );
	ob->set( "objects", ([ 
		"ant worker" : "/d/noden/moyada/monster/ant_worker", 
		"ant killer" : "/d/noden/moyada/monster/ant_killer" ]) );
	ob->reset();
}
