// File: /d/noden/moyada/mainrd3.c
// Generated by Roommaker Mon Dec  4 20:21:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("死胡同");
	ob->set_long( @LONG_DESCRIPTION
你現在站在摩亞達城的主要道路的盡頭，地面乃是以破碎的磚石所
鋪制而成。往北是城中心的圓形廣場與「銀色之塔」。
LONG_DESCRIPTION
	);

	ob->set_outside( "moyada" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/moyada/mainrd7.c" ]) );
	ob->reset();
}
