// File: /d/noden/moyada/mainrd6.c
// Generated by Roommaker Mon Dec  4 20:22:25 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("主要道路");
	ob->set_long( @LONG_DESCRIPTION
你現在站在摩亞達城的主要道路，它大多以破碎的磚石所鋪制而成
。往東就是城中心的著名的圓形廣場與「銀色之塔」。你可以看到一棟
很高且散發銀色光芒的圓形建築物。北邊有一棟古老的建築，生鏽的鐵
門半掩著，破裂的窗戶和高大的藤蔓，散發一股陰森的氣息，像極了電
影中的鬼屋，你的本能告訴你最好別進去。
LONG_DESCRIPTION
	);

	ob->set_outside( "moyada" );
	ob->set( "exits", ([ 
		"east" : "/d/noden/moyada/rndplza.c", 
		"north" : "/d/noden/moyada/old_house/entrance.c", 
		"west" : "/d/noden/moyada/mainrd2.c" ]) );
	ob->set( "objects", ([ 
		"balbal#2" : "/d/noden/moyada/monster/balbal", 
		"balbal#1" : "/d/noden/moyada/monster/balbal" ]) );
	ob->reset();
}
