// File: /d/noden/moyada/mainrd4.c
// Generated by Roommaker Mon Dec  4 20:22:03 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("死胡同");
	ob->set_long( @LONG_DESCRIPTION
你現在站在摩亞達城的主要道路的盡頭，地面多以破碎的磚石所鋪制
而成。往西是城中心的圓形廣場與「銀色之塔」。
LONG_DESCRIPTION
	);

	ob->set_outside( "moyada" );
	ob->set( "exits", ([ 
		"west" : "/d/noden/moyada/mainrd8.c" ]) );
	ob->set( "objects", ([ 
		"worker#1" : "/d/noden/moyada/monster/worker" ]) );
	ob->reset();
}
