// File: /d/noden/moyada/mainrd2.c
// Generated by Roommaker Mon Dec  4 20:21:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("主要道路");
	ob->set_long( @LONG_DESCRIPTION
你現在站在摩亞達城的主要道路，它大多以破碎的磚石所鋪制而成
。往東是城中心的圓形廣場與「銀色之塔」，向西則是西門。
LONG_DESCRIPTION
	);

	ob->set_outside( "moyada" );
	ob->set( "exits", ([ 
		"east" : "/d/noden/moyada/mainrd6", 
		"west" : "/d/noden/moyada/w_gate" ]) );
	ob->reset();
}
