// File: /d/noden/moyada/mainrd5.c
// Generated by Roommaker Mon Dec  4 20:22:17 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("主要道路");
	ob->set_long( @LONG_DESCRIPTION
你現在站在摩亞達城的主要道路，它大多以破碎的磚石所鋪制而成
。往南就是城中心的著名的圓形廣場與「銀色之塔」。你可以看到一棟
很高且散發銀色光芒的圓形建築物。
LONG_DESCRIPTION
	);

	ob->set_outside( "moyada" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/moyada/mainrd1.c", 
		"south" : "/d/noden/moyada/rndplza.c" ]) );
	ob->reset();
}
