// File: /d/eastland/liang_shan/bed1.c
// Generated by Roommaker Tue Nov 21 15:59:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("支援部隊預備室");
	ob->set_long( @LONG_DESCRIPTION
這裡是梁山泊的支援部隊預備室，由於這裡距城牆非常近，若有敵人來襲
可迅速投入戰場，現在這裡駐紮的是魯智深的步兵第一隊。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/liang_shan/path3" ]) );
	ob->set( "objects", ([ 
		"wu" : "/d/eastland/liang_shan/monster/monk", 
		"bandit" : "/d/eastland/liang_shan/monster/small_bandit" ]) );
	ob->reset();
}
