// File: /d/eastland/liang_shan/bed7.c
// Generated by Roommaker Tue Nov 21 15:59:26 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("城牆守備指揮室");
	ob->set_long( @LONG_DESCRIPTION
這裡是梁山泊的城牆守備指揮室，在這裡，城牆指揮官下達所有的作戰指
令，目前的指揮官是花榮。房間中間放著一張會議桌，是守備評議開會時
所使用的，牆上有一張城牆的守備兵力圖。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"southup" : "/d/eastland/liang_shan/wall7" ]) );
	ob->set( "objects", ([ 
		"bandit" : "/d/eastland/liang_shan/monster/small_bandit", 
		"hua" : "/d/eastland/liang_shan/monster/hua" ]) );
	ob->reset();
}
