// File: /d/eastland/liang_shan/bed5.c
// Generated by Roommaker Tue Nov 21 16:02:32 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("軍官休息室");
	ob->set_long( @LONG_DESCRIPTION
這裡是梁山泊典型的軍官休息室，隱藏在四棵巨大的松樹後面，
由窗內看去，則是一片水洗般的青翠，觸目皆是綠意盎然的樹木，有
如一個大盆景擺在你面前，空氣中有著高山的冷冽，但卻使人倍感舒
暢。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/liang_shan/yard1" ]) );
	ob->reset();
}
