// File: /d/eastland/liang_shan/bed2.c
// Generated by Roommaker Tue Nov 21 16:01:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("兵營");
	ob->set_long( @LONG_DESCRIPTION
這裡是梁山泊的部隊休息室，如果強盜們沒有排到偵察或防禦的任務時，
這裡就是他們過夜休息的地方，如果沒有特殊事情的話，部隊的指揮官也
會在這裡休息，直到換防或輪休。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/liang_shan/plaza4" ]) );
	ob->set( "objects", ([ 
		"bandit" : "/d/eastland/liang_shan/monster/small_bandit", 
		"shu" : "/d/eastland/liang_shan/monster/shu" ]) );
	ob->reset();
}
// File: /d/eastland/liang_shan/bed2.c
// Generated by Roommaker Tue Nov 21 16:01:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("兵營");
	ob->set_long( @LONG_DESCRIPTION
這裡是梁山泊的部隊休息室，如果強盜們沒有排到偵察或防禦的任務時，
這裡就是他們過夜休息的地方，如果沒有特殊事情的話，部隊的指揮官也
會在這裡休息，直到換防或輪休。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/liang_shan/plaza4" ]) );
	ob->set( "objects", ([ 
		"bandit" : "/d/eastland/liang_shan/monster/small_bandit", 
		"shu" : "/d/eastland/liang_shan/monster/shu" ]) );
	ob->reset();
}
// File: /d/eastland/liang_shan/bed2.c
// Generated by Roommaker Tue Nov 21 22:11:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("兵營");
	ob->set_long( @LONG_DESCRIPTION
這裡是梁山泊的部隊休息室，如果強盜們沒有排到偵察或防禦的任務時，
這裡就是他們過夜休息的地方，如果沒有特殊事情的話，部隊的指揮官也
會在這裡休息，直到換防或輪休。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/liang_shan/plaza4" ]) );
	ob->set( "objects", ([ 
		"bandit" : "/d/eastland/liang_shan/monster/small_bandit", 
		"shu" : "/d/eastland/liang_shan/monster/shu" ]) );
	ob->reset();
}
