// File: /d/eastland/liang_shan/cave4.c
// Generated by Roommaker Tue Nov 21 16:02:44 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
洞穴的四周插滿了火把，照的四周一片明亮，許多山賊在洞穴裡鑽來鑽去，只有
少數人注意到你的進入而投以懷疑的目光。你似乎聽到了一股潺潺的水流聲。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"eastdown" : "/d/eastland/liang_shan/cave3", 
		"westup" : "/d/eastland/liang_shan/cave5" ]) );
	ob->reset();
}
