// File: /d/eastland/liang_shan/cave3.c
// Generated by Roommaker Tue Nov 21 16:02:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
曲折的洞穴，到了這裡忽然開展，這山腹中竟然是空的，巨大的穹頂，離地至少
數十丈，方圓不知幾百丈，一個人站在這頭呼喊，等他閉上嘴時聲音才傳得到另一頭
。西邊的山壁上，有一條向上的小通路，東邊有一條通道，似乎能夠離開這些洞穴，
剛剛聽到的水聲，你發現是由東面傳來的。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"southup" : "/d/eastland/liang_shan/cave2", 
		"east" : "/d/eastland/liang_shan/water_castle", 
		"westup" : "/d/eastland/liang_shan/cave4" ]) );
	ob->set( "objects", ([ 
		"chi" : "/d/eastland/liang_shan/monster/seven" ]) );
	ob->reset();
}
