// File: /d/eastland/liang_shan/cave1.c
// Generated by Roommaker Tue Nov 21 16:03:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
你進入了城牆上的洞穴，洞穴的四周插滿了火把，照的四周一片明亮，許多山賊
在洞穴裡鑽來鑽去，只有少數人注意到你的進入而投以懷疑的目光。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"northdown" : "/d/eastland/liang_shan/cave2", 
		"out" : "/d/eastland/liang_shan/wall5" ]) );
	ob->reset();
}
