// File: /d/eastland/liang_shan/down_hall.c
// Generated by Roommaker Tue Nov 21 16:04:06 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("忠義廳樓下");
	ob->set_long( @LONG_DESCRIPTION
這是一間小小的房間，四壁都是堅硬的石壁，東北方似乎有個小門。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"up" : "/d/eastland/liang_shan/hall", 
		"northeast" : "/d/eastland/liang_shan/jail2" ]) );
	ob->reset();
}
