// File: /d/eastland/liang_shan/drug.c
// Generated by Roommaker Tue Nov 21 15:58:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("藥店");
	ob->set_long( @LONG_DESCRIPTION
你一走進這家藥鋪，一股強烈的藥味差點讓你窒息，這裡是梁山唯一一家藥
鋪兼醫院，是神醫安道全所開設的，這裡所賣的藥材與價錢以及醫療的費用全都
寫在一張掛在壁上的價格表(list)上，往東走可回到天王大道。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"list" : @LONG_TEXT
--------------------------------------------------
販賣藥材:                    販賣價格:           
    金創藥(plaster):              6 金幣         
    雲南白藥(white plaster):     15 金幣         
    天香斷續膏(spicy plaster):   25 金幣         
    天山雪蓮(snow_lily):        450 金幣         
                                                 
服務項目:                    所需價格:         
    基本醫療(heal):             3 金幣/HP      
    快速止血(clot):            15 金幣/次      
    中和毒性(cure):            25 金幣/次      
    體質改善(sick):            30 金幣/次      
    包紮傷口(bandage):          6 金幣/次      
                                               
                              若醫師不在請稍待片刻
--------------------------------------------------
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/liang_shan/path1" ]) );
	ob->set( "objects", ([ 
		"doctor" : "/d/eastland/liang_shan/monster/doctor" ]) );
	ob->reset();
}
