// File: /d/eastland/liang_shan/dryroom.c
// Generated by Roommaker Tue Nov 21 16:00:09 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("曬衣場");
	ob->set_long( @LONG_DESCRIPTION
這裡是梁山泊的曬衣場，在洗衣房洗乾淨的衣服，全部送到這邊
處理．輕風吹來，翻飛的衣物，讓你覺得頭暈目眩．一個少年正在此
忙碌的工作．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/liang_shan/washroom" ]) );
	ob->set( "objects", ([ 
		"da" : "/d/eastland/liang_shan/monster/washer" ]) );
	ob->reset();
}
