// File: /d/eastland/liang_shan/gate1.c
// Generated by Roommaker Tue Nov 21 15:57:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("梁山泊大寨門");
	ob->set_long( @LONG_DESCRIPTION
這就是聞名的梁山泊，經過數百年不斷的整修擴建，已由原先的規模，
發展成一個極其壯觀的山寨；它目前的規模，簡直已和一個小小的城市差
不多了．從門外看來，那以巨大的樹幹編成的木柵，漆黑的大寨門，在風
中獵獵飄揚的五色旗幟，如果你沒有相當的實力和勇氣，最好還是別和他
們為敵．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"eastup" : "/d/eastland/liang_shan/wall1", 
		"north" : "/d/eastland/liang_shan/path1", 
		"south" : "/d/eastland/liang_shan/out1", 
		"westup" : "/d/eastland/liang_shan/wall6" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"bandit2" : "/d/eastland/liang_shan/monster/small_bandit", 
		"bandit1" : "/d/eastland/liang_shan/monster/small_bandit", 
		"huan" : "/d/eastland/liang_shan/monster/huan" ]) );
	ob->reset();
}
