// File: /d/eastland/liang_shan/path6.c
// Generated by Roommaker Tue Nov 21 16:02:19 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("迴廊");
	ob->set_long( @LONG_DESCRIPTION
你穿過了聚義廳，來到了一條小小的迴廊，迴廊建築的很精巧，也很壯
麗，硃紅的闌干，一塵不染的地板，迴廊外的假山流水，茂林修竹，你不禁
暗暗讚歎設計者的匠心與保養的辛勞，往北通往一片樹林，往東往西都
可通至庭院。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/liang_shan/yard1", 
		"west" : "/d/eastland/liang_shan/yard2", 
		"north" : "/d/eastland/liang_shan/path7", 
		"south" : "/d/eastland/liang_shan/chuyi_hall" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
