// File: /d/eastland/liang_shan/path8.c
// Generated by Roommaker Tue Nov 21 16:03:39 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林間小徑");
	ob->set_long( @LONG_DESCRIPTION
你來到了一條寂靜的林間小徑，空氣中夾帶著山區特有的料峭氣息，
往下俯瞰，可以看到梁山泊在樹影中若隱若現，人間的喧鬧，已隔的好遠
好遠，唯一的聲響，恐怕只有流竄在松林間的些許微風，和腳步踏在落葉
松針上的輕響。不! 仔細聽聽，北邊似乎傳來一陣鼾聲?
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/liang_shan/gate2", 
		"south" : "/d/eastland/liang_shan/path7" ]) );
	ob->set( "objects", ([ 
		"squirrel1" : "/d/eastland/monster/squirrel" ]) );
	ob->reset();
}
