// File: /d/eastland/liang_shan/path4.c
// Generated by Roommaker Tue Nov 21 16:01:18 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("走道");
	ob->set_long( @LONG_DESCRIPTION
這是一條小小的街道，雖然沒有天王大道那麼寬大，但它聯接了寨牆和
大演武場，提供了快速支援防衛的功能．北邊有一個類似碉堡的建築，南方
有一個小門，傳來陣陣菜餚的香氣，使你覺得飢腸轆轆．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"eastup" : "/d/eastland/liang_shan/wall5", 
		"north" : "/d/eastland/liang_shan/bed4", 
		"south" : "/d/eastland/liang_shan/kitchen", 
		"west" : "/d/eastland/liang_shan/plaza3" ]) );
	ob->set( "objects", ([ 
		"captain" : "/d/eastland/liang_shan/monster/captain" ]) );
	ob->reset();
}
