// File: /d/eastland/liang_shan/path1.c
// Generated by Roommaker Tue Nov 21 15:57:42 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("天王大道");
	ob->set_long( @LONG_DESCRIPTION
這山寨內竟有一條街道，一條以整齊的青石板鋪成的，不折不扣的街
道．據說是為了紀念第一代老大: 托塔天王晁蓋而命名．街道兩旁，有各
色各樣的店鋪，每一間店鋪的生意都好的很，只不過店鋪的門外，都沒有
招牌．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/liang_shan/horseroom", 
		"west" : "/d/eastland/liang_shan/drug", 
		"north" : "/d/eastland/liang_shan/path2", 
		"south" : "/d/eastland/liang_shan/gate1" ]) );
	ob->reset();
}
