// File: /d/eastland/liang_shan/plaza2.c
// Generated by Roommaker Tue Nov 21 16:00:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大演武場");
	ob->set_long( @LONG_DESCRIPTION
這裡是山寨內著名的大演武場，平時陘l頭林沖都在此操練部下．訓
練格鬥或陣法．場邊放著各式的兵刃，發出森森的寒光．如果你想加入山
寨，最快的方法就是在此顯顯身手．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/liang_shan/plaza3", 
		"west" : "/d/eastland/liang_shan/flag" ]) );
	ob->reset();
}
