// File: /d/eastland/liang_shan/room1.c
// Generated by Roommaker Wed Nov 22 16:46:55 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小書房");
	ob->set_long( @LONG_DESCRIPTION
這是一間小小的書房，窗明幾靜，樸素典雅，一張古意盎然的紅木書桌，
吸引了你的目光，上面擺著一座小小的香爐，幾本善本書整齊的堆放在桌上
，可見主人相當的愛惜書本。一個男子正坐在桌前，神情肅穆，若有所思。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/liang_shan/yard3" ]) );
	ob->reset();
}
