// File: /d/eastland/liang_shan/wall8.c
// Generated by Roommaker Tue Nov 21 15:59:32 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("柵上小路");
	ob->set_long( @LONG_DESCRIPTION
這裡是梁山泊大寨上的小路，是為了防禦攻擊而建造的．但近幾年
來，已沒有人敢來侵犯了．站在這裡，遠方的風景一覽無遺．小路在這
裡轉向北方，角落有一個木梯可通往上方的□望臺．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/liang_shan/wall7", 
		"up" : "/d/eastland/liang_shan/tower1", 
		"north" : "/d/eastland/liang_shan/wall9" ]) );
	ob->reset();
}
