// File: /d/eastland/liang_shan/wall4.c
// Generated by Roommaker Tue Nov 21 16:01:32 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("柵上小路");
	ob->set_long( @LONG_DESCRIPTION
這裡是梁山泊大寨上的小路，是為了防禦攻擊而建造的．但近幾年
來，已沒有人敢來侵犯了．站在這裡，遠方的風景一覽無遺．小路繼續
向南北方延伸．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/liang_shan/wall3", 
		"north" : "/d/eastland/liang_shan/wall5" ]) );
	ob->reset();
}
