// File: /d/eastland/liang_shan/wall7.c
// Generated by Roommaker Tue Nov 21 15:59:15 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("柵上小路");
	ob->set_long( @LONG_DESCRIPTION
這裡是梁山泊大寨上的小路，是為了防禦攻擊而建造的．但近幾年
來，已沒有人敢來侵犯了．站在這裡，遠方的風景一覽無遺．小路繼續
向東西方延伸．北邊有條往下的土梯通往一棟碉堡型的建築物．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"northdown" : "/d/eastland/liang_shan/bed7", 
		"east" : "/d/eastland/liang_shan/wall6", 
		"west" : "/d/eastland/liang_shan/wall8" ]) );
	ob->reset();
}
