// File: /d/eastland/liang_shan/wall5.c
// Generated by Roommaker Tue Nov 21 16:01:30 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("柵上小路");
	ob->set_long( @LONG_DESCRIPTION
這裡是梁山泊大寨上的小路，是為了防禦攻擊而建造的．但近幾年
來，已沒有人敢來侵犯了．站在這裡，遠方的風景一覽無遺．木柵在這
裡連接到山壁上，小路也只通到此處．北邊山壁上有一個洞，隱隱傳出
人聲．除此之外，你注意到從寨內有條小路可通往此地．
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"westdown" : "/d/eastland/liang_shan/path4", 
		"cave" : "/d/eastland/liang_shan/cave1", 
		"south" : "/d/eastland/liang_shan/wall4" ]) );
	ob->set( "objects", ([ 
		"shei2" : "/d/eastland/liang_shan/monster/shei2" ]) );
	ob->reset();
}
