// File: /d/eastland/liang_shan/water_castle.c
// Generated by Roommaker Tue Nov 21 16:03:15 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("水寨");
	ob->set_long( @LONG_DESCRIPTION
這是一個小小的碉堡，裡面駐紮著梁山泊的水軍。這碉堡地勢非常險要
三面環山，一面臨水，碉堡內有秘道可通往山壁內。臨水的一面停滿了大大
小小的戰船，隨時都可以開入湖中作戰。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/liang_shan/lake/beach1", 
		"west" : "/d/eastland/liang_shan/cave3" ]) );
	ob->set( "objects", ([ 
		"wu" : "/d/eastland/liang_shan/monster/five", 
		"bandit" : "/d/eastland/liang_shan/monster/small_bandit", 
		"zhan" : "/d/eastland/liang_shan/monster/zhan2" ]) );
	ob->reset();
}
