// File: /d/deathland/troll/cave_04.c
// Generated by Roommaker Thu Nov 23 20:55:34 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("充滿了血跡和骨骸的洞");
	ob->set_long( @LONG_DESCRIPTION
整個洞穴到處都是山頂巨人的腳印,明顯地你已經進入了山頂巨人的領域
了.血跡及骨骸到處可見,山頂巨人的嗜血和好殺由此可知.對於一個沒有勇氣
的人來講,沿著原路退回將是活命的唯一機會.
這裡似乎讓你覺得有一種非常奇怪的力量存在著,但是你無法確定到底那是什
麼??
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"northeast" : "/d/deathland/troll/cave_02" ]) );
	ob->set( "objects", ([ 
		"troll#2" : "/d/deathland/monster/troll01", 
		"troll#1" : "/d/deathland/monster/troll01" ]) );
	ob->reset();
}
