// File: /d/deathland/troll/cave_05.c
// Generated by Roommaker Thu Nov 23 20:54:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("充滿了血跡和骨骸的洞");
	ob->set_long( @LONG_DESCRIPTION
整個洞穴到處都是山頂巨人的腳印,明顯地你已經進入了山頂巨人的領域
了.血跡及骨骸到處可見,山頂巨人的嗜血和好殺由此可知.對於一個沒有勇氣
的人來講,沿著原路退回將是活命的唯一機會.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/troll/cave_03", 
		"west" : "/d/deathland/troll/cave_06" ]) );
	ob->reset();
}
