// File: /d/eastland/goomay/bath_shop.c
// Generated by Roommaker Thu Nov 23 18:34:57 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("熱海澡堂");
	ob->set_long( @LONG_DESCRIPTION
你走進一家大澡堂，前面有兩個門，分別是男女浴池。能夠在一天的疲勞
奔波後好好的洗個澡，找個老師傅按摩按摩，這真是人生的一大享受。一個年
老的婆婆正倚在門前的凳子上看著你，要進去當然要先付錢嘍，還有 ! 可別
「不小心」走錯門了。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/goomay/row15" ]) );
	ob->set( "objects", ([ 
		"woman1" : "/d/eastland/goomay/monster/mama" ]) );
	ob->reset();
}
