// File: /d/eastland/goomay/big_house.c
// Generated by Roommaker Thu Nov 23 18:43:23 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("四不欺大院");
	ob->set_long( @LONG_DESCRIPTION
這是著名的清官－文若水告老還鄉後所建的大宅，它是一棟佔地極廣的
四合院，因為懸在門口的皇上御筆－「四不欺」而得名，原來的名字反而被
淡忘了。文若水雖然已經去世，但是他的子孫仍然極為顯赫，所以四不欺大
院在本鎮是權勢與富貴的表徵，東西方各有一個門，南方是正廳大門，不過
這些門都緊閉著。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/goomay/row21" ]) );
	ob->set( "objects", ([ 
		"guard2" : "/d/eastland/goomay/monster/bodyguard", 
		"guard1" : "/d/eastland/goomay/monster/bodyguard", 
		"dog" : "/d/eastland/goomay/monster/watchdog" ]) );
	ob->reset();
}
