// File: /d/eastland/goomay/cellar4.c
// Generated by Roommaker Thu Nov 23 18:49:37 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞");
	ob->set_long( @LONG_DESCRIPTION
你現在正位於一條陰暗的通道中，這條通道佈滿了許多煤渣和炭灰，
通道兩旁則規律地排放著一方方的火爐和鐵□，這裡原來可能是一個鐵工廠
，從地面上四處亂丟的工具看來，原來的主人似乎走的很匆忙，而且再也不
曾回來過。這裡沒有任何的透氣孔，可是不知道從哪裡來的熱風一陣陣地吹
來，你感覺燠熱難耐....
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/eastland/goomay/cellar5", 
		"west" : "/d/eastland/goomay/cellar2" ]) );
	ob->set( "objects", ([ 
		"rat2" : "/d/eastland/goomay/monster/salamander", 
		"rat1" : "/d/eastland/goomay/monster/salamander" ]) );
	ob->reset();
}
