// File: /d/eastland/goomay/col25.c
// Generated by Roommaker Thu Nov 23 18:47:14 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("青石板大道");
	ob->set_long( @LONG_DESCRIPTION
你走在古梅鎮平坦的青石大道上，光潔的青石板顯示著這個城鎮的活力，
伴隨在你身邊的是小販的吆喝聲、馬車的轔轔聲還有偶而疾馳而過的駿馬，那
是一些想要成名的武林人物，古梅鎮的西風塵沙中，不知埋葬了多少年輕人的
夢想。街道向南北方延伸而去，東方是威遠鏢局，現在鏢局門口正貼了一張告
示(sign)，許多年輕人擠在那裡看。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/goomay/wei_yuan", 
		"south" : "/d/eastland/goomay/col24", 
		"north" : "/d/eastland/goomay/col26" ]) );
	ob->set( "item_desc", ([ 
		"sign" : @LONG_TEXT
你用力的擠到人群前面，拼命用肘捶柺子把那些白眼打成黑眼...
最後，你終於看到那張告示，上面寫著：

		誠    徵    鏢    師

	自即日起，本局歡迎各方勇士加入我們的行列，待優，
	食宿包理，每月分紅，論功\\\升遷，意者請內洽。

LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"carter3" : "/d/eastland/goomay/monster/carter", 
		"carter2" : "/d/eastland/goomay/monster/carter", 
		"carter1" : "/d/eastland/goomay/monster/carter" ]) );
	ob->reset();
}
