// File: /d/eastland/goomay/coliseum2.c
// Generated by Roommaker Thu Nov 23 18:50:31 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("武鬥大會會場");
	ob->set_long( @LONG_DESCRIPTION
這裡是每一個習武者夢寐以求的成名地－天下第一武鬥大會會場。在這片
寬闊的會場上，到處擺著刀劍架子和箭垛把子，此刻正有許多人在場上，或練
功或決鬥，拳腳聲哀號聲不時傳來，前方有一座柵門，你可以從它離開(leave)
武鬥大會場。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "PK_ZONE", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/goomay/coliseum3", 
		"leave" : "/d/eastland/goomay/row25", 
		"west" : "/d/eastland/goomay/coliseum1", 
		"south" : "/d/eastland/goomay/coliseum5", 
		"north" : "/d/eastland/goomay/coliseum5" ]) );
	ob->reset();
}
