// File: /d/eastland/goomay/doshu_temple.c
// Generated by Roommaker Thu Nov 23 18:38:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("至陽觀");
	ob->set_long( @LONG_DESCRIPTION
你走進一座道觀，這道觀人潮擁擠，顯得香火十分鼎盛，正堂上供奉著降伏
龜蛇二妖的真武大帝，整座堂上雕樑畫棟金碧輝煌，富貴氣十足。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/goomay/doshu_temple2", 
		"south" : "/d/eastland/goomay/row11" ]) );
	ob->set( "objects", ([ 
		"little doshu2" : "/d/eastland/goomay/monster/little_doshu", 
		"little doshu" : "/d/eastland/goomay/monster/little_doshu" ]) );
	ob->reset();
}
