// File: /d/eastland/goomay/entrance.c
// Generated by Roommaker Thu Nov 23 18:45:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("礦坑入口");
	ob->set_long( @LONG_DESCRIPTION
在你面前矗立著一座礦坑，赭紅色的礦石屑隨著礦車的軌跡
散落在地面上，形成一片片紅色的波紋，向西方一座小山似的礦
石堆漾去，礦坑前來往的礦車不斷，坑口還釘了塊木牌(sign)。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/goomay_mine/m_enter", 
		"south" : "/d/eastland/goomay/ruin5" ]) );
	ob->set( "forsy_appear", 0 );
	ob->set( "item_desc", ([ 
		"sign" : @LONG_TEXT
你看了看木牌，原來是一面告示，上面寫著：

    此地為私人產業，非得允許\\\擅入者以盜賊論處 !! 
    任意毀損產業傷害工作人員者，依法送官究辦 !!

					段鐵
LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"guard2" : "/d/eastland/goomay/monster/mine_guard", 
		"guard1" : "/d/eastland/goomay/monster/mine_guard" ]) );
	ob->reset();
}
