// File: /d/eastland/goomay/ghost_house.c
// Generated by Roommaker Thu Nov 23 18:48:00 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("空屋");
	ob->set_long( @LONG_DESCRIPTION
走進這幢空蕩蕩的屋子裡，一陣似有若無的寒氣向你直逼過來。擺設
得錯落有致的傢俱雖然久被塵封，但是從他們的造型和質料上你仍可以想
見原屋主的品味氣度，不知道發生了什麼奇怪的事，使得屋主匆忙離去，
甚至連小偷也絕足不來。你心中升起一陣不祥的預感。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/eastland/goomay/col26" ]) );
	ob->set( "objects", ([ 
		"rat2" : "/d/noden/farwind/monster/rat", 
		"rat1" : "/d/noden/farwind/monster/rat" ]) );
	ob->reset();
}
