// File: /d/eastland/goomay/guess_house.c
// Generated by Roommaker Thu Nov 23 18:34:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("迎賓客棧");
	ob->set_long( @LONG_DESCRIPTION
這裡是古梅鎮的迎賓客棧，往來本鎮的旅客和武林人士都常常在這裡落腳歇馬，
所以這裡常常可以打聽到各地的消息和傳言，本店的小二哥更是非常熱心「助人」
，如果你有什麼困難儘管向他開口，一定會得到幫助。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/goomay/mgate", 
		"north" : "/d/eastland/goomay/row14" ]) );
	ob->set( "objects", ([ 
		"house keeper" : "/d/eastland/goomay/monster/waiter" ]) );
	ob->reset();
}
