// File: /d/eastland/goomay/hunter_house.c
// Generated by Roommaker Thu Nov 23 18:45:03 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("破落的小屋");
	ob->set_long( @LONG_DESCRIPTION
這是一間破破爛爛的小屋，屋中到處都是油垢和垃圾，牆上掛了一些動物
的毛皮等雜物，幾根結實的木棒擺在門邊，旁邊還堆了些捕獸機具，或許這間
屋子的主人是獵人也說不定。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/goomay/ruin4" ]) );
	ob->set( "objects", ([ 
		"fishman" : "/d/eastland/goomay/monster/hunter" ]) );
	ob->reset();
}
