// File: /d/eastland/goomay/kwi_yi2.c
// Generated by Roommaker Thu Nov 23 18:35:22 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("快意堂內堂");
	ob->set_long( @LONG_DESCRIPTION
你走進快意堂的內堂，隨著你的腳步那些轟鬧的吆喝聲漸漸遠去，相
反的，一路上酒瓶酒□卻越來越多，而且個個來歷不凡，貴州茅臺酒、羊
城五糧液、吐魯番的葡萄酒等等..種類真是不可勝數。可以想見這裡的老
大一定是個好酒品酒的專家。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/goomay/kwi_yi" ]) );
	ob->set( "objects", ([ 
		"master" : "/d/eastland/goomay/monster/master_jau" ]) );
	ob->reset();
}
