// File: /d/eastland/goomay/mgate.c
// Generated by Roommaker Thu Nov 23 18:32:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("古梅鎮鎮口");
	ob->set_long( @LONG_DESCRIPTION
這裡原來是位於翰煙山下的一個小鎮，本來只有三十來戶的人家散佈在一片方圓
不到五里的臺地上，但是自從二十餘年前，飛仙一劍葉孤城與陸小鳳在禁城的一場鬥
智鬥力的精彩決戰後，每年十月皇上都要在此地舉辦武鬥大會，漸漸的，本鎮也成為
武林各幫派的兵家必爭之地。現在古梅鎮的繁華已經跟京城相差不遠了。北方是古梅
鎮的青石板大街，東邊有一家酒樓，西邊是一家客棧，南方通向東方大陸的曠野。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/goomay/wine_shop", 
		"west" : "/d/eastland/goomay/guess_house", 
		"south" : "/d/eastland/2,4.east", 
		"north" : "/d/eastland/goomay/col21" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"guard2" : "/d/eastland/goomay/monster/cityguard", 
		"guard1" : "/d/eastland/goomay/monster/cityguard" ]) );
	ob->reset();
}
