// File: /d/eastland/goomay/office.c
// Generated by Roommaker Thu Nov 23 18:37:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("衙門");
	ob->set_long( @LONG_DESCRIPTION
這裡是古梅鎮的衙門，雖然只是一個小小的地方衙門，但是由於皇上年年
臨幸此地，所以也就格外的引人注意，歷任的縣太爺都十分能幹，把皇上服侍
的舒舒服服後當然升官也特別快。這裡也是審理和判決的地方，凡是在本鎮犯
案的都會被解到這裡受審。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/goomay/police", 
		"north" : "/d/eastland/goomay/row12" ]) );
	ob->set( "objects", ([ 
		"scribe" : "/d/eastland/goomay/monster/scribe" ]) );
	ob->reset();
}
