// File: /d/eastland/goomay/plaster_shop.c
// Generated by Roommaker Thu Nov 23 18:40:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("世德堂藥鋪");
	ob->set_long( @LONG_DESCRIPTION
你走進一家鋪子，迎面而來的是一陣陣馥郁的藥草香，正堂上懸著一塊
烏木匾額，上面大書 "世德其昌" 四個亮金大字，兩旁藥櫃上的牆上滿滿的
懸著各式匾額，顯見這家藥店的主人在古梅鎮的名聲十分良好，目前世德堂
的主人是一個老醫生，他正在鋪裡打瞌睡。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/goomay/col23" ]) );
	ob->set( "objects", ([ 
		"doctor" : "/d/eastland/goomay/monster/old_doctor" ]) );
	ob->reset();
}
