// File: /d/eastland/goomay/rich_house.c
// Generated by Roommaker Thu Nov 23 18:41:28 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("立錐堂");
	ob->set_long( @LONG_DESCRIPTION
這裡是大財主錢不多的家，可是看起來卻一點也不起眼，大廳裡空空
蕩蕩的只有幾張太師椅圍著一張八仙桌，跟你想像的大財主之家實在相差
甚遠，有幾個人正圍著桌子商議不休，看來最好不要打擾他們，西邊有一
道珠簾輕掩的月洞門。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/goomay/green_pearl", 
		"north" : "/d/eastland/goomay/row25" ]) );
	ob->set( "objects", ([ 
		"richman" : "/d/eastland/goomay/monster/richman" ]) );
	ob->reset();
}
