// File: /d/eastland/goomay/row21.c
// Generated by Roommaker Thu Nov 23 18:43:10 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("青石板大道");
	ob->set_long( @LONG_DESCRIPTION
你走在古梅鎮平坦的青石大道上，光潔的青石板顯示著這個城鎮的活力，
伴隨在你身邊的是小販的吆喝聲、馬車的轔轔聲還有偶而疾馳而過的駿馬，那
是一些想要成名的武林人物，古梅鎮的西風塵沙中，不知埋葬了多少年輕人的
夢想。南方是著名的四不欺大院，街道向東延伸而去，北方是一個嘈雜的市場。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/goomay/market", 
		"west" : "/d/eastland/goomay/row22", 
		"south" : "/d/eastland/goomay/big_house" ]) );
	ob->set( "objects", ([ 
		"cop2" : "/d/eastland/goomay/monster/cop", 
		"cop1" : "/d/eastland/goomay/monster/cop" ]) );
	ob->reset();
}
