// File: /d/eastland/goomay/row25.c
// Generated by Roommaker Thu Nov 23 18:41:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("武鬥大會會場門口");
	ob->set_long( @LONG_DESCRIPTION
這裡是著名的天下第一武鬥大會會場門口，每一個習武的人都以能在
武鬥大會上嶄露頭角為畢生大志，所以決鬥的、熟悉場地的還有過過乾癮
的都把武鬥大會會場當成聖地，常要來朝拜一番。原本朝廷禁止民間使用
本會場，後來禁不勝禁，乾脆開放收錢，倒也增加了不少收入。街道向東
西延伸而去，北方是武鬥大會場，南方是立錐堂。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/goomay/row24", 
		"west" : "/d/eastland/goomay/row26", 
		"south" : "/d/eastland/goomay/rich_house" ]) );
	ob->set( "objects", ([ 
		"guardian" : "/d/eastland/goomay/monster/guardian" ]) );
	ob->reset();
}
