// File: /d/eastland/goomay/ruin5.c
// Generated by Roommaker Thu Nov 23 18:45:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("荒廢的廣場");
	ob->set_long( @LONG_DESCRIPTION
你來到一片開闊的廣場，原本平整的地面此刻已長滿了雜草，鵝黃色
的野花隨著微風在小路兩旁款款而笑，泛出赭紅色油光的路面顯示這裡仍
然有許多人每天經過，□□的風聲中，有斷斷續續的軸轤轉動聲自北方傳
來。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/goomay/entrance", 
		"south" : "/d/eastland/goomay/ruin4" ]) );
	ob->reset();
}
