// File: /d/eastland/goomay/ruin2.c
// Generated by Roommaker Thu Nov 23 18:44:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("破落的貧民窟");
	ob->set_long( @LONG_DESCRIPTION
看慣了古梅鎮金碧輝煌的一面，你一下子很難接受這種破落的地方竟然
也是古梅鎮的一部份。這裡是以往舊鎮的遺址，不過還是有些窮人住在這裡
，在頹圮的斷牆間生長的野花，偶而幾聲小孩的吵鬧聲、雞鳴犬吠，都使你
感覺住在這裡的人並不寂寞。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/goomay/ruin3", 
		"north" : "/d/eastland/goomay/ruin4", 
		"west" : "/d/eastland/goomay/ruin1" ]) );
	ob->set( "objects", ([ 
		"drunk" : "/d/eastland/goomay/monster/drunk" ]) );
	ob->reset();
}
