// File: /d/eastland/goomay/ruin4.c
// Generated by Roommaker Thu Nov 23 18:44:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("暗巷");
	ob->set_long( @LONG_DESCRIPTION
這裡是一條幽暗的窄巷，兩旁都是破落的老建築，簷角的密密蛛絲和
厚厚的灰塵，使你有一種時間凍結了的感覺，巷弄左右都是小小的缺口，
好像一條條小路，一陣陣的犬吠雞鳴在破落的廢墟中迴響。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/goomay/hunter_house", 
		"north" : "/d/eastland/goomay/ruin5", 
		"south" : "/d/eastland/goomay/ruin2" ]) );
	ob->reset();
}
