// File: /d/eastland/goomay/sooth_shop.c
// Generated by Roommaker Thu Nov 23 18:35:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("有所不知命相");
	ob->set_long( @LONG_DESCRIPTION
你走進一家命相館，迎面一張特大號的掛簾把內堂遮了大半，上頭畫了
個大大的金錢... 原來這家是專卜金錢掛的，你可別小看了這間小小的店子
，江湖上提起「有所不知」這四個大字真是無人不知，據說他上通天文、下
知地理、前推千載後算百年，十足十的無所不知，這個店名的是由他的口頭
禪「客官你有所不知」來的。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/goomay/row16" ]) );
	ob->set( "objects", ([ 
		"soothsayer" : "/d/eastland/goomay/monster/soothsayer" ]) );
	ob->reset();
}
