// File: /d/eastland/goomay/wei_yuan.c
// Generated by Roommaker Thu Nov 23 18:47:27 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("威遠鏢局");
	ob->set_long( @LONG_DESCRIPTION
這是鐵筆狂鷹周逵所開設的鏢局，一進門就是一片堅實的練武場，
門口兩側高高豎起的旗杆上各自掛著一面黑底金面的錦旗，上面錦繡
著「威遠」兩個大字，迎風烈烈作響，顯得極有威勢。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/goomay/col25" ]) );
	ob->set( "objects", ([ 
		"man3" : "/d/eastland/goomay/monster/mercenary", 
		"man2" : "/d/eastland/goomay/monster/mercenary", 
		"master" : "/d/eastland/goomay/monster/chief_merc", 
		"man1" : "/d/eastland/goomay/monster/mercenary" ]) );
	ob->reset();
}
