// File: /d/eastland/goomay/wine_shop2.c
// Generated by Roommaker Thu Nov 23 18:34:26 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("趙燕居二樓");
	ob->set_long( @LONG_DESCRIPTION
這裡是趙燕居大酒樓的二樓，寬闊的廳堂擺滿了桌椅，此刻雖然客人
不少，可是卻又不顯得吵鬧，鄰街的地方有幾的坐位都還空著，只坐著一
個很有氣派的中年人。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/eastland/goomay/wine_shop" ]) );
	ob->set( "objects", ([ 
		"master" : "/d/eastland/goomay/monster/master_fan", 
		"singer" : "/d/eastland/goomay/monster/singer" ]) );
	ob->reset();
}
