// File: /d/eastland/goomay/yi_hong.c
// Generated by Roommaker Thu Nov 23 18:36:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("怡紅院");
	ob->set_long( @LONG_DESCRIPTION
看見沿門掛出的兩排紅燈籠(lantern)，你已經可以猜到這是什麼地方，
每個燈籠上都寫著「怡紅」兩個大字，怡紅院是專門招待有錢大爺的地方，
所以不管三教九流，只要現在口袋有錢，都是怡紅院的上賓。也因為如此，
院內的姑娘、媽媽還有提大茶壺的王八龜奴每個都是見多識廣，只要你有興
趣一定可以聽到一些有趣的事。□
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/goomay/row16" ]) );
	ob->set( "objects", ([ 
		"servant" : "/d/eastland/goomay/monster/servant" ]) );
	ob->reset();
}
