// File: /d/eastland/haiwei/hockshop.c
// Generated by Roommaker Sat Jan 22 13:08:55 1994

#include "goomay.h"

inherit "/d/eastland/goomay/hocker";
//inherit ROOM;

void create()
{
	::create();
	set_short("同仁當鋪");
	set_long( @LONG_DESCRIPTION
你現在走進了一間佈置得相當考究的廳院，門口一爿藍色的布簾上寫著
四個大字「同仁老當」，這家當鋪是古梅鎮暴發戶錢不多的產業，他剛剛從
以前當鋪的主人手中把這家當鋪巧取豪奪過來，正打算好好賺上一票，不過
他對古董的眼光可真不是蓋的。牆上有一張紙，大概是說一些當鋪的行事規
矩，烏檀木做成的隔窗後面正有一位老朝奉對著你笑。
LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "exits", ([ 
		"west" : Goomay"col22" ]) );
      set("c_item_desc",(["paper":@C_LONG
    這是一張十分陳舊的泛黃皮紙，上面被人用烏亮的濃墨揮灑著
流利的隸書，使你看的心曠神怡。寫著 ：

    親愛的同仁老當客戶大爺們，小店一向秉持誠信態度為客戶服務
，然為避免不必要之糾紛，特此公告小鋪之條規以昭大信，盼小店與
客戶共同遵循，相互規矩為是。下列條規 ：

    一、物品當值均以時價折抵保管費後計算。
    二、本店最多只接受同一位客戶四次保管委託。
    三、所託物品在本店盤點時間之前未取者視同流當，小店得任意處置。
    四、取回託物時本鋪得酌量收取保管費與利息。

小店的營業項目有： 當物 (impawn)、贖回當物(take)、查詢當物(list)
，請您多多照顧小店的生意。謝謝 !!
 
   有需要託物服務的請面洽本鋪大朝奉。

C_LONG

                           ]));

	set( "objects", ([
		"shopkeeper" : Mob"pawnbroker",
		]));

	reset();
}
void init()
{
	::init();
        add_action("impawn2", "impawn");
}
int impawn2(string str)
{
       if ((int)this_player()->query_quest_level("Goddess_statue") > 2 ) 
		return hocker::impawn(str);
	else
	tell_object(this_player(),@C_HOCKSHOP
劉掌櫃嘆了一口氣道：「對不起 !! 客官 !! 小店暫停營業了，我們正在想辦法
找回被偷走的質押品－一尊價值連城的月神像(statue)，如果找不回來，小店信
譽掃地那是不消說了，恐怕連我自己都性命難保 !! 唉 ～～」
C_HOCKSHOP
	);
	return 1;
}
