// File: /d/eastland/goomay/mroad1.c
// Generated by Roommaker Thu Jan 27 01:46:44 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("古梅鎮");
	set_long( @C_LONG_DESCRIPTION
這裡是位於翰煙山下的一個小鎮，三十來戶的人家散佈在一片方圓不到五里
的臺地上，雖然如此，這個小鎮的名字卻是許多人耳熟能詳的，因為每年十月在
古梅鎮所舉行的武鬥大會是所有身負絕藝的高手志在必得的盛會，優勝者可以得
十分豐富的賞賜與「東方第一勇士」的名銜，以及皇上御賜的「金絲甲」。
C_LONG_DESCRIPTION
	);

	set_outside( "goomay" );
	set( "light", 1 );
	set( "exits", ([ 
		"south" : "/d/eastland/2,4.east" ]) );
	reset();
#include <replace_room.h>
}
