// File: /d/eastland/easta/shop.c
// Generated by Roommaker Thu Jan 27 09:58:01 1994

#include <goomay.h>

inherit SHOP;

void create()
{
	::create();
	set_short("集古齋");
	set_long( @LONG_DESCRIPTION
你現在走進了一家陰暗的商店，一塊烏木屏風把你的眼光遮住，屏風上
三個金漆大字寫著「集古齋」，一個長著兩撇鼠須的掌櫃走過來向你哈腰作
揖，滿臉諂媚的表情。你可以在這裡瀏覽買賣貨物，雖然這裡是本鎮暴發戶
錢不多的產業，但是只要你小心一點，還是不會吃虧的。
LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "exits", ([ 
		"east" : Goomay"col23" ]) );
	set( "objects", ([
		"trashcan" : "/obj/trashcan" ]) );
	storeroom()->set( "objects", ([
		"torch" : "/obj/torch",
		"bandage" : "/obj/bandage",
		"bag" : "/obj/bag"
	]) );
	reset();
        replace_program(SHOP);
}
