// File: /d/noden/recamp/camp3.c
// Generated by Roommaker Sat Nov 25 14:16:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->seteuid(getuid());
	ob->set_short("帳棚");
	ob->set_long( @LONG_DESCRIPTION
這裡是一個用獸皮、麻布、以及一些不知名的東西拼湊搭成的帳棚，帳棚
內部的空間並不是很大，你可以看到這裡堆著一些瓶瓶罐罐的藥劑(potions)，
幾個木箱(chests)或立或倒地排在角落裡，往東可以離開這個帳棚。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"chests" : @LONG_TEXT
幾個外面漆著鮮豔色彩的箱子，不過很可惜，裡面除了一些衣物以外，沒有
其他有趣東西。
LONG_TEXT
, 
		"potions" : @LONG_TEXT
這些藥劑有的是綠的，有的是黃的，但是上面都沒有貼標籤，只有調配者
才知道這些藥劑是用來幹什麼的。
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/recamp/camp1" ]) );
	ob->set( "objects", ([ 
		"shaman" : "/d/noden/recamp/npc/shaman" ]) );
	ob->reset();
}
