// File: /d/noden/recamp/camp1.c
// Generated by Roommaker Sat Nov 25 14:08:45 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("營地");
	ob->set_long( @LONG_DESCRIPTION
你現在站在一個營地中央的空地上，你的面前是一堆已經燒光的營火(
campfire)，在你的北邊是一個大帳棚，東邊有一個用茅草搭成的小屋，西
邊是另一個比較小的帳棚，往南可以離開這個營地。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "c_item_desc", ([ 
		"campfire" : @LONG_TEXT
這堆營火已經燒光了, 旁邊有一些焦黑的樹枝與木柴, 很顯然的有人不久
前曾在這聚會或生火煮食。
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/recamp/camp2", 
		"north" : "/d/noden/recamp/camp4", 
		"south" : "/d/noden/15,3.noden", 
		"west" : "/d/noden/recamp/camp3" ]) );
	ob->set( "objects", ([ 
		"boarman" : "/d/noden/recamp/npc/boarman" ]) );
	ob->reset();
}
