// File: /d/noden/recamp/camp8.c
// Generated by Roommaker Sat Nov 25 14:29:10 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地道");
	ob->set_long( @LONG_DESCRIPTION
這條神秘的地道，壁上鑲嵌著耀眼明亮的珠子，照亮整個通道，壁上還繪著
一隻瘦小的恐龍怪物，正大肆破壞諾頓王國東北村落，令人不禁膽跳心驚。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/recamp/camp5", 
		"down" : "/d/noden/recamp/camp_pool" ]) );
	ob->set( "objects", ([ 
		"rat2" : "/d/noden/farwind/monster/grey_rat", 
		"rat1" : "/d/noden/farwind/monster/grey_rat" ]) );
	ob->reset();
}
