// File: /d/noden/recamp/camp2.c
// Generated by Roommaker Sat Nov 25 14:15:48 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小茅屋");
	ob->set_long( @LONG_DESCRIPTION
你現在來到一間簡陋的小茅屋中，這間小茅屋搭得十分簡陋，隨時可能被
一陣強風吹垮，屋子裡堆了不少木柴和乾草，這裡顯然是一間臨時的儲藏室或
倉庫，你可以往西離開這間小茅屋。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/noden/recamp/camp1" ]) );
	ob->set( "objects", ([ 
		"boarman 2" : "/d/noden/recamp/npc/boarman" ]) );
	ob->reset();
}
