// File: /d/noden/recamp/camp6.c
// Generated by Roommaker Sat Nov 25 14:28:19 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地道");
	ob->set_long( @LONG_DESCRIPTION
這條神秘的地道，壁上鑲嵌著耀眼明亮的珠子，照亮整個通道，壁上還繪著
一隻困在泥裡的龍，顯示在諾頓王國的東南方，相當吸引人的留意。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/recamp/camp7", 
		"west" : "/d/noden/recamp/camp5" ]) );
	ob->set( "objects", ([ 
		"toad1" : "/d/noden/farwind/monster/toad", 
		"toad2" : "/d/noden/farwind/monster/toad" ]) );
	ob->reset();
}
