// File: /d/noden/recamp/camp9.c
// Generated by Roommaker Sat Nov 25 14:29:26 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地道");
	ob->set_long( @LONG_DESCRIPTION
這條神秘的地道，壁上鑲嵌著耀眼明亮的珠子，照亮整個通道，壁上畫著
一道閃電降落在諾頓王國的西南方向。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/recamp/camp_wall", 
		"up" : "/d/noden/recamp/camp_pool" ]) );
	ob->set( "objects", ([ 
		"rat#1" : "/d/noden/recamp/npc/rat", 
		"rat#2" : "/d/noden/recamp/npc/rat", 
		"cat" : "/d/noden/recamp/npc/cat" ]) );
	ob->reset();
}
