// Generated by Roommaker Tue Dec  7 22:16:00 1993
// Modified by freeway 5/15 1995

#include <mudlib.h>
#include "camp.h" 

inherit ROOM;

void create()
{
	::create();
   set_short("帳棚");
	set_long( @LONG_DESCRIPTION
你現在來到一個比較大的帳棚，這裡的擺設讓你有一種感覺，住在這個
帳棚裡面的人一定是一位勇猛的戰士，你看見地上鋪著一張熊皮，周圍有一
大堆的野獸頭骨，像是戰利品般的被分類堆放著，你面前有一張座椅，上面
鋪著一張五彩斑斕的虎皮，座椅前面有一個鍋子(cauldron)正放在爐火上煮
著，散發出一股香味。帳棚裡還掛著一張誘人的立體圖片(picture)。
LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "c_item_desc", ([ 
		"cauldron" : @LONG_TEXT
這個鍋子的香味使你忍不住伸長脖子往裡頭看，哇....惡....一粒半獸人
的頭顱正在鍋子裡和你大眼瞪小眼，你突然覺得這股香味變得有點臭了。
LONG_TEXT
,
                "picture":@C_LONG
你不禁吞了吞口水，心跳猛然加速，呼吸急促起來，畫面中畫滿了許多
赤裸裸的女孩，正以各種撩人的姿勢，大膽的展露出那健美的身材。你
發現上面好像有人摸過的痕跡，你不禁也想要摸摸看(touch)。
C_LONG
		]) );

	set( "exits", ([ 
		"south" : "/d/noden/recamp/camp1" ]) );
	set( "objects", ([ 
		"leader" : "/d/noden/recamp/npc/leader" ]) );
		
	reset();
}

void init()
{
	add_action("do_touch","touch");
}

int do_touch(string arg)
{
	if ( !arg || arg != "picture" )
		return notify_fail("你要摸什麼？\n");
	if ( !query("exits/down") ) {
	write(@LONG
你露出邪惡的笑容，伸手向圖中聳起的部份摸去，發現軟軟的，好像真的一樣，
於是你雙出齊出，使了一招「雙龍搶珠」，突然「拍」的一聲，下邊出現了一道
暗門。
LONG
	);
	tell_room(this_object(),this_player()->query("c_name")+
	"伸手向圖中聳起的部份摸去，突然「拍」的一聲，下邊出現了一道暗門。\n",
	this_player() );
	set("exits/down",CAMP"camp5");
   set( "exit_suppress", ({ "down" }) );
	return 1;
	}
	write("你伸手向圖中聳起的部份摸去，暗門就自動關了起來。\n");
	delete("exits/down");
	return 1;
}

void reset()
{
	delete("exits/down");
	::reset();
}
