// File: /d/eastland/yogor/eastgate.c
// Generated by Roommaker Thu Jan 27 00:52:30 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("A empty room", "幽國城");
	set_long( @LONG_DESCRIPTION
This is a simple room created by roommaker.
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你現在來到位於群山環抱的幽國城東門，幽國城自古以來一直是少商谷最大
的首府，少商谷物產豐富，四季如春，不過這幾年西邊太倉山興起一股悍匪，官
兵幾次圍剿都沒能平定，因此幽國城只開東門，南、北、西三門平時都緊閉著。
C_LONG_DESCRIPTION
	);

	set_outside( "eastland" );
	set( "light", 1 );
	set( "exits", ([ 
		"east" : "/d/eastland/5,15.east" ]) );
	reset();
}
