// File: /d/deathland/island/forest02.c
// Generated by Roommaker Thu Nov 23 19:55:17 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("灰暗之島的森林");
	ob->set_long( @LONG_DESCRIPTION
一個黑漆漆的森林, 這森林似乎充滿著荊棘與矮灌木, 地上都是腐爛的樹葉, 是
個令人很想逃離的地方. 這裡的地勢似乎越往東南就越高, 你發覺這個地方似乎已經
森林的深處了. 
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"northwest" : "/d/deathland/island/forest01", 
		"east" : "/d/deathland/island/forest03" ]) );
	ob->set( "objects", ([ 
		"falcon" : "/d/deathland/monster/bird01" ]) );
	ob->reset();
}
