// File: /d/deathland/island/forest17.c
// Generated by Roommaker Thu Nov 23 19:59:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("灰暗之島的森林");
	ob->set_long( @LONG_DESCRIPTION
一個黑漆漆的森林, 這森林似乎充滿著荊棘與矮灌木, 地上都是腐爛的樹葉, 是
個令人很想逃離的地方. 你發覺你已在森林的深處了. 
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/deathland/island/forest14", 
		"north" : "/d/deathland/island/forest16" ]) );
	ob->set( "objects", ([ 
		"plant#1" : "/d/deathland/monster/plant01", 
		"plant#2" : "/d/deathland/monster/plant01" ]) );
	ob->reset();
}
