// File: /d/deathland/island/mountain03.c
// Generated by Roommaker Thu Nov 23 19:52:27 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("灰暗之島的祭壇");
	ob->set_long( @LONG_DESCRIPTION
這地方似乎是一個古代的祭壇, 在祭壇的正中央有著一個奇怪的階梯通往地下深處,
一種神聖的力量從地底傳出, 你能清楚地感受這力量的存在.
    西邊有著一道很強勁的力場保衛這個神聖的地方. 究竟地底下是甚麼地方呢?     
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"down" : "/d/deathland/island/stair01", 
		"west" : "/d/deathland/island/mountain02" ]) );
	ob->reset();
}
