// File: /d/deathland/island/mountain01.c
// Generated by Roommaker Thu Nov 23 19:51:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("灰暗之島的山嶽");
	ob->set_long( @LONG_DESCRIPTION
這裡是灰暗之島地勢較高的地方, 你覺得你每一步都相當浪費你的力氣. 往東北
方看過去, 你只能看到一片光禿禿的山嶽, 隱隱約約地一條小徑蜿沿而上.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"southwest" : "/d/deathland/island/i01", 
		"northeast" : "/d/deathland/island/mountain02" ]) );
	ob->reset();
}
