// File: /d/deathland/island/stair06.c
// Generated by Roommaker Thu Nov 23 19:53:42 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("通往地底的階梯");
	ob->set_long( @LONG_DESCRIPTION
你位於一個階梯上,這階梯以螺旋狀靠在巖壁上往下延伸著.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"down" : "/d/deathland/island/stair07", 
		"up" : "/d/deathland/island/stair05" ]) );
	ob->reset();
}
