// File: /d/deathland/island/swamp06.c
// Generated by Roommaker Thu Nov 23 19:50:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("灰暗之島的沼澤");
	ob->set_long( @LONG_DESCRIPTION
一個黑漆漆的沼澤, 沼澤下似乎有著可怕的生物想把你拖下去, 你必須小心謹慎
你的每一步. 越往東走沼澤的水就越深, 而且你的視線也被霧幾乎完全地遮住了. 這
地裡你已經無法清楚地看到四周的狀況了, 只知道你的腳已經快深陷於沼澤裡了.

LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"east", 
		"north", 
		"south" }) );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/island/swamp10", 
		"south" : "/d/deathland/island/swamp07", 
		"north" : "/d/deathland/island/swamp05", 
		"west" : "/d/deathland/island/swamp02" ]) );
	ob->set( "search_desc", ([ 
		"here" : @LONG_TEXT
你無法看清楚四面八方是否有你能立足的地方, 只知道離開這個沼澤
是你最好的選擇.
LONG_TEXT
 ]) );
	ob->reset();
}
