// File: /d/deathland/island/swamp12.c
// Generated by Roommaker Thu Nov 23 19:47:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("灰暗之島的沼澤");
	ob->set_long( @LONG_DESCRIPTION
一個黑漆漆的沼澤, 沼澤下似乎有著可怕的生物想把你拖下去, 你必須小心謹慎
你的每一步. 越往東走沼澤的水就越深, 而且你的視線也被霧幾乎完全地遮住了. 這
地裡你已經無法清楚地看到四周的狀況了, 只知道你的腳已經快深陷於沼澤裡了.

LONG_DESCRIPTION
	);

	ob->set( "exit_invisble", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/island/swamp16", 
		"west" : "/d/deathland/island/swamp08" ]) );
	ob->set( "objects", ([ 
		"hand" : "/d/deathland/monster/beast04" ]) );
	ob->reset();
}
