// File: /d/deathland/island/swamp02.c
// Generated by Roommaker Thu Nov 23 19:42:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("灰暗之島的沼澤");
	ob->set_long( @LONG_DESCRIPTION
一個黑漆漆的沼澤, 沼澤下似乎有著可怕的生物想把你拖下去, 你必須小心謹慎
你的每一步. 越往東走沼澤的水就越深, 而且你的視線也被霧幾乎完全地遮住了.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/island/swamp06", 
		"west" : "/d/deathland/island/swamp01" ]) );
	ob->reset();
}
