// File: /d/noden/moyada/shop/strange_room.c
// Generated by Roommaker Tue Dec  5 19:29:44 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("奇怪的房間");
	ob->set_long( @LONG_DESCRIPTION
你很訝異這裡竟有這樣的一個房間，漂亮的裝飾品佈滿了四周，這裡的主人
一定十分有氣質。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/moyada/shop/hole" ]) );
	ob->set( "objects", ([ 
		"girl" : "/d/noden/moyada/monster/little_girl" ]) );
	ob->reset();
}
