// File: /d/noden/drow/r02.c
// Generated by Roommaker Mon Nov 27 14:19:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("侍衛隊長休息室");
	ob->set_long( @LONG_DESCRIPTION
一進來，你似乎就可以感覺到一股戰士們蓄勢待發的氣氛，這裡是黑暗
精靈部隊隊長的休息室。你可以看到有張簡單的行軍床，和一張大桌子，桌
上放了一些文件，而角落則有一個大衣架，掛了一件軍服。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/drow/r03" ]) );
	ob->set( "objects", ([ 
		"soldier" : "/d/noden/drow/mob/soldier",
		"captain" : "/d/noden/drow/mob/captain" ]) );
	ob->reset();
}
