// File: /d/noden/drow/r05.c
// Generated by Roommaker Mon Nov 27 14:20:11 1995

#include <mudlib.h>

void create(object ob)
{
        if ( !ob ) return ;
        ob->set_short("兵器儲藏室");
        ob->set_long( @LONG_DESCRIPTION
這是黑暗精靈村裡，士兵們的武器及裝備的收藏室。由於受到大蛇的騷
擾，這裡平時就存放了好多士兵們戰鬥所需的武裝等等，你可以看到牆上掛
的幾幅人像，那些是歷代的勇士們的畫像。
LONG_DESCRIPTION
        );

        ob->set( "light", 0 );
        ob->set( "exits", ([
                "west" : "/d/noden/drow/r04" ]) );
        ob->set( "objects", ([
                "soldier#3" : "/d/noden/drow/mob/soldier",
                "soldier#2" : "/d/noden/drow/mob/soldier",
                "soldier#1" : "/d/noden/drow/mob/soldier" ]) );
        ob->reset();
}
