// File: /d/noden/drow/r06.c
// Generated by Roommaker Mon Nov 27 14:19:28 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地下廣場");
	ob->set_long( @LONG_DESCRIPTION
這是一個地下大廣場，你已經摺服於黑暗精靈族的建築手藝，竟然
能在這由岩石所構成的地底下，建構這種大廣場，這裡平時是黑暗精靈
族人的主要活動場所，也是他們集會，和外來人們交換生活物資的地方
，黑暗精靈沒有錢幣的交易，大多以物易物。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/drow/r08", 
		"north" : "/d/noden/drow/r03", 
		"south" : "/d/noden/drow/r12", 
		"southeast" : "/d/noden/drow/r09" ]) );
	ob->reset();
}
