// File: /d/noden/drow/r07.c
// Generated by Roommaker Mon Nov 27 14:19:19 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("貴族宅院");
	ob->set_long( @LONG_DESCRIPTION
這裡是一個美麗的宅院，低矮的圍牆上，依然雕刻著蜘蛛的圖紋，
小小的庭院種植一些奇奇怪怪的蔬菜，一間石房就在庭院的中央，也許
是黑暗精靈天性的節儉吧，這看似樸實的庭院，就是他們貴族平日居住
的地方，你不禁想想，黑暗精靈的節儉可能跟他們的生活環境有關吧。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/drow/r08" ]) );
	ob->set( "objects", ([ 
		"m2" : "/d/noden/drow/mob/woman", 
		"m3" : "/d/noden/drow/mob/child" ]) );
	ob->reset();
}
