// File: /d/noden/drow/r08.c
// Generated by Roommaker Mon Nov 27 14:19:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("廣大通道");
	ob->set_long( @LONG_DESCRIPTION
這裡是黑暗精靈村的主要通道，由於整個村落都是在地底下的深處
，這裡陰涼而空氣清新，廣大的通道斜向地延伸，這裡寬廣平坦，靠近
石壁的地方，都雕刻有蜘蛛，和蛇的圖案。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/drow/r11", 
		"west" : "/d/noden/drow/r07", 
		"northeast" : "/d/noden/drow/r06" ]) );
	ob->reset();
}
