// File: /d/noden/drow/r12.c
// Generated by Roommaker Mon Nov 27 14:22:14 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("諾思大神殿");
	ob->set_long( @LONG_DESCRIPTION
當你進來時，被眼前巨大的神像所吸引，一股香菸嫋嫋的氣味撲鼻而來，    
來，這裡就是黑暗精靈村中最偉大的建築工藝－－諾思大神殿－－。
黑暗精靈族人供奉的邪神－司娜可女神－是個有八個頭的巨大神像，相傳
在古老的年代時，就有勇者曾企圖打敗她，而被封在水晶中，這故事似乎
有一段淵源，你是否該看看這神像呢？
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/noden/drow/r06" ]) );
	ob->set( "objects", ([ 
		"salin" : "/d/noden/drow/mob/salin" ]) );
	ob->reset();
}
