// File: /d/noden/drow/r16.c
// Generated by Roommaker Mon Nov 27 14:19:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("海倫神殿");
	ob->set_long( @LONG_DESCRIPTION
這裡是海倫神殿，巨大的柱子雕塑著多種花卉，而神殿中央坐落著一
位女神－海倫，這裡是黑暗精靈族人在迎接新生命時，都會帶來給老村長
命名並且接受海倫女神枷筮的地方，通常由老村長來進行這件工作，但是
奴役卻沒有接受女神祝福的機會。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"west" : "/d/noden/drow/r15" ]) );
	ob->set( "objects", ([ 
		"m5" : "/d/noden/drow/mob/chief" ]) );
	ob->reset();
}
