// File: /d/noden/drow/r19.c
// Generated by Roommaker Mon Nov 27 14:20:38 1995

#include <mudlib.h>

void create(object ob)
{
        if ( !ob ) return ;
        ob->set_short("儲藏室");
        ob->set_long( @LONG_DESCRIPTION
這裡是黑暗精靈族人的儲藏室，大部分的糧食以及民生物資都儲存
在此，為了防止『努巴』以及其他的動物來盜取，啃食，這裡也有士兵
的崗哨駐紮此地。
LONG_DESCRIPTION
        );

        ob->set( "light", 0 );
        ob->set( "exits", ([
                "west" : "/d/noden/drow/r18" ]) );
        ob->set( "objects", ([
                "soldier#2" : "/d/noden/drow/mob/soldier",
                "soldier#1" : "/d/noden/drow/mob/soldier" ]) );
        ob->reset();
}
