// File: /d/noden/drow/r21.c
// Generated by Roommaker Mon Nov 27 14:20:57 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("賽亞達神殿");
	ob->set_long( @LONG_DESCRIPTION
哇！眼前一個石像，居然雕刻的跟真人一樣，揮舞雙手，凝視遠方，
全身穿著著一套幽黑色的盔甲，那一雙帶點慈藹卻炯炯有神的眼睛，好像
一個真人般，他就是黑暗精靈的守護神－賽亞達－。　
據說在遠古時，就是他以一人之力，將八歧大蛇封在禁斷之巖，後來族人
為了紀念他，也就蓋了這間神殿，這裡沒有燦麗的雕塑，取而代之的是環
繞在神像旁的小水池，潺潺水聲，令你有種清淨的感覺。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/drow/r27" ]) );
	ob->set( "objects", ([ 
		"keiwi" : "/d/noden/drow/mob/keiwi" ]) );
	ob->reset();
}
