// File: /d/noden/drow/r27.c
// Generated by Roommaker Mon Nov 27 14:18:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑暗精靈村入口");
	ob->set_long( @LONG_DESCRIPTION
通過昏暗的石階，你來到了黑暗精靈村的入口了，這是一個由蜘蛛
圖案雕塑在兩個巨大石柱的大門，兩旁掛有火把，由於黑暗精靈不需要
光，而這火把，則是由村內的人所點燃，為的是使外來的人，能較容易
的找到這地底的村落。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"northwest" : "/d/noden/drow/r24", 
		"north" : "/d/noden/drow/r21", 
		"south" : "/d/noden/drow/r28", 
		"northeast" : "/d/noden/drow/r25" ]) );
	ob->set( "objects", ([ 
		"guard#2" : "/d/noden/drow/mob/guard2", 
		"guard#1" : "/d/noden/drow/mob/guard2" ]) );
	ob->reset();
}
