// File: /d/noden/drow/r28.c
// Generated by Roommaker Mon Nov 27 14:18:27 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地下石階");
	ob->set_long( @LONG_DESCRIPTION
這裡是一處冗長的石階，蜿蜒向下，你看不到石階的盡頭，牆上微弱
的火把還在閃爍著，但是好像快熄滅了，階梯溼漉漉的，長有不少青苔，
你要小心步行，千萬別滑倒了。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/drow/r38", 
		"north" : "/d/noden/drow/r27" ]) );
	ob->reset();
}
