// File: /d/noden/drow/r29.c
// Generated by Roommaker Mon Nov 27 14:15:09 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("蛇窩");
	ob->set_long( @LONG_DESCRIPTION
天啊？！好多的蛇！這裡到處是蛇，有赤尾青竹絲，百步蛇，雨傘節
和巨大的蟒蛇等等，想必這裡是大多數蛇的棲身場所吧。地上佈滿著蛇蛻
下的蛇皮，踩過去有種沙沙的聲音，好惡心!!令你想快步通過。
咦？蛇的蛻皮中好像隱藏了個通道？是在．．．．．
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exit_suppress", ({ 
		"down" }) );
	ob->set( "exits", ([ 
		"down" : "/d/noden/drow/r42", 
		"southeast" : "/d/noden/drow/r32" ]) );
	ob->set( "objects", ([ 
		"snake#4" : "/d/noden/drow/mob/s1", 
		"snake#3" : "/d/noden/drow/mob/s1", 
		"snake#2" : "/d/noden/drow/mob/s1", 
		"snake#1" : "/d/noden/drow/mob/s1" ]) );
	ob->reset();
}
