// File: /d/noden/drow/r36.c
// Generated by Roommaker Tue Nov 28 12:55:53 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("蛇窩");
	ob->set_long( @LONG_DESCRIPTION
天啊？！好多的蛇！這裡到處是蛇，有赤尾青竹絲，百步蛇，雨傘節
和巨大的蟒蛇等等，想必這裡是大多數蛇的棲身場所吧。地上佈滿著蛇蛻
下的蛇皮，踩過去有種沙沙的聲音，好惡心!!令你想快步通過。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"northwest" : "/d/noden/drow/r34", 
		"northeast" : "/d/noden/drow/r35", 
		"southeast" : "/d/noden/drow/r01" ]) );
	ob->set( "objects", ([ 
		"snake#3" : "/d/noden/drow/mob/s5", 
		"snake#2" : "/d/noden/drow/mob/s5", 
		"snake#1" : "/d/noden/drow/mob/s5" ]) );
	ob->reset();
}
