// File: /d/noden/drow/r39.c
// Generated by Roommaker Mon Nov 27 14:18:17 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("潮溼通道");
	ob->set_long( @LONG_DESCRIPTION
這裡既潮溼又陰冷，前方不時傳來陣陣冷颼颼的風聲，令你感覺十分
的不好，四周的牆上結滿了蜘蛛網，你最好趕緊離開。　　
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/drow/r40", 
		"northwest" : "/d/noden/drow/r38", 
		"southeast" : "/d/noden/drow/r41" ]) );
	ob->set( "objects", ([ ]) );
	ob->reset();
}
