// File: /d/noden/drow/r41.c
// Generated by Roommaker Mon Nov 27 14:18:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("潮溼下水道");
	ob->set_long( @LONG_DESCRIPTION
這裡是一處下水道，地上積水大約半尺，並且有一股薰人的黴味，
水流異常緩慢，還飄來一些垃圾，好像是地面上的人亂丟的，四周牆壁
不時滲出水漬，滴滴答答的聲音在這通道里造成迴音。　
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"northwest" : "/d/noden/drow/r39", 
		"east" : "/d/noden/farwind/tunnel3.c", 
		"west" : "/d/noden/drow/r40" ]) );
	ob->set( "objects", ([ ]) );
	ob->reset();
}
