// File: /d/noden/drow/r42.c
// Generated by Roommaker Mon Nov 27 14:14:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("陰暗水池");
	ob->set_long( @LONG_DESCRIPTION
這裡灰暗潮溼，積水約半公尺深，你聞到一股腦人的黴味，與
水流悉娑的聲音，你看到石牆上仍有蛇蛻下的皮黏掛在那兒，可見得
這裡還是有生物的。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"up" : "/d/noden/drow/r29" ]) );
	ob->set( "in_well", 1 );
	ob->set( "objects", ([ 
		"mad snake" : "/d/noden/drow/mob/s7" ]) );
	ob->set( "underwater", 1 );
	ob->reset();
}
