// File: /d/deathland/main/d10.c
// Generated by Roommaker Thu Nov 23 20:16:12 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("深淵的南邊");
	ob->set_long( @LONG_DESCRIPTION
從這往北看去,有一個非常大,又非常深的深淵橫在你的面前,似乎讓人覺得它
就是通往地獄的入口 . 到了這裡 , 一股寒意湧上心頭,讓你不禁懷疑是否你處在
一個噩夢中而一直無法醒來.風不停地由深淵吹上來,越來越強勁,你只能緊緊地貼
著巖壁慢慢地走,這樣你才能避勉整個人被風吹走.往西看去有一團霧(fog)一直滯
留在那兒,你很驚訝為何在如此強勁的風勢之下,那團霧竟然不會被吹散.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/main/d8", 
		"west" : "/d/deathland/main/d12" ]) );
	ob->set( "item_desc", ([ 
		"fog" : "一團黑霧.\n" ]) );
	ob->reset();
}
