// File: /d/deathland/main/d2.c
// Generated by Roommaker Thu Nov 23 20:18:19 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("一個很深的洞穴");
	ob->set_long( @LONG_DESCRIPTION
這洞穴像是一直延申到地底去.而風從地底不停地吹上來. 一些奇奇怪怪的
圖形畫滿了整個洞穴,除此之外,地上的足跡也是零零亂亂的,你無法清楚地分辨
出究竟是屬於那一種生物的腳印.
南方有個水池通往海中,而往北方看去有個洞通往地底深處.
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"northdown" : "/d/deathland/main/d3", 
		"south" : "/d/deathland/main/d6" ]) );
	ob->reset();
}
