// File: /d/deathland/main/d6.c
// Generated by Roommaker Thu Nov 23 20:18:27 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("令人毛骨悚然的地方");
	ob->set_long( @LONG_DESCRIPTION
當你遊進這洞穴中時,你的心靈忽然充滿了毛骨悚然的感覺.
一些殘骸在水中飄浮著,使你想盡快離開水中
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"out" : "/d/deathland/main/d4", 
		"north" : "/d/deathland/main/d2" ]) );
	ob->set( "objects", ([ 
		"octpus" : "/d/deathland/monster/octpus" ]) );
	ob->set( "underwater", 1 );
	ob->reset();
}
