// File: /d/deathland/main/d8.c
// Generated by Roommaker Thu Nov 23 20:16:32 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("深淵的南邊");
	ob->set_long( @LONG_DESCRIPTION
從這往北看去,有一個非常大,又非常深的深淵橫在你的面前,似乎讓人覺得它
就是通往地獄的入口.雖然你目前是處在地底的深處, 但是你仍然能看清附近的地
形地物,這個地方十分的空曠,往東方看似乎有幾個帳篷,但是你無法確定. 往西看
去一片死寂,你無法清晰的看見任何事物.而南邊是一往上的斜坡.
    風不停地由深淵(Abyss)吹上來,一不小心你將摔入這地獄的入口.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"southup" : "/d/deathland/main/d7", 
		"east" : "/d/deathland/main/d9", 
		"west" : "/d/deathland/main/d10" ]) );
	ob->set( "item_desc", ([ 
		"abyss" : "一個非常大,又非常深的深淵.似乎它是通往地獄的捷徑.\n" ]) );
	ob->reset();
}
