// File: /d/deathland/main/d9.c
// Generated by Roommaker Thu Nov 23 20:17:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("深淵南方");
	ob->set_long( @LONG_DESCRIPTION
從這往北看去,有一個非常大,又非常深的深淵橫在你的面前,似乎讓人覺得它就
是通往地獄的入口.往東方看有幾個帳篷( tents ),你相信應該有一些生物住在那兒
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/main/d11", 
		"west" : "/d/deathland/main/d8" ]) );
	ob->set( "item_desc", ([ 
		"tents" : "幾個很大的帳蓬.\n" ]) );
	ob->reset();
}
