// File: /d/eastland/saulin_temple/back_temple.c
// Generated by Roommaker Wed Nov 22 22:57:53 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("後殿");
	ob->set_long( @LONG_DESCRIPTION
空空湯湯的一座大殿，除了正中供奉的釋迦牟尼佛外，幾乎是別無長物，
這裡的地面光亮如鏡，好像常常有一大群人坐在地上似的，也許這裡是少林
僧人參禪打座的地方，不過現在卻是一片死寂。南北方各是一條長廊。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/saulin_temple/hallway22", 
		"south" : "/d/eastland/saulin_temple/hallway12" ]) );
	ob->reset();
}
