// File: /d/eastland/saulin_temple/boro_room1.c
// Generated by Roommaker Wed Nov 22 23:07:28 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("般若院 試掌廳");
	ob->set_long( @LONG_DESCRIPTION
進入這裡後，你只能看見一對對精光閃爍的眼睛此起彼落，呼呼的拳勁
掌風在這狹小的石室中翻騰，然而卻聽不到一點人聲，這裡是少林弟子回山
之後向前輩討教江湖上名門大派掌法的地方，所以在這裡的試掌者都是一等
一的高手。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/eastland/saulin_temple/boro_temple" ]) );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/monk_su1" ]) );
	ob->reset();
}
