// File: /d/eastland/saulin_temple/boro_temple.c
// Generated by Roommaker Wed Nov 22 23:07:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("般若院");
	ob->set_long( @LONG_DESCRIPTION
般若堂是少林寺專門研究各門各派武學的所在，少林武功得享盛名千年，
除了人才輩出外，能夠知己知彼也是制勝之因，現在堂中有許多老僧正在靜思
，隨便打擾他們絕對不是什麼好玩的事情。南北方各有一間黑摸摸的小室，門
外是一片樹林。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/forest9", 
		"north" : "/d/eastland/saulin_temple/boro_room2", 
		"south" : "/d/eastland/saulin_temple/boro_room1" ]) );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/shi" ]) );
	ob->reset();
}
