// File: /d/eastland/saulin_temple/boro_room2.c
// Generated by Roommaker Wed Nov 22 23:07:55 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("般若院 問劍廳");
	ob->set_long( @LONG_DESCRIPTION
進入這裡後，你只能看見一道道的劍光此起彼落，有時撞擊聲綿密漫長
，有時卻良久無聲。這裡是少林弟子回山之後向前輩討教江湖上名門大派劍
法的地方，所以在這裡的試劍者都是一等一的高手。雖然少林弟子鮮少用劍
，但是少林寺卻一直不缺俗家劍法高手，問劍廳實在功不可沒。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/boro_temple" ]) );
	ob->set( "objects", ([ 
		"monk" : "/d/eastland/saulin_temple/monster/yan_guan" ]) );
	ob->reset();
}
