// File: /d/eastland/saulin_temple/chenfo_temple.c
// Generated by Roommaker Wed Nov 22 23:28:47 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("千佛殿");
	ob->set_long( @LONG_DESCRIPTION
你現在進入了千佛殿（又名毗盧殿），看見前方是一座毗盧佛，有六丈高，
神情莊嚴。前面的供桌上有水果，還很新鮮，可惜旁邊有僧人在看，不然就可
以偷拿一兩個來吃。東，北，西三面牆上是吳道子所繪「五百羅漢朝毗盧圖」
，氣勢非凡，人物刻劃細緻，不愧為一代大師之作。門外是一條走廊。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/hallway6" ]) );
	ob->set( "objects", ([ 
		"monka" : "/d/eastland/saulin_temple/monster/little_monk", 
		"monkb" : "/d/eastland/saulin_temple/monster/hwa_son" ]) );
	ob->reset();
}
