// File: /d/eastland/saulin_temple/classroom.c
// Generated by Roommaker Wed Nov 22 23:10:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("講經堂");
	ob->set_long( @LONG_DESCRIPTION
你走進一座寬大的廳堂，堂中此刻正坐滿了人，每個人都聚精會神的
聽著堂上一名老僧說法，還有人不時在佛經上、衣服上、等等只要是可以
寫字的地方做著筆記。雖然堂上擁擠不堪的坐滿了人，可是除了老僧的宏
道說法和沙沙的書寫聲外，竟是半點雜聲也無。西方是一條走廊，東方有
一條小徑。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/stone_path2", 
		"west" : "/d/eastland/saulin_temple/hallway22" ]) );
	ob->set( "objects", ([ 
		"monka" : "/d/eastland/saulin_temple/monster/meditate_monk", 
		"monkb" : "/d/eastland/saulin_temple/monster/meditate_monk", 
		"monkc" : "/d/eastland/saulin_temple/monster/meditate_monk", 
		"monkd" : "/d/eastland/saulin_temple/monster/meditate_monk" ]) );
	ob->reset();
}
