// File: /d/eastland/saulin_temple/damo_temple.c
// Generated by Roommaker Wed Nov 22 23:29:39 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("達摩院");
	ob->set_long( @LONG_DESCRIPTION
走進達摩院，你一眼就被院中的大菩提樹吸引，樹下正有許多老僧正
在入定，院內各處還有幾名年輕僧人在低頭沉思，偶而起身擺弄一些奇怪
的姿勢。達摩院是少林寺發揚本身基本武學的地方，據聞院內諸僧無不身
兼數項絕技，在這裡撒野的人一定討不了好的去。南北方各有一座小殿，
門外則是一片寧靜的樹林。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/saulin_temple/forest11", 
		"south" : "/d/eastland/saulin_temple/damo_room2", 
		"north" : "/d/eastland/saulin_temple/damo_room1" ]) );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/shu_du" ]) );
	ob->reset();
}
