// File: /d/eastland/saulin_temple/damo_room2.c
// Generated by Roommaker Wed Nov 22 23:29:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("達摩院 見性堂");
	ob->set_long( @LONG_DESCRIPTION
走進這裡，只見好幾個年輕和尚在已經被磨的光亮的青石地上擺弄著
各種奇特的姿勢，或似狼踞、似猿呼，或似鳥伸、似鶴展，這些就是少林
內功中的動功，專心致志的他們使得這裡像極了一座蠟像館，你不禁有些
毛骨悚然。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/eastland/saulin_temple/damo_temple" ]) );
	ob->set( "objects", ([ 
		"monk" : "/d/eastland/saulin_temple/monster/monk" ]) );
	ob->reset();
}
