// File: /d/eastland/saulin_temple/damo_room1.c
// Generated by Roommaker Wed Nov 22 23:29:23 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("達摩院 明心堂");
	ob->set_long( @LONG_DESCRIPTION
走進這裡，除了此起彼落的漫長呼吸聲外，幾乎什麼聲音都沒有。
好幾個年輕和尚在已經被磨的光亮的青石地上或坐或躺的修習名聞天下
的少林派內功\，專心致志的他們使得這裡像極了一座古墓，你不禁有些
毛骨悚然。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/damo_temple" ]) );
	ob->reset();
}
