// File: /d/eastland/saulin_temple/enforce_room1.c
// Generated by Roommaker Wed Nov 22 23:26:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("守心堂");
	ob->set_long( @LONG_DESCRIPTION
你走進一個小小的石室，除了一尊達摩祖師像外，室內別無一物
，有幾名少林弟子正背著你端坐面壁靜思，陣陣低沈的誦經聲使得你
昏昏欲睡，你不禁想趕快離開這個沈悶的地方。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/eastland/saulin_temple/enforce_temple" ]) );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/enforcer" ]) );
	ob->reset();
}
