// File: /d/eastland/saulin_temple/enforce_temple.c
// Generated by Roommaker Wed Nov 22 23:26:39 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("戒律院");
	ob->set_long( @LONG_DESCRIPTION
你走進一個大廳堂，廳堂兩側各排了一排戒棍，堂上供奉著一尊大
佛，旁邊還有兩尊怒目金剛，炯炯雙目好像警惕著長跪在堂前懺悔的幾
名僧人。四周還有幾名輪值的掌刑弟子，正專心的督導犯錯的僧人唸經
。門外是一片寧靜的樹林，。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/enforce_room1", 
		"south" : "/d/eastland/saulin_temple/enforce_room2", 
		"west" : "/d/eastland/saulin_temple/forest5" ]) );
	ob->set( "objects", ([ 
		"enforcer" : "/d/eastland/saulin_temple/monster/enforcer", 
		"enforcermaster" : "/d/eastland/saulin_temple/monster/gun" ]) );
	ob->reset();
}
