// File: /d/eastland/saulin_temple/farm1.c
// Generated by Roommaker Wed Nov 22 23:11:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("菜園");
	ob->set_long( @LONG_DESCRIPTION
這裡是一片寬闊的菜園，園中此刻正有許多僧人和長工在工作著，
這些田地都是少林寺的廟產，所收成的五穀蔬果除了能自給自足外還能
賣給批發商，當然，所有的廟產盈餘都是用於濟助四鄉貧民。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/farm2", 
		"west" : "/d/eastland/saulin_temple/grass5", 
		"north" : "/d/eastland/saulin_temple/farm3" ]) );
	ob->set( "objects", ([ 
		"monka" : "/d/eastland/saulin_temple/monster/serv_monk", 
		"monkb" : "/d/eastland/saulin_temple/monster/serv_monk", 
		"worker" : "/d/eastland/saulin_temple/monster/worker" ]) );
	ob->reset();
}
