// File: /d/eastland/saulin_temple/farm4.c
// Generated by Roommaker Wed Nov 22 23:12:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("菜園");
	ob->set_long( @LONG_DESCRIPTION
這裡是一片寬闊的菜園，園中此刻正有許多僧人和長工在工作著，
這些田地都是少林寺的廟產，所收成的五穀蔬果除了能自給自足外還能
賣給批發商，當然，所有的廟產盈餘都是用於濟助四鄉貧民。菜園的東
邊有一口山泉(spring)，僧人們正把泉水引進園中灌溉。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/saulin_temple/farm3", 
		"south" : "/d/eastland/saulin_temple/farm2" ]) );
	ob->set( "item_desc", ([ 
		"spring" : @LONG_TEXT
這是一口清澈的山泉，冷洌的泉水正洶湧的從泉眼噴出，在僧人築成的
護堤內匯成一個大池，不斷冒出的泉水從堤口流出，僧人們引著這些水
作為灌溉以及日常生活用水。當然，你也可以試試這純天然湧出的礦泉
水，不過你得先找到裝水的瓢兒(gourd)。
LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"monka" : "/d/eastland/saulin_temple/monster/serv_monk" ]) );
	ob->set( "water_source", 1 );
	ob->reset();
}
