// File: /d/eastland/saulin_temple/forest4.c
// Generated by Roommaker Wed Nov 22 23:24:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林中的小徑");
	ob->set_long( @LONG_DESCRIPTION
你走在一條小徑上，潔淨的小徑顯示經常有人走過這裡，習習的微風
穿過林梢向你吹來，只有寂寂的四周蟲鳴鳥啼和野花飄香，小徑向南北方
蜿蜒而去。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/forest3", 
		"north" : "/d/eastland/saulin_temple/forest5" ]) );
	ob->set( "objects", ([ 
		"bee" : "/d/eastland/saulin_temple/monster/hornet", 
		"bee2" : "/d/eastland/saulin_temple/monster/hornet" ]) );
	ob->reset();
}
