// File: /d/eastland/saulin_temple/forest11.c
// Generated by Roommaker Wed Nov 22 23:08:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林中的小徑");
	ob->set_long( @LONG_DESCRIPTION
你走在一條小徑上，潔淨的小徑顯示經常有人走過這裡，習習的微風
穿過林梢向你吹來，只有寂寂的四周蟲鳴鳥啼和野花飄香，小徑向南北方
蜿蜒而去，東方好像有一角屋簷在林影間閃動。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/damo_temple", 
		"south" : "/d/eastland/saulin_temple/forest10", 
		"north" : "/d/eastland/saulin_temple/forest12" ]) );
	ob->reset();
}
