// File: /d/eastland/saulin_temple/forest2.c
// Generated by Roommaker Wed Nov 22 23:16:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林中的小徑");
	ob->set_long( @LONG_DESCRIPTION
你走在一條小徑上，潔淨的小徑顯示這裡經常有人走過，習習的微風
穿過林梢向你吹來，只有寂寂的四周蟲鳴鳥啼和野花飄香，小徑向北蜿蜒
而去。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/saulin_temple/forest3", 
		"southeast" : "/d/eastland/saulin_temple/left_path2" ]) );
	ob->set( "objects", ([ 
		"fly2" : "/d/noden/elf/monster/butterfly", 
		"fly" : "/d/noden/elf/monster/butterfly" ]) );
	ob->reset();
}
