// File: /d/eastland/saulin_temple/forest7.c
// Generated by Roommaker Wed Nov 22 23:27:17 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林中的小徑");
	ob->set_long( @LONG_DESCRIPTION
你走在一條小徑上，潔淨的小徑顯示經常有人走過這裡，習習的微風
穿過林梢向你吹來，只有寂寂的四周蟲鳴鳥啼和野花飄香，東方好像有一
角屋簷在林影間閃動。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/rain_temple", 
		"south" : "/d/eastland/saulin_temple/forest6" ]) );
	ob->set( "objects", ([ 
		"fly2" : "/d/noden/elf/monster/rabbit", 
		"fly" : "/d/noden/elf/monster/rabbit" ]) );
	ob->reset();
}
