// File: /d/eastland/saulin_temple/forest1.c
// Generated by Roommaker Wed Nov 22 23:14:06 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林中的廢棄小徑");
	ob->set_long( @LONG_DESCRIPTION
你走在一條小徑上，覆滿枯葉的小徑顯示已經有許久沒有人走過這裡
了，習習的微風穿過林梢向你吹來，只有寂寂的四周蟲鳴鳥啼和野花飄香，
遠方好像有一角屋簷在林影間閃動。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/doshy_temple", 
		"northeast" : "/d/eastland/saulin_temple/left_path2" ]) );
	ob->set( "objects", ([ 
		"fox2" : "/d/eastland/saulin_temple/monster/wild_fox", 
		"fox1" : "/d/eastland/saulin_temple/monster/wild_fox" ]) );
	ob->reset();
}
