// File: /d/eastland/saulin_temple/front_square1.c
// Generated by Roommaker Wed Nov 22 23:31:30 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("廣場");
	ob->set_long( @LONG_DESCRIPTION
這是一片用石板鋪成的大廣場，每個石板的中間都凹了下去，遠遠
望去好像水面上的波紋，十分的壯觀。另外場邊還擺著許多的兵器，看
來此處是是少林寺三千武僧練武的地方。此處的北邊有一些殿堂，可惜
距離太遠你看不到上面寫的字，東邊是一望無際的廣場。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/front_square2", 
		"west" : "/d/eastland/saulin_temple/front_square3", 
		"north" : "/d/eastland/saulin_temple/front_square4" ]) );
	ob->set( "objects", ([ 
		"monk2" : "/d/eastland/saulin_temple/monster/bonze2" ]) );
	ob->reset();
}
