// File: /d/eastland/saulin_temple/front_square5.c
// Generated by Roommaker Wed Nov 22 23:32:15 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("廣場");
	ob->set_long( @LONG_DESCRIPTION
這是一片用石板鋪成的大廣場，每個石板的中間都凹了下去，遠遠望去
好像水面上的波紋，十分的壯觀。另外場邊還擺著許多的兵器，看來此處是
少林寺三千武僧練武的地方。此處的北邊就是大雄寶殿，東南西三邊則是一
望無際的廣場。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/front_square6", 
		"south" : "/d/eastland/saulin_temple/front_square2", 
		"west" : "/d/eastland/saulin_temple/front_square4", 
		"north" : "/d/eastland/saulin_temple/main_temple1" ]) );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/bonze2", 
		"yan" : "/d/eastland/saulin_temple/monster/yan_san" ]) );
	ob->reset();
}
