// File: /d/eastland/saulin_temple/grass3.c
// Generated by Roommaker Wed Nov 22 23:00:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林中小徑");
	ob->set_long( @LONG_DESCRIPTION
你走在一條黃土小徑上，四周都是松林，除了山風吹掠、蟲鳴鳥啼外，沒
有一點塵俗雜音，陰涼幽靜的森林氣息深深的迷醉每一顆來自俗世塵囂的心，
你頓時放下世俗的一切種種牽絆，放開心胸來體會這份難得的自然之美。南北
方各有一條小徑，東方是塔林，西方則是碑林。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/towers1", 
		"south" : "/d/eastland/saulin_temple/grass4", 
		"west" : "/d/eastland/saulin_temple/tomb_stones1", 
		"north" : "/d/eastland/saulin_temple/grass2" ]) );
	ob->reset();
}
