// File: /d/eastland/saulin_temple/grass5.c
// Generated by Roommaker Wed Nov 22 23:00:10 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林中小徑");
	ob->set_long( @LONG_DESCRIPTION
你走在一條黃土小徑上，四周都是松林，除了山風吹掠、蟲鳴鳥啼外，沒
有一點塵俗雜音，陰涼幽靜的森林氣息深深的迷醉每一顆來自俗世塵囂的心，
你頓時放下世俗的一切種種牽絆，放開心胸來體會這份難得的自然之美。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/farm1", 
		"south" : "/d/eastland/saulin_temple/stone_path0", 
		"west" : "/d/eastland/saulin_temple/kitchen", 
		"north" : "/d/eastland/saulin_temple/grass4" ]) );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/jay_yeng" ]) );
	ob->reset();
}
