// File: /d/eastland/saulin_temple/guess_house1.c
// Generated by Roommaker Wed Nov 22 23:36:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("客房");
	ob->set_long( @LONG_DESCRIPTION
走進這個房間，一陣清新的檀香味迎面而來，這裡是專供香客歇腳掛
單的客房，兩側寬敞的大通鋪上此刻正稀稀落落的坐著躺著一些休息的香
客，門口有幾名服事僧垂手低眉而立，等著接受香客們的差遣。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/saulin_temple/stone_path0" ]) );
	ob->set( "objects", ([ 
		"guestb" : "/d/eastland/saulin_temple/monster/guest", 
		"monk" : "/d/eastland/saulin_temple/monster/serv_monk", 
		"guesta" : "/d/eastland/saulin_temple/monster/guest" ]) );
	ob->reset();
}
