// File: /d/eastland/saulin_temple/hallway22.c
// Generated by Roommaker Wed Nov 22 22:56:30 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("走廊");
	ob->set_long( @LONG_DESCRIPTION
你走在一條長廊上，兩旁都是庭臺堂蕪，廊上僧人來往香客如織，擠的
根本沒有心情去欣賞四周的環境。少林寺號稱千廊百院，像這樣的長廊不知
有多少，你可得小心迷路。北方是一條石階小徑，南方是後殿，東方是講經
堂，西方則是普賢院。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/classroom", 
		"west" : "/d/eastland/saulin_temple/pusan_temple", 
		"south" : "/d/eastland/saulin_temple/back_temple", 
		"north" : "/d/eastland/saulin_temple/stone_path1" ]) );
	ob->reset();
}
