// File: /d/eastland/saulin_temple/hallway7.c
// Generated by Roommaker Wed Nov 22 22:50:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("走廊");
	ob->set_long( @LONG_DESCRIPTION
你走在一條長廊上，兩旁都是庭臺堂蕪，廊上僧人來往香客如織，擠的
根本沒有心情去欣賞四周的環境少林寺號稱千廊百院，像這樣的長廊不知有
多少，你可得小心迷路。南北方各是一條長廊。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/hallway6", 
		"north" : "/d/eastland/saulin_temple/hallway8" ]) );
	ob->reset();
}
