// File: /d/eastland/saulin_temple/hallway0.c
// Generated by Roommaker Wed Nov 22 22:55:44 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("穿堂");
	ob->set_long( @LONG_DESCRIPTION
你走在一條長廊上，兩旁都是庭臺堂蕪，廊上僧人來往香客如織，擠的
根本沒有心情去欣賞四周的環境少林寺號稱千廊百院，像這樣的長廊不知有
多少，你可得小心迷路。向北向西各有一條走廊，南方則是大殿，長廊兩旁
門戶重疊，不知道通往什麼地方。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/main_temple3", 
		"north" : "/d/eastland/saulin_temple/hallway1", 
		"west" : "/d/eastland/saulin_temple/hallway21" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"mobs" : "/d/eastland/saulin_temple/monster/yang_win" ]) );
	ob->reset();
}
