// File: /d/eastland/saulin_temple/hallway1.c
// Generated by Roommaker Wed Nov 22 22:51:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("走廊");
	ob->set_long( @LONG_DESCRIPTION
你走在一條長廊上，兩旁都是庭臺堂蕪，廊上僧人來往香客如織，擠的
根本沒有心情去欣賞四周的環境。少林寺號稱千廊百院，像這樣的長廊不知
有多少，你可得小心迷路。南方是一條穿堂，長廊往東方延伸而去。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/hallway2", 
		"south" : "/d/eastland/saulin_temple/hallway0" ]) );
	ob->set( "objects", ([ 
		"monk2" : "/d/eastland/saulin_temple/monster/hwei_lin" ]) );
	ob->reset();
}
