// File: /d/eastland/saulin_temple/herb_room.c
// Generated by Roommaker Wed Nov 22 23:37:34 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("藥閣");
	ob->set_long( @LONG_DESCRIPTION
踏進這裡，一陣濃郁的藥草香撲鼻而來，這裡是少林寺貯藏藥物的
地方，一格格的木櫃放置的各種不同的藥草，層層疊疊地直堆到屋頂。
雖然這裡貴重的藥物很多，但是有毒的也不少，所以除非有精通藥物學
的人代勞，否則最好不要亂打這些藥草的主意。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/herb_field", 
		"west" : "/d/eastland/saulin_temple/plaster_temple" ]) );
	ob->set( "objects", ([ 
		"monk2" : "/d/eastland/saulin_temple/monster/herb_monk", 
		"monk" : "/d/eastland/saulin_temple/monster/herb_monk" ]) );
	ob->reset();
}
