// File: /d/eastland/saulin_temple/left_path2.c
// Generated by Roommaker Wed Nov 22 23:14:31 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("三叉小徑");
	ob->set_long( @LONG_DESCRIPTION
你走在一條青石小徑上，磨損得圓潤光華的石徑無言的對你誇耀
少林寺的悠久歷史。清風習習四下寂寂，只有蟲鳴鳥啼和野花飄香，
和少林寺的其他部份比起來，這裡就像世外桃源一樣。小徑在此處分
向西南和西北而去，西南方看似有一座森林。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"southwest" : "/d/eastland/saulin_temple/forest1", 
		"northwest" : "/d/eastland/saulin_temple/forest2", 
		"east" : "/d/eastland/saulin_temple/left_path1" ]) );
	ob->set( "objects", ([ 
		"monk" : "/d/eastland/saulin_temple/monster/hwei_ti" ]) );
	ob->reset();
}
