// File: /d/eastland/saulin_temple/lohan_temple.c
// Generated by Roommaker Wed Nov 22 23:38:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("羅漢堂");
	ob->set_long( @LONG_DESCRIPTION
一踏進羅漢堂你的眼光立刻被兩旁供奉的十八羅漢所吸引，降龍伏虎
迦葉阿難等等神態姿勢各異其趣的羅漢塑像分立兩旁，它們背後的牆上各
自繪著每一名羅漢苦修成道的壁畫。同時這裡也是寺中武藝有成的武僧互
相切磋功力的地方，現在正有不少武僧在切磋討論，拳來掌往刀光劍影十
分熱鬧。門外是一條走廊。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/hallway8" ]) );
	ob->reset();
}
