// File: /d/eastland/saulin_temple/main_temple1.c
// Generated by Roommaker Wed Nov 22 23:32:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大雄寶殿前廳石階");
	ob->set_long( @LONG_DESCRIPTION
你現在來到了一處石階前，你的目光被前方雄偉的石柱(stonehenge)所吸引。
你仰頭望去，高聳的橫樑上掛著一塊匾額，上面用蒼勁有力的字體寫著——大雄
寶殿。往北看去就是大雄寶殿的前廳，這裡莊嚴肅穆的氣氛讓你的心情不由得嚴
肅起來。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/side_temple2", 
		"south" : "/d/eastland/saulin_temple/front_square5", 
		"west" : "/d/eastland/saulin_temple/side_temple1", 
		"north" : "/d/eastland/saulin_temple/main_temple2" ]) );
	ob->set( "item_desc", ([ 
		"stonehenge" : "這是一根十分巨大的石柱，上面好像有雕刻，可惜距離太遠看不清楚。\n" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
