// File: /d/eastland/saulin_temple/main_temple2.c
// Generated by Roommaker Wed Nov 22 23:33:24 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("少林寺大雄寶殿前廳");
	ob->set_long( @LONG_DESCRIPTION
你現在來到了少林寺大雄寶殿的前廳，你的目光被兩旁雄偉的石柱
(stonehenge)所吸引。你仰頭望去，兩邊的牆壁上刻滿了玄奘西遊取經
的故事。左邊牆上有一塊牌子，上面密密麻麻的不知道寫些什麼。前廳
的中央有一個香爐(censer)，裡面鼎盛的香火顯示這裡是個佛教興盛之
地。往北看去就是鼎鼎有名的大雄寶殿，南邊似乎有一個很大的廣場。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/main_temple1", 
		"north" : "/d/eastland/saulin_temple/main_temple3" ]) );
	ob->set( "item_desc", ([ 
		"stonehenge" : @LONG_TEXT
這個石柱上雕滿了龍，鳳和麒麟，雖然已經歷經數代，但是仍然十分的細緻，可稱的
上是藝術的傑作。
LONG_TEXT
, 
		"sign" : "玄慧虛空\n", 
		"censer" : "這是一個用青銅鑄造的大香爐，看起來已經年代久遠了，上面插滿了香。\n" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
