// File: /d/eastland/saulin_temple/plaster_temple.c
// Generated by Roommaker Wed Nov 22 23:37:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("藥王殿");
	ob->set_long( @LONG_DESCRIPTION
這裡是供奉藥王菩薩的地方，同時也是寺僧看病醫療的所在，這裡的掌藥
師父同時也是醫道高深的醫生，小如熱感風寒、跌打損傷，大至毒癰腫瘤，他
們都能妥善處理，當然，這裡也施醫施藥，不過如果方便的話，求藥的香客最
好還是捐點香油錢。你可以問掌藥師父目前殿內的藥物的種類。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/herb_room", 
		"north" : "/d/eastland/saulin_temple/hallway4" ]) );
	ob->set( "objects", ([ 
		"monk" : "/d/eastland/saulin_temple/monster/heal_monk" ]) );
	ob->reset();
}
