// File: /d/eastland/saulin_temple/pusan_temple.c
// Generated by Roommaker Wed Nov 22 23:27:42 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("普賢院");
	ob->set_long( @LONG_DESCRIPTION
走進這個充滿彩繪壁畫的小院，你幾乎忽略了正堂供奉的普賢菩薩，騎
著白象的普賢菩薩現在看起來好像有些苦惱，不知道在煩些什麼？你突然注
意到牆上(wall)的壁畫空了一塊，難怪怎麼看都不對勁。西方是雨花院，東
方則是一條走廊。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/hallway22", 
		"west" : "/d/eastland/saulin_temple/rain_temple" ]) );
	ob->set( "item_desc", ([ 
		"elephant" : "看什麼？大象都跑了! 只留下白白的一塊了!\n", 
		"pushan" : @LONG_TEXT
你看著普賢菩薩的畫像，突然，普賢菩薩開口說話了: 
  唉! 我那頭孽畜不知道跑到哪裡去了，待會佛祖查問起來，我可如何是好？如
  果你能幫我找到它，一定要替我狠狠地教訓它，這樣就能把它逼回來。還有，
  劣騎的三昧真火極強，如果還沒找到剋制它的方法，最好不要去惹它。
LONG_TEXT
, 
		"wall" : @LONG_TEXT
這是一面充滿了絢麗彩畫的牆壁，畫中描述南無釋迦牟尼會見弟子，諸天諸佛齊
來朝拜，十八羅漢及八部天龍在兩旁護法，文殊菩薩騎著青獅、普賢(Pushan)菩
薩騎著 .... 咦？他的白象(elephant)呢？
LONG_TEXT
 ]) );
	ob->reset();
}
