// File: /d/eastland/saulin_temple/right_path1.c
// Generated by Roommaker Wed Nov 22 23:40:38 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("青石小徑");
	ob->set_long( @LONG_DESCRIPTION
你走在一條青石小徑上，磨損得圓潤光華的石徑無言的對你誇耀
少林寺的悠久歷史。清風習習四下寂寂，只有蟲鳴鳥啼和野花飄香，
和少林寺的其他部份比起來，這裡就像世外桃源一樣。小徑一直向東
西方而去。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/right_path2", 
		"west" : "/d/eastland/saulin_temple/hallway5" ]) );
	ob->reset();
}
