// File: /d/eastland/saulin_temple/river_side2.c
// Generated by Roommaker Wed Nov 22 23:09:21 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林緣草地");
	ob->set_long( @LONG_DESCRIPTION
你走在一片草地上，南方是一片松林，除了山風吹掠、蟲鳴鳥啼外，沒
有一點塵俗雜音，陰涼幽靜的森林氣息深深的迷醉每一顆來自俗世塵囂的心
，你頓時放下世俗的一切種種牽絆，放開心胸來體會這份難得的自然之美。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/river_side4", 
		"north" : "/d/eastland/saulin_temple/stone_path2" ]) );
	ob->reset();
}
