// File: /d/eastland/saulin_temple/river_side3.c
// Generated by Roommaker Wed Nov 22 23:10:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("河邊草地");
	ob->set_long( @LONG_DESCRIPTION
你走在一片草地上，北方是一片松林，除了山風吹掠、蟲鳴鳥啼外，沒
有一點塵俗雜音，陰涼幽靜的森林氣息深深的迷醉每一顆來自俗世塵囂的心
，你頓時放下世俗的一切種種牽絆，放開心胸來體會這份難得的自然之美。
東方有一條小河，河水蜿蜒地沿著藏經閣向南流去，南方則是藏經閣前的廣
場。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/book_temple1", 
		"west" : "/d/eastland/saulin_temple/river_side1" ]) );
	ob->reset();
}
