// File: /d/eastland/saulin_temple/road4.c
// Generated by Roommaker Wed Nov 22 23:39:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山腰");
	ob->set_long( @LONG_DESCRIPTION
此處位於少室山的山腰，在你的上方少林寺的山門雄偉的矗立著。此
刻你位於一條用雲石鋪設成的石階上，的四周都是蒼蒼老松，把此處點綴
的綠意盎然，而繁花萬千更顯生氣活潑。 
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"down" : "/d/eastland/saulin_temple/road3", 
		"up" : "/d/eastland/saulin_temple/gate" ]) );
	ob->set( "objects", ([ 
		"fighter" : "/d/eastland/saulin_temple/monster/barbarian" ]) );
	ob->reset();
}
