// File: /d/eastland/saulin_temple/road1.c
// Generated by Roommaker Wed Nov 22 23:38:46 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山腳下");
	ob->set_long( @LONG_DESCRIPTION
此處位於少室山的山腳下，附近都是連綿不絕的高山，你的眼前有一條
用雲石鋪設成的石階盤旋上山顛，山頂似乎有一群建築物，可惜距離太遠你
看不清是何種建築物。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"up" : "/d/eastland/saulin_temple/road2", 
		"north" : "/d/eastland/2,8.east" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
