// File: /d/eastland/saulin_temple/road2.c
// Generated by Roommaker Wed Nov 22 23:38:58 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山下");
	ob->set_long( @LONG_DESCRIPTION
此處位於少室山的山下，附近都是連綿不絕的高山，你正站在一條用
雲石鋪設成的石階上，你的四周都是蒼蒼老松，把此處點綴的綠意盎然，
而繁花千萬更顯活潑生氣，遠處山頂似乎有一群建築物，可惜距離太遠你
看不清是何種建築。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"down" : "/d/eastland/saulin_temple/road1", 
		"up" : "/d/eastland/saulin_temple/road3" ]) );
	ob->set( "objects", ([ 
		"guest" : "/d/eastland/saulin_temple/monster/guest" ]) );
	ob->reset();
}
