// File: /d/eastland/saulin_temple/side_temple1.c
// Generated by Roommaker Wed Nov 22 23:32:34 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("偏殿");
	ob->set_long( @LONG_DESCRIPTION
這裡是偏殿，寬闊的殿堂中列著一排排的架子，架上則點著由各地善男
信女所奉獻的長明燈，每盞油燈放出的微光，都是世上苦難眾生的希望，望
著點點明燈似海如浪，一股肅穆虔誠的感覺油然而生，你不禁也想長跪佛前
，祈求佛祖的導引。往西看去有一座塔樓，東方是大雄寶殿的石階，南方則
是一片廣場。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/main_temple1", 
		"west" : "/d/eastland/saulin_temple/bell_tower", 
		"south" : "/d/eastland/saulin_temple/front_square4" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/staff_monk" ]) );
	ob->reset();
}
