// File: /d/eastland/saulin_temple/small_path2.c
// Generated by Roommaker Wed Nov 22 23:06:00 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("後山小徑");
	ob->set_long( @LONG_DESCRIPTION
這裡是少林寺的後山，四周都是青蔥蒼鬱的茂林，到了這裡，你已經完全遠
離了少林寺中的遊人笑語、禪吟佛唱，但在這片可愛的青草地上，卻有一些樹倒
草掀的破壞痕跡，幾個大腳印(footsteps) 踩爛了草皮，直直的往遠方的森林迤
灑而去。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/saulin_temple/small_path3", 
		"south" : "/d/eastland/saulin_temple/small_path1" ]) );
	ob->set( "item_desc", ([ 
		"footsteps" : @LONG_TEXT
你彎下腰去觀察地上的腳印。乖乖! 這一定是一頭特大號的大象，光看這些臉盆
大的腳印就可以想像它那龐大的身軀! 萬一不小心被它壓到那就慘了。你確定你
要去找它麻煩嗎？ 
LONG_TEXT
 ]) );
	ob->reset();
}
