// File: /d/eastland/saulin_temple/stone_path0.c
// Generated by Roommaker Wed Nov 22 22:59:30 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石階小徑");
	ob->set_long( @LONG_DESCRIPTION
你走在少林寺內千廊百院間的通道上，磨損得圓潤光華的石階無言的對你
誇耀少林寺的悠久歷史。遙望寺外蓊鬱松林，寺內黃瓦朱牆，寺僧來去、遊客
相接，你不禁有出世之想。往南北方望去各式一條小徑，東邊是客房，西邊則
是禪房。
LONG_DESCRIPTION
	);

	ob->set_outside( "saulin_temple" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/guess_house1", 
		"west" : "/d/eastland/saulin_temple/monk_room1", 
		"south" : "/d/eastland/saulin_temple/stone_path1", 
		"north" : "/d/eastland/saulin_temple/grass5" ]) );
	ob->reset();
}
