// File: /d/eastland/saulin_temple/stone_path1.c
// Generated by Roommaker Wed Nov 22 22:59:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石階小徑");
	ob->set_long( @LONG_DESCRIPTION
你走在少林寺內千廊百院間的通道上，磨損得圓潤光華的石階無言的對你
誇耀少林寺的悠久歷史。遙望寺外蓊鬱松林，寺內黃瓦朱牆，寺僧來去、遊客
相接，你不禁有出世之想。南北方各是一條小路。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/hallway22", 
		"north" : "/d/eastland/saulin_temple/stone_path0" ]) );
	ob->set( "objects", ([ 
		"monk" : "/d/eastland/saulin_temple/monster/yeng_dou" ]) );
	ob->reset();
}
