// File: /d/eastland/saulin_temple/tomb_stones4.c
// Generated by Roommaker Wed Nov 22 23:05:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("碑林");
	ob->set_long( @LONG_DESCRIPTION
這裡是少林寺著名的碑林，存放著歷代少林所獲得的榮譽象徵。每一面
石碑都記錄著當代執政者和社會輿論對少林寺的肯定。當然，其中也有一些
少林寺對寺內圓寂高僧的追思，以藉此鼓勵後進。不過，站在這麼許多石碑
當中，一不小心恐怕就會迷路，所以這裡平時人跡罕至。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/tomb_stones2", 
		"west" : "/d/eastland/saulin_temple/tomb_stones3", 
		"south" : "/d/eastland/saulin_temple/tomb_stones4", 
		"north" : "/d/eastland/saulin_temple/small_path1" ]) );
	ob->reset();
}
