// File: /d/eastland/saulin_temple/unsu_temple.c
// Generated by Roommaker Wed Nov 22 23:24:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("文殊院");
	ob->set_long( @LONG_DESCRIPTION
這裡是供奉文殊菩薩的地方，正堂上供奉著騎青獅的文殊菩薩，溫和微笑
的文殊菩薩是大智慧的象徵，所以現在正有許多在佛理上產生疑問的僧人對著
菩薩沈思，祈求菩薩能賜給他們破除迷惘的智慧。門外是一片寧靜的樹林。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/saulin_temple/forest3", 
		"south" : "/d/eastland/saulin_temple/unsu_room2", 
		"north" : "/d/eastland/saulin_temple/unsu_room1" ]) );
	ob->set( "objects", ([ 
		"monk2" : "/d/eastland/saulin_temple/monster/kon_hwei", 
		"monk" : "/d/eastland/saulin_temple/monster/hwa_wan" ]) );
	ob->reset();
}
