// File: /d/eastland/saulin_temple/unsu_room2.c
// Generated by Roommaker Wed Nov 22 23:25:03 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("文殊院 懺堂");
	ob->set_long( @LONG_DESCRIPTION
這裡是文殊院的懺堂，凡是寺中僧人覺得心中有所疑惑或是對經文有
所疑問，都可以來這裡唸經拜懺，以求得內心的平靜與對佛法的更深一步
體會。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/eastland/saulin_temple/unsu_temple" ]) );
	ob->set( "objects", ([ 
		"monk2" : "/d/eastland/saulin_temple/monster/meditate_monk", 
		"monk" : "/d/eastland/saulin_temple/monster/pray_monk" ]) );
	ob->reset();
}
