// File: /d/eastland/saulin_temple/unsu_room1.c
// Generated by Roommaker Wed Nov 22 23:25:11 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("文殊院 經堂");
	ob->set_long( @LONG_DESCRIPTION
這裡是文殊院的經堂，一部份需要特殊人才解讀翻譯或是講解的
西天竺文原經都會先在這裡副錄抄本後再送到藏經閣典藏，所以這裡
也收藏了極為豐富的佛學經典，必要的時候你可以請經堂裡的師傅幫
你講解經中的精義。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/eastland/saulin_temple/unsu_temple" ]) );
	ob->set( "objects", ([ 
		"monk2" : "/d/eastland/saulin_temple/monster/meditate_monk", 
		"monk" : "/d/eastland/saulin_temple/monster/pray_monk" ]) );
	ob->reset();
}
