// File: /d/eastland/saulin_temple/white_temple.c
// Generated by Roommaker Wed Nov 22 23:41:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("白衣殿");
	ob->set_long( @LONG_DESCRIPTION
進入了白衣殿，迎面而來的就是一座和人等高的白衣大士金身，
慈眉善目的白衣大士雙目靈動栩栩如生，好像正在注視你，你的心中
感到一陣肅穆，絲毫不敢輕慢。環顧四壁令你大感興趣。東邊的牆上
有著名的「十三和尚救唐王圖」，北邊壁上是「心意六合掌譜」，南
邊壁上是各種兵器的招式分解圖。都是少林的入門武功。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"northwest" : "/d/eastland/saulin_temple/right_path2" ]) );
	ob->set( "objects", ([ 
		"monk1" : "/d/eastland/saulin_temple/monster/hand_monk", 
		"monk2" : "/d/eastland/saulin_temple/monster/hand_monk" ]) );
	ob->reset();
}
