// File: /d/eastland/saulin_temple/cave.c
// Generated by Roommaker Wed Nov 22 23:36:14 1995

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
	set_short("黑暗的洞穴");
	set_long( @LONG_DESCRIPTION
你來到一個漆黑的洞穴裡, 這個洞穴並不大, 而且因為地勢的關係, 空氣中充滿了
令人不太舒服的水氣, 地上也有淺淺的積水.
LONG_DESCRIPTION
	);
        set("exits",([
            "out" : "/d/eastland/saulin_temple/grass7.c"]) );
        set("objects",([
            "monk" : "/d/eastland/saulin_temple/monster/fire_monk1.c"]) );
	reset();
}

init()
{
   add_action( "do_songin", "songin" );
}

int do_songin()
{
    object obj;
    obj = this_player();
    if (obj->query("class")!="monk") return 0;
    if( !obj->query_temp("alignment") ) {
            obj->set_temp("alignment",obj->query("alignment"));
            return 0; }
    if(((int)obj->query("alignment")-(int)obj->query_temp("alignment")) > 500)
      {     obj->set_temp("monk_movement",1);
            return 0; }
    obj->add("alignment",50+random(obj->query_skill("recitation")));
    return 0;
}
