// File: /d/eastland/saulin_temple/grass7.c
// Generated by Roommaker Wed Nov 22 23:36:14 1995

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
	set_short("_grass7","林中蒼松");
	set_long( @DESC
你走到了一片草地上，四周都是松林，其中有三棵特別蒼勁挺拔，矗立
在其他松樹間顯得十分矯矯不群，你注意到這三棵呈品字形排列的松樹下都
有一個樹洞，洞中各有一個老僧低頭靜思，你突然注意到三松之間的地面似
有一洞(cave)，黑黝黝的看不清。
DESC
	);
	set( "item_desc", ([ 
		"cave" : @MSG1
你想要走上前去看清楚這個洞穴，突然一陣如雷的語聲傳來：

	施主請留步，此處乃禁地，閒雜人等不得進入 !!

你嚇了一大跳，那個發話者也不似故意要大聲說話，好像是天生如
此，甚或內功已達超凡入聖的境界，你直覺地提高警戒。
MSG1
 ]) );
        set( "exits", ([
             "south" : "/d/eastland/saulin_temple/grass6" ]) );
        set("pre_exit_func",([
            "cave" : "do_say" ]) );
	reset();
}

init()
{
     add_action( "do_say" , "say" );
}

int do_say(string arg)
{
     if( arg != "詢問楞枷經的下落") {
         write("老衲已經說過, 請施主留步, 施主請自重\n");
	return 1;
     }
     if( this_player()->query_temp("book_quest/step")==3 ) {
         write(@MSG2
你只聽得一個蒼老的聲音說道：嗯！是方丈派你來的啊！
好! 就讓你進去吧。
一陣微風吹過, 你的身子突然騰空而起, 掉入一個漆黑的洞穴中。
MSG2
);
         tell_room( environment(this_player()),
   sprintf("你看到一道黑影將%s捲起,很快地不見了。\n",this_player()->query("c_name"))
              , this_player() );
         this_player()->move_player("/d/eastland/saulin_temple/cave","SNEAK");
                    }
   else {
         write("一個蒼老的聲音說道：抱歉！沒有方丈的法旨, 誰也不能進去.\n");
	            }
      return 1;
}
