
             東方皇帝陵寢區域開放說明  --  作者 Almuhara  at 94/11/1
             ========================
 
I. 背景 :
	多年以前，東方大國之國師  孝光遊歷東方大陸，無意間發現一處鍾天地
	之靈氣所形成的寶穴。孝光細細觀察此地後，稟告皇上將陵寢設置於此，
	可保風調雨順、國運昌隆。皇帝素喜收集寶劍，下旨將歷年收集之寶劍盡
	收於陵寢中，此即劍冢之由來。又大國師  孝光在皇上賓天後，即退隱至
	墓中，負責守衛陵墓。

II. 適合等級 :
	此區域適合15級以上之玩家進入。
		 
III. 任務概要 :
	任務 ： 消滅「 天罪 」。
	
	「 天罪 」乃魔族三大神兵之一，素以兇名著稱。東方皇帝將其收入劍冢
	陪葬，然而「 天罪 」上一顆具有鎮壓作用之寶石，卻不知為何而失落，
	致使「 天罪 」吸取寶穴靈氣精華，幻化成形。此任務即在消滅「 天罪 
	」這人間兇獸。
 
	 
IV.  動物列表
 
動物名稱    檔名          等級  AC/DB  WC  傷害範圍  武器裝備   特殊能力
=========== ============= ====  ====== === ========= ========== ========
蟑螂        cockroach     1     8/0    3   1-3
筍龜        beetle        2     10/4   5   4-8       
青竹絲      snake         5     25/10  8   4-5                  噴毒
盜墓賊      thief         5     40/5   20  5-13      W)盜墓者匕
						       首
墓地守衛    guard1        11    52/10  5   5-5       W)青鋼長劍
						     A)銅盔帽
						     A)鐵鱗甲
金龍	    dragon        15    78/30 30  25-30
聖地守衛    holy_guard1   15    72/20  45  15-30     A)伏魔聖盔
聖地守衛    holy_guard2   15    54/15  39  10-35     A)東天聖甲
聖地守衛    holy_guard3   15    78/12  50  12-42     A)滅魔鞋
聖地守衛    holy_guard4   15    70/10  48  18-45     A)除魔盾
火之護衛    fire_guard    15    75/13  40  15-38     A)火之護符 火焰攻擊
						     A)火焰脛甲
水之護衛    water_guard   15    78/11  42  12-39     A)水之護符 寒冷攻擊
						     A)神水戒
風之護衛    wind_guard    15    77/14  46  14-36     A)風之護符 自我醫療
						     A)清風靴
雷之護衛    thunder_guard 15    70/8   55  25-45    A)雷之護符 電系攻擊
						     A)雷電手套
小善童      good_boy      17    85/20  45  10-30     W)金虹劍   神聖攻擊
						     A)白肚兜
						     I)七彩鑰匙
小惡童      evil_boy      17    80/25  40  15-35     W)邪皇匕   邪惡攻擊
						     A)黑肚兜
劍聖        sword_saint   18    110/45 50  30-40     W)古劍「蒼 劍氣攻擊
						       松」	
劍魂        sword_soul    18    105/40 45  25-35     W)名劍「長 劍氣攻擊
						       歌」 
劍奴	    sword_slave   18    100/35 40  20-30     W)寶劍「屠	劍氣攻擊
                                                       刀」
『 天罪 』  sky_guilt     19    120/50 80  40-80     
大國師 孝光 master        19    60/45  35  20-30     W)天師令   轉移攻擊
						     A)紫金道冠 電系攻擊
						     A)天師靴
						     A)大國師袍
						     A)天師護符
						     A)渾沌戒
						     A)五色印

V. 武器列表
 
武器名稱     檔案名稱       武器類別     WC   傷害範圍     特殊攻擊
===========  =============  ===========  ===  ===========  ===========
盜墓者匕首   dagger1        dagger       14   6-11         
邪皇匕       evil_dagger    dagger       30   15-30        
金虹劍       sunsword       shortblade   30   18-35        劍光
古劍「蒼松」 antique_sword  longblade    32   20-34     
名劍「長歌」 famous_sword   longblade    33   20-35 
寶劍「屠刀」 gemmy_sword    longblade    34   20-33
天師令       ling           wand         41   20-38        轉移防具、銀光
『 天罪 』   d_sky_guilt    long_blade   45   30-55        吸血、流血
 
VI. 防具列表
 
防具名稱   檔名           形態     質料     AC/DB    特殊效果
=========  =============  =======  =======  =======  =======================
白肚兜     white_du_do    body     cloth    15/3     divine 10, evil -5
黑肚兜     black_du_do    body     cloth    15/3     divine -5, evil 10
伏魔聖盔   helmet1        head     light_m  6/2      evil 5 
東天聖甲   plate1         body     light_m  35/0     evil 20
滅魔鞋     shoes1         feet     cloth    6/3      evil 5, 
除魔盾     shield2        shield   light_m  6/2      evil 5, cold 5
火之護符   fire_amulet    misc     cloth    0/5      fire 15, cold -10
水之護符   water_amulet   misc     cloth    0/5      cold 15, fire -10 
風之護符   wind_amulet    misc     cloth    0/5      evil 15, divine -10
雷之護符   thunder_amulet misc     cloth    0/5      electric 15, mental -10
火焰脛甲   fire_leggings  legs     leather  6/2      fire 5,cold -10,con -1
神水戒     water_ring     finger   element  0/4      cold 5, fire -10
						     inner-force 10, dex -1
清風靴     wind_boots     feet     cloth    6/2      dodge 15, pie -1
雷電手套   thunder_gloves hands    cloth    5/2      electric 10, poison -5
						     parry 10,int -1,str -1
五色印     shield1        shield   stone    8/6      none 5,evil 5,block 7
天師護符   master_amulet  misc     cloth    0/7      fire 6, cold 6,
						     energy 6, electric 6
大國師袍   master_robe    body     cloth    35/10    evil 10, none 2
紫金道冠   master_hat     head     mage     8/3      evil 5, divine 5,
						     mental 4
天師靴     master_boots   feet     cloth    6/4      divine 10, none 2
渾沌戒     master_ring    finger   element  0/7      poison 5, magic 10

VII. 物品列表
 
物品名稱      檔名         形態    特殊用途
==========    ============ ======= =========
九轉金丹      great_pill   藥品    quest
金龍珠        orbkey       鑰匙    開陵墓門        
七彩鑰匙      key1         鑰匙    開劍冢門
皇冠          crown        物品    陷阱
龍袍          robe         物品    陷阱
發黃的羊皮紙  paper1       物品    提示
短函          paper2       物品    提示
紅寶石        ruby         物品    鎮壓『 天罪 』
