// File: /u/i/iris/beholder/entrance.c
// Generated by Roommaker Sat Nov  4 07:08:10 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑色山谷入口");
	ob->set_long( @LONG_DESCRIPTION
這裡是諾頓大陸最奇特的種族－眼魔生存的地方, 前面一片死氣
沉沉, 不愧被稱為黑色山谷。從前有很多冒險者進去後, 就不曾活著
出來...., 近年來這種情況已有改善, 不少勇敢的商人已經出現在眼
魔城中, 不過在城外可能還有一些危險的生物, 你最好考慮清楚再往
前走, 以免遭到不測。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"down" : "/u/i/iris/beholder/valley1", 
		"up" : "/u/i/iris/workroom" ]) );
	ob->reset();
}
