// File: /d/eastland/dragon/cave6.c
// Generated by Roommaker Sat Nov 25 14:00:30 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("龍穴");
	ob->set_long( @LONG_DESCRIPTION
當你進入此洞穴時你發現此處是一個火山熔洞，四周都是奇怪的火紅色岩石，並且
有時有一些奇怪的岩石結晶，當其被火光映照之時，會反射出絢麗的光線，加上原有的
火紅構成一副優美的景色，令你幾乎忘了身在何處。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/dragon/cave20", 
		"west" : "/d/eastland/dragon/cave21" ]) );
	ob->set( "objects", ([ 
		"fighter2" : "/d/eastland/dragon/monster/fighter", 
		"fighter1" : "/d/eastland/dragon/monster/fighter", 
		"fighter3" : "/d/eastland/dragon/monster/fighter" ]) );
	ob->reset();
}
