// File: /d/eastland/dragon/cave13.c
// Generated by Roommaker Sat Nov 25 14:02:39 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地下城出口");
	ob->set_long( @LONG_DESCRIPTION
此處是一個古老的地下城房間，此處的牆壁及地板都是以大理石鋪設成的同時牆上正
有幾隻火把燃燒著，而天花板上則有許多的奇怪的小孔，應該是此地下城的通風孔，由四
周的景物看來此地必定有千年以上的歷史，但是景物依舊且空氣清新，你不得不佩服當初
設計人的匠心與才氣，你的前方似乎有一些不同於火把的光線透出。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/dragon/cave10", 
		"south" : "/d/eastland/dragon/cave18" ]) );
	ob->set( "objects", ([ 
		"soldier2" : "/d/eastland/dragon/monster/soldier", 
		"soldier1" : "/d/eastland/dragon/monster/soldier" ]) );
	ob->reset();
}
