// File: /d/eastland/dragon/cave21.c
// Generated by Roommaker Sat Nov 25 14:00:38 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("龍穴");
	ob->set_long( @LONG_DESCRIPTION
你發現此處是一個火山熔洞，四周都是奇怪的火紅色岩石，並且有時有一些奇怪的巖
石結晶，當其被火光映照之時，會反射出絢麗的光線，加上原有的火紅構成一副優美的景
色，令你幾乎忘了身在何處。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/dragon/cave6", 
		"west" : "/d/eastland/dragon/cave7" ]) );
	ob->reset();
}
