// File: /d/eastland/dragon/cave36.c
// Generated by Roommaker Sat Nov 25 14:08:09 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地下城");
	ob->set_long( @LONG_DESCRIPTION
這是一間十分秀氣的房間，因為它裡面的擺飾全部漆以粉紅色，當以進入此房間
時你還以為你自己是置身於夢中呢，有一個書桌放在左角，其旁有一個梳□臺，其上
有一一面大鏡子，左側則有一張大床，當你靠近它時有陣陣幽香由床上傳出，左面牆
上還掛著一些弓箭式的武器，看起來此屋的主人似乎能文能武。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/dragon/cave35" ]) );
	ob->reset();
}
