// File: /d/eastland/dragon/cave12.c
// Generated by Roommaker Sat Nov 25 14:02:24 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地下城");
	ob->set_long( @LONG_DESCRIPTION
此處是一個古老的地下城的房間，此處的牆壁及地板都是以大理石鋪設成的同時牆上正
有幾隻火把燃燒著，這房間擺設簡陋，僅有一張木床，一張木桌及幾張石椅，但是在屋子的
角落有一堆堆的木材，真不知屋主要這許多木材來做什麼，也許是一個樵夫吧!
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/dragon/cave10" ]) );
	ob->set( "objects", ([ 
		"woodman" : "/d/eastland/dragon/monster/woodman" ]) );
	ob->reset();
}
