// File: /d/eastland/dragon/cave29.c
// Generated by Roommaker Sat Nov 25 14:06:21 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大戶之家");
	ob->set_long( @LONG_DESCRIPTION
這裡是一個富麗堂皇的房間，四處都是以黃金沏造成的傢俱，而地板則是以珍貴的
紅珊玉製成，當人踩在其上一種透骨的清涼湧上心頭令人神清氣爽，天花板則是彩色琉
璃瓦，而由千年麝香鯨油製成的火把中傳出一股似有似無的神秘芳香，讓你有置身仙境
的感覺，真不愧是富可敵國的鄭大戶所擺出的排場。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/dragon/cave30", 
		"south" : "/d/eastland/dragon/cave27" ]) );
	ob->set( "objects", ([ 
		"man1" : "/d/eastland/dragon/monster/man1" ]) );
	ob->reset();
}
