// File: /d/eastland/dragon/cave15.c
// Generated by Roommaker Sat Nov 25 14:03:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地下城");
	ob->set_long( @LONG_DESCRIPTION
此處是一個古老的地下城，此處的牆壁及地板都是以大理石鋪設成的同時牆上正有幾
只火把燃燒著，而天花板上則有許多的奇怪的小孔，應該是此地下城的通風孔，由四周的
景物看來此地必定有千年以上的歷史，但是景物依舊且空氣清新，你不得不佩服當初設計
人的匠心與才氣，你的北方有一個奇特的房間，其外面各掛著許多的風乾植物及動物，看
去十分詭異。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/dragon/cave11", 
		"north" : "/d/eastland/dragon/cave17" ]) );
	ob->reset();
}
