// File: /d/eastland/dragon/cave19.c
// Generated by Roommaker Sat Nov 25 14:03:53 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地下城");
	ob->set_long( @LONG_DESCRIPTION
此處是一個古老的地下城，此處的牆壁及地板都是以大理石鋪設成的同時牆上正有幾
只火把燃燒著，而天花板上則有許多的奇怪的小孔，應該是此地下城的通風孔，由四周的
景物看來此地必定有千年以上的歷史，但是景物依舊且空氣清新，你不得不佩服當初設計
人的匠心與才氣。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/dragon/cave14" ]) );
	ob->set( "objects", ([ 
		"artisan" : "/d/eastland/dragon/monster/artisan" ]) );
	ob->reset();
}
