// File: /d/eastland/dragon/cave8.c
// Generated by Roommaker Sat Nov 25 14:01:06 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("龍穴");
	ob->set_long( @LONG_DESCRIPTION
你發現此處是一個火山熔洞，四周都是奇怪的火紅色岩石，並且有時有一些奇怪的
岩石結晶，當其被火光映照之時，會反射出絢麗的光線，加上原有的火紅構成一副
優美的景色，令你幾乎忘了身在何處。你的前方所傳來的腥味越來越濃的，現在每
當你踏出一步，就不禁有毛骨悚然的感覺，前方同時已傳來野獸的低吼聲。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/dragon/cave5", 
		"west" : "/d/eastland/dragon/cave9" ]) );
	ob->reset();
}
