// File: /u/l/layuter/elf/elf1.c
// Generated by Roommaker Thu Nov 11 14:52:14 1993

#include "../layuter.h"

inherit ROOM;
int layuteraa;

void create()
{
	::create();
	set_short("龍穴");
	set_long( @C_LONG_DESCRIPTION
此處是一個火山熔洞，四周都是奇怪的火紅色岩石，並且有時有一些奇怪的岩石結晶
，當其被火光映照之時，會反射出絢麗的光線，此處有一個奇怪的巨石，其旁有許多摩擦
的痕跡，地上並有許多石屑，在此處的東方有一個用稻草覆蓋的窩，其旁並有許多的血跡
，也許是某一猛獸的巢穴。
C_LONG_DESCRIPTION
	);
set("item_desc",([
    "stone":"這塊石頭看起來十分奇怪。\n"]));

	set("objects",([
	    "Chilin": Ldmonster"chilin"]));
	set( "light", 0 );
	set( "exits", ([
	    "east" : Lcave"cave8"
	]) );
	reset();
}

void init()
{
 add_action("do_move","move");
 }
 
int do_move(string arg)
{
  if (!arg||arg!="stone") return 0;
  if ((int) this_player()->query_stat("str")<15) 
  {
   write("你的力量不夠搬不動石頭，回去練一練力量再來吧!!\n");
   }
  else if (layuteraa==1)
   {
   tell_room(this_object(),"石頭緩緩移動，遮住往下的樓梯\n");
   layuteraa=0;
   set("exits",([
       "east":Lcave"cave8"]));
       }  
  else{
   layuteraa=1;
   tell_room(this_object(),"石頭緩緩移動，露出一個往下的樓梯\n");
   add("exits",([
       "down":Lcave"cave10"]));           
        this_player()->set_explore("eastland#1");
  }     
  return 1;
}


void reset()
{
   ::reset();
   set("exit",([
       "east":Lcave"cave8"
       ]));   
   layuteraa=0;    
}


