// File: /u/l/layuter/elf/elf1.c
// Generated by Roommaker Thu Nov 11 14:52:14 1993

#include "../layuter.h"
inherit ROOM;

void create()
{
	::create();
	set_short("噴泉");
	set_long( @C_LONG_DESCRIPTION
這裡是一個乾枯的噴泉，除了石頭以外這裡空無一物。
C_LONG_DESCRIPTION
	);
	set( "light", 0 );
	set( "exits", ([
	    "out" : Lcave"cave30"
	]) );
	set("layuter_dig",1);
	reset();
}
void init()
{
 add_action("do_search","search");
 this_player()->set_explore("eastland#3");
}
void reset()
{
	::reset();
	set("beer_control",1);
}

int do_search(string arg)
{
	object obj;
        if (!arg) arg="here";
	if( arg!="here")
	  return notify_fail(
	    "你在這裡中找來找去，但並沒有找到任何奇特的東西。\n"
	  );
        else {
          if ((string)this_player()->query("class")=="scholar") {
 write("你發現噴泉北邊的土似乎有點鬆動，於是就試著去挖挖看.............，\n"); 
 write("挖著挖著...............突然一團黑影從土□竄了出來..............，\n");
 write("你的面前一團黑影正不斷的在遊移著，你聽到一個聲音從黑影中傳了出來：\n");
 write("我被困在□面好久了...謝謝你幫我離開...以後假如須要幫助，在所不辭。\n");
 write("你看到那團黑影漸漸消散了。\n");
          this_player()->set("demand/dark",2);
          } 
          else
            write( "這噴泉北邊的土似乎點鬆動。\n");
   	  return 1;
	}
}
