// File: /u/l/layuter/elf/elf1.c
// Generated by Roommaker Thu Nov 11 14:52:14 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("龍穴");
	set_long( @C_LONG_DESCRIPTION
你已經走完洞窟，來到一個神秘的地方，此處是一個四周都圍繞著高山峻嶺的山谷
，山谷的的中央有一個漂亮的湖，湖的四周有許多的垂楊，並且遍地鮮花綠草，並且從
此望去天空明晰可見，這裡真是個世外桃源，但是有點奇怪的是，這裡居然看不到任何
生物的蹤跡，真是有點糟蹋此處之美。湖的前方有一座祭壇，並且它的右方有一巨鼓。
C_LONG_DESCRIPTION
	);
	set("beat_control",1);
	set_outside("dragoncave");
	set( "light", 1 );
	set( "exits", ([
		"east" : Lcave"cave21"
	]) );
	reset();
#include <replace_room.h>
}
