// File: /u/l/layuter/elf/elf1.c
// Generated by Roommaker Thu Nov 11 14:52:14 1993

#include "../layuter.h"

inherit ROOM;
int room_control;

void create()
{
	::create();
	set_short("森林");
	set_long( @LONG_DESCRIPTION
這裡是一座古老的原始森林，這裡的所有樹木看起來都是古老而滄桑，彷佛歷經無
數歲月的磨練，但當你走在森林步道上，耳聽黃鶯清脆的鳴叫並享受芬多精的薰陶，這
一切切都讓冒險者的心，不知不覺中平靜下來。
LONG_DESCRIPTION
	);
	set_outside("dragoncave");
	set( "light", 1 );
	set( "exits", ([
		"north" : Lcave"cave13",
		"west" : Lcave"cave32",
		"south" : Lcave"cave33",
		"east"  : Lcave"cave34"
	]) );
	reset();
}

void init()
{
 add_action("do_search","search");
 }

void reset()
{
	::reset();
	room_control=this_object()->query("room_control");
	room_control++;
	if (room_control==5) room_control=1;
	set("room_control",room_control);
	set("tree_find",0);
}

int do_search(string arg)
{
	object ob1,ob2,ob3;
	
	ob1=(object)Lcave"cave18";
    if (!arg) arg="here";
	if( arg!="here")
		return notify_fail( 
			"你在這裡中找來找去，但並沒有找到任何奇特的東西。\n");

    else if ((int)ob1->query("room_control")==3 && !ob1->query("tree_find"))  {
        ob2=new(Lditem"layuter_tree");
        ob3=environment(this_player());
        ob2->move(ob3);
		write( 
			"一棵神秘的樹突然從你的眼前冒出。\n");
		ob1->set("tree_find",1);
		return 1;
	}
	return notify_fail(
			"你在這裡中找來找去，但並沒有找到任何奇特的東西。\n");
}
