// File: /d/noden/hawk/path2.c
// Generated by Roommaker Mon Dec  4 21:10:38 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石階坡道");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在一條簡陋的石階坡道上，幾塊大型的石塊被堆置在坡道的兩旁，以
免行人失足跌入山谷，在你西南不遠處好像有幾間茅屋，山中不時傳來不知名野獸的
啼叫聲。
LONG_DESCRIPTION
	);

	ob->set_outside( "hawk" );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/hawk/path3", 
		"north" : "/d/noden/hawk/path1" ]) );
	ob->reset();
}
