// File: /d/noden/hawk/path1.c
// Generated by Roommaker Mon Dec  4 21:10:31 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山路");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在一條崎嶇的山路上，往東北邊下坡處是一片長著疏落青草的平原
矮丘，往南是一條上山的石階坡道，這裡的山路並不是很寬，只能容納兩個人並肩
而行，東邊是深不見底的深谷，西邊則是幾乎直立的峭壁，山谷深處傳來陣陣「嗚
....嗚....」的叫聲，不知道是什麼東西。
LONG_DESCRIPTION
	);

	ob->set_outside( "hawk" );
	ob->set( "exits", ([ 
		"south" : "/d/noden/hawk/path2", 
		"northeast" : "/d/noden/10,10.noden" ]) );
	ob->set( "objects", ([ 
		"scout#2" : "/d/noden/hawk/monster/scout", 
		"scout#1" : "/d/noden/hawk/monster/scout" ]) );
	ob->reset();
}
