// File: /d/noden/hawk/pit.c
// Generated by Roommaker Mon Dec  4 21:11:26 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴底部");
	ob->set_long( @LONG_DESCRIPTION
你現在來到一個極深的洞穴底部，在你頭頂上方很高的地方遠遠地有一個圓形的
出口，你可以看到外面的一小片天空。這裡地上一片狼藉——許多破碎的骨頭碎片和
衣物，像是被一群飢餓的野獸囫圇撕裂所殘留的，在這個地方你彷佛可以聽到從前的
犧牲者慘叫的聲音，一種絕望和恐怖的感覺正襲擊著你的理智。
LONG_DESCRIPTION
	);

	ob->reset();
}
