// File: /d/noden/hawk/room2-10.c
// Generated by Roommaker Mon Sep 30 14:37:18 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("內城觀察哨");
	ob->set_long( @LONG_DESCRIPTION
這裡是整個天空之城最高的地方，因此也派有數名眼力極佳哨兵負責觀察，
眼尖的你發現了東邊有一個淡綠色的霧團，不知道那是啥東東。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/hawk/room2-21", 
		"southdown" : "/d/noden/hawk/room2-8" ]) );
	ob->set( "objects", ([ 
		"sentry" : "/d/noden/hawk/monster/scout", 
		"sentry2" : "/d/noden/hawk/monster/scout" ]) );
	ob->reset();
}
