// File: /d/noden/hawk/room2-13.c
// Generated by Roommaker Mon Sep 30 14:38:31 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("中央大道");
	ob->set_long( @LONG_DESCRIPTION
你走在內城最寬廣的中央大道，你可以看到許許多多的鳥人或飛行在空中，
或走在道路上。但是他們都用懷疑的眼神看著你，當你想上前與他們攀談的時候
，更是躲你躲的遠遠的，真不知道為什麼他們會這樣排斥你。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/noden/hawk/room2-11", 
		"southeast" : "/d/noden/hawk/room2-14" ]) );
	ob->set( "objects", ([ 
		"man" : "/d/noden/hawk/monster/man", 
		"woman" : "/d/noden/hawk/monster/woman" ]) );
	ob->reset();
}
