// File: /d/noden/hawk/room1-13.c
// Generated by Roommaker Mon Sep 30 10:32:49 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("貧民窟");
	ob->set_long( @LONG_DESCRIPTION
這裡是天空之城裡最灰暗的角落。由於戰爭的因素，鳥人們過份的重視戰
鬥能力的高低，因此許多年邁的老戰士們就失去了賴以為生的依據，如果沒有
親人供養的，最後的下場通常是來到這貧民窟渡過餘生。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/hawk/room1-12", 
		"southeast" : "/d/noden/hawk/room1-14" ]) );
	ob->set( "objects", ([ 
		"older" : "/d/noden/hawk/monster/older" ]) );
	ob->reset();
}
