// File: /d/noden/hawk/room2-17.c
// Generated by Roommaker Mon Sep 30 14:39:08 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("中央大道");
	ob->set_long( @LONG_DESCRIPTION
你繼續走在內城的道路上，觀察鳥人們所建築的房子，發現大部份比較雄
偉的屋子都是頗新的，而老舊的房子則都是破破爛爛的，但是還是很多人住，
而較新較好的房子反而空空蕩蕩，或許是鳥人天性喜歡住在比較簡陋的房子
吧....但不知道為什麼會多出這些新建築呢？
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/hawk/room2-16", 
		"northeast" : "/d/noden/hawk/room2-19" ]) );
	ob->reset();
}
