// File: /d/noden/hawk/room2-2.c
// Generated by Roommaker Mon Sep 30 14:33:49 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("碧玉森林");
	ob->set_long( @LONG_DESCRIPTION
這裡是鳥人族人最引以自豪的碧玉森林，所有的樹幹都泛著淡綠色的光
茫，又彷佛可以直視入樹幹的內部。這種樹即使是如你一般見聞廣博的旅行
家也是前所未見的。樹林裡更瀰漫著一股淡淡的香味，更是讓你留連忘返。
樹梢上開滿了許多翠綠色的花朵(flower)，同時也有不少的果實(fruit) ，　
看起來很好吃的樣子。　
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "c_item_desc", ([ 
		"fruit" : "飽滿的紫色果子，你想要吃一口嗎？\n", 
		"flower" : "淡綠色的花朵，同時又散發出淡淡的香味。\n" ]) );
	ob->set( "exits", ([ 
		"north" : "/d/noden/hawk/room2-4" ]) );
	ob->set( "objects", ([ 
		"injured" : "/d/noden/hawk/monster/injured" ]) );
	ob->reset();
}
