// File: /d/noden/hawk/room1-20.c
// Generated by Roommaker Mon Sep 30 10:32:27 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小屋");
	ob->set_long( @LONG_DESCRIPTION
這是一間裝飾很簡陋的小屋，不過打掃的滿乾淨的，而且擺設也滿有
格調的，或許在這居住的是一位很有氣質的人唷。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/noden/hawk/room1-14" ]) );
	ob->set( "objects", ([ 
		"war" : "/d/noden/hawk/monster/bernice" ]) );
	ob->reset();
}
