// File: /d/noden/hawk/room1-19.c
// Generated by Roommaker Mon Sep 30 10:33:14 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("軍營哨站");
	ob->set_long( @LONG_DESCRIPTION
鳥人族的軍營，你可以看到很多年輕的士兵們在這裡努力的鍛練自己的武
藝，希望能慢慢的提升自己的地位，也因此整棟建築裡充滿了汗臭味和吆喝的
聲音。外面則是一高聳的小塔臺，上面站了個哨兵，負責觀察敵人的動向。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/hawk/room1-12" ]) );
	ob->set( "objects", ([ 
		"soldier" : "/d/noden/hawk/monster/soldier", 
		"scout" : "/d/noden/hawk/monster/scout", 
		"soldier1" : "/d/noden/hawk/monster/soldier" ]) );
	ob->reset();
}
