// File: /d/noden/hawk/room3-6.c
// Generated by Roommaker Mon Sep 30 14:41:43 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("領袖辦公室");
	ob->set_long( @LONG_DESCRIPTION
鳥人族歷代領袖所居住的地方，因此牆邊放滿了許許多多的兵器，都是
以往的領袖所使用的神兵利器和具有強大防護力的鎧甲，不過這邊戒備森嚴
，勸你還是不要圖謀不軌。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/noden/hawk/room3-1" ]) );
	ob->set( "objects", ([ 
		"leader" : "/d/noden/hawk/monster/adolph" ]) );
	ob->reset();
}
