// File: /d/noden/hawk/room2-16.c
// Generated by Roommaker Mon Sep 30 14:39:01 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("中央大道");
	ob->set_long( @LONG_DESCRIPTION
你走在內城最寬廣的中央大道，你可以看到許許多多的鳥人或飛行在空中，
或走在道路上。但是他們都用懷疑的眼神看著你，當你想上前與他們攀談的時候
，更是躲你躲的遠遠的，真不知道為什麼他們會這樣排斥你。
    路旁有一棟黑色的建築，屋頂上的煙囪正冒出一股股濃濃的黑煙，同時也傳
來噹噹的打鐵聲，看來是間鐵匠鋪。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/hawk/room2-14", 
		"enter" : "/d/noden/hawk/smithroom", 
		"north" : "/d/noden/hawk/room2-17" ]) );
	ob->reset();
}
