// File: /d/noden/hawk/room2-4.c
// Generated by Roommaker Mon Sep 30 14:34:09 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("碧玉森林");
	ob->set_long( @LONG_DESCRIPTION
這裡是鳥人族人最引以自豪的碧玉森林，所有的樹幹都泛著淡綠色的光
茫，又彷佛可以直視入樹幹的內部。這種樹即使是如你一般見聞廣博的旅行
家也是前所未見的。樹林裡更瀰漫著一股淡淡的香味，更是讓你留連忘返。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/hawk/room2-2", 
		"northeast" : "/d/noden/hawk/room2-5" ]) );
	ob->set( "objects", ([ 
		"tailor" : "/d/noden/hawk/monster/saw" ]) );
	ob->reset();
}
