// File: /d/noden/hawk/room2-15.c
// Generated by Roommaker Mon Sep 30 14:38:50 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("內城中心");
	ob->set_long( @LONG_DESCRIPTION
你現在站在天空之城內城的中心，雄偉高聳的建築物代表了鳥人族科技
工業與建築技術的高明，兩側樓房排列的整整齊齊，不過最引起你注意的是
這些房子都沒有門。當你正在懷疑的時候，你看到幾隻鳥人從牆上的大窗戶
飛了出來，才讓你恍然大悟。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/hawk/room1-9", 
		"north" : "/d/noden/hawk/room2-14" ]) );
	ob->reset();
}
