// File: /d/noden/hawk/room2-19.c
// Generated by Roommaker Mon Sep 30 14:39:18 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("軍備戰用道路");
	ob->set_long( @LONG_DESCRIPTION
離開了中央大道，你又開始感到一股沉重的壓力，往來的人潮變少了，但是
卻多了來來往往巡邏的士兵。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/hawk/room2-17", 
		"northup" : "/d/noden/hawk/room2-21" ]) );
	ob->reset();
}
