// File: /d/noden/hawk/room1-16.c
// Generated by Roommaker Mon Sep 30 10:31:55 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("光輝森林");
	ob->set_long( @LONG_DESCRIPTION
名雖曰光輝森林，不過你看了半天還是不知道這森林有啥特別的地方，讓你
覺得有受騙了的感覺。四處晃晃，你突然覺得這裡的空氣遠比外面新鮮多了，讓
你感到身心舒爽，精神也好多了。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"west" : "/d/noden/hawk/room1-15", 
		"northeast" : "/d/noden/hawk/room1-17" ]) );
	ob->reset();
}
