// File: /d/noden/hawk/room2-14.c
// Generated by Roommaker Mon Sep 30 14:38:39 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("市政大廳");
	ob->set_long( @LONG_DESCRIPTION
映在你眼前的是天空之城的行政中心，鳥人族平常聚會商議事情就是在這邊舉
行，你可以看到許多強壯的士兵守護在這裡。往上就可以進入市政大廳，你可以進
去參觀參觀，說不定可以看到一些奇奇怪怪的東西。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"northwest" : "/d/noden/hawk/room2-13", 
		"south" : "/d/noden/hawk/room2-15", 
		"up" : "/d/noden/hawk/room3-1", 
		"northeast" : "/d/noden/hawk/room2-16" ]) );
	ob->reset();
}
