// File: /d/noden/hawk/room1-15.c
// Generated by Roommaker Mon Sep 30 10:32:13 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小公園");
	ob->set_long( @LONG_DESCRIPTION
一個小小髒髒的公園，是這些老人閒來無事時聊天閒晃的地方，你可以看到
不少年老力衰的鳥人在這邊聊天。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"northwest" : "/d/noden/hawk/room1-14", 
		"east" : "/d/noden/hawk/room1-16" ]) );
	ob->set( "objects", ([ 
		"older3" : "/d/noden/hawk/monster/older", 
		"older1" : "/d/noden/hawk/monster/older", 
		"oldera" : "/d/noden/hawk/monster/older1", 
		"older2" : "/d/noden/hawk/monster/older" ]) );
	ob->reset();
}
