// File: /d/noden/hawk/room2-8.c
// Generated by Roommaker Mon Sep 30 14:37:05 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("軍備戰用道路");
	ob->set_long( @LONG_DESCRIPTION
走到了這裡，你又開始感到一股沉重的壓力，往來的人潮變少了，但是
卻多了來來往往巡邏的士兵，戒備森嚴的氣氛讓你感到渾身不自在。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/hawk/room2-7", 
		"northup" : "/d/noden/hawk/room2-10", 
		"southeast" : "/d/noden/hawk/room2-11" ]) );
	ob->set( "objects", ([ 
		"soldier3" : "/d/noden/hawk/monster/fighter", 
		"soldier" : "/d/noden/hawk/monster/soldier", 
		"soldier2" : "/d/noden/hawk/monster/soldier" ]) );
	ob->reset();
}
