// File: /d/noden/hawk/altar2.c
// Generated by Roommaker Sun Jan  9 07:54:22 1994

#include <mudlib.h>
#include "hawk.h"
inherit ROOM;

void create()
{
        object pontiff;

        ::create();
        set_short("圓形祭壇");
        set_long( @C_LONG_DESCRIPTION
你現在來到了一個圓形的大祭壇，祭壇中央有一個圓形的洞穴(pit)，在洞穴四周
散佈著六個石桌(table)，最大的一個石桌上放著一個三角錐(prymaid)，環繞著祭壇總
共有二十四根白色石柱(pillars)，祭壇的東、北、西三個方向都被極高的懸崖峭壁所
繞，往南是一片空地。
C_LONG_DESCRIPTION
        );

        set_outside( "hawk" );
        set( "item_desc", ([
                "table" : "這些石桌有大有小，全部都是圓形，似乎是某種魔法陣的裝置。\n",
                "prymaid" : @LONG_TEXT
這個三角錐是透明的，但又不是水晶或玻璃做的，它的一個平面正對著東方
太陽昇起的地方，祭壇四周二十四根石柱的影子映在三角錐內部，似乎排列
成什麼符號 ....
LONG_TEXT
,
                "pillars" : @LONG_TEXT
這些石柱都是大理石做成的，有高有低，有粗有細，不知道當初建造這些石柱
的人為什麼要把它們做成這樣，難道有什麼機關 ....
LONG_TEXT
,
                "pit" : @LONG_TEXT
這個洞穴深不見底，跳(jump)下去不知道會有什麼後果？你似乎隱約聽到洞穴
底部傳來一陣女人哭泣的嗚咽聲。
LONG_TEXT
 ]) );
        set( "exits", ([
                "south" : "/d/noden/hawk/altar1" ]) );

        // pontiff is unique, one reboot one pontiff
        pontiff = new( MOB"pontiff");
        pontiff->move(this_object());

        set( "objects", ([
                "guard#1": "/d/noden/hawk/monster/altar_guard",
                "guard#2": "/d/noden/hawk/monster/altar_guard",
                "guard#3": "/d/noden/hawk/monster/altar_guard" ]) );

        reset();
}

//int clean_up()
//{

//      return 0;
//}

void init()
{
        if( this_player() ) this_player()->set_explore("noden#23");
        add_action("do_jump","jump");
        add_action("put_misc", "put");
}

int do_jump(string str)
{
        if ( (!str) || (str != "pit") ) return 0;
        tell_object(this_player(),@LONG
你鼓起勇氣往這個小洞穴一跳，忽然一陣黑霧襲來，你暈了過去。
LONG
        );
        this_player()->set_temp("block_command",1);
        call_out ("to_go",5,this_player());
        return 1;
}

int put_misc(string str)
{
   	object misc,player;
	player = this_player();
   	misc = present( "sky amulet", this_player() );

   	if( !str )
   	{
        	write( "你要放啥?\n" );
        	return 1;
     	}
   	if( str != "amulet into prymaid" ) 
	{
        	write( "你要放啥在哪?\n" );
        	return 1;
      	}
   	if( !misc ) 
	{
        	write( "你身上沒有適當的東西可以放進三角錐!\n" );
         	return 1;
     	}
   	if( (string)misc->query("c_name")!="天空守護徽章" )
        	return 1;

	tell_room(environment(player),set_color(
		(string)player->query("c_name")+"把一枚閃閃發光的徽章放"+
		"入三角錐的裡面，頓時一道綠紅色的光芒從三角錐的內部直射"+
		"天際，四周的石柱發出悲鳴聲，你發現"+
		(string)player->query("c_name")+"身上的傷口發出金色的光"+
		"芒，一瞬間就癒合了。\n","HIG"),this_player() );

	tell_object(this_player(),"你把手中的天空守護徽章放入三角錐裡，"+
		"一時天雷勾動地火，綠紅色的光芒直射天際，四周的石柱發出"+
		"震耳欲聾的悲鳴聲。在你為之驚愕的同時，你身上的傷口竟都"+
		"癒合了。\n");

	player->set("medication_resistance", 0);
	player->set("hit_points", (int)player->query("max_hp"));
        player->set("spell_points", (int)player->query("max_sp"));
       	player->set("talk_points", (int)player->query("max_tp"));
        player->set("force_points", (int)player->query("max_fp"));
	misc->remove();
   	return 1;
}

int to_go()
{
        tell_object(this_player(),@LONG
過了不知道多久，你才醒了過來，發現自己身處在一個不知道是哪裡的地方。
LONG
        );
        this_player()->move_player(HAWK"room1-1","SNEAK");
        this_player()->set_temp("block_command",0);
        return 1;
}

