// File: /d/noden/hawk/clearing.c
// Generated by Roommaker Sun Jan  9 02:36:37 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("半山腰");
	set_long( @C_LONG_DESCRIPTION
你現在來到半山腰的一處平地，西邊的峭壁上有一處巨大的裂縫(crack)，南邊
和東邊都是斷崖，這裡有幾間簡陋的茅屋(hut)，看起來像是一般獵人外出時居住的
小屋，這裡的土地大部分都是光禿禿的黏土，靠近斷崖的地方長著幾棵樹(trees)，
從這裡往下看，你好像可以看見山谷底下有一個圓形的祭壇之類地方。
C_LONG_DESCRIPTION
	);

	set_outside( "hawk" );
	set( "item_desc", ([ 
		"hut" : "這些茅屋大部分都空無一物，通常只有在狩獵季節才有獵人到這裡暫住。\n", 
		"crack" : @LONG_TEXT
這個裂縫很大，看起來像是一個狹窄的山洞，恰可以容納一個人進入(enter)，不
過你似乎隱約看見裂縫中有幾對發亮的眼睛，或許是什麼野獸躲在裡面。
LONG_TEXT
, 
		"trees" : @LONG_TEXT
這些樹好像長期受到來自谷底的強風吹襲，枝幹都朝同一個方向彎曲，看起來
詭異之至。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/hawk/path4" ]) );
	set( "objects", ([
		"warrior": "/d/noden/hawk/monster/warrior" ]) );
	reset();
}

void init()
{
	add_action( "do_enter", "enter" );
}

int do_enter(string arg)
{
	switch( arg ) {
		case "hut":
			write( 
				"你逐一進入每一個小茅屋查看，但是並沒有發現任何有趣的東西。\n"
                             );
       			return 1;
			break;
		case "crack":
			tell_room( environment(this_player()), 
				this_player()->query("c_name") + "將自己擠進山邊的一個裂縫中。\n"
				,({this_player(),this_object() }) );
			this_player()->move_player( "/d/noden/hawk/crack1","SNEAK" );	
			return 1;
			break;
		default:
			return notify_fail( "進入哪裡？\n" );
	}
}
