// File: /d/eastland/1,16.east.c
// Generated by Roommaker Mon Jan 31 06:36:48 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("山丘");
	set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘組成的丘陵地上，這裡的地勢起伏
並不很大，青黃交錯的短草皮覆蓋著舉目所及的山丘，幾株大樹散
布在山坡上。你看到某個山丘上有座墳場, 一股詭異的烏雲籠罩著
這個小山頭, 或許你應該爬上去看看。
LONG_DESCRIPTION
	);

   set_outside( "eastland" );
   set( "no_monster", 1 );
	set( "exits", ([ 
           "north" : "d/eastland/11,13.east",
           "east" : "d/eastland/12,14.east" ]) );
   set( "original", "d/eastland/11,14" );
	set( "virtual_server", "/d/eastland/virtual/east_server" );
   set( "x_coordinate", 11 );
   set( "y_coordinate", 14 );
	reset();
}

void init()
{
   add_action( "climb_up", "climb" );
}

int climb_up(string arg)
{
   if( !arg || arg != "up" )
   return notify_fail( "你趴在地上往前爬, 看起來有夠蠢!\n" );
   write( "你慢慢地往上爬向山丘之頂。\n" );
   tell_room( environment(this_player()),
     "你看到"+this_player()->query("c_name")+"慢慢地往上爬。\n"
     , this_player() );
   this_player()->move_player( "/d/eastland/ianyeu/grave_yard1", "SNEAK" );
   return 1;
}
