// File: /d/eastland/8,5.east.c
// Generated by Roommaker Thu Jan 27 03:14:49 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("路口");
	set_long( @LONG_DESCRIPTION
你現在來到一處交叉路口，路邊有一塊大招牌，上面寫著「天馬號飛船載客站」
，若嵐城的西門就在你的東邊不遠處，往南一條筆直的大道通往南方的幽國城，向西
的道路 穿過一片草原通往古梅鎮。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "exits", ([ 
		"south" : "d/eastland/8,6.east", 
		"north" : "d/eastland/8,4.east", 
		"west" : "d/eastland/7,5.east", 
		"east" : "/d/eastland/easta/westgate" ]) );
	set( "original", "d/eastland/8,5" );
	set( "virtual_server", "/d/eastland/virtual/east_server" );
	set( "x_coordinate", 8 );
	set( "y_coordinate", 5 );
	reset();
#include <replace_room.h>
}

void init()
{
	if( !find_object("/d/std/cloud/airship_pegasus") )
		"/d/std/cloud/airship_pegasus"->frog();
}
