// File: /d/eastland/1,12.east.c
// Generated by Roommaker Wed Nov 22 13:04:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山丘");
	ob->set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘組成的丘陵地上，這裡的地勢起伏
並不很大，青黃交錯的短草皮覆蓋著舉目所及的山丘，幾株大樹散
布在山坡上。在北邊的山坡上，生長著許多蘆葦，蘆叢當中有一條狹
窄的小路，不知通向何處?
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/2,12.east", 
		"south" : "d/eastland/1,13.east", 
		"north" : "/d/eastland/liang_shan/out3" ]) );
	ob->set( "objects", ([ 
		"thief#2" : "/d/eastland/monster/mt_bandit", 
		"thief#1" : "/d/eastland/monster/mt_bandit" ]) );
	ob->set( "original", "d/eastland/1,12" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 1 );
	ob->set( "y_coordinate", 12 );
	ob->reset();
}
