// File: /d/eastland/12,5.east.c
// Generated by Roommaker Wed Nov 22 13:08:23 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("叉路");
	ob->set_long( @LONG_DESCRIPTION
你現在來到一處叉路，往北是一條黃泥夾著碎石的大路，通往捍衛北方的牧馬關
，往東的碎石路穿過一片碧綠的田野，通往東海濱的海威鎮，往西的大道通往繁華富
庶的京城「若嵐城」。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/13,5.east", 
		"west" : "d/eastland/11,5.east", 
		"north" : "d/eastland/12,4.east", 
		"south" : "d/eastland/12,6.east" ]) );
	ob->set( "original", "d/eastland/12,5" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 12 );
	ob->set( "y_coordinate", 5 );
	ob->reset();
}
