// File: /d/eastland/13,14.east.c
// Generated by Roommaker Wed Nov 22 13:08:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("平原");
	ob->set_long( @LONG_DESCRIPTION
你現在走在一片平地上，疏落的青草點綴著一些碎石，這裡開闊的視
野使你可以清楚地看到遠方的景物。你看到東北方有個小村莊。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"west" : "d/eastland/12,14.east", 
		"northeast" : "/d/eastland/ianyeu/hamlet_path1" ]) );
	ob->set( "original", "d/eastland/13,14" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 13 );
	ob->set( "y_coordinate", 14 );
	ob->reset();
}
