// File: /d/eastland/16,9.east.c
// Generated by Roommaker Wed Nov 22 13:10:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("青石道");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在一條濱海的青石大道上，東邊是一片潔白的沙灘，青石大道
向東南穿過一座雄偉的牌樓進入海威鎮，兩排高大的木棉樹種在大道兩旁，樹
影在青石板上映出一條條的斑紋。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "d/eastland/16,10.east", 
		"north" : "d/eastland/16,8.east", 
		"west" : "d/eastland/15,9.east", 
		"southeast" : "/d/eastland/haiwei/n_gate" ]) );
	ob->set( "original", "d/eastland/16,9" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 16 );
	ob->set( "y_coordinate", 9 );
	ob->reset();
}
