// File: /d/eastland/3,15.east.c
// Generated by Roommaker Wed Nov 29 02:35:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("平原");
	ob->set_long( @LONG_DESCRIPTION
你現在走在一片平地上，疏落的青草點綴著一些碎石，這裡開闊的視
野使你可以清楚地看到遠方的景物。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"west" : "d/eastland/2,15.east", 
		"north" : "d/eastland/3,14.east", 
		"south" : "d/eastland/3,16.east" ]) );
	ob->set( "original", "d/eastland/3,15" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 3 );
	ob->set( "y_coordinate", 15 );
	ob->reset();
}
