// File: /d/eastland/5,1.east.c
// Generated by Roommaker Wed Nov 22 13:15:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山丘");
	ob->set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘組成的丘陵地上，這裡的地勢起伏
並不很大，青黃交錯的短草皮覆蓋著舉目所及的山丘，幾株大樹散
布在山坡上。一座龐大的黑色山脈矗立在北方，遙遠的山頂上還冒
著嫋嫋的白煙。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"west" : "d/eastland/4,1.east", 
		"south" : "d/eastland/5,2.east", 
		"northeast" : "/d/eastland/volcano/wild1" ]) );
	ob->set( "original", "d/eastland/5,1" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 5 );
	ob->set( "y_coordinate", 1 );
	ob->reset();
}
