// File: /d/eastland/5,9.east.c
// Generated by Roommaker Wed Nov 22 13:16:43 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林");
	ob->set_long( @LONG_DESCRIPTION
你現在漫步在一座森林之中，繁茂的樹木散發出一股淡淡的、
舒爽宜人的氣息，你可以聽到樹林間小鳥吱吱喳喳的鳴叫聲，腳底
下一層落葉鋪滿了你所站立的地方。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/6,9.east", 
		"west" : "d/eastland/4,9.east", 
		"north" : "d/eastland/5,8.east", 
		"south" : "d/eastland/5,10.east" ]) );
	ob->set( "objects", ([ 
		"bar#1" : "/d/eastland/monster/barbarian", 
		"bar#2" : "/d/eastland/monster/barbarian" ]) );
	ob->set( "original", "d/eastland/5,9" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 5 );
	ob->set( "y_coordinate", 9 );
	ob->reset();
}
