// File: /d/eastland/7,18.east.c
// Generated by Roommaker Wed Nov 22 13:17:24 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("龍穴入口");
	ob->set_long( @LONG_DESCRIPTION
在你的眼前是一面高聳的山壁，有一個巨大的山洞在其左側，當你走到此處時，
你發現往山洞望去是無邊的黑暗，你想這應該是一個相當深隧的山洞，並且由山洞中
傳來陣陣的陰風中帶有濃厚的腥風，令人聞之慾睡，你想其中也許有前古猛獸居住其
中。
LONG_DESCRIPTION
	);

	ob->set_outside( "dragoncave" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"cave" : "/d/eastland/dragon/cave2", 
		"east" : "/d/eastland/8,18.east", 
		"north" : "/d/eastland/7,17.east" ]) );
	ob->reset();
}
