// File: /d/eastland/8,13.east.c
// Generated by Roommaker Mon Nov 20 15:19:09 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大石橋");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在一座長約一百公尺的大石橋上，羿水河滔滔不絕地在大石橋下
流過，河水流過橋孔，發出轟隆隆如雷的聲響，往北一條筆直的大道穿過一望無
際的田野，過石橋往南則是通往幽國城的官道。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "d/eastland/8,14.east", 
		"north" : "d/eastland/8,12.east" ]) );
	ob->set( "objects", ([ 
		"wife" : "/d/eastland/monster/bandit_wife", 
		"bandit" : "/d/eastland/monster/bandit" ]) );
	ob->set( "original", "d/eastland/8,13" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 8 );
	ob->set( "y_coordinate", 13 );
	ob->reset();
}
