// File: /d/eastland/9,3.east.c
// Generated by Roommaker Wed Nov 22 13:19:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山丘");
	ob->set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘組成的丘陵地上，這裡的地勢起伏
並不很大，青黃交錯的短草皮覆蓋著舉目所及的山丘，幾株大樹散
布在山坡上。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/eastland/10,3.east", 
		"west" : "d/eastland/8,3.east", 
		"south" : "d/eastland/9,4.east" ]) );
	ob->set( "objects", ([ 
		"hunter" : "/d/eastland/monster/hunter" ]) );
	ob->set( "original", "d/eastland/9,3" );
	ob->set( "virtual_server", "/d/eastland/virtual/east_server" );
	ob->set( "x_coordinate", 9 );
	ob->set( "y_coordinate", 3 );
	ob->reset();
}
