
		古梅鎮區域開放說明  --  作者 茹比   at 94/9/4
		==================

I. 歷史 :

    這裡原來是位於翰煙山下的一個小鎮，本來只有三十來戶的人家散佈在一片方圓
不到五里的臺地上，但是自從二十餘年前，飛仙一劍葉孤城與陸小鳳在禁城的一場鬥
智鬥力的精彩決戰後，每年十月皇上都要在此地舉辦武鬥大會，漸漸的，本鎮也成為
武林各幫派的兵家必爭之地。現在古梅鎮的繁華已經跟京城相差不遠了。

    古老的古梅鎮原來以農業為生，只有寥寥幾戶在瀚煙山上種植香菇的菇農，後來
有一個神秘的教派在此地建立了一坐巨大的神殿，供奉善良與醫療之神--月神，傳說
月神神殿金碧輝煌，十分壯觀，而且還藏有龐大的財富，但是它的所在位置一直是個
謎，久而久之，人們也只把它當個傳說來看。

    古梅鎮真正繁榮起來是在四十年前，一位名聞天下的鑄劍師發現了瀚煙山下蘊藏
有豐富的魔法磁鐵礦，於是買下數百畝的礦田，舉家遷到古梅鎮來定居，從此古梅鎮
的武器鑄造冠絕天下，所有的武者都以手執古梅鎮鍛鑄的利器為身份地位的表徵，也
由於這個原因，古梅鎮也成為各武林幫派的必爭之地，鬥毆殺戮之事時有所聞，到最
後古梅鎮居然成為武林人士決鬥的聖地，在這裡決鬥不論勝負，都被認為是一件光榮
的事。

    二十幾年前，一代大俠陸小鳳和被目為當代劍神的天外飛仙--飛仙一劍葉孤城相
約在禁城決戰，這是轟動一時的武林大事，甚至驚動了東方帝國的皇帝，機警的陸小
鳳看出了葉孤城的目的，在兩人決戰前後的鬥智鬥力中，成功的阻止了一場即將發生
的宮庭叛變，也使得東方皇帝體會到武林人士的力量，於是他設立了天下第一武鬥大
會，藉著每年一次的武鬥大會網羅武林奇才為己用，這個成功的策略使東方帝國的武
風大為興盛，也直接對國防產生正面而巨大的影響，於是，天下第一武鬥大會就這麼
沿襲成俗，每年一次的盛會更加使得古梅鎮日益繁榮，終於有了現在的成果。

II. 政府

    現在古梅鎮設有縣衙一處，屬古梅縣治，縣官一名，有捕房一所，該管設有監獄
，除正式官衙外，古梅鎮上設有天下第一武鬥大會場管理處，負責場地維護和管理，
鎮內還有一處大宅，人稱四不欺大院，是一退休清官所有，對本鎮政經有舉足輕重的
影響力。

III. 商店

   鎮內有雜貨鋪、醫院、當鋪、鏢局、賭場和妓院，都是合法經營。

IV. 任務概要

   目前鎮內有三個任務：
   I.   拯救漁夫    -- 幫助一個孤苦無依的漁夫。完成後可使用醫院
   II.  段鐵的苦惱  -- 幫助段鐵的火爐爐火再旺，完成後可得段鐵的幫助和一面
		       御賜金牌。
   III. 當鋪危機    -- 由於失落了客人的重要物品，當鋪面臨關門的危機。完成後
		       可使用當鋪，和日後的進行線索。

   任務並未結束，這三個任務都是前導而已。

V.  動物列表

動物名稱    檔名       等級  防禦力   武器等級  傷害範圍  武器裝備  特殊能力

野狗        dog          1    5/2        3        1-3 
大黃貓      yellow_cat   1    5/2        3        1-3
老鼠        rat          1    8/0        3        1-3
窮人小孩    poor_child   1    5/2        3        1-3
車伕        carter       2   10/4        9        3-9
家庭主婦    woman        3   16/6        10       4-10   I)菜籃    菜藍攻擊
小道童      little_doshu 3   20/2        11       6-14
鐵匠        smith        3   30/10       10       6-13   W)鐵錘    防具破壞
賣花女      flower_girl  4   40/20       13       5-12             花籃攻擊
媽媽桑      mama         4   26/0        12       5-13             板凳攻擊
囚犯        prisoner1    4   20/0        13       5-15
皮條        servant      4   25/5        16       6-16
老吳        servant_wu   4   25/5        16       6-16             熱水攻擊
洗衣婦      poor_woman   5   25/0        20       5-18             衣服打擊
賭棍        gambler      5   25/5        18       6-20 
店小二      waiter       5   25/10       16       6-15             抹布攻擊
觀光客      visitor      5   30/10       19       6-18   A)墨鏡
賣唱少女    singer       6   30/10       26       7-21             琵琶撞擊
大狼狗      watchdog     6   30/10       21       8-22             主動攻擊
大狼狗      watchdog2    6   30/10       21       8-22
婢女        maid         *     *          *        *               no_attack
逃犯        prisoner     7   40/10       23       12-20
趙燕居掌櫃  wine_owner   7   34/14       22       9-21
唐如        tang_ru      7   35/16       19       9-21   A)小金圈兒 撒毒
鏢師        mercenary    8   40/16       26      10-27
魚販        merchant     8   40/25       53      25/50   W)大桿秤
                                                         A)珍珠戒指
捕快        cop          9   48/10       34      13/21   W)鐵鏈     全體攻擊
							 A)捕快服
							 A)捕快帽
刑師爺      scribe       9   40/10       26      10/27              sleet 2
縣太爺      migastrate   9   40/10       26      10/27 
道士        doshu        9   55/15       32      12/26   W)精鋼短劍 主動攻擊
							 A)八卦袍   布衣神功
醉漢        drunk       10   51/0        52      17/35   W)檜木棒   主動攻擊
							 A)皮外套
劉朝奉      pawnbroker  10   62/20       50      15/35   W)算盤
							 A)綠玉戒指
							 A)瓜皮小帽
							 A)天藍色長袍
火蜥蜴      salamander  10   50/0        31      11/25               噴火
護院武師    bodyguard   11   45/20       51      26/46               主動攻擊
護院武師    bodyguard2  11   45/20       51      26/46
鎮口守衛    cityguard   11   55/10       37      16-27   W)精鋼短劍  全體攻擊
 							 A)鋼盔
							 A)鋼胸甲
有所不知    soothsayer  12   70/25       48      16-42            ether-bolt 2
綠珠        green_lady  12   74/30       62      24-48   W)粉紅絲帶   阻擋攻擊
							 A)柔絲情網
漁夫        fishman     12   64/0        46      22-43   W)木槳      no_kill
左無心      roger       12   72/11       56      21-41               不會死
段飛鷹      chief_cop   1    70/25       43      16-37               打輸就跑
火妖        fire_beast  13   60/20       31      15-33               噴火+失明
火焰獸      fire_monster 13  70/30       48      19-34               噴火+失明
唐副總鑣頭  chief_merc  14   75/30       59      29-44               雙手攻擊
					 38	 20-30
烏不拉龜    fighter1     14  75/27       45      18-35   A)必勝頭帶  過肩摔
                                                         A)勇者護臂  奪命剪刀腳
醉鬼阿丁    din         14   77/21       12      5-14    A)皮外套    醉拳
							 A)黑靴
賭場保鏢    body_guard  15   75/10      61/39    19-42   W)大板斧    雙斧
						 14-28   W)大板斧
至陽道人    master_doshu 15  85/25       55      20-45   W)玄冰劍    無名劍法
							 A)八卦袍
老醫生      doctor       16  75/20       59      28-48   W)小銀刀    aim
							 A)醫生診袍
靈兒        ling         17  89/36       44      21-39   W)彩虹劍    屠狼劍法
							 A)翠煙羅
							 A)玉墜項□
修行武鬥家  traveller    17  85/27       90      64-74   W)黃金爪
							 A)武鬥服
							 I)旅行袋
蛇魔女      snake        17  85/35       59      29-59               噴酸噴毒
								     混亂
段鐵        master_smith 18  90/27       82      30-60   W)還情劍
                                                         A)情關意鎖
方傲天	    master_fan   18  95/42      104      50-75   W)吹雪劍
							 A)火焰盾
趙堂主      master_jau   18  90/22       87      30-60   W)雷神之□
							 A)雷神手套

VI. 物品列表

物品名稱   檔名         形態    特殊用途

菜籃       basket       容器    無
萬年冰晶   crystal_ice  物品    quest 用
火之精     fire_element 物品    quest 用
精鋼封印   fire_key     鑰匙    quest 用
鐵鑰匙     key1         鑰匙    牢門鑰匙
羊皮紙     letter01     文件    quest 用
老酒       old_wine     酒      for funny
御賜金牌   royal_mark   物品    quest 用 non_drop
月神像     statue       物品    quest 用
旅行袋     travell_bag  容器    無

VII. 武器列表

武器名稱    檔案名稱    武器類別    武器等級    傷害範圍    特殊攻擊

大桿秤      balance     polearm       25        15-30

鐵爪        claws       unarmed       10         8-16     變成黃金爪(adv only)
黃金爪      claws       unarmed      skill/2     與屬性有關

檜木棒      club        blunt         25         5-25
算盤        abacus      blunt         25        10-20
木槳        oar         blunt         25        10-24
鐵錘        hammer      blunt          6         4-11
雷神之□    thor_hammer blunt         45        25-45      召喚雷電

精鋼短劍    shortsword01 shortblade   25        11-22
玄冰劍      icy_sword   shortblade    30        15-30
吹雪劍      icey_sword  shortblade    45        25-40      冰雪攻擊

大板斧      iron_axe    axe           35        15-30

粉紅絲帶    ribbon      whip          20         9-18      block attack
鐵鏈        iron_chain  whip          15         8-16

還情劍      love_sword  longblade     40        20-40      心靈攻擊
彩虹劍      rainbow_sword longblade   35        15-32      bleed 13

小銀刀      silvery_dagger dagger     25        18-28      神聖攻擊 

 
VIII. 防具列表

防具名稱  檔名          形態    質料       AC/DB    特殊效果

捕快服    black_robe    body    cloth      15/0
精鋼胸甲  braso_mail    body    heavy      20/0
皮外套    coat          body    leather     5/0
武鬥服    fighter_robe  body    cloth      15/7   dex+1 con -1 none+30
八卦袍    doshu_robe    body    cloth      15/0
翠煙羅    green_cloth   body    cloth      20/10
醫生診袍  healer_robe   body    cloth      20/0
天藍色長袍 long_garb    body    cloth       8/0
柔絲情網  web           body    element     2/9

小金圈兒  tang_ring     finger  light       0/2
珍珠戒指  pearl_ring    finger  stone       0/5
綠玉戒指  emerald_ring  finger  stone       0/0    trading + 15 

火焰盾    flame_shield  shield  element     5/2   dex-1 con-2 shortblade+10

捕快帽    black_hat     head    cloth       3/0
瓜皮小帽  round_cap     head    leather     4/0
鋼盔      steel_helm    head    heavy       5/0
墨鏡      glasses       head    element     2/0   抗強光

玉墜金□  gold_necklace misc    light       0/8   
情關意鎖  lovekey       misc    light       0/7  con-2 mental+30

精鋼尾甲  steel_tail    tail    heavy      30/0 

勇者護臂  stone_armband arms    stone       4/0

雷神手套  thor_gloves   hands   light       0/2  str-1 dex-2 con-2 blunt+20

黑靴      black_boots   feet    leather     6/2

