                   蜥蜴人洞穴區域背景說明---Ishige

I. 背景大綱:
　　在魔族古帝國創建的初期，蜥蜴人這個種族就時常被各地諸侯大力聘用
，擔任暗殺的工作，由於其單純簡單的思考，因而成為諸侯們最喜愛的「工
具」，一時間，蜥蜴人們都一致認為：就要隨著魔族而飛黃騰達了！但是，
幸運之星並沒有一直眷顧這個種族，就在大家紛紛以服侍貴族為發達之路時
，突然有一位王儲遭到陰謀暗殺，該事件轟動了帝國上下，經過冗長的追查
雖然沒有查出誰為主謀者，但唯一可確定的是：是蜥蜴人殺手暗殺了王儲，
帝國皇帝一怒之下，下令屠殺境內所有的蜥蜴人平民，貴族內侍不準任用蜥
蜴人，現已任用者除剝奪其奉祿外，一律發配邊疆。不過這些都只是表面上
的動作，大部分被發配者在押送過程就已經遭到屠殺了。皇室該項動作不過
是藉機削弱貴族們的力量，以利中央集權統治，並防止產生異族諸侯，蜥蜴
人族群只不過是開刀的對象罷了。
    
　　就在這時，隸屬於中央的蜥蜴人軍團團長－藏馬侯爵，當然也遭逢了這
個大難。在其押解途中，發現了這項陰謀，憤而以枷鎖擊斃負責押解魔族戰
士，單人逃回集中營，欲解救其舊屬。正在苦無對策之時，赫然發現其夥伴
數人同時被押解出來，心想：真是大神保佑啊！於是想也不想，立刻上前救
人，還真是符合蜥蜴人的單純頭腦；魔族戰士們發現有人劫囚，而且只有一
人，不免放鬆了心，待得發現來人原來是前軍團團長時，戰士們多數已經被
打倒了，高階魔導士聞訊趕了出來，希望能以魔法將其格殺，無奈咒語尚未
唱畢，身體已經被撕成碎片了！經過一陣混戰，稍強的團員大都能為自己殺
出一條血路而衝出重圍，其他的大多仍難逃被補的命運。

    這一次的劫獄事件，再度驚動了帝國皇室，此時皇帝的心中只有一個想
法：除惡務盡，以免將來激發了該族的民族意識，使其團結起來。因而更嚴
厲的執行屠戮的工作；另一方面，逃脫的數名團員則是不分日夜的向邊境前
進。一天夜裡，一行數人已經奔至離邊境約只有半天行程的沼澤地帶，大夥
兒都已經疲倦了，望著天上的烏雲，藏馬心想：難道我蜥蜴一族就此命絕了
嗎？想著想著，突然身旁的草叢中傳來輕微的腳步聲，大夥兒心一驚，雖想
搏命戰鬥，無奈長途跋涉，已用盡全身力氣了。只見草叢中走出一位眼睛小
小的，全身長滿鱗片，還有著一根長長的尾巴的人，心想來人是我族類，不
免心情放鬆，一個個昏倒在地了。

    確實，這一群人確實是獲救了，拯救他們的是住在沼澤深處的一個小部
落，因為地處蠻荒，所以魔族的毒掌尚未伸至該地，一行人就在該部落中定
居下來，並以自己所知的一切教導他人。平靜的日子如此的過了數年，漸漸
的，大夥兒都以為災難就此結束了，思鄉情節一日甚於一日，希望能到外頭
去看看，就在數人打算不告而別的前一日，當地突然發生了難以想像的大地
震，村落毀壞無疑，死傷人數亦很可觀，待得安頓村民後，一行人立即動身
，尋原路向回走，只走了半天，就來到海邊，不解充滿了眾人的心頭，頓時
，大家都明白了，地震............！他們在四處探索，終於確定了心頭的
猜測，更令大家吃驚的是，這個地方已經變成一個小島了，一群人雖然歸鄉
心切，但均不懂水性，因此決定忍痛切斷思鄉情節，終老在此小島上了。說
來說去，蜥蜴人應該可以說是該島的原住民吧！

II. 政治體制:
    蜥蜴人基本上是個散漫的民族，並無正式的政治體制，形式上以族群中
最強壯的男性為領導者，目前以號稱『戰神』之『布倫希多』為領袖，旗下
有四大護法『將軍 阿卡巴』、『劍術師 亞邦』、『團長 亞瑟』、『祭司
拉索達』；一般男性輪流擔任戍守與保衛的工作。與其說是個國家，不如說
是個部落來得恰當。

III. 任務概要
		～創世神戟之傳說～
     尚未完備....

IV. NPC 列表
NPC 名稱      檔名        Lv  AC/DB   WC/MIN/MAX  武器裝備      特殊能力 
領袖 布倫希多 leader      19  109/45  92/38/75    W)布倫希多劍  尾巴攻擊
                                                  A)戰神頭盔    (damage:50-65) 
                                                  A)戰神盾
                                                  A)戰神鎧甲
						  A)戰神護臂
						  A)戰神披風

大將軍 阿卡巴 imperator   19  86/31   90/35/55    W)地獄鬼斧
				      73/30/48    W)地獄鬼斧
						  A)惡魔面罩
						  A)黑麵血甲
						  A)烙印戒指
						  A)死神披風

劍術師 亞邦   swordman    19  94/39   95/30/55    W)火麟劍
						  A)火麟戰甲
						  A)火麟護臂
						  A)火麟盾

團長 亞瑟     colonel     18  106/15  87/40/80    W)龍騎士槍
						  A)火龍鬚頭巾
						  A)龍骨
						  A)大地鎧甲
						  A)銀絲披風
						  A)龍鱗尾甲
						  A)灼熱盾

祭司 拉索達   poutiff     17  81/35   65/27/47    W)魔法長鞭    cast magic:
						  A)聖冠        flare [1]
						  A)天使翅膀    fireball [6]
						  A)加護戒指    sleet [4]
						  A)誓言披風
						  A)鳳凰長袍

禁衛軍        life_guard  16  72/31   70/25/48    W)黑檀木柄長槍
						  A)魚鱗甲
						  A)魚鱗尾甲

哨兵          sentry      16  60/29   60/33/44    W)黑色長矛
						  A)守衛識別臂環
						  A)黑色鎧甲
老工匠        old_feller  15  70/34   73/26/51

鋸木工人      feller      16  70/34   77/26/51
				      60/15/35

小女孩        girl        7   20/5    10/8/23     W)梳子

小孩          child       5   20/5    10/5/17     W)美津濃球棒

戰事指揮官    lizard05    19  116/43  89/31/62    W)方天戟	流血(60hp)
(戰爭用)					  A)白金面罩
						  A)白金鎖子甲
						  A)白金護臂
						  A)白金盾

騎士	      lizard04	  17  107/29  73/33/63    W)銀色長槍
(戰爭用)					  A)青銅鎧甲
						  A)青銅護腕
						  A)青銅盾
						  A)皮革碼靴

中尉	      lizard03	  15  99/41   62/22/36    W)長柄戰斧
(戰爭用)					  A)銀色面罩
						  A)銀色鱗甲
						  A)銀色護腕
						  A)銀色刺盾

班長	      lizard02    12  50/15   50/21/42    W)制式長劍
(戰爭用)					  A)軍帽
						  A)軍服

士兵	      lizard01	  10  50/20   28/14/29    W)制式短劍
(戰爭用)					  A)軍帽
						  A)軍服

黑豹	      cougar      16  100/35  87/21/47
				      70/15/35

大黑熊	      panda       18  115/40  89/31/53
				      70/23/38

小黑熊	      little_panda 8  75/30   53/16/36			向媽媽求救
				      40/13/27			if attacker
								lv > 14

吸血蝙蝠      vampire01   16   150/80 99/11/32		        吸血(20-50hp)

吸血鬼        vampire02   19   100/0  81/26/55			召喚二隻小蝙蝠

小蝙蝠	      vampire03   10   60/10  35/6/24		        吸血(10-25hp)

食人魚	      fish1	  15   40/10  68/16/45

紅龍	      fish2	   8   25/8   42/6/20

V. 物品列表：
物品名稱   檔名      	型態     特殊用途
紫水晶	   amethyst  	物品     quest 用
空瓶子     bottle    	物品     quest 用
樹枝	   branch    	物品     quest 用
白花	   flower1   	物品     quest 用
紅花	   flower2   	物品     quest 用
藍花	   flower3   	物品     quest 用
黃花	   flower4   	物品     quest 用
聖水	   holy_potion	物品     quest 用
鋸子	   saw		物品     quest 用
桃木短刀   kirs		武器     quest 用

VI. 武器列表
武器名稱     檔案名稱      武器類別    WC/MIN/MAX   特殊攻擊
地獄鬼斧     axe1          axe         40/25/40     bleeding
						    惡鬼攻擊 damage(25-40)
長柄戰斧     axe2          axe         32/22/36
美津濃求棒   bat           blunt       8/5/15
魔法長鞭     chabok        whip        33/15/30
梳子	     comb          blunt       8/5/15
創世神戟     jousting      jousting    45/25/55 ------這兩把武器是為了鼓勵騎士
龍騎士槍     jousting2     jousting    45/23/54 ------用象徵騎士的武器,一天一把
布倫希多劍   king_sword    longblade   35/20/40
銀色長槍     lance1        jousting    35/20/38
黑檀木柄長槍 lance2	   jousting    35/20/40
制式長劍     longsword     longblade   25/13/24
方天戟       polearm       polearm     35/20/40
火麟劍       scale_sword   shortblade  40/20/40     fire damage(15-34)
制式短劍     shortsword    shortblade  15/8/15
黑色長矛     spear1        thrusting   28/20/30


VII. 防具列表
防具名稱     檔案名稱   型態    質料		AC/DB	特殊效果
藍寶石項鍊   amulet1	misc	element		0/6
白金徽章     amulet2	misc	element		0/4
龍骨	     amulet3	misc	element		0/6
天使翅膀     amulet4	misc	element		0/5
戰神臂環     arms1      arms    light_metal	4/4
守衛識別臂環 arms2	arms	light_metal	0/2
鈦合金臂環   arms3	arms	light_metal	4/4
白金臂環     arms4	arms	knight		3/2
火麟護臂     arms5	arms	leather		6/4
皮革馬靴     boots1	feet	lether		6/0
鈦合金戰靴   boots2	feet	light_metal	8/3
青銅護腕     bracer1	hands	heavy_metal	4/2
銀色護腕     bracer2	hands	light_metal	4/2
戰神披風     cloak1	cloak	cloth		8/4
死神披風     cloak2	cloak   cloth		5/6	fire:25,cold:10
							none:15
銀絲披風     cloak3	cloak	cloth		6/4	fire:30,cold:-10
							none:15
誓言披風     cloak4	cloak	cloth		6/4	evil:20
鳳凰長袍     cloth1	body	leather		30/4	fire:30,evil:20
軍服	     cloth2	body	cloth		20/4
鈦合金護手   gloves1	hands	light_metal	4/4
戰神頭盔     helmet1	head	light_metal	8/2
鈦合金覆面   helmet2	head	light_metal	8/3
白金面罩     helmet3	head	knight		6/2
銀色面罩     helmet4	head	light_metal	4/0
惡魔面罩     helmet5	head	light_metal	6/2	使陣營變成-1500
							hp減少50
火龍鬚頭巾   helmet6	head	leather		6/2
聖冠	     helmet7	head	light_metal	6/4	evil:20
軍帽	     kepi	head	cloth		4/2
藍寶石項鍊   necklace1	misc	element		0/8
鈦合金鎧甲   plate	body	light_metal	35/5
青銅鎧甲     plate1	body	heavy_metal	30/3
戰神鎧甲     plate2	body	light_metal	35/6
火麟戰甲     plate3	body	cloth		25/0	evil:20,cold:30
							騎士穿上時:AC=level*2
						 	        DB=knighthood*2
黑色鎧甲     plate4	body	light_metal	20/2
大地鎧甲     plate5	body	cloth		34/6
白金鎖子甲   plate6	body	knight		32/4
銀色鱗甲     plate7	body	light_metal	26/2
魚鱗甲	     plate8	body	cloth		26/4
黑麵血甲     plate9	body	light_metal	33/6
加護戒指     ring1	finger	element		0/6	evil:20
藍寶石戒指   ring2	finger	element		0/8
烙印戒指     ring3	finger	element		0/7
青銅盾       shield1	shield	heavy_metal	8/4
戰神盾       shield2	shield	light_metal	6/0	fire:10,cold:10
鈦合金盾     shield3	shield	light_metal	8/5
白金盾	     shield4	shield	knight		7/5	fire:30,cold:-15
銀色刺盾     shield5	shield	light_metal	5/2	fire:30,cold:-15
灼熱盾	     shield6	shield	light_metal	6/3	fire:30,cold:-15
火麟盾       shield7	shield  light_metal	8/0	fire:30,cold:10
鈦合金尾甲   tail1	tail	light_metal	8/3
魚鱗尾甲     tail2	tail	cloth		6/2
龍鱗尾甲     tail3	tail	heavy_metal	8/3