    

                      "傳說" 區域簡介

                      作者：Player&Dony

II.商店：
       
       II).旅行商人    vendor1
      
III.任務概要：

       完成男主人的三件工件 ：
     I ). 完成「薪膽村」的 quest
    II ). 完成女主人愛美的心願
   III ). 完成漁村村長的心願


IV.怪物 : /u/d/dony/legend/monster

等級   怪物名稱      檔名         AC/DB  WC  傷害範圍  武器裝備       

[ 15 ] 青靈之眼      beholder1.c  60/16  61  24/32     青靈護盾圓球
[  6 ] 小男孩        boy.c        30/2    13  6/11
[ 18 ] 漁村 村長     captain1.c   80/40  81  30/62     漁衣
[  1 ] 老船東        captain2.c   不能打
[ 17 ] 山貓          cat.c        80/1    58  23/36
[ 16 ] 五彩斑斕的巨型花蜈蚣
                     centipede.c  40/10  58  26/31
[  6 ] 大螃蟹        crab.c       1/0    14  6/14
[ 19 ] 茅山道士 黃天化 
   	             daoist.c     65/55  87  30/61     茅山八卦袍
						       盤古之斧
[  7 ] 小女孩        girl.c       35/2    14  7/12
[ 17 ] 隱者          hermit.c     55/50  81  25/38     冰魄銀針
[ 14 ] 冰蟾蜍        icetoad.c    60/15  41  16/25
[ 18 ] 天水螞蝗      leech.c      10/20  67  31/56
[ 13 ] 食人蜥蜴      lizard.c     45/10  49  21/27
[ 18 ] 男主人        man1.c       70/46  71  33/48     日符
						       日戒
						       鳳凰長刃
[  8 ] 魚販          merchant.c   40/2    15  6/12
[ 13 ] 銀線蛞蝓      mollusk.c    10/40  51  6/15
[ 10 ] 花斑毒蚊      mosquito.c   45/10  35  11/19
[ 17 ] 鬼面蛾        moth.c       10/10  58  21/31
[ 19 ] 老漁翁        older.c      75/46  79  35/61     漁衣
						       業火之杖
[ 19 ] 諸保昆        pao_kun.c    116/38 100 52/63     玄鐵通臂  
           ( only one )                  75  38/57     銀龍戰甲  
						       疾風破月錐
						       地母雷公轟
[ 10 ] 紙人          paperman.c   15/5   48  16/31   
[ 19 ] 莽牯朱蛤      redtoad.c    80/30  87  56/71
           ( only one )
[ 16 ] 水晶變形蟲    shapeshifter1.c  
                                  10/207 87  26/35
[ 19 ] 神木上人      spirit1.c    不能打
[ 14 ] 老虎          tiger.c      70/1    47  18/33 
[ 10 ] 市井流氓      vagabond.c   50/4   20  11/22
[  6 ] 旅行商人      vendor1.c    不能打
[ 15 ] 流浪者        wanderer.c   70/18  38  19/39
[ 19 ] 水怪 無支祈   water_mob.c  30/1   105 41/48
[ 16 ] 媽媽桑        woman.c      70/18  38  19/39
[ 18 ] 女主人        woman1.c     70/41  71  33/46


V.武器： /u/d/dony/weapon

武器名稱    檔案名稱      武器類別     WC   傷害範圍          特殊攻擊    

業火之杖   hell_wand.c    wand         38    20/37            fire 
冰魄銀針   ice_needle.c   dagger       42    23/30         
盤古之斧   mahogany_axe.c axe          36    25/43 
鳳凰長刃   phenix1.c      longblade    47    27/47         
紅袖刀     red_sle.c      longblade    35    25/40
地母電公轟 t_star.c       chain     chain/2  8+lv / 26+lv     energy 
    ( only one )
疾風破月錐 wind_awl.c     thrusting    45    28 / 42  bleeding 10~20
    ( only one )                                    ( 依 explore 算 )	


VI.防具： /u/d/dony/armor

防具名稱     檔案名稱      型態     質料        AC/DB     

茅山八卦袍 daoist_cloth.c  body     cloth       5/10    "fire":30
                                                        "devil":30
  							"magic":30
							"cold":-30
							"mental":-70
漁衣       fish_cloth.c    body     cloth       10/7    "poison":20
							"acid":20
青靈護盾圓球 globe1.c      globe    element     0/15    
玄鐵通臂  iron_armband.c   arms     heavy_metal 5/0     
      ( only one )   
銀龍戰甲   iron_plate.c    body     heavy_metal 40/1    
      ( only one )
紫晶核     kernel1.c       kernel   element     0/7     
月符       moon_amulet.c   misc     cloth       0/3     "evil":40
月戒       moon_ring.c     finger   element     0/7
日符       sun_amulet.c    misc     cloth       0/9     
日戒       sun_ring.c      finger   element     0/2     "magic":30
						        "evil":30
       
VII.其他物品：/u/d/dony/item
  
       物品名稱       檔名            用途
 
       朱果         fruit.c           1.quest 
                                      2.50hp+50fp (every reborn one)
       鐵鎖         iron_lock.c       1.quest
       兜率彌陀珠   lifeball.c        1.加全滿 only one
       橡木槳       oar.c             plz look file
       定海珠       sea_ball.c        plz look file
