
            
             梁山泊山寨及大湖計畫報告
             ========================        作者Takeda 於 94/12/12

1. 地理部份: 
     梁山泊位於幽國城的西北方的太倉山，山勢高峻，地勢險要，俯臨少商谷
     山腳下有一大淡水湖，盛產各類魚蝦蟹貝，為東方大陸第一大河羿水河的
　 　起源，湖水主要來自附近高山溶化的雪水。
2. 歷史部份:
     由於此地物產豐富，又且易守難攻，因此從古到今，許多大規模的亂事都
　　 發源於此，十年前，由於東方大國朝政腐敗，許多英雄豪傑嘯聚於此，圖
　　 謀大舉，當時朝廷進剿數次，互有勝敗，皇帝於是接納大軍師諸葛不明的
     建議，將重兵屯聚少商谷口的幽國城內，由名將風起雲任指揮使，從此梁
     山泊和幽國城便成對峙之局，轉眼十年。　
　　 由於山寨內人丁眾多，許多鉅商大賈基於市場考量，紛紛來此投資開業， 
     熱鬧非凡，今日的梁山泊，與其說是土匪窩，不如說是一個小型的商業都
     市，交換著少商谷，大湖，東方大陸，與西方深山內少數民族的貨物。
 3. 區域內的任務介紹
　　　構想中有三個相關任務
　　　　1.幫助山寨內的廚子重新振作(類似將太壽司)
        2.查明傳說中湖怪的真相(因有人在晚上看到湖上一片光明(shell)
          且最近村裡常有人走失(snake)不知與傳說之水怪有無關連)
        3.解決百年來山寨與帝國對峙之局
      其中1.完成，但有點羅嗦
　　　　  2.正試圖完成 
          3.須要皇宮和幽國城完成，計畫中是可多向解的ｑｕｅｓｔ
  4. 區域內店鋪介紹
     酒店: 完成且連上(提供食物可見食物表)
     商店: 完成且連上(買賣物品)
     診所: 完成且連上(提供藥品和醫療)
     馬市: 完成且連上(提供基本醫療與馬匹供應)  
     武器鍛造店: 未完成(待段家鐵礦完成後可依等級訂作武器)
     聚義廳: 未完成(可在內結拜兄弟姐妹)  
5. 區域內怪物介紹
  a.寨內一般怪物     
由於此地為軍事區，怪物普遍較強，多為戰士型怪物
     有* 者表示是別人的怪物在此出現
山寨區
名稱        檔名   等級  AC/DB  WC  傷害範圍   特殊攻擊
松鼠*    squirrel.c  2    7/ 0   7   3 -  6
洗衣婦*poor_woman.c  5   25/ 0  11   5 - 18
阿達       washer.c  6   10/ 2  15   5 - 14
山賊*   mt_bandit.c  6   20/ 8  22  14 - 21
山賊  small_bandit.c 7   20/ 8  24  12 - 21 
皇甫端    huanpo.c   8   70/23  42  18 - 37 ------------>
安道全    doctor.c   8   70/23  42  18 - 37 ------------> ps 不希望人家殺所
阮小五     five.c   10   46/12  29  16 - 24                 以有點強
阮小七     seven.c  10   46/12  29  16 - 24
阮小二       two.c  11   46/12  29  16 - 24 
孫二孃      sun1.c  12   52/19  26  10 - 18    對男人作傷害性特殊攻擊10hp
阿香        pang.c  12   30/15  36  11 - 30
楊春       yang1.c  13   50/18  31  18 - 28
解寶       shei1.c  13   55/15  30  15 - 25    特殊武器(藥叉)
解珍       shei2.c  13   55/15  30  15 - 25       同上
韓滔        han.c   13   39/14  34  20 - 31
郭盛        guo.c   14   46/17  43  24 - 38
呂方         lu.c   14   46/16  43  24 - 38
張順      zhan2.c   14   59/24  48  22 - 43    
時遷        shi.c   15   43/20  31  16 - 25    偷錢和丟金錢鏢(均會造成傷害)
                                               特殊武器(盜賊匕首)
黃信       huan.c   15   58/20  44  23 - 36
吳用      wuyong.c  16  132/59  50  23 - 56    治療自己90hp
宋江       song.c   16  127/52  58  26 - 45    將人送到別處
徐寧        shu.c   16   78/34  46  34 - 54 
朱武        zhu.c   17   69/31  43  13 - 26    呼叫山賊
張青      zhan1.c   17   65/33  52  17 - 30    完全停止攻擊
花榮        hua.c   17   89/36  75  33 - 59    特殊武器(泥金雕鵲細弓)
公孫勝   wizard.c   17   63/43  76  36 - 54    黑暗魔法(flare 3)
                                               特殊武器(松文古定劍)
楊志      yang2.c   18   85/36  80  38 - 65    特殊武器(渾鐵點鋼槍)
武松         wu.c   18   84/39  83  43 - 68    
史進     shijin.c   18   80/36  80  33 - 58    特殊武器(水火風雷棍)
李逵         li.c   18   97/37  88  51 - 81    
魯智深     monk.c   18   77/43  90  45 - 77    
秦明       chin.c   19  111/52  82  38 - 65    特殊武器(玄鐵狼牙棒)
董平       dong.c   19   96/52  90  35 - 65    特殊武器(繡絲爛銀槍x2)
關勝       guan.c   19  115/52 102  48 - 77    傷害性特殊攻擊50hp 
呼延灼    huyang.c  19  110/57  84  38 - 65    特殊武器(水磨八稜鋼鞭)
林沖         lin.c  19  111/62 102  44 - 72    特殊武器(丈八蛇矛)
    b.湖內的怪物
大肚魚    fish2.c   2    10/ 4   6   2 -  6
泥鰍      fish9.c   4    20/ 8   7   4 -  9
香魚      fish1.c   5    25/10  10   4 -  9
鯽魚      fish3.c   7    35/14  11   4 - 11
鯉魚      fish4.c   7    35/14  11   5 - 11
草魚      fish5.c   8    40/16  12   6 - 12
鯰魚      fish6.c   8    40/16  12   5 - 13
鱸鰻      fish7.c  10    50/20  14   7 - 17
七星鱧    fish8.c  10    50/20  15   8 - 18
千年老蚌  shell.c  19   140/65  79  36 - 67

// 你的武器有特殊功能的太多，雖然不是不好，但太氾濫了也不是好現象
   如果想強調 mob 的能力，何不把特殊功能移到 mob 身上？
   否則太好的武器會打破 ES 原先的平衡，我不反對你幫武器加特殊能力
   ，但是不需要每把都有吧 !! 

其實, 若有毒的不算, 這次修改後, 目前強力的特殊武器只有七把, 其中松文古定劍
與水火風雷棍是由int 來決定, 可說是為scholar and healer 量身定做的武器
水磨八稜鋼鞭現在只有adv 可以用, 所以剩下的特殊武器, 只有四種而已
再談到平衡問題，最近一直有騎士抱怨，別的職業越調越強，騎士的武器卻越來越少
或越變越弱，我不知道要怎麼對付他們，所以我寫了些不同的特殊武器。如果你認為
種類太多的話，或許我可以將五虎大將全改成只有一隻，不知你認為呢?

6.武器簡介 

名稱                檔名        武器等級     傷害範圍   附註
朴刀               poblade.c  longblade 17     9 - 18
藥叉                  fork.c  thrusting 17     7 - 17   有毒 
漁師短刀    fishman_dagger.c shortblade 17     8 - 16
鐵瓜錘          ironhammer.c      blunt 18    10 - 20
盜賊匕首      thief_dagger.c     dagger 18     8 - 16   有毒
分水蛾眉刺     waterdagger.c     dagger 18     9 - 18  
棗木槊             woodoar.c      blunt 20    12 - 23 
三尖兩刃刀      threeblade.c  longblade 25    13 - 26   bleeding 5 
                                                       + parry skill 10
鉤鐮槍           hooklance.c  thrusting 26    21 - 33
喪門劍          deathsword.c  longblade 26    15 - 28   bleeding 6
方天畫戟           polearm.c    polearm 26    16 - 30
雁翎刀              yanlin.c  longblade 30    17 - 30   bleeding 5
繡絲爛銀槍    silver_spear.c  thrusting 40    17 - 35   special attack(25)
                                                        only when use 2
渾鐵點鋼槍       ironlance.c  thrusting 35    20 - 35   block attack(2 or 3)
水磨八稜鋼鞭    steel_whip.c       whip 35    20 - 35   block attack(3)
                                                        +special attack(8)
水磨禪杖        huge_staff.c      blunt 42    27 - 47  
玄鐵狼牙棒       iron_club.c      blunt 35    20 - 35   
蚩尤七殺斧      flower_axe.c        axe 40    28 - 44   
丈八蛇矛     snake_polearm.c    polearm 45    26 - 42  special attack(5)+
						       block_attack 2 run
泥金鵲畫細弓           bow.c      blunt 35    18 - 34   special(15)
水火風雷棍 elemental_staff.c      blunt 35    15 - 28   4 kinds of special attack
雪花鑌鐵刀       snowblade.c  longblade 37    25 - 38   bleeding 14
松文古定劍      pine_sword.c  longblade 35    20 - 35   special attack(16)
青龍偃月刀     dragonblade.c  longblade 48    30 - 47 

7.防具簡介:


1.身體部份

  名稱              檔名       AC/DB   material  special defense   附註
麻衫            small_cloth.c   12/ 3    cloth
皂直綴          black_cloth.c   15/ 3    cloth
硃紅甲            red_armor.c   18/ 3 light_metal none 4 poison 1
白甲            white_armor.c   18/ 4 light_metal none 3 poison 1
白緞子征衫    white_warcape.c   18/ 5    cloth    none 5 poison 1
魚皮水靠          fish_skin.c   19/ 2   leather   none 4 acid -5
虎皮套體        tiger_cloth.c   24/ 3   leather   none 8
格子布背心             vest.c   20/ 3    cloth
油膩的廚師服     cook_cloth.c   25/ 3    cloth
黑絲綢法衣        dark_cape.c   22/ 5    cloth    magic 10       str-2 con-1 
                                                  energy 10 fire 15 kar-1
                                                  cold 15 electric 10
ps 因這件衣服點明為法衣, 所以我想屬性互衝的情形應該不要緊

紫繡團胸戰甲   purple_plate.c   25/ 7 heavy_metal
裹金生鐵甲       iron_plate.c   25/ 4 heavy_metal
熊皮烏油甲       bear_cloth.c   26/ 4   leather  
點翠團花戰甲green_chainmail.c   34/ 4 heavy_metal         
鐵葉鎧甲        leave_plate.c   35/ 6 heavy_metal
梅花榆葉甲     floral_plate.c   36/ 7 light_metal 
鎖子黃金甲   gold_chainmail.c   40/ 5 heavy_metal  
連環獸面鏜猊鎧  beast_plate.c   30/10   leather 
金縷玉衣         jade_cloth.c   31/10   element   evil 10        dex-3 kar+1
                                                  poison 8 devine -10 str -1
                                                  acid 6 none 7
 
2.頭部

  名稱              檔名        AC/DB   material   special defense  附註
皂巾             black_hood.c    3/ 1     cloth
一字巾             one_hood.c    4/ 1     cloth
黃銅道冠          brass_hat.c    4/ 1 light_metal evil 5 devine -4 mental 5
白范陽氈大帽       wool_hat.c    6/ 2    leather  cold 3 fire -3
廚師帽             cook_hat.c    4/ 2     cloth   fire 4 mental 1
深簷暖帽            fur_hat.c    6/ 1    leather  cold 4 fire -3
渾鐵打就四方鐵帽   iron_hat.c    5/ 2 light_metal none 5
沖天角鐵頭鏷       iron_cap.c    6/ 2      adv                whipskill+10
紅綴金束髮盔    gold_helmet.c    6/ 2 light_metal none 1 magic 2
皂紗轉角簇花巾    silk_hood.c    6/ 2     cloth   fire 3 cold 5 acid 2
麻羅卍字頂巾    buddha_hood.c    6/ 3     cloth   evil 7 mental 5
箍頭鐵戒尺    iron_headband.c    7/ 2     monk    mental 2  dodge +15 con -1
鋪霜耀日鑌鐵盔  iron_helmet.c    9/ 4 heavy_metal fire 5 cold-2
鳳翅紫金冠   phoenix_helmet.c   10/ 4 heavy_metal poison3 none 3 mental 2
紫金道冠           gold_hat.c    6/ 5     mage    evil 7 divine -5 mental 8
綸巾           scholar_hood.c    7/ 5    scholar   magic 5 mental 2
熟鋼獅子盔      lion_helmet.c    9/ 3 heavy_metal 
渾青抓角頭巾     green_hood.c    7/ 5     cloth   fire 4 cold -5 mental 2   

3.鞋

  名稱              檔名        AC/DB   material special defense  附註
麻鞋           simple_boots.c    3/ 0     cloth  none 1 acid 1
鷹爪皮四縫乾黃靴eagleclaw_boots.c4/ 5    leather energy 2
黃皮襯底靴    cowskin_boots.c    6/ 2    leather  
獐皮窄溝靴       deer_boots.c    7/ 1    leather
金線抹綠皂朝靴 golden_boots.c    6/ 2    leather
藕絲步雲履  waterlily_boots.c    7/ 5   element evil 8 poison 2 divine -8 

4.披風

黑綠羅襖    darkgreen_cloak.c    5/ 4     cloth  none 1 divine 1 evil 2
白衲襖          white_cloak.c    4/ 2     cloth
紅衲襖            red_cloak.c    4/ 2     cloth
乳白苧絲戰袍     white_robe.c    4/ 2     cloth  none 3 divine 2
青錦襖           blue_cloak.c    4/ 3     cloth  
緋紅團花袍     floral_cloak.c    5/ 1     cloth
百花點翠皂羅袍  floral_cape.c    5/ 2     cloth                  
鸚哥綠苧絲戰袍  green_cloak.c    6/ 3     cloth
貂鼠皮襖        sable_cloak.c    6/ 1    leather evil 2 fire -4 cold 2
軍師護袍       scholar_cape.c    6/10    scholar  evil -3 cold -10 fire 2
                                                 divine 4
                                                             inner-force+10
霞飛怪獸絳紅袍  beast_cloak.c    7/ 4    leather  none 3 magic 4 fire -2
挽絨金繡絲羅袍 golden_cloak.c    6/ 2    leather  
七星打釘皂羅袍    nail_cape.c    5/ 4     cloth  none 3 divine 2  dodge+10
五雷天心護袍  thunder_cape.c     7/10      mage  electric 20     target +5

5.護身符

護心鏡               mirror.c    0/ 3  light_metal poison 5
黎明護身符     thief_amulet.c    0/ 5    cloth     evil 10, poison 10
獸面掩心          beastface.c    0/ 8   leather    poison 5 none 4
和氏壁           hoshi_jade.c    0/ 8   element   poison 8 none -7 evil 8
繩文玉佩          wire_jade.c    0/ 7   element evil 6 none -6
孫子兵法           sun_book.c    0/ 6   scholar mental 6 none -6  tactic+10

//	ps 我覺得兵法是帶兵打仗的人看的, 不知你以為然否?
//	對啊 ! 但是西方的騎士會隨身帶這種東西嗎？ by Ruby
//	你覺得這種東西不該屬於東方的讀書人嗎？

人頂骨數珠    skeleton_bead.c    0/ 6     stone  evil -5 divine 5   pie-2

6.戒指

太原府紐絲金環  golden_ring.c    0/ 6     adv                    whip+10
羊脂珠玉環   whitejade_ring.c    0/ 7    scholar                   
紅寶石戒指        ruby_ring.c    0/ 5    element		dodge-5 
								unarmed -10

ps 設成cloth 是想讓大家都能使用他, 因為玩家現在缺少中級的戒指，若你有意
   見可以再改 
// hoho .. 這麼可怕的戒指沒人要啦 :P)

7.臂環

鞣牛皮臂環      fur_armband.c    5/ 3   leather   cold 2 con -1 str-1 whip+20

8.盾

不沾鍋                  pot.c    5/ 0 light_metal mental 5      

9.脛甲

鮮紅生絹裙         red_skirt.c   5/ 4   cloth    cold-2 fire 3
豹皮褲         panther_pants.c   8/ 3  leather   cold 4 fire -5
蚩尤尾甲          tail_armor.c  10/ 4  leather axe +10 for very evil only

 8. 商品表:

山寨內目前有三個主要的店鋪，分別為酒店，藥店及馬市，茲將其商品列表如下:
1.酒店        價格(銀幣)    存量(個)        效能

手工精製肉包    100          10          hp+8+random(2)
蔥爆牛肉        260          10          hp+15+random(5)
炒青菜          130          10          hp+3+random(2) mp+8
麻辣豆腐        100          10          hp+7+random(3)
竹葉青           20          10           as before

2.藥店       價格(金幣)     存量(個)        效能

金創藥           6            50          as before
雲南白藥        15            40          as before
天香斷續膏      25            30          as before
天山雪蓮       450             2           內力全滿

3.馬市       價格(銀幣)     存量(只)        載重(kg)
小花馬         1500           4              155            
紅鬃烈馬       2000           2              200
踏雪烏騅       3000           2              230 

ps 在寫程式的時候遇到一個問題，本來計畫蚩尤七殺斧的wc 為44
   理論上有88 的axe skill即可使用，但騎士的上限只有80 所以
   我在蚩尤尾甲上加了extra skill axe+10
   但我測試時卻發現, 雖然我順利的穿上尾甲, axe skill 也變成
   90 但仍然不能使用這個武器, 迫於無奈, 我便把蚩尤七殺斧硬降
   到wc 40，因此現在可能damage 偏高....   