                         武士城堡
１　歷史：
　　　　這是一群由諾頓大陸遷移而來的居民，由於他們原本在諾頓的政治問題
　　　　因而遷移而來，也由於長期處在不安的戰爭狀態下故其配製有常駐兵力
　　　　武士團以保衛自己家園，而當他們遷移到此地時，發現他們島上的的蜥
        蜴人和魔族相當的危險，也發生數次大戰故他們再度將武士團的戰力重
　　　　組，並建立起一個防衛據點，武士城堡來保衛自己，原本在他們的策略
　　　　是，他們是對所有的蜥蜴人和魔族都採格殺物論的策略，但由於和平條
　　　　約的簽訂，故而放棄此策略，改以和平的方法希望能在此地好好生活下
        去！！

２　政府：
　　　　目前是由軍方管理一切事務，及武士團長管一切事務
　　　　目前的首領是：武士隊長　約修
　　　　　　　　　　：副隊長　　星卡
　　　　　　　　　　：秘密力量　忍者葛拉
                                雷帝亞協斯.妮

３　任務：
　　　　1.幫加爾福特送禮物給娜考璐璐

４　人物姓名　　檔名　　等級 AC/DB WC 傷害範圍 武器裝備      特殊攻擊 
   
    青年士兵 soldier.c  7    35/14 10   5-12   鐵長刀 
    灰衣武士 guard.c    10   45/9  34  13-28   東方片羽劍
                                               武士鎧甲
    紅衣武士 guard1.c   14   55/11 63  15-30   風刃劍
                                               武士鎧甲
    白衣武士 guard2.c   15   64/16 68  26-44   拉克尼安劍
                                               武士護手
                                               武士戰甲
    武士守衛 guard3.c   14   55/11 63  20-46   武士短刃
                                               武士鎧甲
    守衛武士 guard4.c   16   71/17 61  23-51   拉刻尼安劍
                                               武士護手
                                               武士戰甲
                                               武士頭盔
    市民     citizen.c   6   30/12 4   1-4
    大老鼠   big_rat.c   7   35/14 4   1-4
    魚販   fish_merchant 6   30/12 4   1-4
    水果販fruit_merchant 6   30/12 4   1-4
    菜販   vage_merchant 6   30/12 4   1-4
    雜貨商人 merchant    3   15/6  7   4-8
    市場守衛market_guard 12  40/8  45  7-20   木棍
    武士約克 yark        17  99/35 75  25-62  名刀龍光
                                              武士護腕
                                              武士披風
                                              武士戰甲
    武士 威  wei.c       17  93/45 66  32-63  龍鱗之劍
                                              武士護膝
                                              武士長靴
                                              心形項鍊
    武士安卡斯 ekars.c   18  99/34 83  35-73  十字槍
                                              黑色護手
                                              黑色戰甲
                                              黑色頭盔
    劍術老師   ziba.c    17  85/29 64  26-50  名刀千鳥
    甘席巴                         52  25-44  名刀魚走
                                              劍術道服
                                              白頭巾
    武士札克  zark.c     19 105/26 83  35-70  音升之劍
                                              空手道服
    武士星卡  si_ka.c    19  94/36 72  35-75  黑夜叉     不動明王斬 20-45
                                              武士之服
                                              武士長靴
                                              武士護手
    武士隊長 ya_shu      18  99/39 72  35-78  鍔鳴刀     蝶舞阿修羅斬
    約修                                      菊形家徽
                                              阿修羅之鎧
                                              夜影披風
    老鷹那那 eagle      15   65/18 56  16-50
    魯哈
    娜考璐璐 nakoruru.c 18  125/44 75  35-70  雪之顏
                                              冰雪護符
                                              冰雪披風
                                              冰雪護手
                                              冰雪護袍
    忍者葛拉 kola.c     19  112/27 88  45-87  妖刀村正
                                              飛龍之鎧
    忍者加爾 calford.c  18   98/36 70 35-65   忍者匕首   忍法飛天摔 
    福特                                      忍者網甲   忍法手裡劍
                                              忍者手套
                                              忍者鞋 
                                              紅圍巾
    忍犬 巴比 poppy.c  16   60/25  69 16-42
    忍者    ninja.c    14   80/12  55 20-50   忍者刀
                                              忍者衣
    菊右京  uyko.c     18  101/27  67 30-80   飛燕之劍
                                              櫻之服
    殺手幻庵 killer.c  18  125/45  90 35-80   刀鎖      噴毒氣和亂咬
    雷帝亞協斯.妮 nei.c 19 118/52  88 37-82   雷神劍    雷擊鷲爪斬
                                              雷電神盾  落雷
                                              雷電戰甲
                                              雷電披風
    戰爭用怪物
    守備隊長十兵衛 19      90/24   67 25-60   名刀星落
    juibei.c                       42 21-42   名刀月殘
                                              武士紋章 
                                              武士護腕
                                              武士披風
                                              武士之服
    黑衣武士 war1.c    16  65/13   70 20-63   精剛長劍
                                              武士戰甲
    藍衣武士 war2.c    16  65/13   55 34-65   鋼斧
                                              武士戰甲
    武士團士兵 war3.c  13  50/10   50 20-50   風刃劍

４．武器：

　名稱　　　　檔名　　  　  　ＷＣ　　Ｄａｍａｇｅ　　特殊攻擊 價格
雷神劍       sword2.c         42      17-42           放雷攻擊 2000
刀鎖         lock.c           40      15-40           咬住敵人武器
                                                      飛砍敵人  2000
名刀千鳥   bird_sword          26       15-26          none     1320
黑夜叉     black_ya_sha        35       20-40          none     1500
木棍       club.c              22        7-20          none     320
十字槍     cross_lance         36       15-38          none     1230
名刀龍光 dragonlight_sword.c   30       15-32          none     1030
龍鱗之劍 dragonscale_sword.c   27       12-28          流血     930
東方片羽劍 east_feather_blade  22       10-20          none     320
妖刀村正  evil_sword.c         45       25-47        吸持有者HP 1300
                                                     出特殊攻擊
名刀魚承  fish_sword.c         26       15-26          none     1120
鐵長刀    iron_blade.c         10        5-12          none     320
拉克尼安劍lakonia_sword.c      26       13-26          bleeding 620
長刀      long_blade.c         15       10-18          bleeding 420
忍者匕首  ninja_dagger.c       30       15-30          bleeding 1320
忍者刀    ninja_sword.c        25       10-25          bleeding 720
武士短刃samuria_shirt_blade.c  27       13-28          none     1000
雪之顏    snow_dagger.c        38       15-30        冰之攻擊女 1200
                                                     子專用
        
音升之劍  sound.c              42       15-30        有特殊攻擊func 1200
鍔鳴刀    sound_blade.c        35       20-38        none       1000
飛燕之劍  swallow_sword.c      35       15-35        none       1720
風刃劍    wind_blade_sword.c   27       15-30         bleeding  820
名刀星落  moon_sword.c         35       14-40        bleeding   920
名刀月殘  star_sword.c         30       15-30        bleeding   920
精鋼常劍  steel_sword.c        30       10-28        bleeding   720
鋼斧      axe.c                25       15-30        none       620



５．防具：

 名稱         檔名           AC/DB special material    weight value type
阿修羅之鎧 a_shu_la.c        34/4          heavy_metal  250   1200  body
黑色護手   black_gauntlets.c 4/3           heavy_metal  100   650   hands
黑色戰甲   black_vest.c      25/5  fire 10 heavy_metal  270   1200  body
                                   evil 10
飛龍之鎧  dragon_chainmail.c 35/4 +dodge 5 light_metal  170   1600  body
劍術道服  fencing_cloth      20/2          cloth        130   600   body
心形項鍊  heart_necklace.c    0/5          element      50    1000  misc
空手道服  karate.c           10/1          cloth        100   300   body
菊形家徽  mark.c              0/6  fire 20 light_metal  30    800   misc
夜影披風  night_cloak.c       5/4  cold 10 leather      70   1200  cloak
                                  mental 10
忍者鞋    ninja_boots.c       5/2          leather      30    600  feet
忍者衣    ninja_cloth.c       16/2         leather      90    760  body
忍者手套  ninja_gloves.c      3/2 poison 30leather      20    1160 hands
忍者網甲  ninja_vest.c       30/3          light_metal  100   1160 body
紅圍巾    red_scraf.c        0/4  fire 20  cloth        20    660  misc
櫻之服    sakura.c           31/2          cloth        110   1160 body
武士護腕  samurai_armband.c  3/2           light_metal  100   650  arms
武士長靴  samurai_boots.c    7/3           leather      100   600  feet
武士鎧甲  samurai_chainmail.c 15/3         heavy_metal  200   450  body
武士披風  samurai_cloak.c     6/3          leather      70    800  cloak
武士之服  samurai_cloth.c    33/5 energy 5 light_metal  120   900  body
武士護手  samurai_gloves.c   4/3           leather      70    500  hands
武士頭盔  samurai_helm.c     7/1           light_metal  70    780  head
武士護膝  samurai_leggings.c 6/2           light_metal  100   600  leggings
武士紋章  samurai_makr.c     0/4           light_metal  70    800  misc
武士戰甲  samurai_vest.c     15/5          heavy_metal  250   900  body
冰雪護符  snow_amulet.c      0/5  cold 10  cloth        10    800  misc
                                  fire -5
冰雪披風  snow_cloak.c       7/5  cold 5   cloth        30    1200 cloak
                                  fire -5
冰雪護袍  snow_cloth.c      34/6  cold 20  cloth        90    1600 body
                                  fire -15
冰雪護手  snow_gloves.c     4/3   cold 5   cloth        30    980  hands
                                  fire -5
白頭巾    white_headband.c  5/2            cloth        30    300  head
雷電神盾  nei_shield.c      8/6   eleetric light_metal  100   1200 shield
                                  6
雷電戰甲  nei_vest.c        37/6 eletric 10 light_metal 110    1700 body
雷電披風  nei_cloak.c       7/5  eletric 7  cloth       30      700 cloak


 