
                少林寺區域開放說明  --  作者 茹比   at 94/10/4
                ==================

I. 歷史 :

    少林寺是什麼時候建寺的，並沒有人清楚，但是真正使得這個少室山下的佛教
殿堂聲名遠播的首推達摩祖師，這個從天竺跋山涉水千里而來的高僧不僅為少林寺
帶來了佛教正統禪宗的教義，更重要的，他為了維持這些整日打坐參禪的和尚們的
健康，特別將天竺密傳的導氣之術配合瑜珈和技擊之法結合，而成為一套新型的活
動，這項創舉引起了闔寺僧眾的熱中，成為每日例行的活動，漸漸的，一些僧侶發
現這些新活動竟然有自衛強身鋤強扶弱的功能，於是對它的研究形成風潮，漸漸的
，少林寺和尚的神奇能耐隨著少林寺的大名在東方大陸傳揚開來，人們就用東方大
陸的傳統說法 -- 功夫來稱這個新加入的流派，從此以後，少林寺幾乎被人和功夫
劃上了等號，反而忽略了它是禪宗的重鎮。

    少林寺不僅在功夫上享有盛名，它同時也備受東方帝國皇室的尊重，相傳在東
方帝國第一代高祖皇帝建國之時，他慕名上少林，用民族統一大義說動了一些關心
人世苦難的高僧，後來這些高僧隨他東征西討，立下了無數汗馬功勞，更多次將他
從敵人的威脅下救出，而且又在帝國安定之後，不求任何報酬的回到少林，所以歷
代皇帝都對少林寺禮敬有加，一方面是以示不忘本，另一方面是少林寺藏有高祖皇
帝御頒的丹書鐵卷，持卷者如高祖親臨，有哪個大膽皇帝敢惹到祖宗頭上？

II. 組織

    少林寺有方丈一位，統籌全寺的運作，其下各殿各堂不計其數，分別有高僧掌
理，其中專門負責武術開發與資料收集的羅漢堂、達摩堂、般若堂更是世人心目中
的武學寶山。

III. 任務列表

    a. 天心的藥草 : 藥王殿的天心大師最近很煩惱，需要有人幫忙調查一些事情。

    b. 普賢的白象 : 普賢菩薩的座騎大白象偷偷跑去玩了，把他逮回去吧 !!

IV. 生物列表

動物名稱    檔名       等級  防禦力   武器等級  傷害範圍  武器裝備   特殊能力

野蜂        hornet       2   10/4        8       3-8                 中毒
野貓        wild_cat     3   20/8        8       4-10
野狐        wild_fox     3   20/8        7       4-9
小沙彌      little_monk  4   25/8       12       5-12
靈芝寶寶    small_bug    4   25/10      12       5-13                催眠
鹿          deer         4   25/12      13       5-12
大白象      elephant     5   35/12      23      11-26                變身
靜平        gin_ping     5   30/12      18       4-11                少林長拳
知客僧      greet_monk   5   30/10      17       6-15
進香客      guest        5   32/10      17       8-17     I)藤藍
靜華        gin_hwa      6   35/11      19       8-16     W)破短掛   少林長拳
長工        worker       6   35/10      18      11-22     W)小鋤頭
初級武僧    bonze        6   35/10      12       7-14                羅漢拳
晦堤        hwei_ti      7   37/13      17       9-16     A)短掛     羅漢拳
服事僧      serv_monk    7   38/18      17       7-17     A)僧袍     少林長拳
沈思和尚    meditate_monk 8  41/18      24      11-21     A)僧袍
晦林        hwei_lin     8   37/15      23      10-18     A)短掛     伏魔棍法
                                                          W)青銅禪杖
嚴觀        yan_guan     8   40/16      21      14-24     A)短掛     太左刀法
                                                          W)長刀
嚴參        yan_san      8   40/16      22      12-22     W)鐵刀     太左刀法
管工        worker_leader 9  50/20      22      20-31     W)皮鞭
掌廚師傅    cooking_monk 9   55/20      22      20-43     W)勺子
武僧        bonze2      10   55/20      24      12-23     W)齊眉棍   伏魔棍法
華尚        hwa_son     10   55/18      28      11-26     A)黑絲綁尾 點穴
華妄        hwa_wan     10   55/18      14       2-13     A)短掛     伏虎拳
掌法僧      hand_monk   11   60/19      14       5-13                韋陀掌
棍法僧      stuff_monk  11   60/20      26      14-27     W)齊眉棍   伏魔棍法
黑衣和尚    monk        12   65/24       5       1-8      A)貓眼指環 捻花指
靈芝媽媽    big_bug     12   64/20      33      16-33                主動攻擊
								     催眠
觀宏        guan_hong   12   64/18      28      15-28     A)鹿皮衣形 伏魔棍法
                                                          W)熟銅棍
觀明        guan_ming   13   68/15      19       5-13     A)鹿皮衣形 韋陀掌
掌藥僧      herb_monk   13   65/20      33      14-34     A)紫蘇診袍 瞄神經
                                                          A)文殊牒衣 自我醫療
                                                          W)蟬翼薄刃
                                                          I)玉靈散
馬紀        monk_su1    13   60/25      34      15-30     W)如來索
                                        27       2-13     W)判官筆
誦經僧      pray_monk   14   74/30      42      19-34     A)銀灰補衲 聖言攻擊
                                                          A)伏虎指套
                                                          W)聖言杖
火工頭陀    fire_monk   14   70/30      40      20-36
紅衣羅漢    red_monk    14   65/33      30      10-25     A)白雲石手釧
                                                          A)大紅袈裟 無色刀法
                                                          W)精鋼戒刀
遠道        yeng_dou    14   64/28      30      10-25     A)鹿皮衣形 無色刀法
                                                          W)長刀
達摩的影子  damo        15   80/32      48      21-47                邪惡氣息
戒律院執事  enforcer    15   75/32      35       8-12     W)守戒棍   伏魔棍法
                                                          A)黃色袈裟
                                                          A)紫檀念珠
守閣僧      book_guard  16   85/38      21      13-28     A)紫檀念珠 捻花指
                                                          A)鹿皮衣形
掌閣僧      book_keeper 16   77/47      28      15-33     A)紫檀念珠 般若掌
                                                          A)灰補衲

狐狸精      fox         16   80/36      48      26-46     I)狐狸尾巴 專吸陽氣
空慧        kon_hwei    16   65/41      48      23-41     A)菩提念珠 金剛不壞
                                                          A)文殊牒衣 金剛禪唱
野蠻人戰士  barbarian   16   80/21      50      25-45	  W)大石棒
							  A)巨石護膝
							  A)大地之盔
戒律院空剛  gun         17   92/49      25      16-36     A)觀音臂環 龍爪手
                                                          A)如來甲冑
虛行        shi         17   96/44      55      36-62     A)御賜臂環 一指禪
                                                          A)菩提念珠
                                                          A)金剛環
                                                          A)紫羅袈裟
                                                          W)金剛杵
虛渡        shu_du      17   101/58     20      10-15     A)觀音臂環 無色刀法
                                                          A)黑□手釧
                                                          S)金剛波羅法輪
                                                          W)修羅刀
虛竹        shu_ju      17   60/35      42      23-44     A)伏虎指套 金剛不壞
                                                          A)灰補衲
                                                          W)掃把
覺遠大師    jay_yeng    18   89/50      59      40-55     A)黑晶念珠 鐵桶攻擊
                                                          A)銀灰補衲
                                                          W)大鐵桶
噴火銀象    fire_elephant 19 150/90     75      40-73                變弱
								     噴火
								     跺腳
								     quest 用
天心大師    heal_monk   19   100/48     64  	30-57     A)銀龍靴   瞄弱點
							  A)紫羅袈裟 quest
							  W)天心小刀 醫療
慧空方丈    leader_monk 19   93/55      40      24-50     A)愛染明王戒指
                                                          A)硫璃手鐲 金剛不壞
                                                          A)達摩袈裟 生命恢復
                                                          A)紫檀念珠
                                                          S)金剛波羅法輪
                                                          W)韋陀杵

* 四位絕技測試僧 *

空凡	    kon-fan     14   70/21      12       1-6      A)菩提念珠 捻花指
							  A)文殊牒衣 
空見        kon-gem	14   25/10      98      16-46                金剛不壞
								     
空性        kon-shin    14   77/19      12       1-6      A)觀音臂環 龍爪手 
							  A)如來甲冑 
虛合大師    shi-hur     14   77/22      12       1-6      A)紫羅袈裟 般若掌
                                                          A)愛染明王戒指

V. 物品列表

物品名稱   檔名         形態    特殊用途

□籃       basket       容器    無
大塊靈芝   big_pill     藥品    +HP 50
乾井	   dry_well     容器    for funny
狐狸尾巴   fox_tail     物品    隱形 for quest
葫蘆瓢兒   gourd 	物品    裝水 for quest
回陽草     herb		物品    拿回去種 for quest
達摩舍利子 magic_seed   物品    扔人 for quest
玉靈散	   red_pill     藥品	+HP 40
小塊靈芝   small_pill   藥品    +HP 20


VI. 武器列表

武器名稱    檔案名稱    武器類別    武器等級    傷害範圍    特殊攻擊

如來勾      go          longblade       35      18-30       明王攻擊
修羅刀      blade	longblade     	35	20-37
精鋼戒刀    blade3      longblade       30      20-30
少林戒刀    blade1 	longblade     	25	12-25
長刀	    blade4	longblade     	22      10-20
鐵刀        iron_blade  longblade       15       7-14

掃把        whisk       blunt            5       3-9
小鋤頭      spud        blunt            6       5-10
勺子        scoop       blunt            7       7-12
齊眉棍	    club	blunt	      	10   	 8-15
熟銅棍      copper_club blunt 	    	15     	12-18
柳木棍      poplar_club blunt           19      10-16
方便鏟      shovel      blunt           20      12-20
守戒棍      rule_staff  blunt           25      18-28
韋陀杵      staff1      blunt           30      20-40
大石棒      stone_club1 blunt           30      15-35
金剛杵      thu         blunt           32      16-32

大鐵桶	    coul	chain		15	10-15

蟬翼薄刃    healer_dagger1 dagger	30	13-26
天心小刀    holy_dagger2   dagger	36	15-32	    神聖攻擊

聖言杖	    holy_wand	wand		35	 8-14	    真言攻擊

如來鎖      rope        whip            20       1-10
皮鞭	    knout	whip		10	10-16


VII. 防具列表

防具名稱 	 檔名         	 形態    質料    AC/DB    特殊效果

達摩袈裟  	cloth1		body    monk     26/6
破摩聖甲  	cloth1a       	body    heavy    30/5
紫羅袈裟  	cloth2        	body    monk     27/5
如來甲冑  	cloth2a       	body    monk     32/6
文殊牒衣  	cloth3        	body    cloth    20/3
銀灰補衲  	cloth4        	body    monk     19/4
灰補衲    	grey_pallium  	body    cloth    10/9
鹿皮衣形  	cloth5a       	body    leather  28/0
短掛      	cloth7        	body    cloth    10/3
破短掛    	cloth8        	body    cloth    10/2
僧袍      	pallium       	body    cloth     1/3
黃色袈裟  	yellow_pallium 	body    cloth    20/5
大紅袈裟  	red_pallium   	body    cloth    15/5

金剛環    	glove1        	hands   stone     5/3
琉璃手鐲  	glove2        	hands   element   5/3
黑□手鐲  	glove3        	hands   stone     3/4
白雲石手釧	glove3a      	hands   stone     5/0

觀音臂環        armband1        arms    leather   5/3
御賜臂環        armband2        arms    leather   4/4

天帝雲鞋        boot1           feet    cloth     8/2
銀龍靴          boot2           feet    leather   8/3

紫蘇診袍        cloak3          cloak   cloth     6/2

黑晶石念珠 	necklace     	misc    stone     0/6
紫檀念珠  	necklace01    	misc    wood      0/8
菩提念珠  	necklace2     	misc    wood      0/8

愛染明王戒指 	ring1      	finger  element   0/7
金剛指環  	ring2 		finger  element   0/8
伏虎指套  	ring3		finger  leather   0/6
貓眼石指環 	ring4   	finger	stone	  0/4

金剛波羅法輪 	shield1 	shield  monk     10/6
蓮華法輪  	shield2		shield  monk	  8/2
梵天法輪  	shield3 	shield  monk	  8/4

黑絲綁尾  	silk_tail     	tail    cloth     5/0

大地之盔  	stone_helmet  	head    stone     8/1

巨石護膝  	stone_leggings 	legs    stone     8/0

