
                      火山地區域簡介(僅就目前已完成做描述)

                      作者：老貓(Oldcat)

   I.歷史背景：

    這並不是東方大陸板塊形成時就有的區域，它是大約一萬年前，由於東方板塊的
能量經過長久的累積，終於在某一天從這裡宣洩出來了。談起那一次的火山爆發真是
聞之色變，本來這裡是一大片濃密的森林，從那一刻起，瞬間天地變色，幾乎整個東
方大陸的天空都被它所噴出的火山灰所遮蔽，一連持續一個月之久，火山的熔岩才不
至又流出來，原來的森林早已成為一堆焦土，一座巨大的火山也因此而形成。

    上面的看法只是一般學者的想像，其實不然，在上古時代約幾十萬年前，掌管天
地的神創造了東方大陸，夢想把這裡建立成一個下界的樂土，眾神皆表贊同。

    在眾神間有一職司火的小神，由於相貌醜陋，諸神皆不願與之同行，久而久之，
從心裡產生了一股怨恨之氣，只是都沒有表現出來。

    後來在一個偶然的機會，聽到一個消息，有一個寶盒名曰白虎，乃是當年開天闢
地時，女媧用來裝五色彩石的盒子，該盒子乃具有靈性之物，經過數十萬年，在不斷
的隨著擁有者修煉之後，其所擁有的能力以足以翻江、倒海、移山，只要擁有者有能
力使用它。

    這個小神開始暗中調查現在這個寶盒是落在誰的手裡，．．．終於被他查出現在
的擁有者是一條黑龍，是北海龍王的嫡子，正在東方大陸的某處修煉；有一天他偷偷
的跑去黑龍住處，是一個泉水底下，正巧碰到黑龍正不知運什麼大法，只見得黑龍全
身發出青色的光芒，令他心跳加速的是看到那個盒子，盒蓋開著，盒子裡一道紫色的
光芒直射黑龍全身，他想可能黑龍正利用那盒子在修煉，他心裡想著，一定要把那盒
子偷到手。

    終於，機會來了，一天群神聚會要討論有關下界大陸應做如何安排較好，身為北
海龍王嫡子的黑龍也就陪父親開會去了，卻把寶盒留在住處未曾拿走，這個司火小神
因眾神皆不注意他，所以他就趁會開到一半時，先溜了出來，偷進黑龍的住處把寶盒
拿到手，然而他也不知道寶盒的使用方法，就想把寶盒打開看看，他慢慢的把貼在寶
盒口的符撕去，撕掉的時候，寶盒輕微的振了一下，不過這個神沒有發現，這個神將
寶盒慢慢的打開，盒子裡面是一團黃色的東西，如一塊雲團一般，漸漸的顏色變為橘
色而紅色，盒子也隨之振動的越來越厲害，這個小神已經知道有點不對勁，便想將盒
子蓋上，但已經來不及了，盒子已不能蓋上，匆忙之際，火神急忙運用神力在地上打
出一個大洞，將盒子往洞中丟去，瞬間，整個大地也隨之震動，附近的地面開始龜裂
，動物開始四處逃散，驀然、大地裂了開來，一大片火焰從裂開處竄了出來，如猛獸
般的地獄之火瞬間就把那司火的小神吞了進去，這附近的地面開始隆起，火焰不斷的
從裂口處冒出，熔岩也隨之流出，整個天空通紅一片，一座火山就這樣形成了，隨著
火山噴出的灰逐漸散佈開來，漸漸的連陽光都被遮蔽住，由於大氣的改變，產生了數
個龍捲風向四周掃去，原來的大片濃密的森林早已成為一堆焦土，這次的災難一直持
續了一個月之久，終於平靜下來。

    天上的眾神終於發覺了這次鉅變，掌管眾神的玉帝聽到之後相當憤怒，除了責罵
了眾神一頓之外，對於北海龍王父子的不慎，一沒有把寶盒收藏妥當，讓別人有機可
趁，一沒有盡到管教的責任，就把他們貶到凡間，重新修煉，對於那被火焰吞沒的小
神就去讓他去受無盡的烈火圍身之苦吧。

    ==================================================================

    在經過了時間歲月的洗禮，原來被破壞殆盡的森林終於也慢慢的有新生命的產生
，但是因為火山還是間歇的有小型的爆發，只是規模已不如第一次那樣，而且火山附
近還是很熱，不是一般人可以忍受的，而動植物也就相對的減少，由於在靠近火山的
區域謀生較為困難，所以大部份這裡的生物都是危險性較高的。 

    現在這裡是個危險的區域，很大且很容易迷路，從不少死裡逃生的東方居民口中
獲知這區域內除了一些毒物之外還住著專門獵人頭的矮靈族，已經有不少居民進去之
後就沒有回來過，當每年的特定日子，這些矮靈族人就會舉行一場盛大的矮靈祭，鼓
聲及吶喊聲在遠遠的地方就可以聽到，聽說他們都是拿活人來血祭火神來乞求來年的
平安。

   II.商店：

         無。

   III.任務概要：

         A. 幫忙找尋俄亥俄的兄弟俄勒岡。
         B. 幫助矮靈村中青年，讓他能順利的向村中美少女求婚。
         C. 找尋黑龍的寶盒。

   IV.怪物：

怪物名稱     檔名     等級   AC/DB  WC  傷害範圍  武器裝備    特殊能力    
垂死之人     deadman                            提示任務所需訊息，不可殺。
俄勒岡       oregon     3    10/3   3    1-3
眼鏡蛇       cobra      4    20/8   4    1-3                中毒
矮靈族小女孩 wgirl      4    15/4   5    4-7      紅色肚兜
                                                  玩具匕首
矮靈族小男孩 wboy       5    20/5   5    5-8      藍色肚兜
                                                   玩具槍
食屍蟲       worm       5    25/10  6    5-8                中毒
山老鼠       mrat       6    25/7   7    6-9
魚兵      fish_soldier  6    25/7   9    6-9
俄亥俄       ohio       7    30/8   10   6-10
矮靈族美少女 wmaid      8    35/10  15   8-15
矮靈族祈禱者 wprayer    8    35/10  15   8-15    祈禱者之袍
                                                 祈禱者手環
矮靈族青年   wman      10    45/15  25  10-20       
矮靈族老人   wolder    10    45/15  25  10-20      布鞋
                                                   柺杖
正殿執事    m_enforcer 11    48/20  30  12-25     執事之袍
                                                   火神鞭 
右殿執事    r_enforcer 11    48/20  30  12-25     執事之袍
                                                   火龍鞭
左殿執事    l_enforcer 11    48/15  30  12-25     執事之袍
                                                   麒麟鞭
小龍女       princess                            任務，不可殺
冒險者     advanturer  12    55/20  31  10-23     護身長槍
酋長寵物暴狼 wolf      13    60/25  21  11-25
矮靈族衛兵   wguard    14    63/15  37  15-20      火山岩鱗甲
                                                   矮靈之劍
矮靈族獵頭者 whunter   14    63/30  42  15-25      火山岩鎖子甲   
                                                   矮靈之斧
矮靈族守衛   wjailor   14    63/30  39  18-38      火山岩鎧甲
                                                   矮靈流星錘
文臣      fish_scholar 14    64/30  33  18-35      學者之袍     咒語攻擊
                                                   珊瑚戒指
                                                   學者之匕
武將      fish_general 14    63/29  34  18-40      水臂環
                                                   紅鱗甲
                                                   破冰杖
掃地工       worker    15    65/30  30  12-23     工作手套
                                                    掃把
看井守衛     wellguard 15    64/34  40  19-40     武者鬥蓬
                                                   黑長矛  
矮靈族巫醫   wdoctor   16    70/29  52  20-45     矮靈護身符   瞄血管
                                                   矮靈披風
                                                   矮靈鞋
                                                   矮靈之匕
矮靈族祭師   wwizard   16    63/28  52  17-45      矮靈護甲     咒語攻擊 
                                                   矮靈戒指
                                                   矮靈短劍
右護法－□□ right_guard 17  70/29  54  23-37      綠鬥蓬       醫療自己
                                                   狂風杖       法術攻擊
                                                                吸取敵人生命
左護衛－左青城 left_guard 17 70/32  45  25-50      雪盔         特殊攻擊
                                                   □盾
                                                   巨靈斧
獨角獸       unicorn   18    80/45  65  21-40 
矮靈族酋長   wchief    18    77/29  53  20-45      火山岩鎧冑   群體攻擊
                                                   矮靈脛甲
                                                   矮靈盾
                                                   矮靈臂環
                                                   矮靈頭盔
                                                   矮靈權杖
極惡盜賊－冷如霜 shuang 18   80/29  63  20-46      火護身符     吸取敵人生命
                                                   盜賊戒指     迷惑敵人(block)
                                                   青水短劍     特殊攻擊
                                                   黑龍寶盒
矮靈族長老   elder     19    86/41  66  18-50      矮靈手套     法術攻擊
                                                   魚皮帽       (lightning 3)
                                                   流雲脛甲
                                                   神聖護身符
                                                   矮靈長老之袍
                                                   長老法杖
井龍王    dragon_king  19   107/53  72  30-55      黃金索子甲
                                                   步雲靴
                                                   紫金冠
                                                   黑暗脛甲
                                                   龍劍

   V.武器：

武器名稱    檔案名稱     武器類別   WC   傷害範圍   特殊攻擊

玩具匕首     dagger01    dagger      4     4-7
玩具槍       wgun        thrusting   5     5-10
柺杖         wstick      blunt      10     5-15
骨刀         blade1      longblade   8     6-9
掃把         broom       blunt      10     5-15
火龍鞭       whip2       whip       20    10-20     fire
麒麟鞭       whip1       whip       20     9-18     fire
火神鞭       whip3       whip       20    10-20     fire
護身長槍     lance       jousting   23    15-28
矮靈之劍     wsword      longblade  25    15-20     fire
學者之匕     dagger03    dagger     25    18-25     energy
破冰杖       staff1      blunt      28    15-28     normal
矮靈之斧     waxe        axe        30    15-25     normal
矮靈權杖     w_staff     blunt      30    15-30     evil
黑長矛       spear1      thrusting  30    15-30   
矮靈之匕     dagger02    dagger     35    19-33     divine (for evil)
矮靈流星錘   wstar       chain      27    13-30
狂風杖       wand1       wand       35    18-27     energy
矮靈短劍     shortsword1 shortblade 35    10-30
長老法杖     wand2       wand       41    13-35     energy
青水短劍     shortsword2 shortblade 40    13-36
巨靈斧       axe1        axe        35    15-35     normal(20)
龍劍         sword1      longblade  45    25-45     cold

   VI.防具：

防具名稱    檔案名稱    型態    質料     AC/DB    特殊效果

矮靈頭盔     helmet1    head    element   6/1   energy 5
魚皮帽       helmet3    head    lether    6/2   electric 5
紫金冠       helmet2    head    element   8/0   energy 5
紅色小肚兜   dudo1      body    cloth     7/0
藍色小肚兜   dudo2      body    cloth     8/0
學者之袍     cloth2     body    cloth    11/0
祈禱者之袍   cloth1     body    cloth    11/0
執事者之袍   cloth3     body    cloth    13/0
矮靈長老之袍 cloth4     body    cloth    20/8
火山岩鱗甲   mail2      body    stone    13/0
火山岩鎖子甲 mail3      body    stone    18/0   
火山岩鎧甲   mail4      body    stone    23/1   fire 5  cold -2
紅鱗甲       mail8      body    light_m  23/5   cold -5 energy 15
矮靈護甲     mail1      body    element  27/6   mental 5
火山岩鎧冑   mail5      body    stone    28/2   fire 10 cold -5
雪盔         mail7      body    heavy_m  28/5   cold 20 fire -5
黃金索子甲   mail6      body    heavy_m  35/6   mental 10
武者鬥蓬     cloak3     cloak   cloth     8/0   energy 10 electric -5
矮靈披風     cloak1     cloak   element   4/5   divine 5
綠鬥蓬       cloak2     cloak   magic     5/6   cold 30 electric 20 fire -10
                                                white-magic -10 black-magic 10
                                                elemental 5
矮靈護身符   amulet1    misc    element   0/5   acid 5
火護身符     amulet2    misc    lether    0/7   fire 13
神聖護身符   amulet3    misc    lether    0/7   evil 10
祈禱者手環   armband1   arms    light_m   2/0
矮靈臂環     armband2   arms    element   4/4   cold 5
水臂環       armband3   arms    element   2/4   cold -5 fire 10
矮靈手套     glove1     hand    lether    4/3   
工作手套     glove2     hand    cloth     7/0
矮靈盾       shield1    shield  element   6/6   magic 5
□盾         shield2    shield  heavy_m   7/7   evil 15 mental -5
盜賊戒指     ring3      finger  lether    0/6
矮靈戒指     ring1      finger  element   0/7   poison 5
珊瑚戒指     ring2      finger  element   0/7   
矮靈脛甲     legging1   legs    element   5/2   evil 5
黑暗脛甲     legging2   legs    light_m   7/3   evil 5
流雲脛甲     legging3   legs    element   6/6   electric 5
布鞋         boots1     feet    cloth     5/0
矮靈鞋       boots2     feet    element   8/3   fire 5
步雲靴       boots3     feet    cloth     7/3   cold 5

   VII.其他物品：
  
       物品名稱       檔名         用途
 
       看守室之鑰   wguard_key    開矮靈族看守室 
       俄亥俄之戒   ohio_ring     任務用
       俄勒岡之戒   oregon_ring   任務用
       金色巧克力   g_chocolate   任務用 (hp +5)
       銀色巧克力   s_chocolate   任務用 (sp +5)
       紅色巧克力   r_chocolate   任務用 (tp +10)
       藍色巧克力   b_chocolate   任務用 (fp +5)
       黃色巧克力   y_chocolate   任務用 (alignment +10)
       大水桶       bucket        任務用
       冒險者遺體   adv_corpse    可割頭
       人頭         head          進入矮靈族部落信物
       銳利小刀     head_knife    割人頭工具
       小槌子       club          任務用
       布           cloth         任務用
       人參果       fruit         任務用
       續命藥丸     wpill         任務用
       鑽石鑰匙     daimond_key   開公主寢室
       藍玫瑰       rose          任務用
       闢水珠       waterball     可在井中來去自如
       黑龍的盒子   dragon_box    任務用

   VIII 房間數：

        野外(包括火山、地牢)：23
        部落(包括密道)：15
        神殿：21
        井(包括井龍宮)：13
