// File: /d/deathland/ruin1/down01.c
// Generated by Roommaker Thu Nov 23 20:45:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遺蹟地下室");
	ob->set_long( @LONG_DESCRIPTION
這裡是遺蹟的地下室 ,似乎是用來避難的地方 .然而地上到處是一堆堆的骨骸與乾
掉的血跡 .更讓人覺得氣氛顯得十分的詭異 .你無法想像當時的情況是如何 ,但是你或\
\許可以理解到為甚麼這地方一直沒有人發現它 ,因為當時的一場災難把這座城市的人都
給毀滅了 .甚至於躲在這裡的人都不能幸勉 .
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"up" : "/d/deathland/ruin1/ruin55", 
		"south" : "/d/deathland/ruin1/down02" ]) );
	ob->reset();
}
