// File: /d/deathland/ruin1/entry.c
// Generated by Roommaker Thu Nov 23 20:51:14 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遺蹟入口");
	ob->set_long( @LONG_DESCRIPTION
除了在你面前的一座破舊的遺蹟之外,這裡似乎是一片虛無的世界,在你的上下都是
黝黑的岩石,使你有一種沉重的壓迫感,除了退回去之外,\或許你可以進入那處未知的遺
跡看看.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"ruin" : "/d/deathland/ruin1/ruin31", 
		"back" : "/d/deathland/ruin1/path04" ]) );
	ob->reset();
}
