// File: /d/deathland/ruin1/path04.c
// Generated by Roommaker Thu Nov 23 20:51:35 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑黑的小徑");
	ob->set_long( @LONG_DESCRIPTION
一條黑黑的小路 ,這小路的通道狹隘 ,你必須很費力地才能通過這裡 .這裡是
路的盡頭 ,繼續向東走將到達另一個未知的地方 .
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/ruin1/entry", 
		"west" : "/d/deathland/ruin1/path03" ]) );
	ob->reset();
}
