// File: /d/deathland/ruin1/path01.c
// Generated by Roommaker Thu Nov 23 20:52:24 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑黑的小徑");
	ob->set_long( @LONG_DESCRIPTION
在這個隱密的大洞穴中 ,你查覺到這裡與迷宮中其他地方有一些不同 ,這裡的
空間比較開闊 .而且當你小心的把這個地方仔細地看了一遍後 ,你注意到有一條很
隱密的小徑通向東方 .
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/ruin1/path02", 
		"west" : "/d/deathland/dwarf/darkroom" ]) );
	ob->reset();
}
