// File: /d/deathland/ruin1/ruin53.c
// Generated by Roommaker Thu Nov 23 20:46:58 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遺蹟");
	ob->set_long( @LONG_DESCRIPTION
一座破舊的遺蹟 ,這裡似乎已經荒廢很久了 .地上到處是殘磚破瓦 ,更讓人覺得
這地方已經許久未曾有人煙了 .一種綠色的蘚苔植物附在兩旁的牆壁上 ,使得這地方
的氣氛更顯得十分的詭異 .
    這裡是遺蹟的一處死胡同 ,似乎這個地方是市場的所在 .你似乎還能聽到小販叫
賣的聲音 .
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/deathland/ruin1/ruin43" ]) );
	ob->set( "objects", ([ 
		"merchant" : "/d/deathland/monster/merchant03" ]) );
	ob->reset();
}
