// File: /d/deathland/ruin1/ruin34.c
// Generated by Roommaker Thu Nov 23 20:50:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遺蹟");
	ob->set_long( @LONG_DESCRIPTION
一座破舊的遺蹟 ,這裡似乎已經荒廢很久了 .地上到處是殘磚破瓦 ,更讓人覺得
這地方已經許久未曾有人煙了 .一種綠色的蘚苔植物附在兩旁的牆壁上 ,使得這地方
的氣氛更顯得十分的詭異 .
    在這裡你發現你的北邊似乎存在著人類活動的訊息 ,但是你不能夠確定 .
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/deathland/ruin1/ruin35", 
		"south" : "/d/deathland/ruin1/ruin33" ]) );
	ob->reset();
}
