// File: /d/deathland/ruin1/ruin23.c
// Generated by Roommaker Thu Nov 23 20:47:15 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遺蹟");
	ob->set_long( @LONG_DESCRIPTION
一座破舊的遺蹟 ,這裡似乎已經荒廢很久了 .地上到處是殘磚破瓦 ,更讓人覺得
這地方已經許久未曾有人煙了 .一種綠色的蘚苔植物附在兩旁的牆壁上 ,使得這地方
的氣氛更顯得十分的詭異 .
    從這裡你可以更進一步的深入遺蹟的內部 .但是你慢慢地感覺到危險已經漸漸的
逼近了 .    
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/ruin1/ruin33", 
		"west" : "/d/deathland/ruin1/ruin13" ]) );
	ob->reset();
}
