// File: /d/noden/asterism/city31.c
// Generated by Roommaker Thu Nov 23 19:12:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("城市大路");
	ob->set_long( @LONG_DESCRIPTION
這裡是艾斯特律恩(asterism)城的大道路, 由於半身人靈巧的設計天份及矮人的
建築技巧,這裡的道路十分寬敞筆直, 而且道路兩旁種植的樹木花草在相互搭配之下, 
讓人好像置身於一座優美的公園。北邊是面堅固的城牆, 經過數百年風吹日曬, 依然
屹立不搖。南邊有一條綠色的小路,似乎通往一座美麗的花園.
LONG_DESCRIPTION
	);

	ob->set_outside( "asterism" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/asterism/city21", 
		"south" : "/d/noden/asterism/city_garden", 
		"west" : "/d/noden/asterism/city41" ]) );
	ob->reset();
}
