// File: /d/noden/asterism/city11.c
// Generated by Roommaker Thu Nov 23 19:13:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("城市大路");
	ob->set_long( @LONG_DESCRIPTION
這裡是艾斯特律恩(asterism)城的大道路, 由於半身人靈巧的設計天份及矮人的
建築技巧, 這裡的道路十分寬敞筆直, 而且道路兩旁種植的樹木花草在相互搭配之下, 
讓人好像置身於一座優美的公園。北邊和東邊是堅固的城牆, 經過數百年的風吹日曬, 
依然屹立不搖。
LONG_DESCRIPTION
	);

	ob->set_outside( "asterism" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/noden/asterism/city21", 
		"south" : "/d/noden/asterism/city12" ]) );
	ob->reset();
}
