// File: /d/noden/asterism/path4.c
// Generated by Roommaker Thu Nov 23 19:14:22 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小徑");
	ob->set_long( @LONG_DESCRIPTION
你現在正漫步在一片樹林中。四周的蟬鳴鳥聲使你幾乎想要永遠住在這人間仙境,
不再回到那紛擾的世界。
LONG_DESCRIPTION
	);

	ob->set_outside( "asterism" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/asterism/path3", 
		"south" : "/d/noden/asterism/wall" ]) );
	ob->reset();
}
