// File: /d/noden/asterism/patha.c
// Generated by Roommaker Thu Nov 23 19:13:27 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小徑");
	ob->set_long( @LONG_DESCRIPTION
你現在正漫步在一片樹林中。四周的蟬鳴鳥聲使你幾乎想要永遠住在這人間仙境,
不再回到那紛擾的世界。在你西邊有棟建築物,裡面不時傳出大型動物的吼聲。
LONG_DESCRIPTION
	);

	ob->set_outside( "asterism" );
	ob->set( "exits", ([ 
		"east" : "/d/noden/asterism/path1", 
		"west" : "/d/noden/asterism/train_field" ]) );
	ob->reset();
}
