// File: /d/noden/asterism/tower2-4.c
// Generated by Roommaker Thu Nov 23 19:16:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人高塔的第四層");
	ob->set_long( @LONG_DESCRIPTION
這裡是艾斯特律恩城中矮人高塔的第四層,也就是矮人王阿萊特斯四世的起居室，
但這裡似乎是個小孩子的遊戲間。再往上一層是矮人的會議室.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/asterism/tower2-3", 
		"up" : "/d/noden/asterism/tower2-5" ]) );
	ob->set( "objects", ([ 
		"drynurse" : "/d/noden/asterism/monster/drynurse" ]) );
	ob->reset();
}
