// File: /d/noden/asterism/tower3-4.c
// Generated by Roommaker Thu Nov 23 19:15:38 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地精高塔的四樓");
	ob->set_long( @LONG_DESCRIPTION
這裡是艾斯特律恩城中地精高塔的第四層。矮人和半身人為這片土地本來的
主人建築了這麼一座外觀宏偉的住所。這兒四周的牆璧,被各式各色的寶石鑲點
得五彩繽紛。靠北邊的牆看來雖是剛補的，但是現在又是坑坑洞洞，好像被很強
的力量衝擊過很多次。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/asterism/tower3-3", 
		"up" : "/d/noden/asterism/tower3-5" ]) );
	ob->set( "objects", ([ 
		"student#2" : "/d/noden/asterism/monster/gnome_student", 
		"student#1" : "/d/noden/asterism/monster/gnome_student", 
		"teacher" : "/d/noden/asterism/monster/gnome_teacher" ]) );
	ob->reset();
}
