// File: /d/noden/asterism/tower1-1.c
// Generated by Roommaker Thu Nov 23 19:14:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("半身人高塔的底層");
	ob->set_long( @LONG_DESCRIPTION
這裡是艾斯特律恩城中半身人高塔的底層,一些名貴的壁畫以及昂貴的雕刻品讓這地
方顯得很氣派,除此之外這裡的守衛也十分森嚴,因為半身人族長就住在塔的最高層.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/asterism/tower1-0", 
		"out" : "/d/noden/asterism/city55", 
		"up" : "/d/noden/asterism/tower1-2" ]) );
	ob->set( "objects", ([ 
		"guard#3" : "/d/noden/asterism/monster/halfling_guard01", 
		"guard#2" : "/d/noden/asterism/monster/halfling_guard01", 
		"guard#1" : "/d/noden/asterism/monster/halfling_guard01" ]) );
	ob->reset();
}
