// File: /d/noden/asterism/tower1-4.c
// Generated by Roommaker Thu Nov 23 19:14:43 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("半身人高塔的第四層");
	ob->set_long( @LONG_DESCRIPTION
這裡是艾斯特律恩城中半身人高塔的第四層,許許多多的建築設計都是在此產
生的,半身人靈巧的頭腦造就了這個漂亮的城市.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/asterism/tower1-3", 
		"up" : "/d/noden/asterism/tower1-5" ]) );
	ob->set( "objects", ([ 
		"artisan" : "/d/noden/asterism/monster/artisan" ]) );
	ob->reset();
}
