// File: /d/noden/asterism/tower3-0.c
// Generated by Roommaker Thu Nov 23 19:15:24 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地精高塔的地下室");
	ob->set_long( @LONG_DESCRIPTION
這裡是艾斯特律恩城中地精高塔的地下室，所有即將外出尋求發展的地精年輕人，
依慣例都會先在這接受地精長老的訓勉。這□佈置得富麗堂皇,壁上全鑲上各式寶
石,什麼祖母綠,貓眼石,紅榴石,鑽石都看得到。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/asterism/court", 
		"up" : "/d/noden/asterism/tower3-1" ]) );
	ob->set( "objects", ([ 
		"elder" : "/d/noden/asterism/monster/gnome_elder" ]) );
	ob->reset();
}
