// File: /d/noden/asterism/tower3-5.c
// Generated by Roommaker Thu Nov 23 19:15:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地精高塔的五樓");
	ob->set_long( @LONG_DESCRIPTION
這裡是艾斯特律恩城中地精高塔的第五層。矮人和半身人為這片土地本來的
主人建築了這麼一座外觀宏偉的住所。這兒四周的牆璧,被各式各色的寶石鑲點
得五彩繽紛。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/asterism/tower3-4", 
		"up" : "/d/noden/asterism/tower3-6" ]) );
	ob->set( "objects", ([ 
		"chest" : "/d/noden/asterism/item/bigchest" ]) );
	ob->reset();
}
