// File: /d/noden/asterism/tower1-0.c
// Generated by Roommaker Thu Nov 23 19:14:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("半身人高塔的地下室");
	ob->set_long( @LONG_DESCRIPTION
這裡是艾斯特律恩城中半身人高塔的地下室,堆積著一堆雜七雜八的廢棄物,讓這地
方顯得十分混亂.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exit_c_msg", ([ ]) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/asterism/court", 
		"up" : "/d/noden/asterism/tower1-1" ]) );
	ob->set( "objects", ([ 
		"elder" : "/d/noden/asterism/monster/halfling_elder" ]) );
	ob->reset();
}
