// File: /d/noden/asterism/tower1-2.c
// Generated by Roommaker Thu Nov 23 19:14:37 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("半身人高塔的第二層");
	ob->set_long( @LONG_DESCRIPTION
這裡是艾斯特律恩城中半身人高塔的第二層,一種快樂的氣氛感染了你的心頭,在
半身人無可救藥的樂天派的影響下,他們認為一層的防衛措施已經足夠,因此這裡天天
都在開宴會,充滿著歡笑的聲音.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/asterism/tower1-1", 
		"up" : "/d/noden/asterism/tower1-3" ]) );
	ob->set( "objects", ([ 
		"girl#1" : "/d/noden/asterism/monster/halfling_girl", 
		"boy#1" : "/d/noden/asterism/monster/halfling_boy", 
		"girl#2" : "/d/noden/asterism/monster/halfling_girl", 
		"boy#2" : "/d/noden/asterism/monster/halfling_boy" ]) );
	ob->reset();
}
