// File: /d/eastland/legend/lake/house12.c
// Generated by Roommaker Thu Mar 21 17:26:33 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮房子");
	ob->set_long( @LONG_DESCRIPTION
這裡是漁村村長的住處；你一進門就看見八張椅子圍繞著中間的大桌子，椅子
大小不等，桌上還有些紙張，看來，這是開會的場所。在牆上供奉的是一張仕女圖
；圖上人物：身材苗窕，體態豐滿，雙眉間隱隱威嚴貌，顧盼間頗有勾魂奪魄之態
，這對一個平時打漁為生的村落是不尋常點。在牆角邊還有幾支漁簍子和幾根釣杆
。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/eastland/legend/lake/village12" ]) );
	ob->set( "objects", ([ 
		"captain" : "/d/eastland/legend/monster/captain1" ]) );
	ob->reset();
}
