// File: /d/eastland/legend/lake/house1.c
// Generated by Roommaker Thu Mar 21 17:25:20 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小木屋");
	ob->set_long( @LONG_DESCRIPTION
一間用繪木製成的屋子。屋內並無神壇，卻有絲絲檀香香氣撲鼻芬芳。建築雖
不似宮闕鏤簋朱宏，雕粱畫棟，但靜逸的氣氛油然而生。桌椅傢俱排列井然，桌上
一本茶花『二喬』，兩朵一白一紅的盛開著，花色純正無絲毫駁雜，可見主人對茶
花頗有研究。除此之外，屋內更無他物。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/eastland/legend/lake/village3" ]) );
	ob->set( "objects", ([ 
		"man" : "/d/eastland/legend/monster/man1", 
		"woman" : "/d/eastland/legend/monster/woman1" ]) );
	ob->reset();
}
