// File: /d/eastland/legend/lake/house18.c
// Generated by Roommaker Thu Mar 21 17:26:58 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小茅屋");
	ob->set_long( @LONG_DESCRIPTION
屋子裡幾乎沒有什麼貴重的擺設，除了牆角邊一張破爛的桌子和幾張椅子外，
四周斑白的牆壁把這裡襯托得更是淒涼。牆的另一邊有幾支破爛的漁簍子，和一支
釣杆，似乎很久沒人使用它們，它們上面都積了一層厚厚的灰塵。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/eastland/legend/lake/village18" ]) );
	ob->set( "objects", ([ 
		"older" : "/d/eastland/legend/monster/older" ]) );
	ob->reset();
}
