// File: /d/eastland/legend/lake/mountain6.c
// Generated by Roommaker Tue Jul 30 18:52:39 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山腰");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在一條山路上，山路的坡度從這裡開始平緩了些。路旁長滿了一些　　
不知名的白色花朵，聞起來有點淡淡的香氣。在花朵上有幾隻蝴蝶翩翩地飛舞著，
盡情地吸吮著花蜜；草叢裡還有蚱蜢跳來跳去，一副不怕人的樣子；路旁樹上的鳥
兒正呼朋引伴地高歌，似乎很快樂的樣子。或許，你該放下手邊的工作，投入大自
然的懷抱裡，誠所謂「休息是為了走更長的路」。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exit_suppress", ({ 
		"nu", 
		"sed" }) );
	ob->set( "exits", ([ 
		"northup" : "/d/eastland/legend/lake/mountain5", 
		"sed" : "/d/eastland/legend/lake/mountain7", 
		"southeastdown" : "/d/eastland/legend/lake/mountain7", 
		"nu" : "/d/eastland/legend/lake/mountain5" ]) );
	ob->reset();
}
