// File: /d/eastland/legend/lake/mountain4.c
// Generated by Roommaker Thu Mar 21 17:30:20 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山巔");
	ob->set_long( @LONG_DESCRIPTION
你翻過剛才那面峭壁之後來到了山的另一邊。 你現在正走在一條山巔的山路
上,山路崎嶇不平,地上長了些稀稀疏疏的野草,旁邊有一顆大樹。這裡的視野很好
,你俯視下去可以看到一面大湖。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exit_suppress", ({ 
		"bluff" }) );
	ob->set( "exits", ([ 
		"bluff" : "/d/eastland/legend/lake/mountain3", 
		"west" : "/d/eastland/legend/lake/mountain5" ]) );
	ob->reset();
}
