// File: /d/eastland/legend/lake/mountain5.c
// Generated by Roommaker Tue Jul 30 18:50:49 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山巔");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在一條山巔的山路上,山路依舊很陡, 地上長了些稀稀疏疏的野草
。這裡的視野很好,你俯視下去可以看到一面大湖。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exit_suppress", ({ 
		"sd" }) );
	ob->set( "exits", ([ 
		"sd" : "/d/eastland/legend/lake/mountain6", 
		"southdown" : "/d/eastland/legend/lake/mountain6", 
		"east" : "/d/eastland/legend/lake/mountain4" ]) );
	ob->reset();
}
