// File: /d/eastland/legend/lake/mountain0.c
// Generated by Roommaker Tue Jul 30 18:48:57 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山腳下");
	ob->set_long( @LONG_DESCRIPTION
你的四周都是峻嶙的高山,眼前有一條蜿延而上的山路。上山時可要特別小心
,尤其是在這種人煙稀少的地方,通常都會有獅子老虎這類的猛獸出現。 你身邊最
好多帶些乾糧以備後患,尤其是當山難發生時,那可是叫天天不應,叫地地不靈喔。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exit_suppress", ({ 
		"nwd" }) );
	ob->set( "exits", ([ 
		"nwd" : "/d/eastland/beggar/area/s4e2", 
		"northwestdown" : "/d/eastland/beggar/area/s4e2", 
		"up" : "/d/eastland/legend/lake/mountain1" ]) );
	ob->reset();
}
