// File: /d/eastland/legend/lake/mountain2.c
// Generated by Roommaker Thu Mar 21 17:30:00 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山巔");
	ob->set_long( @LONG_DESCRIPTION
你走著走著來到了山巔的位置, 身旁的浮雲把你籠罩在一片白霧裡,白茫茫地
使你看不到任何東西。 遠遠望去,隱隱約約有幾座突出雲層的小山群,小山群好似
戴著一頂頂白色的帽子。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exit_suppress", ({ 
		"east", 
		"down" }) );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/legend/lake/mountain3", 
		"down" : "/d/eastland/legend/lake/mountain1" ]) );
	ob->reset();
}
