// File: /d/eastland/legend/lake/mountain1.c
// Generated by Roommaker Thu Mar 21 17:29:40 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山腰");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在一條蜿延而上的山路，四周都是峻嶙的高山。這條山路出乎意外
的狹窄，它的坡度很陡讓你有種快要往下掉的感覺。山路的地上光禿禿的連一根雜
草也沒有，兩旁還有幾塊巨大的岩石。    
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"down" : "/d/eastland/legend/lake/mountain0", 
		"up" : "/d/eastland/legend/lake/mountain2" ]) );
	ob->set( "objects", ([ 
		"tiger#2" : "/d/eastland/legend/monster/tiger", 
		"tiger#1" : "/d/eastland/legend/monster/tiger" ]) );
	ob->reset();
}
