// File: /d/eastland/legend/lake/tree1.c
// Generated by Roommaker Thu Mar 21 17:26:35 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("樹洞");
	ob->set_long( @LONG_DESCRIPTION
你身處在神木的樹洞裡，在這裡，冥冥中似乎可以聽到佛家的梵語聲，它帶給你內
心一陣陣的平和感受，使你不再想要有嘶殺的念頭。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/eastland/legend/lake/plain0" ]) );
	ob->set( "objects", ([ 
		"spirit" : "/d/eastland/legend/monster/spirit1" ]) );
	ob->reset();
}
