// File: /d/eastland/legend/lake/village15.c
// Generated by Roommaker Thu Mar 21 17:29:56 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("海堤");
	ob->set_long( @LONG_DESCRIPTION
你正走在海堤上，海堤往南、北方向延申。海堤旁種滿一排排的防風林，枝幹
不硬，細細軟軟的，像木麻黃一類的植物。東邊是一片汪洋的大海，海浪不停地拍
打著坡堤。忽然！一個大浪打在岩礁上，濺起漫天的水花，你閃避不及被淋個正著
；海風吹來，遠遠眺望，幾艘漁船正隨波載浮載沈；晦暗不明的天空，烏雲團簇好
似一隻只正在張牙舞爪的野獸。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/legend/lake/village15", 
		"south" : "/d/eastland/legend/lake/village14" ]) );
	ob->reset();
}
