// File: /d/eastland/legend/lake/village2.c
// Generated by Roommaker Tue Jun 11 20:05:14 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("古木小徑");
	ob->set_long( @LONG_DESCRIPTION
你來到了一條古木小徑，小徑的兩旁有一排排不知名的樹木，樹枝擋住了陽光
，顯得有些陰涼，樹上一些鳥兒正啾啾地叫著。在北邊的樹底下似乎有著足跡，不
仔細看還不太清楚。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exit_suppress", ({ 
		"north" }) );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/legend/lake/village4", 
		"west" : "/d/eastland/legend/lake/village1", 
		"north" : "/d/eastland/legend/lake/village3" ]) );
	ob->reset();
}
