// File: /d/eastland/legend/lake/village1.c
// Generated by Roommaker Tue Jun 11 20:05:32 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("古木小徑");
	ob->set_long( @LONG_DESCRIPTION
你來到了一條古木小徑，小徑的兩旁有一排排不知名的樹木，樹枝擋住了陽光
，顯得有些陰涼，樹上一些鳥兒正啾啾地叫著。你西方有一面大湖，湖上波潭相映
，一波波的漣漪，一隻只的白鷺絲或飛或停，煞是情趣。在西南邊是湖邊的沼澤地
帶。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"lake" : "一面綠色的大湖。\n" ]) );
	ob->set( "exit_suppress", ({ 
		"southwest", 
		"west" }) );
	ob->set( "exits", ([ 
		"southwest" : "/d/eastland/legend/lake/swamp0", 
		"east" : "/d/eastland/legend/lake/village2", 
		"west" : "/d/eastland/legend/lake/lake7" ]) );
	ob->reset();
}
