// File: /d/eastland/legend/lake/village11.c
// Generated by Roommaker Thu Mar 21 17:29:14 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("漁村道路");
	ob->set_long( @LONG_DESCRIPTION
你正走在漁村的道路上，迎面撲來的是一股濃濃的腥臭味；在地上，縱橫交錯
著血水枯乾的小河；一團團蒼蠅，正汲汲於腐爛的魚肉上，不時發出嗡嗡地鳴聲。
晦暗不明的天空，烏雲團簇好似一隻只正在張牙舞爪的野獸，野獸正惡狠狠地瞪著
你，好像對著你說：『快來吧，快來吧，我的食物』。道路往西、北邊延申；南邊
有片空地；東邊有兩間房子。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/legend/lake/village12", 
		"west" : "/d/eastland/legend/lake/village9" ]) );
	ob->reset();
}
