// File: /d/eastland/legend/lake/village4.c
// Generated by Roommaker Thu Mar 21 17:27:48 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("古木小徑");
	ob->set_long( @LONG_DESCRIPTION
你來到了一條古木小徑的盡頭。小徑的兩旁有一排排不知名的樹木，樹枝擋住
了陽光，顯得有些陰涼。咦，你耳際傳來一陣陣水落差的聲音，鼻子一嗅，感到空
氣中佈滿些許的水氣，淙淙的水聲，附近似乎有條瀑布。你南邊是一座古色古香的
涼亭，累了可以去那裡稍微休憩小番。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exit_suppress", ({ 
		"east" }) );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/legend/lake/village5", 
		"south" : "/d/eastland/legend/lake/village6", 
		"west" : "/d/eastland/legend/lake/village2" ]) );
	ob->reset();
}
