// File: /d/noden/moyada/anthill/cabaret.c
// Generated by Roommaker Mon Dec  4 20:44:38 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("酒館");
	ob->set_long( @LONG_DESCRIPTION
疑! 酒館? 這蟻窩越來越奇怪了，看老闆正在辛勤的招待它的客人的模樣，
生意似乎不錯哩。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"eastdown" : "/d/noden/moyada/anthill/cellar3", 
		"eastup" : "/d/noden/moyada/anthill/cellar2" ]) );
	ob->set( "objects", ([ 
		"ant solider" : "/d/noden/moyada/monster/ant_solider", 
		"ant keeper" : "/d/noden/moyada/monster/ant_keeper", 
		"ant knight#2" : "/d/noden/moyada/monster/ant_knight", 
		"ant knight#1" : "/d/noden/moyada/monster/ant_knight" ]) );
	ob->reset();
}
