// File: /d/noden/moyada/anthill/check_point.c
// Generated by Roommaker Mon Dec  4 20:45:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("崗哨");
	ob->set_long( @LONG_DESCRIPTION
看這裡守衛森嚴的樣子，裡面一定住著極為重要的人物。守衛蟻正盯著
你看，似乎並不歡迎你。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"northwest" : "/d/noden/moyada/anthill/cellar3", 
		"east" : "/d/noden/moyada/anthill/square" ]) );
	ob->set( "objects", ([ 
		"ant guard#2" : "/d/noden/moyada/monster/ant_guard", 
		"kaisa ant" : "/d/noden/moyada/monster/kaisa_ant", 
		"ant guard#1" : "/d/noden/moyada/monster/ant_guard", 
		"ant knight" : "/d/noden/moyada/monster/ant_knight" ]) );
	ob->reset();
}
