// File: /d/noden/moyada/anthill/kitchen.c
// Generated by Roommaker Mon Dec  4 20:47:07 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("餐廳");
	ob->set_long( @LONG_DESCRIPTION
這裡看起來像是這些怪蟻們吃飯用餐的地方，蟻廚師正在忙著把食物弄的更
美味。幾隻戰士蟻正在享受它們的大餐，看起來似乎很好吃的樣子。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"northwest" : "/d/noden/moyada/anthill/cellar2" ]) );
	ob->set( "objects", ([ 
		"ant solider#1" : "/d/noden/moyada/monster/ant_solider", 
		"ant solider#2" : "/d/noden/moyada/monster/ant_solider", 
		"ant solider#3" : "/d/noden/moyada/monster/ant_solider", 
		"ant cooker" : "/d/noden/moyada/monster/ant_cooker" ]) );
	ob->reset();
}
