// File: /d/noden/forest/ruin/hidden_path4.c
// Generated by Roommaker Mon Dec  4 21:22:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("獸徑");
	ob->set_long( @LONG_DESCRIPTION
小徑南北延伸著。從這裡, 可以遙望對面的山頭, 有點模糊的影像讓
人意識到自己原來已經走了這麼遠呀! 環顧四周, 全是朦朧的山影, 這個
小盆地的四周完全被山所包圍了, 難怪人跡罕至。在往北的路上, 一些零
散的石板被鋪在地面上, 或許小徑的終點已經接近了吧?
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/forest/ruin/entry", 
		"south" : "/d/noden/forest/ruin/hidden_path3" ]) );
	ob->set( "objects", ([ 
		"wolf3" : "/d/noden/monster/wolf", 
		"wolf1" : "/d/noden/monster/wolf", 
		"wolf2" : "/d/noden/monster/wolf" ]) );
	ob->reset();
}
