// File: /d/noden/forest/ruin/hidden_path2.c
// Generated by Roommaker Mon Dec  4 21:20:57 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("獸徑");
	ob->set_long( @LONG_DESCRIPTION
小徑在樹林中南北蜿蜒著。雖說是人跡罕至, 但樹木仍然整齊地沿路
生長著。雖然枝葉已經能遮蔽整個路面, 落葉也早已積了厚厚的一大層,
但是要認出路面依然不難。只是, 大樹們總是毫無變化地排排站著。原先
就已經漫長的路, 因此更加顯得無窮無盡了。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/forest/ruin/hidden_path3", 
		"south" : "/d/noden/forest/ruin/hidden_path" ]) );
	ob->set( "objects", ([ 
		"tiger1" : "/d/noden/forest/ruin/monster/tiger" ]) );
	ob->reset();
}
