// File: /d/noden/forest/ruin/hidden_path.c
// Generated by Roommaker Mon Dec  4 21:20:34 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("獸徑");
	ob->set_long( @LONG_DESCRIPTION
小徑在你眼前向北延伸。這大概就是往谷底的路吧! 好像是非常漫長
的樣子。這裡據說是人跡罕至, 但看來似乎不是這麼回事。小徑上有著不
少來來往往的痕跡, 雖然其中有些看起來並不太像是人的...
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/forest/ruin/hidden_path2", 
		"up" : "/d/noden/forest/ruin/plate" ]) );
	ob->set( "objects", ([ 
		"boar" : "/d/noden/monster/boar", 
		"falcon" : "/d/noden/monster/falcon" ]) );
	ob->reset();
}
