// File: /d/noden/forest/ruin/n_hall.c
// Generated by Roommaker Mon Dec  4 21:22:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大廳");
	ob->set_long( @LONG_DESCRIPTION
你身處於山洞之中。這裡並不是非常黑暗, 空間也相當地廣大。雖然
年代久遠, 但從石制的地板、牆壁與天花板上時時可見精美的雕刻, 可以
看出這是個大廳。而你現在正位於這個大廳的北側, 北邊似乎有一條通道
, 但入口並不十分明顯。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exit_suppress", ({ 
		"north" }) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/forest/ruin/ne_hall", 
		"west" : "/d/noden/forest/ruin/nw_hall", 
		"north" : "/d/noden/forest/ruin/tunnel", 
		"south" : "/d/noden/forest/ruin/hall" ]) );
	ob->set( "objects", ([ 
		"goblin3" : "/d/noden/forest/monster/goblin", 
		"goblin2" : "/d/noden/forest/monster/goblin", 
		"goblin1" : "/d/noden/forest/monster/goblin" ]) );
	ob->reset();
}
