// File: /d/noden/forest/ruin/s_hall.c
// Generated by Roommaker Mon Dec  4 21:26:15 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大廳");
	ob->set_long( @LONG_DESCRIPTION
雖然是在山洞內, 但這裡並不是非常黑暗。空間也遠遠超過了原先在
入口時的估計。地面、牆壁與天花板都是石砌的, 雖然年代久遠, 但仍然
時時可見到原先精美的雕飾。是誰, 為什麼要在山腹中埋著這麼大的一個
建築物呢? 能創造這麼偉大的建築物的種族, 為什麼現在會消失無蹤呢?
    不過有件事是可以確定的, 你現在所在的場所在從前應該是個大廳。
或許曾經繁華非凡, 或許曾經莊嚴肅穆, 但現在只餘下空虛的迴音了。
    你現在身處於這個大廳的南側, 再往南就可以離開這個洞穴了。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/forest/ruin/se_hall", 
		"west" : "/d/noden/forest/ruin/sw_hall", 
		"north" : "/d/noden/forest/ruin/hall", 
		"south" : "/d/noden/forest/ruin/entry" ]) );
	ob->reset();
}
