// File: /d/noden/forest/ruin/tunnel.c
// Generated by Roommaker Mon Dec  4 21:29:37 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("通道");
	ob->set_long( @LONG_DESCRIPTION
這裡是條南北方向的通道, 上下左右的牆壁均是由石塊砌成的, 看來
相當地雄偉壯觀。通道的兩側排列著精美的石雕像, 而且各個都有不同的
神情姿勢, 令人為建造者的心思讚歎不已。
    通道的南邊是個大廳, 往北則是一片黑暗。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"north" : "/d/noden/forest/ruin/tunnel_2", 
		"south" : "/d/noden/forest/ruin/n_hall" ]) );
	ob->set( "item_desc", ([ 
		"statues" : @LONG_TEXT
    這些石雕像都被安置於壁上一個個凹入的半圓形小洞中, 被維護得相
當好。他們均是以小鬼族的造型來塑造的, 活潑的神情與栩栩如生的姿態
令觀賞者不由得發出會心的一笑。
LONG_TEXT
, 
		"statue" : @LONG_TEXT
    這個石雕像被安置於壁上一個個凹入的半圓形小洞中, 被維護得相當
好。他是以小鬼族的造型來塑造的, 活潑的神情與栩栩如生的姿態令觀賞
者不由得發出會心的一笑。
LONG_TEXT
 ]) );
	ob->reset();
}
