// File: /d/noden/forest/ruin/w_hall.c
// Generated by Roommaker Mon Dec  4 21:31:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("大廳");
	ob->set_long( @LONG_DESCRIPTION
你身處於山洞之中。這裡並不是非常黑暗, 空間也相當地廣大。雖然
年代久遠, 但從石制的地板、牆壁與天花板上時時可見精美的雕刻, 可以
看出這是個大廳。而你現在身處於這個大廳的西側。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/forest/ruin/hall", 
		"north" : "/d/noden/forest/ruin/nw_hall", 
		"south" : "/d/noden/forest/ruin/sw_hall" ]) );
	ob->reset();
}
