// File: /d/eastland/ianyeu/elder_house.c
// Generated by Roommaker Wed May 15 19:34:19 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("長老之屋");
	ob->set_long( @LONG_DESCRIPTION
當你踏進這□時, 立刻被四周的物品所吸引。在牆上, 
掛滿了寶刀、利劍、長弓 .... 等各類武器, 同時在牆角及
大大小小的櫥櫃中, 亦堆滿了數不清的各式珠寶衣物; 但你
也注意到其中竟也有如繃帶、火把、藥瓶之類的『垃圾』, 
看來這□的主人是個『蒐集狂』。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/ianyeu/hamlet_path2" ]) );
	ob->set( "objects", ([ 
		"elder" : "/d/eastland/ianyeu/monster/elder" ]) );
	ob->reset();
}
