// File: /d/eastland/ianyeu/guey_home.c
// Generated by Roommaker Wed May 15 19:35:29 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("民宅");
	ob->set_long( @LONG_DESCRIPTION
這是一間磚造的平房。雖然屋內仍擺置著許多傢俱,
但是卻都堆積著厚厚的一層灰塵, 甚至在牆角等陰暗之處還
有蛛網! 可見得此屋不是無人居住, 即是主人無心打掃....
就在你想離去之時, 你發現在牆角處竟有一張桌子特別乾淨!
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"tablet" : "一個紫檀木刻成的靈位牌, 上面寫著『愛女筱梅(sheaumei)之靈』。\n", 
		"table" : @LONG_TEXT
一張擦拭得潔淨十分的檀木桌, 桌上除了一些鮮花素果外, 你還看到有一個牌位(tablet)。
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/ianyeu/hamlet_path2" ]) );
	ob->set( "objects", ([ 
		"mother" : "/d/eastland/ianyeu/monster/guey_mother" ]) );
	ob->reset();
}
