// File: /d/eastland/ianyeu/hamlet_path1.c
// Generated by Roommaker Wed May 15 19:37:15 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小徑");
	ob->set_long( @LONG_DESCRIPTION
你正走在煙雨村內的小徑上。當你往前走時, 你感覺到
這兒似乎是人煙稀少; 不僅屋宇疏落, 連小路上都雜草叢生,
你不禁懷疑這是否為一個廢棄的村莊! 不過你注意到在東、
西兩方各有一間小屋。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"southwest" : "/d/eastland/13,14.east", 
		"east" : "/d/eastland/ianyeu/wang_home", 
		"north" : "/d/eastland/ianyeu/hamlet_path2", 
		"west" : "/d/eastland/ianyeu/hunter_house" ]) );
	ob->reset();
}
