// File: /d/eastland/ianyeu/hunter_house.c
// Generated by Roommaker Wed May 15 19:37:53 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("獵人小屋");
	ob->set_long( @LONG_DESCRIPTION
一間用茅草蓋成的小屋。你看到四周的牆上掛滿了各種
動物的標本, 而最令你驚訝的是: 不僅有鹿角、狼皮、虎頭
、獅身、熊掌 .... 等, 甚至在北面的牆上還有一隻麒麟牙!!
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/ianyeu/hamlet_path1" ]) );
	ob->set( "objects", ([ 
		"hunter" : "/d/eastland/ianyeu/monster/hunter" ]) );
	ob->reset();
}
