// File: /d/eastland/ianyeu/wang_home.c
// Generated by Roommaker Wed May 15 19:38:23 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("民宅");
	ob->set_long( @LONG_DESCRIPTION
你正在一間狹小的木屋中, 可是或許是主人太窮了, 
以致於讓你有一種空曠的感覺。你看到除了一張桌子及幾
把椅子外, 就沒有其它的傢俱了。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/ianyeu/hamlet_path1" ]) );
	ob->set( "objects", ([ 
		"wang" : "/d/eastland/ianyeu/monster/wang" ]) );
	ob->reset();
}
