// File: /u/m/mad/room/grave_yard4.c
// Generated by Roommaker Tue May 23 17:25:38 1995

#include "mad.h"

inherit ROOM;

void create()
{
	::create();
   set_short( "墓地" );
	set_long( @LONG_DESCRIPTION
這裡是墳場的一處盡頭, 四周仍然是高大濃密的樹木,
而且除了剛才通向這兒的小徑, 到處佈滿了雜草荊棘, 令你
寸步難行。當你掃視這裡時, 你看到所有的墓碑(headstone)
不是歪斜傾頹, 就是損壞不堪辨認; 但是你竟然看到在角落
處竟有一個完整的墓碑!
LONG_DESCRIPTION
	);

   set( "c_item_desc", ([
     "headstone" : "一大塊青石刻成的石碑, 可惜上面的字跡已斑駁不堪辨認。\n"
        ]) );
   set( "objects", ([
            "father" : IANMOB"false_father" ]) );
	set( "exits", ([ 
            "northeast" : IAN"grave_yard1" ]) );
	reset();
}
