// File: /u/m/mad/room/grave_yard1.c
// Generated by Roommaker Tue May 23 17:29:09 1995

#include "mad.h"

inherit ROOM;

void create()
{
	::create();
   set_short( "墓場叉路" );
	set_long( @LONG_DESCRIPTION
當你爬上此山丘之頂時, 眼前出現的是一大片的亂葬崗。
抬頭望去, 四周都是高大蓊鬱的相思木, 因此即使是在日正當
中時, 陽光亦絲毫無法照射進這裡。
LONG_DESCRIPTION
	);

   set( "objects", ([
           "zombie" : IANMOB"zombie2" ]) );
	set( "exits", ([ 
           "southeast" : IAN"grave_yard2", 
           "north" : IAN"grave_yard3", 
        "down" : "/d/eastland/11,14.east",
           "southwest" : IAN"grave_yard4" ]) );
	reset();
}
