// File: /u/m/mad/room/hamlet_path2.c
// Generated by Roommaker Wed May  3 12:47:05 1995

#include "mad.h"

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
	set_short("小徑");
	set_long( @LONG_DESCRIPTION
你正走在煙雨村內的小徑上。當你往前走時, 你感覺到
這兒似乎是人煙稀少; 不僅屋宇疏落, 連小路上都雜草叢生,
你不禁懷疑這是否為一個廢棄的村莊! 不過你注意到在東、
西、北各有一間小屋。
LONG_DESCRIPTION
	);

   set_outside("eastland");
	set( "exits", ([ 
           "east" : IAN"guey_home", 
           "north" : IAN"elder_house", 
           "west" : IAN"liang_home", 
           "south" : IAN"hamlet_path1" ]) );
   create_door( "west", "east", ([
                "keyword" : ({ "wooden door", "door" }),
                "name" : "wooden door",
                "c_name" : "木門",
                "c_desc" : "一扇很普通的木門",
                "status" : "locked",
                "lock" : "IANYEU_LIANG_HOME"
        ]) );
	reset();
}
