// File: /u/m/mad/room/liang_home.c
// Generated by Roommaker Wed May  3 12:28:48 1995

#include "mad.h"

inherit DOORS;
inherit ROOM;

int cleaver = 1;

void create()
{
	::create();
   set_short( "民宅" );
	set_long( @LONG_DESCRIPTION
這是一間平凡的小木屋。當你環顧四周時, 看到所有的
窗戶均被釘上木條而封死; 雖然大門敞開, 卻有一層厚厚的
布幔遮住了門口, 因此, 縱使是白日, 屋內仍是一片黑暗,
或許這家人在懼怕什麼吧!
LONG_DESCRIPTION
	);

   set( "objects", ([
           "mother" : IANMOB"liang_mother",
           "girl" : IANMOB"girl" ]) );
	set( "exits", ([ 
          "east" : IAN"hamlet_path2" ]) );
   create_door( "east", "west", ([
                "keyword" : ({ "wooden door", "door" }),
                "name" : "wooden door",
                "c_name" : "木門",
                "c_desc" : "一扇很普通的木門",
                "status" : "locked",
                "lock" : "IANYEU_LIANG_HOME"
        ]) );
   set( "c_item_desc", ([
            "bed" : "一個普普通通的小木床.\n" ]) );
   set( "search_desc", ([
            "bed" : "@@search_bed" ]) );
	reset();
}

void reset()
{
   ::reset();
   cleaver = 1;
}

string search_bed()
{
   object obj;

   if( !cleaver ) return "你找了又找，並沒有發現任何東西。\n";

   obj = new( IANOBJ"cleaver" );

   obj->move(this_object());
   cleaver = 0;
   return "你仔細地搜找小木床, 發現了一把屠刀!\n";
}
void init()
{
  if(this_player()) this_player()->set_explore("eastland#20");
}
