// File: /d/eastland/haiwei/hockshop.c
// Generated by Roommaker Sat Jan 22 13:08:55 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("豐來當鋪");
        set_long( @C_LONG_DESCRIPTION
你現在走進了一間佈置得相當考究的廳院，門口一爿藍色的布簾上寫著四個大字
「豐來當鋪」，這家當鋪是海威鎮大財主聶員外的產業，大朝奉錢先生是從京城來的
有名骨董專家，對稀奇古怪的東西特別有研究。
C_LONG_DESCRIPTION
        );

        set( "light", 1 );
        set( "exits", ([ 
                "east" : "/d/eastland/haiwei/mroad4" ]) );
        set( "objects", ([
                "keeper" : "/d/eastland/haiwei/monster/keeper_chien" ]) );
        reset();
#include <replace_room.h>
}
