// File: /d/eastland/haiwei/inn1.c
// Generated by Roommaker Sat Jan 22 03:02:22 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("悅來客棧");
        set_long( @C_LONG_DESCRIPTION
你現在正站在一間客棧門前的空地上，門口有幾根讓客人栓馬用的木樁，客棧
的大門敞開著，一串燈籠垂在大柱旁，上面寫著「悅來客棧」四個字。往西是一條
青石大道，南邊一排大樹，樹後是一片青翠的田野。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "exits", ([ 
                "west" : "/d/eastland/haiwei/mroad4", 
                "east" : "/d/eastland/haiwei/inn2" ]) );
        set( "objects", ([
                "carter#1": "/d/eastland/haiwei/monster/carter",
                "carter#2": "/d/eastland/haiwei/monster/carter" ]) );
        reset();
#include <replace_room.h>
}
