// File: /d/eastland/haiwei/inn2.c
// Generated by Roommaker Sat Jan 22 03:12:03 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("悅來客棧");
        set_long( @C_LONG_DESCRIPTION
這裡是海威鎮的悅來客棧，往來官道上的旅客和官差都常常在這裡休息，在這裡
可以打聽到各地的消息和傳言，這裡的店小二非常熱心助人，如果你有什麼困難儘管
向他開口，一定會得到幫助。
C_LONG_DESCRIPTION
        );

        set( "light", 1 );
        set( "exits", ([ 
                "up" : "/d/eastland/haiwei/inn3", 
                "west" : "/d/eastland/haiwei/inn1" ]) );
        set( "objects", ([
                "waiter" : "/d/eastland/haiwei/monster/waiter",
                "chief" : "/d/eastland/haiwei/monster/chief_merc",
                "merc#1" : "/d/eastland/haiwei/monster/mercenary",
                "merc#2" : "/d/eastland/haiwei/monster/mercenary",
                "merc#3" : "/d/eastland/haiwei/monster/mercenary"]) );
        reset();
#include <replace_room.h>
}
