// File: /d/eastland/haiwei/inn3.c
// Generated by Roommaker Sat Jan 22 03:19:17 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("悅來客棧");
        set_long( @LONG_DESCRIPTION
這裡是悅來客棧的二樓上座，喜歡清淨和出手闊綽的人都喜歡在這裡喝酒聊天
，面對著西邊的座位可以看到客棧前的空地和大街，一排綠意盎然的盆栽裝飾著靠
窗的扶手，靠東邊一座木梯往下通往一樓。
LONG_DESCRIPTION
        );

        set( "light", 1 );
        set( "exits", ([ 
                "down" : "/d/eastland/haiwei/inn2" ]) );
        reset();
}
