// File: /d/eastland/haiwei/market2.c
// Generated by Roommaker Mon Jan 10 13:34:29 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("魚市場");
        set_long( @C_LONG_DESCRIPTION
你現在來到海威鎮的魚市場中，這裡原來是從前的造船廠，但是現在漁民們都
將在海上捕到的漁獲拿到這裡拍賣，久而久之就成了專賣漁獲的市集，地面上到處
都是從魚簍中落下來的魚鱗和血水，一股濃濃的魚腥味充斥這整個市場。
C_LONG_DESCRIPTION
        );

        set( "light", 1 );
        set( "exits", ([ 
                "south" : "/d/eastland/haiwei/market4", 
                "east" : "/d/eastland/haiwei/market1" ]) );
        set( "objects", ([ 
                "merchant#1" : "/d/eastland/haiwei/monster/merchant" ]) );
        reset();
#include <replace_room.h>
}
