// File: /d/eastland/haiwei/mroad2.c
// Generated by Roommaker Tue Jan 25 02:51:16 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("海威鎮大街");
        set_long( @C_LONG_DESCRIPTION
你現在正走在海威鎮的大街上，北邊是一個小茶棚，茶棚外懸掛著一個素色
燈籠，上面寫著「好茶亭」。往東是一條寬敞的大街，西邊是條青石大道，海威
鎮的居民們把這條大道稱做「官道」，因為往來南北的官差常常日夜不停地縱馬
馳騁在這條大道上。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "light", 1 );
        set( "exits", ([ 
                "north" : "/d/eastland/haiwei/tea_shop", 
                "west" : "/d/eastland/haiwei/mroad3", 
                "east" : "/d/eastland/haiwei/mroad1" ]) );
        set( "objects", ([ 
                "soothsayer" : "/d/eastland/haiwei/monster/soothsayer" ]) );
        reset();
#include <replace_room.h>
}
