// File: /d/eastland/haiwei/mroad4.c
// Generated by Roommaker Sat Jan 22 13:03:48 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("青石大道");
        set_long( @C_LONG_DESCRIPTION
你現在正走在一條青石大道上，東邊是一間兩層樓高的客棧，客棧門口插著數
十枝綠色鑲白邊的旗子(flags)，西邊是一家當鋪，往南的大道通往一片青翠的田
野。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "light", 1 );
        set("item_desc",([
                "flags" : "這幾枝旗子看起來像是家鏢局的旗幟，上面繡著一個大大的「周」字。\n" ]) );
        set( "exits", ([ 
                "west" : "/d/eastland/haiwei/hockshop", 
                "north" : "/d/eastland/haiwei/mroad3",
           //     "south" : "/d/eastland/haiwei/cornfield",
               "south" : "/d/eastland/beggar/area/mroad5", 
                "east" : "/d/eastland/haiwei/inn1" ]) );
        reset();
#include <replace_room.h>
}
