// File: /d/eastland/haiwei/mroad1.c
// Generated by Roommaker Sat Jan 22 06:54:16 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("海威鎮大街");
        set_long( @C_LONG_DESCRIPTION
你現在正走在海威鎮的大街上，東邊是海威鎮中心的路口，南邊是魚市場，不過
從這裡沒有路進去，北邊不遠處就是海岸，一些磚瓦屋散佈在路旁，為了抵擋海風，
這些屋子都在屋後種了一排排的樹木，海威鎮的大街往西邊延伸出去。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "light", 1 );
        set( "exits", ([ 
                "west" : "/d/eastland/haiwei/mroad2", 
                "east" : "/d/eastland/haiwei/road_cross" ]) );
        set( "objects", ([ 
                "beggar" : "/d/eastland/haiwei/monster/beggar" ]) );
        reset();
#include <replace_room.h>
}
