// File: /d/eastland/haiwei/mroad3.c
// Generated by Roommaker Sat Jan 22 02:47:08 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("青石大道");
        set_long( @C_LONG_DESCRIPTION
你現在正走在一條青石板鋪成的大道，往東是海威鎮的大街，西邊是一家鎮上
的大財主聶員外開的商店，青石大道由南往北貫通海威鎮，往北是一座雄偉的牌樓
，上面刻著「鎮海門」三個大字，往南的青石大道通往一片綠油油的田野。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "exits", ([ 
                "south" : "/d/eastland/haiwei/mroad4", 
                "west" : "/d/eastland/haiwei/shop", 
                "north" : "/d/eastland/haiwei/n_gate", 
                "east" : "/d/eastland/haiwei/mroad2" ]) );
        set( "objects", ([ 
                "vender" : "/obj/vendor" ]) );
        reset();
#include <replace_room.h>
}
