// File: /d/eastland/haiwei/n_gate.c
// Generated by Roommaker Fri Jan 21 20:16:14 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("鎮海門");
        set_long( @C_LONG_DESCRIPTION
你現在來到一座雄偉的牌樓前，牌樓上的石匾刻著三個龍飛鳳舞的大字「鎮海
門」，青石道穿過牌樓往北是一條兩旁種滿木棉樹的大道，往南的路口銜接海威鎮
的大街，東邊一座小茶亭，不過入口不在這一邊。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "exits", ([ 
                "south" : "/d/eastland/haiwei/mroad3", 
                "northwest" : "/d/eastland/16,9.east" ]) );
        set( "objects", ([ 
                "bonze" : "/d/eastland/haiwei/monster/bonze" ]) );
        reset();
#include <replace_room.h>
}
