// File: /d/eastland/haiwei/road_cross.c
// Generated by Roommaker Thu Dec 30 02:14:30 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("海威鎮街道");
        set_long( @C_LONG_DESCRIPTION
你現在站在海威鎮中心的路口，北邊是一條碎石路，通往海威鎮的港口，東邊
是海威鎮有名的「鎮海將軍廟」，裡面奉祀著三百年前打敗入侵的海盜王的鎮海大
將軍，南邊是一個熱鬧的魚市場，從這裡都可以聽見魚販叫賣的吆喝聲，往西則是
海威鎮的大街。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "light", 1 );
        set( "exits", ([ 
                "west" : "/d/eastland/haiwei/mroad1", 
                "north" : "/d/eastland/haiwei/road_jetty", 
                "south" : "/d/eastland/haiwei/market1", 
                "east" : "/d/eastland/haiwei/temple_square" ]) );
        reset();
#include <replace_room.h>
}
