// File: /d/eastland/haiwei/road_jetty.c
// Generated by Roommaker Tue Dec 28 22:44:58 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("海威港");
        set_long( @C_LONG_DESCRIPTION
你現在正走在海威鎮通往港口的碎石路上，你的西邊是一望無際的大海，海岸
邊怪石嶙峋，顯示海威港得天獨厚的地理環境，據說這一帶雖然有海盜出沒，但是
他們從來不敢攻打海威鎮，就是因為海威鎮的地形易守難攻，東邊的空地上是一列
列曬魚網的木架，往南不遠處是一個魚市場。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "light", 1 );
        set( "exits", ([ 
                "north" : "/d/eastland/haiwei/jetty", 
                "south" : "/d/eastland/haiwei/road_cross" ]) );
        reset();
#include <replace_room.h>
}
