// File: /d/eastland/haiwei/shop.c
// Generated by Roommaker Fri Jan 21 02:37:34 1994

#include <mudlib.h>

inherit SHOP;

void create()
{
        ::create();
        set_short("聶記商行");
        set_long( @C_LONG_DESCRIPTION
你現在來到一家裝飾得美侖美奐的商店，漆著烏亮光澤紅漆的櫃檯和雕工精細
的檀木桌椅，大廳中央鋪著一張白熊皮，廳上掛著一塊大匾「門庭若市」，在大廳
西邊一座屏風隔出一個內廳，東邊是往大街的出口。
C_LONG_DESCRIPTION
        );

        set( "light", 1 );
        set( "exits", ([ 
                "east" : "/d/eastland/haiwei/mroad3" ]) );
        set( "objects", ([
                "trashcan" : "/obj/trashcan" ]) );
        reset();
}
