// File: /d/eastland/haiwei/tea_shop.c
// Generated by Roommaker Sat Jan 22 02:36:54 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("好茶亭");
        set_long( @C_LONG_DESCRIPTION
你現在來到一個小茶亭，一塊碧綠泛著油亮的竹板掛在茶亭的橫樑上，上面
用娟秀的字體寫著一些價目表(menu)，這裡的桌椅大多是竹製的，茶亭的四面都
是透光的竹簾窗，你可以看到北邊不遠處的海岸以及東北邊的碼頭。
C_LONG_DESCRIPTION
        );

        set( "light", 1 );
        set( "exits", ([ 
                "south" : "/d/eastland/haiwei/mroad2" ]) );
        set( "objects", ([ 
                "girl" : "/d/eastland/haiwei/monster/girl" ]) );
        reset();
}
void init()
{ if(this_player()) this_player()->set_explore("eastland#18");
}
