
// File: /d/eastland/haiwei/temple_square.c
// Generated by Roommaker Mon Jan 31 06:47:24 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("廟前廣場");
        set_long( @C_LONG_DESCRIPTION
你現在正站在鎮海將軍廟前的廣場，一對神態威武的石獅子(statue)站在廟門
口，廣場中央還有一個大香爐(censer)，嫋嫋的香菸襯托著將軍廟宏偉的建築，營
造出一種虔誠祈福的氣氛。
C_LONG_DESCRIPTION
        );

        set_outside( "haiwei" );
        set( "light", 1 );
        set( "item_desc", ([ 
                "censer" : "這是一個銅鑄的大型香爐，上面刻著「威鎮四海，保境衛民」八個大字。\n", 
                "statue" : "這對石獅子因為歲月的關係，上面已經被海風侵蝕出許多的坑洞。\n" ]) );
        set( "exits", ([ 
                "west" : "/d/eastland/haiwei/road_cross", 
                "east" : "/d/eastland/haiwei/temple" ]) );
        set( "objects", ([ 
                "martialist" : "/d/eastland/haiwei/monster/entertainer", 
                "sparrow#1" : "/d/eastland/haiwei/monster/sparrow", 
                "sparrow#2" : "/d/eastland/haiwei/monster/sparrow", 
                "sparrow#3" : "/d/eastland/haiwei/monster/sparrow" ]) );
        reset();
#include <replace_room.h>
}
