// File: /d/eastland/haiwei/temple.c
// Generated by Roommaker Thu Dec 30 02:04:36 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
        ::create();
        set_short("鎮海將軍廟");
        set_long( @C_LONG_DESCRIPTION
你現在正站在鎮海將軍廟的大殿裡，一張硃紅色的大供桌上排滿了各式鮮花
素果，鎮海將軍的神像威風凜凜地站在你面前的供桌上，兩邊的石柱上刻著一副
對聯(distich)，北邊和南邊的圓形拱門通往將軍廟旁的迴廊，東邊敞開的大門
門板上畫著兩個手執方天畫戟的威武將軍(lieutenant)，正對廟裡的人們瞪視著
。你可以向鎮海將軍拜拜許願(worship)，說不定他會保佑你。
C_LONG_DESCRIPTION
        );

        set( "light", 1 );
        set( "item_desc", ([ 
                "distich" : "上面寫著:\n      風調雨順、國泰民安\n", 
                "lieutenant" : "這是鎮海將軍當年打敗海盜時的副將，人稱「左將軍」與「右將軍」。\n" ]) );
        set( "exits", ([ 
                "west" : "/d/eastland/haiwei/temple_square" ]) );
        reset();
}
void init()
{
	add_action("do_worship","worship");
}
int do_worship()
{
	tell_object(this_player(),
	"你雙手合什，向鎮海將軍的神像拜拜，默默的祈求 ES 風調雨順，\n"
	"每一個 ES 的朋友都幸福快樂 !!\n");
	this_player()->save_me();
        this_player()->set_explore("eastland#17");
	"/adm/daemons/backup"->user_backup(this_player());
	return 1;
}
