// File: /d/noden/11,5.noden.c
// Generated by Roommaker Tue Dec 14 12:38:27 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("河流上游");
	set_long( @LONG_DESCRIPTION
你現在沿著河流來到它的上游，你的西邊是一座高聳入雲的山脈，河流從山上
直瀉而下造成一道壯觀的瀑布(waterfall)，你發現岸邊有一些腳印通往瀑布後面，
難道....，如果你想探個究竟的話，最好先學會游泳再來。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "c_item_desc", ([ 
		"waterfall" : @LONG_TEXT
這道瀑布從半山腰直瀉而下，高度至少有 200 公尺，聲勢頗為壯觀，從河邊
草叢的腳印判斷，瀑布後面可能有山洞，如果你想穿過(pass)瀑布進入山洞的
話，必須先逆流游到瀑布前面。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "d/noden/11,4.noden", 
		"east" : "d/noden/12,5.noden" ]) );
	set( "original", "d/noden/11,5" );
	set( "virtual_server", "/d/noden/virtual/noden_server" );
	set( "x_coordinate", 11 );
	set( "y_coordinate", 5 );
	set( "objects", ([
		"boar" : "/d/noden/monster/boar" ]) );
	reset();
}

void init()
{
	add_action( "do_pass", "pass" );
}

int do_pass(string arg)
{
	if( !arg || arg!="waterfall" )
            return notify_fail(
                    "通過什麼？\n" );
	if( random( (int)this_player()->query_skill("swimming") ) < 20 ) {
               write(
                    "你企圖遊過瀑布下的急流，但是被湍急的河水給衝回來。\n"
              );
		return 1;
	}
   write(
            "你奮力向瀑布游去，果然不出所料，瀑布後面有一個洞穴！\n"
     );
	this_player()->move_player( "/d/noden/tamumu/cave1", "SNEAK" );
   this_player()->set_explore("noden#27");
	return 1;
}

