// File: /d/noden/13,8.noden.c
// Generated by Roommaker Sun Dec 19 20:10:49 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("森林");
	set_long( @LONG_DESCRIPTION
你現在正走在一片森林之中，在你東邊和南邊都是空曠的平地，但是這裡的
樹木長得異常茂密，你注意到有一顆大得很不尋常的暗紅色岩石(stone)，上面光
溜溜的，沒有任何青苔或藤蔓。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "c_item_desc", ([ 
		"mark" : "一個小小的蜘蛛符號，不仔細看會誤認為是岩石上的小斑點。\n", 
		"stone" : @LONG_TEXT
這塊岩石看起來應該是火山地區才有的東西，怎麼會出現在這裡？你左看右看
總是覺得似乎有什麼不對勁.....
LONG_TEXT
, 
		"crack" : "這個裂縫不大，不過如果你不怕髒的話，勉強可以擠進去(enter)看。\n" ]) );
	set( "exits", ([ 
		"south" : "d/noden/13,9.noden", 
		"north" : "d/noden/13,7.noden", 
		"west" : "d/noden/12,8.noden", 
		"east" : "d/noden/14,8.noden" ]) );
	set( "objects", ([ 
		"spider" : "/d/noden/monster/spider" ]) );
	set( "original", "d/noden/13,8" );
	set( "search_desc", ([ 
		"stone" : "@@search_stone",
 ]) );
	set( "virtual_server", "/d/noden/virtual/noden_server" );
	set( "x_coordinate", 13 );
	set( "y_coordinate", 8 );
	reset();
}

void init()
{
	add_action( "do_enter", "enter" );
}

string search_stone()
{
    if( this_player() ) this_player()->set_explore("noden#28");
   return
      "你仔細地撥開岩石附近的草叢，發現了一個蜘蛛的符號(mark)，這個符號刻在\n"
        "岩石的一個裂縫(crack)旁邊。\n" ;
}

int do_enter(string arg)
{
	if( !arg || arg!="crack" )
            return notify_fail(
                    "進入哪裡？\n" );
   write(
            "你小心地擠進窄小的縫隙，突然，腳下一個踩空....\n" );
    tell_room( this_object(),
            this_player()->query("c_name") + "走到岩石後面，你聽到一聲驚呼，然後人就不見了....\n",
		this_player() );
	this_player()->move_player( "/d/noden/tomb/tomb1", "SNEAK" );
   tell_room( "/d/noden/tomb/tomb1",
            this_player()->query("c_name") + "從上面的洞口掉了下來。\n",
		this_player() );
	return 1;
}
