// File: /d/noden/16,10.noden.c
// Generated by Roommaker Thu Nov 25 09:27:03 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("河邊彎路");
	set_long( @LONG_DESCRIPTION
這條路在這裡彎向東方，河流在你的東北方不遠處注入大海，路旁許多
修剪整齊的樹木筆直地站在道路兩旁，你的東邊就是繁華熱鬧的海港都市藍
沙港，這裡一向是許多冒險者常到的交通要道，許多傳奇的故事也都以這裡
做背景。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "exits", ([ 
		"south" : "d/noden/16,11.noden", 
		"north" : "d/noden/16,9.noden", 
		"west" : "d/noden/15,10.noden", 
		"east" : "/d/noden/bluesand/port_r0" ]) );
	set( "objects", ([
	   "chocobo#1" : "/d/noden/moyada/monster/chocobo",
        ]));
	set( "original", "d/noden/16,10" );
	set( "virtual_server", "/d/noden/virtual/noden_server" );
	set( "x_coordinate", 16 );
	set( "y_coordinate", 10 );
	reset();
}

int clean_up() { return 0; }
