// File: /d/noden/16,13.noden.c
// Generated by Roommaker Wed Dec 22 14:55:12 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("廢棄古屋");
	set_long( @LONG_DESCRIPTION
你現在來到一處荒涼的空地上，北邊和西邊是一片茂密的森林，南邊和東邊
則是烏黑惡臭的沼澤地帶，在你面前的是一棟看起來荒廢了很久的古屋(house)
，屋子的牆壁已經大部分被苔蘚(moss)類植物蓋滿了，大門歪歪斜斜地倒在一旁
，這個景象使你不禁想到小時候所聽過的鬼故事。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "c_item_desc", ([ 
		"house" : @LONG_TEXT
這間屋子大概就是傳說中的鬼屋吧，大門沒有關，你敢不敢進去(enter)試試
自己的膽量？
LONG_TEXT
, 
		"moss" : @LONG_TEXT
這些苔蘚植物看起來青一塊、白一塊，有的上面還有一些綠色的黏液，實在
有夠噁心。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"south" : "d/noden/16,14.noden", 
		"north" : "d/noden/16,12.noden", 
		"west" : "d/noden/15,13.noden", 
		"east" : "d/noden/17,13.noden" ]) );
	set( "original", "d/noden/16,13" );
	set( "virtual_server", "/d/noden/virtual/noden_server" );
	set( "x_coordinate", 16 );
	set( "y_coordinate", 13 );
	reset();
}

void init()
{
	add_action( "do_enter", "enter" );
}

int do_enter(string arg)
{
	if( !arg || arg!="house" ) return 0;
   write(
            "你小心地跨過頹圮的大門，進入古屋。\n" );
    tell_room( this_object(),
            this_player()->query("c_cap_name") + "跨過頹圮大門，進入古屋。\n",
		this_player() );
	this_player()->move_player( "/d/noden/house/hall", "SNEAK" );
    tell_room( "/d/noden/house/hall",
            this_player()->query("c_cap_name") + "從門外走了進來。\n",
		this_player() );
	return 1;
}

