// File: /d/noden/2,5.noden.c
// Generated by Roommaker Tue Nov 21 00:40:35 1995

#include <mudlib.h>
inherit ROOM;

void create()
{
	::create();
	set_short("森林");
	set_long( @LONG_DESCRIPTION
你現在漫步在一座森林之中，繁茂的樹木散發出一股淡淡的、舒爽
宜人的氣息，你可以聽到樹林間小鳥吱吱喳喳的鳴叫聲，腳底下一層落
葉(leaves)鋪滿了你所站立的地方，底下似乎藏著什麼東西。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "exits", ([ 
		"east" : "d/noden/3,5.noden", 
		"north" : "d/noden/2,4.noden", 
		"south" : "d/noden/2,6.noden" ]) );
	reset();
}

void init()
{
	add_action("do_search","search");
	add_action("do_enter","enter");	
}

int do_search(string s)
{
	if (!s || s != "leaves")
		return notify_fail("你找了又找，並沒有發現任何東西。\n");
	tell_object(this_player(),@LONG
你仔細察看四周，竟然在西邊的樹蔭下找到一個被樹葉蓋住的小洞，看起來
像是某樣東西的入口(entrance)，你想進去(enter) 看看嗎？
LONG
	);
	return 1;
}

int do_enter(string s)
{
	if (!s || s != "entrance")
		return notify_fail("你要進哪裡？\n");
	this_player()->move_player("/d/noden/hawk/tomb.c","SNEAK");
	return 1;
}

