// File: /d/noden/6,9.noden.c
// Generated by Roommaker Sat May 14 04:32:03 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("路口");
	set_long( @LONG_DESCRIPTION
你現在來到了一處交叉路口，往北直走的路可以到達諾達尼亞城，也
就是王宮的所在地。往南的路沿著貝爾基山向西南方走，可以到達魔法之
都摩亞達。往東一條筆直的大路是通往諾頓王國東方的主要道路，向東一
直走下去可以到達坎達拉峽谷。
LONG_DESCRIPTION
	);

	set_outside( "noden" );
	set( "exits", ([ 
		"south" : "d/noden/6,10.noden", 
		"north" : "d/noden/6,8.noden", 
		"west" : "d/noden/5,9.noden", 
		"east" : "d/noden/7,9.noden" ]) );
	set( "objects", ([
	    "black chocobo#1" : "/d/noden/moyada/monster/black_chocobo",
	    ])); 	
	set( "original", "d/noden/6,9" );
	set( "virtual_server", "/d/noden/virtual/noden_server" );
	set( "x_coordinate", 6 );
	set( "y_coordinate", 9 );
	reset();
}

int clean_up() { return 0; }
