// File: /d/noden/10,10.noden.c
// Generated by Roommaker Tue Nov 21 00:21:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山腳");
	ob->set_long( @LONG_DESCRIPTION
你現在來到一座高大山峰的山腳下，北邊是一條碎石路，你的東北邊是一個
峽谷，這裡的地勢稍高，你發現地上似乎有一些馬車走過的痕跡，一條蜿蜒曲折
的山路通往西南邊的山上。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/hawk/path1", 
		"east" : "d/noden/11,10.noden", 
		"north" : "d/noden/10,9.noden" ]) );
	ob->set( "original", "d/noden/10,10" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 10 );
	ob->set( "y_coordinate", 10 );
	ob->reset();
}
