// File: /d/noden/12,13.noden.c
// Generated by Roommaker Tue Nov 21 00:24:34 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("沼澤");
	ob->set_long( @LONG_DESCRIPTION
你現在來到一處海邊的沼地，由於海水的沖刷，這裡的臭味比起沼澤
中其他地方減輕了不少，你注意到海岸邊有一塊突起的岩石(rock)，孤獨
地立在烏黑的沼泥和海邊的細沙之中。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "c_item_desc", ([ 
		"rock" : "這塊岩石下隱藏著一個小洞，裡面似乎有一些小生物在活動。\n" ]) );
	ob->set( "exits", ([ 
		"east" : "d/noden/13,13.noden", 
		"north" : "d/noden/12,12.noden", 
		"west" : "d/noden/11,13.noden" ]) );
	ob->set( "objects", ([ 
		"crab" : "/d/noden/monster/crab" ]) );
	ob->set( "original", "d/noden/12,13" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 12 );
	ob->set( "y_coordinate", 13 );
	ob->reset();
}
