// File: /d/noden/13,5.noden.c
// Generated by Roommaker Tue Nov 21 00:26:50 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("河邊小徑");
	ob->set_long( @LONG_DESCRIPTION
你現在正沿著河邊的小徑前進，河邊不少的鵝卵石雜亂地排列著，往東
你可以看見一片田野與交錯的小徑，河流在你的南邊緩緩流過，一條沿著河
床的小路向東南通往與遠風鎮西邊的石板橋，西邊不遠處有幾座低矮的山丘
。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/14,5.noden", 
		"north" : "d/noden/13,4.noden", 
		"west" : "d/noden/12,5.noden", 
		"southeast" : "/d/noden/farwind/bridge" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "original", "d/noden/13,5" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 13 );
	ob->set( "y_coordinate", 5 );
	ob->reset();
}
