// File: /d/noden/13,7.noden.c
// Generated by Roommaker Tue Nov 21 00:27:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("河邊森林");
	ob->set_long( @LONG_DESCRIPTION
你現在正沿著河邊的林中小徑漫步，北邊的河流日夜不停的流著，這裡
的空氣有些潮溼，但是涼爽的微風使你覺得全身舒暢。通往遠風鎮的道路就
在你的東邊，但是如果你願意的話，也可以經由你東北邊的石板橋進入遠風
鎮。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/14,7.noden", 
		"south" : "d/noden/13,8.noden", 
		"west" : "d/noden/12,7.noden", 
		"northeast" : "/d/noden/farwind/bridge" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"snake" : "/d/noden/monster/snake", 
		"snake#2" : "/d/noden/monster/snake" ]) );
	ob->set( "original", "d/noden/13,7" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 13 );
	ob->set( "y_coordinate", 7 );
	ob->reset();
}
