// File: /d/noden/14,9.noden.c
// Generated by Roommaker Mon Nov 20 12:34:31 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("交叉路口");
	ob->set_long( @LONG_DESCRIPTION
你現在來到了一處交叉路口，這條路在這裡分成三個方向，往北的
路通往冒險者的故鄉遠風鎮，往東邊的路可以到達藍沙港市，西邊的大
路穿過遠方山脈中間的坎達拉峽谷，銜接通往諾頓王國西半部的要道。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/15,9.noden", 
		"west" : "d/noden/13,9.noden", 
		"north" : "d/noden/14,8.noden", 
		"south" : "d/noden/14,10.noden" ]) );
	ob->set( "objects", ([ 
		"ghoul" : "/d/noden/monster/ghoul", 
		"troll" : "/d/noden/monster/troll" ]) );
	ob->set( "original", "d/noden/14,9" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 14 );
	ob->set( "y_coordinate", 9 );
	ob->reset();
}
