// File: /d/noden/14,7.noden.c
// Generated by Roommaker Mon Nov 20 12:36:15 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石板橋");
	ob->set_long( @LONG_DESCRIPTION
你現在正站在一座石板橋的橋面上，橋下河水正緩緩地由西向東流去，你
可以看見北方不遠處遠風鎮的街道和商店。過橋往南是一條碎石鋪成的道路，
通往銜接諾頓王國東西的主要道路。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"west" : "d/noden/13,7.noden", 
		"north" : "/d/noden/farwind/smain2", 
		"south" : "d/noden/14,8.noden" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"orc rogue" : "/d/noden/monster/orc", 
		"halfling girl" : "/d/noden/monster/halfling" ]) );
	ob->set( "original", "d/noden/14,7" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "weight", 0 );
	ob->set( "x_coordinate", 14 );
	ob->set( "y_coordinate", 7 );
	ob->reset();
}
