// File: /d/noden/14,13.noden.c
// Generated by Roommaker Tue Nov 21 00:30:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草地");
	ob->set_long( @LONG_DESCRIPTION
你現在走在一片綠油油的草地上，青翠的草地帶著令人愉悅的
氣息。幾叢植物散佈在碧綠的草地間，點綴著五彩繽紛的不知名野
花，使人心曠神宜。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/15,13.noden", 
		"west" : "d/noden/13,13.noden", 
		"north" : "d/noden/14,12.noden", 
		"south" : "d/noden/14,14.noden" ]) );
	ob->set( "objects", ([ 
		"toad" : "/d/noden/monster/toad" ]) );
	ob->set( "original", "d/noden/14,13" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 14 );
	ob->set( "y_coordinate", 13 );
	ob->reset();
}
