// File: /d/noden/14,5.noden.c
// Generated by Roommaker Mon Nov 20 12:38:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("遠風鎮郊區");
	ob->set_long( @LONG_DESCRIPTION
現在在你面前的是一片綠油油的田野，青翠的農作物與疏落的農舍散佈
在田野間，這裡寧靜的鄉村氣息使你感覺十分親切。在你的北方與西方不遠
處散佈著一些低矮的山丘，東邊則是一片森林，往南走就是遠風鎮的大街。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/15,5.noden", 
		"south" : "/d/noden/farwind/nmain", 
		"north" : "d/noden/14,4.noden", 
		"west" : "d/noden/13,5.noden" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"wife" : "/d/noden/monster/farmer_wife", 
		"farmer" : "/d/noden/monster/farmer" ]) );
	ob->set( "original", "d/noden/14,5" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 14 );
	ob->set( "y_coordinate", 5 );
	ob->reset();
}
