// File: /d/noden/15,5.noden.c
// Generated by Roommaker Tue Nov 21 00:31:11 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草地");
	ob->set_long( @LONG_DESCRIPTION
你現在走在一片綠油油的草地上，青翠的草地帶著令人愉悅的
氣息。幾叢植物散佈在碧綠的草地間，點綴著五彩繽紛的不知名野
花，使人心曠神宜。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/16,5.noden", 
		"west" : "d/noden/14,5.noden", 
		"north" : "d/noden/15,4.noden", 
		"south" : "d/noden/15,6.noden" ]) );
	ob->set( "original", "d/noden/15,5" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 15 );
	ob->set( "y_coordinate", 5 );
	ob->reset();
}
