// File: /d/noden/15,3.noden.c
// Generated by Roommaker Mon Nov 20 12:39:35 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("平原");
	ob->set_long( @LONG_DESCRIPTION
"你現在走在一片平地上，疏落的青草地上散佈著大大小小的石塊，東邊
和北邊都是低矮連綿的山丘，你的前方有一個營地(camp)，似乎有人住在這
裡，營地裡傳來陣陣食物的香味。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "c_item_desc", ([ 
		"camp" : "這個營地看起來像是幾天前才搭的，也許你可以進去瞧瞧？\n" ]) );
	ob->set( "exits", ([ 
                "camps" : "/d/noden/recamp/camp1",
		"east" : "d/noden/16,3.noden", 
		"west" : "d/noden/14,3.noden", 
		"north" : "d/noden/15,2.noden", 
		"south" : "d/noden/15,4.noden" ]) );
	ob->set( "original", "d/noden/15,3" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 15 );
	ob->set( "y_coordinate", 3 );
	ob->reset();
}
