// File: /d/noden/15,6.noden.c
// Generated by Roommaker Mon Nov 20 12:40:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("河邊林地");
	ob->set_long( @LONG_DESCRIPTION
你現在來到森林靠近河邊的一塊林地，河流在你的南方緩緩流過，潺潺的
流水聲和林間的蟲吟鳥鳴交織成一首美麗的交響曲，你的西邊是遠風鎮的圍牆
，但是從這裡沒有通往鎮上的入口。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/16,6.noden", 
		"north" : "d/noden/15,5.noden" ]) );
	ob->set( "objects", ([ 
		"crow" : "/d/noden/monster/crow" ]) );
	ob->set( "original", "d/noden/15,6" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 15 );
	ob->set( "y_coordinate", 6 );
	ob->reset();
}
