// File: /d/noden/17,11.noden.c
// Generated by Roommaker Tue Nov 21 00:33:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("白色沙灘");
	ob->set_long( @LONG_DESCRIPTION
你現在來到一處鋪滿白色沙子的美麗海灘，白沙中點點寶藍色的細點
將沙灘妝點出一種神秘迷人的氣氛，美麗的藍沙港就在你的北方不遠處，
可是這裡沒有入口可以進入藍沙港。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/18,11.noden", 
		"west" : "d/noden/16,11.noden", 
		"south" : "d/noden/17,12.noden" ]) );
	ob->set( "original", "d/noden/17,11" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 17 );
	ob->set( "y_coordinate", 11 );
	ob->reset();
}
