// File: /d/noden/17,15.noden.c
// Generated by Roommaker Tue Nov 21 00:34:36 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("沼澤");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在一個泥濘的沼澤中，烏黑的爛泥夾帶著令人作嘔
的臭味令你不得不掩住鼻子，泥漿中不少深綠色的植物及藤蔓互相
交錯糾葛，一些高大植物的頂端開著不少詭異的白花。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/18,15.noden", 
		"west" : "d/noden/16,15.noden", 
		"north" : "d/noden/17,14.noden", 
		"south" : "d/noden/17,16.noden" ]) );
	ob->set( "objects", ([ 
		"frog#2" : "/d/noden/monster/swamp_frog", 
		"frog#3" : "/d/noden/monster/swamp_frog", 
		"frog#1" : "/d/noden/monster/swamp_frog", 
		"frog#4" : "/d/noden/monster/swamp_frog" ]) );
	ob->set( "original", "d/noden/17,15" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 17 );
	ob->set( "y_coordinate", 15 );
	ob->reset();
}
