// File: /d/noden/18,4.noden.c
// Generated by Roommaker Tue Nov 21 00:35:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("巖岸");
	ob->set_long( @LONG_DESCRIPTION
你現在來到一處突出岸邊的岩石上，在你的腳下是個約有五公尺高的懸崖(cliff)
，這裡是諾頓大陸的東北角，附近的居民把這裡叫做「蝙蝠角」，據說懸崖下住著一
大群蝙蝠，這裡的視野相當開闊，天氣好的時侯可以望見東北方的古拉幹島。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "d/noden/18,5.noden", 
		"west" : "d/noden/17,4.noden" ]) );
	ob->set( "original", "d/noden/18,4" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 18 );
	ob->set( "y_coordinate", 4 );
        ob->set( "objects",([ "mob4":"/d/noden/recamp/npc/mob4.c" ])) ;
	ob->reset();
}
