// File: /d/noden/3,5.noden.c
// Generated by Roommaker Tue Nov 21 00:40:35 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林");
	ob->set_long( @LONG_DESCRIPTION
你現在漫步在一座森林之中，繁茂的樹木散發出一股淡淡的、
舒爽宜人的氣息，你可以聽到樹林間小鳥吱吱喳喳的鳴叫聲，腳底
下一層落葉鋪滿了你所站立的地方。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/4,5.noden", 
		"west" : "d/noden/2,5.noden", 
		"north" : "d/noden/3,4.noden", 
		"south" : "d/noden/3,6.noden" ]) );
	ob->set( "original", "d/noden/3,5" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 3 );
	ob->set( "y_coordinate", 5 );
        ob->set( "objects",(["mob3":"/d/noden/recamp/npc/mob3.c"])) ;
	ob->reset();
}
