// File: /d/noden/5,14.noden.c
// Generated by Roommaker Tue Nov 21 00:42:23 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山丘");
	ob->set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘組成的丘陵地上，這裡的地勢起伏
並不很大，青黃交錯的短草皮覆蓋著舉目所及的山丘，幾株大樹散
布在山坡上。北邊是魔法之都——摩亞達城，一個力場保護著它。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "d/noden/5,15.noden", 
		"west" : "d/noden/4,14.noden" ]) );
	ob->set( "original", "d/noden/5,14" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 5 );
	ob->set( "y_coordinate", 14 );
	ob->reset();
}
