// File: /d/noden/6,13.noden.c
// Generated by Roommaker Tue Nov 21 00:44:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("山丘");
	ob->set_long( @LONG_DESCRIPTION
你正走在一由一些低矮山丘組成的丘陵地上，這裡的地勢起伏
並不很大，青黃交錯的短草皮覆蓋著舉目所及的山丘，幾株大樹散
布在山坡上。西邊是魔法之都——摩亞達城，一個力場保護著它。
這裡有座巨大的石梯，一直往山上蜿蜒而上。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"up" : "/d/noden/asterism/ladder01", 
		"north" : "d/noden/6,12.noden" ]) );
	ob->set( "original", "d/noden/6,13" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 6 );
	ob->set( "y_coordinate", 13 );
	ob->reset();
}
