// File: /d/noden/7,7.noden.c
// Generated by Roommaker Tue Nov 21 00:45:28 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林");
	ob->set_long( @LONG_DESCRIPTION
你現在漫步在一座森林之中，繁茂的樹木散發出一股淡淡的、
舒爽宜人的氣息，你可以聽到樹林間小鳥吱吱喳喳的鳴叫聲，腳底
下一層落葉鋪滿了你所站立的地方。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/8,7.noden", 
		"south" : "d/noden/7,8.noden", 
		"west" : "/d/noden/nodania/castle_r3" ]) );
	ob->set( "original", "d/noden/7,7" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 7 );
	ob->set( "y_coordinate", 7 );
	ob->reset();
}
