// File: /d/noden/8,15.noden.c
// Generated by Roommaker Tue Nov 21 00:46:07 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("沼澤");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在一個泥濘的沼澤中，烏黑的爛泥夾帶著令人作嘔
的臭味令你不得不掩住鼻子，泥漿中不少深綠色的植物及藤蔓互相
交錯糾葛，一些高大植物的頂端開著不少詭異的白花。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "/d/noden/8,16.noden", 
		"north" : "/d/noden/8,14.noden", 
		"west" : "/d/noden/7,15.noden" ]) );
	ob->set( "original", "d/noden/8,15" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 8 );
	ob->set( "y_coordinate", 15 );
	ob->reset();
}
