// File: /d/noden/8,8.noden.c
// Generated by Roommaker Tue Nov 21 00:46:48 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林");
	ob->set_long( @LONG_DESCRIPTION
你現在漫步在一座森林之中，繁茂的樹木散發出一股淡淡的、
舒爽宜人的氣息，你可以聽到樹林間小鳥吱吱喳喳的鳴叫聲，腳底
下一層落葉鋪滿了你所站立的地方。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "d/noden/8,9.noden", 
		"north" : "d/noden/8,7.noden", 
		"west" : "d/noden/7,8.noden" ]) );
	ob->set( "objects", ([ 
		"wererat#2" : "/d/noden/monster/wererat", 
		"wererat#1" : "/d/noden/monster/wererat" ]) );
	ob->set( "original", "d/noden/8,8" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 8 );
	ob->set( "y_coordinate", 8 );
	ob->reset();
}
