// File: /d/noden/9,9.noden.c
// Generated by Roommaker Tue Nov 21 00:47:26 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("坎達拉峽谷");
	ob->set_long( @LONG_DESCRIPTION
這裡是坎達拉峽谷，高聳的山脈擋住了南方及北方的通路。這裡
是接通諾頓王國東西交通的主要通道，從前這裡本來有一座堡壘以守
御天險，但是自從魔法師們發現了傳送法術的奧秘之後，這裡的軍事
價值就沒有那麼重要了。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "d/noden/10,9.noden", 
		"west" : "d/noden/8,9.noden" ]) );
	ob->set( "objects", ([ 
		"bandit 2" : "/d/noden/monster/bandit" ]) );
	ob->set( "original", "d/noden/9,9" );
	ob->set( "virtual_server", "/d/noden/virtual/noden_server" );
	ob->set( "x_coordinate", 9 );
	ob->set( "y_coordinate", 9 );
	ob->reset();
}
