// File: /d/deathland/palace/pa_09.c
// Generated by Roommaker Thu Nov 23 20:43:36 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("法拉第的起居室");
	ob->set_long( @LONG_DESCRIPTION
大兒子法拉第(Falady )的起居室.雖然法拉第已經死了,但是他的房間並
沒有因此而被遺棄,這裡仍然保持的一塵不染,就像法拉第生前一樣.
牆壁上掛著一把很銳利的短劍,以及一個畫有莫拉德皇室徽章的盾牌. 這兩項
武器是法拉第生前最常用的武器.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/deathland/palace/pa_05" ]) );
	ob->reset();
}
