// File: /d/deathland/palace/pa_03.c
// Generated by Roommaker Thu Nov 23 20:36:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("皇宮走廊");
	ob->set_long( @LONG_DESCRIPTION
皇宮走廊,標準的矮人建築特色,筆直,刻板,單調.這走廊連接著大廳與僕人
的住所.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/deathland/palace/pa_01", 
		"south" : "/d/deathland/palace/pa_06" ]) );
	ob->reset();
}
