// File: /d/deathland/palace/pa_01.c
// Generated by Roommaker Thu Nov 23 20:35:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("皇宮大廳");
	ob->set_long( @LONG_DESCRIPTION
這裡是皇宮的大廳,但是除了周圍的牆壁是用純金砌成的外,與其他矮人的
建築物並無太大的不同.而且這建築物的造形非常呆板,顯示矮人缺乏藝術修養
.大廳的北方是一間會議室,而東方則是矮人皇室的起居室.南方是僕人的住所.
西方是皇宮通往外面的出口.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/palace/pa_02", 
		"north" : "/d/deathland/palace/pa_04", 
		"south" : "/d/deathland/palace/pa_03", 
		"west" : "/d/deathland/city/c7" ]) );
	ob->set( "objects", ([ 
		"guard#2" : "/d/deathland/monster/royal01", 
		"guard#1" : "/d/deathland/monster/royal01" ]) );
	ob->reset();
}
