// File: /d/deathland/palace/pa_06.c
// Generated by Roommaker Thu Nov 23 20:37:38 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("僕人的住所");
	ob->set_long( @LONG_DESCRIPTION
許多僕人忙進忙出的,雖然矮人皇室的成員不多,但是僕人的工作仍是很忙
碌的. 這裡是僕人的住所,一些床與衣櫥擺在角落,而中央放著一張飯桌與幾個
椅子.往北是通往大廳的走廊.而東邊似乎是一個很大的廣場.
的住所.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/palace/pa_07", 
		"north" : "/d/deathland/palace/pa_03" ]) );
	ob->set( "objects", ([ 
		"servant#3" : "/d/deathland/monster/servant", 
		"servant#2" : "/d/deathland/monster/servant", 
		"servant#1" : "/d/deathland/monster/servant" ]) );
	ob->reset();
}
