// File: /d/deathland/palace/pa_04.c
// Generated by Roommaker Thu Nov 23 20:35:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("會議室");
	ob->set_long( @LONG_DESCRIPTION
這裡是一間會議室,矮人常常在此地召開作戰會議或是處理緊急事件.有一張
非常大的圓形會議桌在房間的中央,另外有數十張的椅子放在會議桌的旁邊.而在
牆壁上掛著一張矮人國度的地圖(map),以及莫拉德一世(Molader I)的畫像.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"map" : @LONG_TEXT
---------------------------------------------------------------------

                         教堂                  村落
                           |                     |
                           |                     |
--------------------------------------------------------皇宮
                           |                |
                           |                |
                         酒吧             礦坑


---------------------------------------------------------------------
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"south" : "/d/deathland/palace/pa_01" ]) );
	ob->set( "objects", ([ 
		"calford" : "/d/deathland/monster/calford" ]) );
	ob->reset();
}
