// File: /d/eastland/forest/3,1.forest.c
// Generated by Roommaker Fri Nov 24 00:08:39 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的深處");
	ob->set_long( @LONG_DESCRIPTION
這裡是猛獸森林的深處，樹木非常地茂盛，連陽光都無法進入，因此也
顯得格外的陰森。當你向四周圍望去，你發現黑暗中有無數雙碧綠閃爍的眼
睛正邪惡地注視著你，令你有毛骨聳然的感覺，恨不得拔腿就跑。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"southwest" : "/d/eastland/forest/2,0.forest", 
		"northwest" : "/d/eastland/forest/2,2.forest", 
		"east" : "/d/eastland/forest/4,1.forest" ]) );
	ob->reset();
}
