// File: /d/eastland/forest/4,2.forest.c
// Generated by Roommaker Fri Nov 24 12:47:24 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林中的空地");
	ob->set_long( @LONG_DESCRIPTION
走過眼前的樹叢，你來到一個奇特的地方。在這裡，你看不到任何樹
木，但是天空仍被四周樹木的枝葉所遮蔽。更奇怪的是，這裡看不到任何
的野獸，連足跡都沒有，似乎不太尋常。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/healer/het/room1", 
		"south" : "/d/eastland/forest/4,1.forest", 
		"north" : "/d/eastland/forest/4,3.forest" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
