// File: /d/eastland/forest/4,3.forest.c
// Generated by Roommaker Fri Nov 24 12:45:30 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的深處");
	ob->set_long( @LONG_DESCRIPTION
這裡是猛獸森林的深處，樹木非常地茂盛，連陽光都無法進入，因此也
顯得格外的陰森。當你向四周圍望去，你發現黑暗中有無數雙碧綠閃爍的眼
睛正邪惡地注視著你，要不是為了尋找傳說中的靈獸，誰也不願意到這種鬼
地方來。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/eastland/forest/5,3.forest", 
		"west" : "/d/eastland/forest/3,3.forest", 
		"south" : "/d/eastland/forest/4,2.forest" ]) );
	ob->set( "objects", ([ 
		"lion#1" : "/d/eastland/forest/monster/lion", 
		"lion#0" : "/d/eastland/forest/monster/lion" ]) );
	ob->reset();
}
