// File: /d/eastland/forest/5,1.forest.c
// Generated by Roommaker Fri Nov 24 12:48:47 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的深處");
	ob->set_long( @LONG_DESCRIPTION
這裡是猛獸森林的深處，樹木非常地茂盛，連陽光都無法進入，因此也
顯得格外的陰森。當你向四周圍望去，你發現黑暗中有無數雙碧□閃爍的眼
睛正邪惡地注視著你，令你有毛骨聳然的感覺，恨不得拔腿就跑。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/eastland/forest/4,1.forest", 
		"southeast" : "/d/eastland/forest/6,0.forest", 
		"northeast" : "/d/eastland/forest/6,2.forest" ]) );
	ob->set( "objects", ([ 
		"gorilla#1" : "/d/eastland/forest/monster/gorilla", 
		"gorilla#0" : "/d/eastland/forest/monster/gorilla" ]) );
	ob->reset();
}
