// File: /d/eastland/forest/6,0.forest.c
// Generated by Roommaker Fri Nov 24 12:48:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的內部");
	ob->set_long( @LONG_DESCRIPTION
你現在正身處於猛獸森林的內部，狂暴的氣息令人不寒而慄，尤其是
此起彼落的野獸狂嘯聲，更是讓人膽顫心驚。要是沒有什麼重要的事，還
是快快回頭的好。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"northwest" : "/d/eastland/forest/5,1.forest", 
		"northeast" : "/d/eastland/forest/7,1.forest" ]) );
	ob->set( "objects", ([ 
		"antelope#0" : "/d/eastland/forest/monster/antelope", 
		"antelope#1" : "/d/eastland/forest/monster/antelope" ]) );
	ob->reset();
}
