// File: /d/eastland/forest/6,4.forest.c
// Generated by Roommaker Fri Nov 24 12:46:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的內部");
	ob->set_long( @LONG_DESCRIPTION
你現在正身處於猛獸森林的內部，狂暴的氣息令人不寒而慄，尤其是
此起彼落的野獸狂嘯聲，更是讓人膽顫心驚。如果沒有什麼重要的事，現
在回頭還來得及。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"southwest" : "/d/eastland/forest/5,3.forest", 
		"southeast" : "/d/eastland/forest/7,3.forest" ]) );
	ob->set( "objects", ([ 
		"owl#0" : "/d/eastland/forest/monster/owl", 
		"owl#1" : "/d/eastland/forest/monster/owl" ]) );
	ob->reset();
}
