// File: /d/eastland/forest/7,1.forest.c
// Generated by Roommaker Fri Nov 24 12:49:30 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的邊緣");
	ob->set_long( @LONG_DESCRIPTION
你現在所在的地方是一片茂密的森林，似乎就是人們所說的猛獸森林
。傳說猛獸森林中有很多兇猛的野獸，有不少的人在此失蹤，如果沒有什
麼重要的事，千萬不要隨便進入森林內部。                
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"southwest" : "/d/eastland/forest/6,0.forest", 
		"northwest" : "/d/eastland/forest/6,2.forest", 
		"northeast" : "/d/eastland/forest/8,2.forest" ]) );
	ob->set( "objects", ([ 
		"rabbit#0" : "/d/eastland/forest/monster/rabbit", 
		"rabbit#2" : "/d/eastland/forest/monster/rabbit", 
		"rabbit#1" : "/d/eastland/forest/monster/rabbit" ]) );
	ob->reset();
}
