// File: /d/eastland/forest/7,3.forest.c
// Generated by Roommaker Fri Nov 24 12:46:12 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("森林的邊緣");
	ob->set_long( @LONG_DESCRIPTION
你現在所在的地方是一片茂密的森林，似乎就是人們所說的猛獸森林
。傳說猛獸森林中有很多兇猛的野獸，有不少的人在此失蹤，如果沒有什
麼重要的事，千萬不要隨便進入森林內部。                
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"southwest" : "/d/eastland/forest/6,2.forest", 
		"northwest" : "/d/eastland/forest/6,4.forest", 
		"southeast" : "/d/eastland/forest/8,2.forest" ]) );
	ob->reset();
}
