// File: /d/abyss/hell/bridge.c
// Generated by Roommaker Wed Jan  5 09:52:16 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("A empty room", "奈何橋");
	set_long( @LONG_DESCRIPTION
This is a simple room created by roommaker.
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你現在正站在一座青石板砌成的巨大拱橋上，橋的北方有一座城樓，你可以隱約
地看見城樓上一塊烏黑大匾上寫著「酆都城」三個大字，石橋兩邊的欄杆上雕著許多
奇異的文字，一陣「轟隆轟隆」的聲音從橋下(down)傳來，聽起來不像是水流的聲音
。你回首望向橋的南邊，只見一片白茫茫中隱約地有一片青山綠水。
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "c_item_desc", ([ 
		"down" : @LONG_TEXT
你靠近橋邊，探頭往橋底下望去，差點沒嚇得喊了出來，只見一片殷紅的血池
中翻滾著無以數計的黑色小蛇，血池裡還有一些不知是人還是什麼的斷肢殘骸，有
些人還有知覺，正張大了嘴想要哀號，卻發不出半點聲音。
LONG_TEXT
 ]) );
	set( "exits", ([ 
/*		"south" : "/d/abyss/hell/bridge", */
                "south" : "/d/abyss/entrance/start",
/*		"north" : "/d/abyss/hell/bridge" ]) );*/
                "north" : "/d/abyss/hell/gate" ]));
	reset();
}
