// File: /d/abyss/hell/hall.c
// Generated by Roommaker Wed Jan  5 09:38:36 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("A empty room", "森羅殿");
	set_long( @LONG_DESCRIPTION
This is a simple room created by roommaker.
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你現在正位於一間充滿鬼氣的大殿上，這裡的光線十分陰暗，但是你仍然可以
很清楚地看見周遭的事物，大殿的北端是一道階梯，階梯上端放著一張巨大的烏木
桌子，兩旁林立著數十根雙人合抱的火紅色圓柱，圓柱後面站著兩排不知是人還是
雕像的黑影，你感覺到自己正被好幾十雙眼睛注視著，一種恐懼夾雜著不安的情緒
正縈繞在你的腦中。
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "objects", ([
		"horseface" : "/d/abyss/hell/monster/horseface",
		"bullhead" : "/d/abyss/hell/monster/bullhead",
		"judge" : "/d/abyss/hell/monster/judge",
		"lord_chinguan" : "/d/abyss/hell/monster/lord_chinguan"]) );
	reset();
}
