// File: /d/abyss/hell/monpoh_bower.c
// Generated by Roommaker Wed Jan  5 11:27:32 1994

#include "hell.h"

inherit ROOM;

void create()
{
	::create();
	set_short("Monpoh place", "孟婆亭");
	set_long( @LONG_DESCRIPTION
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你來到一個有著濃綠樹蔭的小茶亭，涼亭旁的大樹垂掛著一塊木牌(sign)，上面
寫著「孟婆亭」及幾行小字。你放眼四周，全是白茫茫的一片，頭頂上好像有十個大
太陽在照著一般，令你覺得酷熱難當，還是進亭子去歇一會兒吧。
C_LONG_DESCRIPTION
	);

    set("item_func",([
        "sign":"look_sign",]) );
	set( "light", 1 );
    set("exits",([
              "east":"/d/abyss/hell/street2"
                 ]));
	reset();
}

int look_sign()
{
    write("這木牌上寫著:免費招待孟婆湯.\n");
    return 1;
}
