// File: /d/abyss/hell/street2.c
// Generated by Roommaker Wed Jan  5 10:09:57 1994

#include "hell.h"

inherit ROOM;

void create()
{
	::create();
	set_short("Street of ghost city", "酆都城街道");
	set_long( @LONG_DESCRIPTION
This is a simple room created by roommaker.
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你現在正走在酆都城的街道上，你看見四周的建築物都黑黝黝地矗立著，一片白
茫茫的霧氣籠罩著這裡，分不出是白天還是黑夜。許多白色的人影在你的身邊飄來飄
去，但是全都靜悄悄地沒有任何聲音，你感到一股寒氣正在啃噬你的神智，也許在這
種地方呆太久你會瘋掉....。
往西邊走是路的盡頭, 似乎有個小茶亭在那邊.
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "exits", ([ 
		"west" : Hell"/monpoh_bower", 
		"east" : Hell"/street1" ]) );
	reset();
}
