// File: /d/abyss/hell/street1.c
// Generated by Roommaker Wed Jan  5 10:07:43 1994

#include "hell.h"

inherit ROOM;

void create()
{
	::create();
	set_short("Street of ghost city", "酆都城街道");
	set_long( @LONG_DESCRIPTION
LONG_DESCRIPTION
		, @C_LONG_DESCRIPTION
你現在正走在酆都城的街道上，你看見四周的建築物都黑黝黝地矗立著，一片白
茫茫的霧氣籠罩著這裡，分不出是白天還是黑夜。許多白色的人影在你的身邊飄來飄
去，但是全都靜悄悄地沒有任何聲音，你感到一股寒氣正在啃噬你的神智，也許在這
種地方呆太久你會瘋掉....。
往南邊走出城門就是奈何橋了, 聽說一但過了奈何橋就能重返陽間, 不必受輪迴之苦.
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "exits", ([ 
		"south" : Hell"/gate",
		"north" : Hell"/street4",
		"west" : Hell"/street2", 
		"east" : Hell"/street3" ]) );
	reset();
}
