// File: /d/noden/nodania/alley1.c
// Generated by Roommaker Mon Dec  4 19:49:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("陰暗小巷");
	ob->set_long( @LONG_DESCRIPTION
這是一條陰暗的小巷子，髒亂狹窄的路面上到處都是垃圾，即使是像
諾達尼亞這樣的大城市，也依然有貧窮的存在。巷子的東方隱隱約約有人
說話的聲音，但是在這裡聽不清楚。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/alley2", 
		"west" : "/d/noden/nodania/nodania_r1" ]) );
	ob->set( "objects", ([ 
		"cat" : "/d/noden/nodania/monster/cat" ]) );
	ob->reset();
}
