// File: /d/noden/nodania/barrack.c
// Generated by Roommaker Mon Dec  4 19:50:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("皇家騎士團軍營");
	ob->set_long( @LONG_DESCRIPTION
你現在來到皇家騎士團的軍營，這裡是武器專家們訓練騎士使用
武器戰鬥的所在地。牆邊有一個排滿各式武器的架子，北邊傳來陣陣
金屬碰撞與戰鬥呼喝的聲音。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"south" : "/d/noden/nodania/e_path2", 
		"north" : "/d/noden/nodania/yard1" ]) );
	ob->set( "objects", ([ 
		"squire#2" : "/d/noden/nodania/monster/squire", 
		"squire#1" : "/d/noden/nodania/monster/squire" ]) );
	ob->reset();
}
