// File: /d/noden/nodania/castle_r3.c
// Generated by Roommaker Mon Dec  4 19:53:58 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("城堡路，諾達尼亞");
	ob->set_long( @LONG_DESCRIPTION
城堡路沿著諾達尼亞城的城牆往東西向延伸，路旁種了不少樹木及
矮樹叢。在你的西方可以看到城堡的南門。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/7,7.noden", 
		"west" : "/d/noden/nodania/castle_r2" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
