// File: /d/noden/nodania/collection.c
// Generated by Roommaker Mon Dec  4 19:59:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("收藏室");
	ob->set_long( @LONG_DESCRIPTION
這是皇后依莉雅的收藏室，國王和皇后都很喜歡收集來自世界各地的
珍奇寶物，並且展示給他們的賓客看。依莉雅皇后的珍藏十分豐富，其中
以一套鑲滿翡翠的盔甲(armor)和一隻用龍的牙齒雕成的鸚鵡(parrot) 最
引人注目。往東走可以回到議事廳。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"armor" : @LONG_TEXT
這套盔甲上面據說鑲了超過兩萬片上等的翡翠，並且經過強大的魔法加以
祝福，能保護穿它的人不受邪惡魔法的傷害。
LONG_TEXT
, 
		"parrot" : @LONG_TEXT
這是一隻用龍的牙齒雕成的鸚鵡，雖然它的大小和一般的鸚鵡差了很多，但
是至少有十名以上的王宮僕役都曾發誓過他們聽到這隻鸚鵡說話。
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/throne_room", 
		"west" : "/d/noden/nodania/tower1" ]) );
	ob->set( "objects", ([ 
		"queen" : "/d/noden/nodania/monster/iriah" ]) );
	ob->reset();
}
