// File: /d/noden/nodania/courtyard.c
// Generated by Roommaker Mon Dec  4 20:00:31 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("王宮前庭");
	ob->set_long( @LONG_DESCRIPTION
這裡是王宮的前庭，一片綠地上佈置著幾叢花樹。國王耶拉曼十一世的
宮殿就在前方，東邊一條石板鋪成的小徑通往皇家騎士團的軍營，往西是國
王的馬場。王宮大門就在你的南邊。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/e_path", 
		"west" : "/d/noden/nodania/w_path", 
		"south" : "/d/noden/nodania/s_gate", 
		"north" : "/d/noden/nodania/palace_hall" ]) );
	ob->set( "objects", ([ 
		"guard#2" : "/d/noden/nodania/monster/palace_guard", 
		"guard#1" : "/d/noden/nodania/monster/palace_guard", 
		"gardener" : "/d/noden/nodania/monster/gardener" ]) );
	ob->reset();
}
