// File: /d/noden/nodania/dump.c
// Generated by Roommaker Mon Dec  4 20:00:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("垃圾堆");
	ob->set_long( @LONG_DESCRIPTION
小巷子到這裡成了死巷，在你面前的是一堆垃圾(debris)、瓦礫(rubbles)
與一大堆各式各樣的廢棄物，很顯然的，窮人們把這裡當作垃圾場，你向這些垃
圾只看了一眼，就可以確定裡面絕對不會有任何有價值的東西。一陣低沈緩慢的
吟誦從東邊的牆(wall)後面傳出，但是你並沒有發現任何出口，唯一值得注意的
只是離地面約三、四公尺高的地方有一扇窗子(window)。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"west" : "/d/noden/nodania/alley2" ]) );
	ob->set( "item_desc", ([ 
		"rubbles" : "一堆碎石和破瓦片，也許是某戶人家修補牆壁所留下來的。\n", 
		"window" : "那扇窗戶緊閉著，但是從這裡看不到屋子裡的情形。\n", 
		"wall" : "這面牆比其他方向的牆看起來新，大概是新蓋好的。\n", 
		"debris" : "這堆垃圾多半是吃剩的食物和紙張，看起來怪噁心的。\n" ]) );
	ob->set( "objects", ([ 
		"child2" : "/d/noden/nodania/monster/poor_child", 
		"child1" : "/d/noden/nodania/monster/poor_child" ]) );
	ob->reset();
}
