// File: /d/noden/nodania/e_hall.c
// Generated by Roommaker Mon Dec  4 20:01:42 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("王宮迴廊");
	ob->set_long( @LONG_DESCRIPTION
這裡是諾達尼亞王宮中的一處迴廊，往東走你可以到達王宮的廚房，
西邊是王宮入口的大廳。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/kitchen", 
		"west" : "/d/noden/nodania/palace_hall" ]) );
	ob->reset();
}
