// File: /d/noden/nodania/e_path2.c
// Generated by Roommaker Mon Dec  4 20:02:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石板小徑");
	ob->set_long( @LONG_DESCRIPTION
你現在走在一條石板鋪成的小徑，兩旁生著疏疏落落的灌木叢。小
徑通往北邊和西邊。東邊一座碉堡般的建築物，想必就是諾頓王國的主
力騎士公會。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"east" : "/d/knight/fortress/knight_guild", 
		"north" : "/d/noden/nodania/barrack", 
		"west" : "/d/noden/nodania/e_path" ]) );
	ob->reset();
}
