// File: /d/noden/nodania/greeting_hall.c
// Generated by Roommaker Mon Dec  4 20:04:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("貴賓室");
	ob->set_long( @LONG_DESCRIPTION
這裡是諾達尼亞王宮的貴賓室，裝飾華麗的璧畫、地毯等傢俱顯示
這裡的主人相當重視他的客人。往東可以回到王宮大廳。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/palace_hall" ]) );
	ob->set( "objects", ([ 
		"servant" : "/d/noden/nodania/monster/servant" ]) );
	ob->reset();
}
