// File: /d/noden/nodania/hgarden.c
// Generated by Roommaker Mon Dec  4 20:04:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("空中花園");
	ob->set_long( @LONG_DESCRIPTION
這裡是諾達尼亞王宮二樓的空中花園，這裡不但屋頂是透明的，連四周的牆
壁都適用玻璃做的，為了給花卉們充足的陽光。國王收集了不少各地的珍奇花卉
都種在這裡，甚至最近還派遣了一支特使團到東方大國去尋找一種名貴的蘭花，
你在這裡參觀時最好小心一點，要是碰壞了任何一株花卉的枝葉花瓣，可是會有
大麻煩的。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/nodania/upstair_1" ]) );
	ob->reset();
}
