// File: /d/noden/nodania/kitchen.c
// Generated by Roommaker Mon Dec  4 20:05:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("廚房");
	ob->set_long( @LONG_DESCRIPTION
這裡是諾達尼亞王宮中的廚房，你可以看到許多的豬肉、牛肉、蔬
菜、水果等，井井有條的放在桌上或櫃子中。這個地方看起來很乾淨，
看起來國王的廚子相當盡職。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/noden/nodania/e_hall" ]) );
	ob->set( "objects", ([ 
		"cook" : "/d/noden/nodania/monster/cook" ]) );
	ob->reset();
}
