// File: /d/noden/nodania/library.c
// Generated by Roommaker Mon Dec  4 20:05:30 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("諾達尼亞圖書館");
	ob->set_long( @LONG_DESCRIPTION
你現在位於諾達尼亞圖書館的大廳中，觸目所及全是各式各樣的書
籍、卷軸、文件。有一位圖書館員(librarian) 坐在一張書桌前，你可
問她有關書籍(books) 的借閱規則。往東可以回到諾達尼亞廣場。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/square" ]) );
	ob->set( "item_desc", ([ 
		"librarian" : @LONG_TEXT
圖書館員正坐在書桌前翻閱一些文件，你可以問問題，但是最好小聲地
問，以免吵到其他的人。

LONG_TEXT
, 
		"books" : @LONG_TEXT
這裡到處都是書，核桃木的書架上整整齊齊地排滿了各式各樣的書籍
與文件，如果你沒有圖書館員的協助，恐怕很難找到你想要的書籍。

LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"librarian" : "/d/noden/nodania/monster/librarian" ]) );
	ob->reset();
}
