// File: /d/noden/nodania/palace_hall.c
// Generated by Roommaker Mon Dec  4 20:05:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("王宮大廳");
	ob->set_long( @LONG_DESCRIPTION
你現在來到了王宮大廳之中，整個大廳佈置得富麗堂皇，牆壁上裝飾著
出自名家的浮雕與璧畫。大廳四個角落各有一根三人合抱的大理石柱，柱子
上各裝飾著一個天使的石雕，天使手中舉著的光球照亮整個大廳。東邊的回
廊通往王宮的廚房，西邊是貴賓室，國王接待貴賓的地方，往北你可以遠遠
望見國王的寶座。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/e_hall", 
		"west" : "/d/noden/nodania/greeting_hall", 
		"south" : "/d/noden/nodania/courtyard", 
		"north" : "/d/noden/nodania/throne_room" ]) );
	ob->reset();
}
