// File: /d/noden/nodania/s_gate.c
// Generated by Roommaker Mon Dec  4 20:10:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("諾達尼亞，南門");
	ob->set_long( @LONG_DESCRIPTION
你現在站在諾達尼亞城，也就是諾達尼亞王宮南邊的大門口。在你的北
方不遠處，就是國王耶拉曼十一世的宮殿。城堡路向東西方延伸下去，南邊
則是諾達尼亞廣場。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/castle_r2", 
		"west" : "/d/noden/nodania/castle_r1", 
		"north" : "/d/noden/nodania/courtyard", 
		"south" : "/d/noden/nodania/square" ]) );
	ob->set( "objects", ([ 
		"gate guard#2" : "/d/noden/nodania/monster/gate_guard", 
		"gate guard#1" : "/d/noden/nodania/monster/gate_guard" ]) );
	ob->reset();
}
