// File: /d/noden/nodania/square.c
// Generated by Roommaker Mon Dec  4 20:11:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("諾達尼亞廣場");
	ob->set_long( @LONG_DESCRIPTION
這裡是諾達尼亞大廣場。廣場中央有一座巨大火龍(dragon)的雕像，四
個全副武裝的騎士(knight)雕像將火龍團團圍住，在每個雕像前面都有一塊
銅牌說明(plaque)。從這裡往北走可以到達諾達尼亞王宮的南門，東邊一棟
有很多石柱的白色建築，西邊則是諾達尼亞圖書館。往南通往諾達尼亞大道
。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/theater", 
		"north" : "/d/noden/nodania/s_gate", 
		"south" : "/d/noden/nodania/nodania_r1", 
		"west" : "/d/noden/nodania/library" ]) );
	ob->set( "item_desc", ([ 
		"knight" : "這四個騎士似乎都已經身負重傷，但是看他們的動作仍在英勇奮戰。\n", 
		"dragon" : @LONG_TEXT
一條面目猙獰，兇狠異常的大火龍，它大約有 8 公尺高，巨大的利爪可以
抓住敵人，身上披著紅光閃閃的鱗片，看起來就知道很不好對付。


LONG_TEXT
, 
		"plaque" : @LONG_TEXT
銅牌上寫著: 白騎士加爾魯斯(Garluse)，紅騎士貝迪安(Bedian)，綠騎士
伊歐洛特(Eoralt)，藍騎士卡魯吉安(Carukien)。

LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"bard" : "/d/noden/nodania/monster/bard" ]) );
	ob->reset();
}
