// File: /d/noden/nodania/stable.c
// Generated by Roommaker Mon Dec  4 20:11:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("馬房");
	ob->set_long( @LONG_DESCRIPTION
你現在來到了國王的馬房，這裡打掃得相當乾淨，負責照顧國王戰馬的
馬童對他的工作十分引以榮，從這裡你可以望見西邊的跑馬場，往南是一條
石板鋪成的小徑。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/nodania/w_path2" ]) );
	ob->set( "objects", ([ 
		"horse#3" : "/d/noden/nodania/monster/white_horse", 
		"horse#2" : "/d/noden/nodania/monster/brown_horse", 
		"horse#1" : "/d/noden/nodania/monster/brown_horse" ]) );
	ob->reset();
}
