// File: /d/noden/nodania/theater.c
// Generated by Roommaker Mon Dec  4 20:12:09 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("諾達尼亞露天劇院");
	ob->set_long( @LONG_DESCRIPTION
這裡是遠近馳名的諾達尼亞露天劇院，每當這裡有歌劇因演出或音樂
會時，諾頓王國各地的人們都會聚集在這裡。東邊的牆上有一張巨幅的壁
畫(wall painting) ，大廳入口中央有一座小噴水池(fountain)。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/noden/nodania/square" ]) );
	ob->set( "item_desc", ([ 
		"fountain" : @LONG_TEXT
一座用大理石砌成的小噴泉，據說許多諾達尼亞的少女喜歡將玫瑰花的花
瓣丟進噴泉中許願，因此你可以看到噴泉的底部有一層厚厚的花瓣。
LONG_TEXT
, 
		"wall painting" : @LONG_TEXT
這幅壁畫是宮廷畫家比拉得的名作「少年騎士與吟遊詩人」，畫的是傳說
中吉爾瑞克(Gelreck)少年時代和吟遊詩人芙娜(Pheuna)相遇的故事。
LONG_TEXT
 ]) );
	ob->reset();
}
