// File: /d/noden/nodania/tower1.c
// Generated by Roommaker Mon Dec  4 20:13:07 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("塔樓底層");
	ob->set_long( @LONG_DESCRIPTION
你現在正站在一座塔樓的底層，西邊有一道樓梯通往二樓，從北邊的窗戶
可以看到諾達尼亞北方的森林，牆角有幾個木箱(boxes)堆在一起，往南是一
條幽暗的迴廊，伊莉亞皇后的儲藏室就在你的東方。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/collection", 
		"south" : "/d/noden/nodania/sealroom", 
		"up" : "/d/noden/nodania/tower2" ]) );
	ob->set( "item_desc", ([ 
		"boxes" : @LONG_TEXT
這幾個木箱看起來像是在這裡堆了有幾個世紀之久，上面所積的灰塵厚得
令你不敢大口吐氣，不過其中一個木箱上面印了一個圓形的痕跡，也許是
燭臺、杯子....只有天知道。
LONG_TEXT
 ]) );
	ob->reset();
}
