// File: /d/noden/nodania/tower2.c
// Generated by Roommaker Mon Dec  4 20:13:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("塔樓二樓");
	ob->set_long( @LONG_DESCRIPTION
你現在正站在一座塔樓的二樓，牆角的樓梯分別通往一樓與三樓
，從北方的窗戶望出去可以看到諾達尼亞森林，以及雄踞在東北方的
高大山脈。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"down" : "/d/noden/nodania/tower1", 
		"up" : "/d/noden/nodania/tower3" ]) );
	ob->set( "objects", ([ 
		"cat" : "/d/noden/nodania/monster/cat" ]) );
	ob->reset();
}
