// File: /d/noden/nodania/tower3.c
// Generated by Roommaker Mon Dec  4 20:13:43 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("塔樓三樓");
	ob->set_long( @LONG_DESCRIPTION
你現在正站在一座塔樓的三樓，牆角的樓梯分別通往頂樓與二樓，北邊的
窗戶不知道為了什麼原因用木板釘死了，使得這裡看起來有些陰暗，一些破舊
的木桶和沙包凌亂地堆在地上。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"down" : "/d/noden/nodania/tower2", 
		"up" : "/d/noden/nodania/tower4" ]) );
	ob->reset();
}
