// File: /d/noden/nodania/upstair_3.c
// Generated by Roommaker Mon Dec  4 20:15:12 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("長廊轉角");
	ob->set_long( @LONG_DESCRIPTION
這裡是王宮二樓長廊的一處轉角，西邊是公主的臥室，長廊通往東邊與南
邊，在牆角有一座耶拉曼六世的半身像(bust)，看起來威風凜凜。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/upstair_2", 
		"south" : "/d/noden/nodania/upstair_4" ]) );
	ob->set( "objects", ([ 
		"artist" : "/d/noden/nodania/monster/artist" ]) );
	ob->reset();
}
