// File: /d/noden/nodania/upstair_2.c
// Generated by Roommaker Mon Dec  4 20:14:55 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("長廊");
	ob->set_long( @LONG_DESCRIPTION
這裡是諾達尼亞王宮的一處長廊，白色大理石鋪成的地板將兩邊牆壁的
精緻浮雕點綴得富麗堂皇，從這裡你可以沿著長廊往東或往西。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/upstair_1", 
		"west" : "/d/noden/nodania/upstair_3" ]) );
	ob->reset();
}
