// File: /d/noden/nodania/upstair_1.c
// Generated by Roommaker Mon Dec  4 20:14:45 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("長廊");
	ob->set_long( @LONG_DESCRIPTION
這裡是諾達尼亞王宮二樓的一處長廊，平日只有國王和他的家人才會在這裡
出現，你可以看到許多精緻的壁畫與浮雕裝飾著兩邊的牆壁，地板是用白色的大
裡石鋪成的，往南是一座種著許多花卉的空中花園，往西是長廊的另一端。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/nodania/e_throne", 
		"south" : "/d/noden/nodania/hgarden", 
		"west" : "/d/noden/nodania/upstair_2" ]) );
	ob->reset();
}
