// File: /d/noden/nodania/upstair_4.c
// Generated by Roommaker Mon Dec  4 20:15:37 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("長廊");
	ob->set_long( @LONG_DESCRIPTION
這裡是長廊的盡頭，國王和皇后的臥室在你的南方，在你的西邊有一個
窗戶可以望見國王的馬場，兩邊的牆壁都裝飾著精美的壁畫，臥室的門口有
一對純金的燭臺，這是皇后依莉雅上次到東方大國旅行所帶回來的。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/noden/nodania/upstair_3" ]) );
	ob->reset();
}
