// File: /d/noden/nodania/w_path2.c
// Generated by Roommaker Mon Dec  4 20:16:18 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石板小徑");
	ob->set_long( @LONG_DESCRIPTION
你現在走在一條石板鋪成的小徑，兩旁生著疏疏落落的灌木叢。小徑在
一叢玫瑰花(rose)樹前轉往北邊，你從這裡可以看到一間相當大的馬房，裡
面飼養著國王專用的戰馬。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/w_path", 
		"north" : "/d/noden/nodania/stable" ]) );
	ob->set( "item_desc", ([ 
		"$1" : @LONG_TEXT
一叢鮮紅色的玫瑰花，上面長滿了尖刺，這種玫瑰花諾達尼亞人為她取
了個有趣的名字叫做「仇人的妻子」。
LONG_TEXT
, 
		"rose" : @LONG_TEXT
一叢鮮紅色的玫瑰花，枝幹上長滿了尖尖的小刺，諾達尼亞人為這種玫
瑰花取了個有趣的名字叫做「仇人的妻子」。
LONG_TEXT
 ]) );
	ob->reset();
}
