// File: /d/noden/nodania/w_path.c
// Generated by Roommaker Mon Dec  4 20:15:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石板小徑");
	ob->set_long( @LONG_DESCRIPTION
你現在走在一條石板鋪成的小徑，兩旁生著疏疏落落的灌木叢。東
邊是王宮前庭，小徑向西延伸。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"east" : "/d/noden/nodania/courtyard", 
		"west" : "/d/noden/nodania/w_path2" ]) );
	ob->reset();
}
