// File: /d/noden/nodania/yard1.c
// Generated by Roommaker Mon Dec  4 20:16:41 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("武器教練場");
	ob->set_long( @LONG_DESCRIPTION
你現在來到一個鋪滿砂子的圓形教練場，旁邊有許多放置武器的架子，一些
騎士們常在這裡操練武器技能，如果你對自己有信心的話，不妨和他們較量看看
，往南是一列整齊的軍營。
LONG_DESCRIPTION
	);

	ob->set_outside( "nodania" );
	ob->set( "exits", ([ 
		"south" : "/d/noden/nodania/barrack" ]) );
	ob->set( "objects", ([ 
		"horse" : "/d/noden/nodania/monster/horse", 
		"soldier#3" : "/d/noden/nodania/monster/soldier", 
		"soldier#2" : "/d/noden/nodania/monster/soldier", 
		"soldier#1" : "/d/noden/nodania/monster/soldier", 
		"dalifore" : "/d/noden/nodania/monster/master" ]) );
	ob->reset();
}
