// File: /d/noden/nodania/nodania_r1.c
// Generated by Roommaker Tue Nov 30 15:57:15 1993
// translation done 2-22-94 - Elon  (fix desc and add item desc)

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("諾達尼亞路");
	set_long( @C_LONG_DESCRIPTION
你現在走在諾達尼亞路上，兩行整齊的橄欖樹種植在寬闊的街道兩旁，路
上的行人都穿著相當體面的服飾。你注意到你的西邊有一家規模頗大的商店，
如果不是門口那塊醒目的招牌(sign)，你也許會把這家商店誤認為是一間神殿
或博物館。往東是一條看起來陰森森的小巷子，冷冷清清的和這裡的繁華熱鬧
成為強烈的對比。
C_LONG_DESCRIPTION
	);

	set_outside( "nodania" );
	set( "c_item_desc", ([ 
		"sign" : "「王記商行」\n" ]) );
    set( "item_desc", ([
        "sign" : "[The Shop of Wang]\n" ]) );
    set( "exits", ([ 
		"west" : "/d/noden/nodania/shop", 
		"north" : "/d/noden/nodania/square", 
		"south" : "/d/noden/6,8.noden", 
		"east" : "/d/noden/nodania/alley1" ]) );
	reset();
#include <replace_room.h>
}
