// File: /d/noden/nodania/tower4.c
// Generated by Roommaker Fri Sep  2 16:15:43 1994

#include <mudlib.h>

inherit ROOM;
int inwar;

void create()
{
	::create();
	set_short("塔樓頂樓");
	set_long( @C_LONG_DESCRIPTION
你現在來到一座塔樓的樓頂，從這裡可以遠眺諾達尼亞四周的景物，北方
是一片蓊鬱的森林，東北方環繞著黑色山谷的大山給人一種莫名的壓迫感，這
裡也是諾達尼亞軍隊的瞭望臺，一旦有敵人來襲，這裡的衛兵就會馬上去報告
守軍將領。
C_LONG_DESCRIPTION
	);

	set( "exits", ([ 
		"down" : "/d/noden/nodania/tower3" ]) );
	set( "objects", ([ 
		"guard" : "/d/noden/nodania/monster/tower_guard" ]) );
	reset();
}

void init()
{
   add_action( "do_brandish", "brandish" );
}

void reset()
{
   ::reset();
   inwar = 0;
}

int do_brandish(string arg)
{
   object guard, sword;

   if( !arg || (arg!="sword of markara" && arg!="markara"
        && arg!="sword") ) return 0;
   if( !present("sword of markara",this_player()) )
        return notify_fail("你用力地揮舞著雙手。\n" );
   if( this_player()->query_level()<5 )
     return notify_fail("你舉起瑪卡拉之劍，向天空揮舞著, 但是沒人注意你。\n" );
   if( inwar ) return notify_fail("默爾斯大軍已經進攻了, 不需要再揮劍了!\n");

   guard = present("tower guard",environment(this_player()));
   sword = present("sword of markara",this_player());

   tell_object( this_player(),"你舉起瑪卡拉之劍，向天空揮舞著。\n" );
   tell_room( environment(this_player()), 
sprintf( "%s舉起瑪卡拉之劍朝著天空揮舞。\n",this_player()->query("c_name")), this_player() );
   sword->remove();
   this_player()->add( "alignment", -1000 );
   this_player()->set_temp( "war_spy", 1 );
   find_object_or_load("/adm/daemons/event/moorth")->start_war();
   inwar = 1;

   if( present("tower guard",environment(this_player())) ) {
     tell_room(environment(this_player()),
        "\n看守塔樓的衛兵怒道: 可惡的間諜! 下地獄吧!!\n\n" );
     guard->kill_ob(this_player());
     this_player()->kill_ob(guard);
     return 1;
     }
   return 1;
}
