// File: /d/thief/hall/thief_trainroom.c
// Generated by Roommaker Sat Nov 11 11:55:33 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("小偷訓練中心");
	ob->set_long( @LONG_DESCRIPTION
這裡是小偷的訓練中心。小偷們到各地磨練各種技能, 到一定程度後, 
常常會遇到瓶頸。因此畢克林老爹找了一些經驗豐富的神偷幫助小偷們
提升技巧。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/thief/hall/thief_guild" ]) );
	ob->set( "objects", ([ 
		"taylers" : "/d/thief/hall/monsters/taylers" ]) );
	ob->reset();
}
