// File: /d/deathland/city/c2.c
// Generated by Roommaker Sat Nov 11 15:09:32 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人國度的主要道路");
	ob->set_long( @LONG_DESCRIPTION
矮人國度的主要道路,道路的兩旁有火把照亮著,由於矮人高超的建築技術,
這道路修築的非常筆直,很難相信你是處在地底下數十里的地方.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/city/c3", 
		"west" : "/d/deathland/city/c1" ]) );
	ob->reset();
}
