// File: /d/deathland/city/c4.c
// Generated by Roommaker Sat Nov 11 12:12:25 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人國度的主要道路");
	ob->set_long( @LONG_DESCRIPTION
矮人國度的主要道路,道路的兩旁有火把照亮著,由於矮人高超的建築技術,
這道路修築的非常筆直,很難相信你是處在地底下數十里的地方.
北邊是一座教堂,不知矮人族是祭拜那個神明,而南邊好像是一座市場,只見一群
矮人們聚集著,明顯的你已經到了矮人國度了.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/city/c5", 
		"south" : "/d/deathland/city/m1", 
		"north" : "/d/deathland/city/church", 
		"west" : "/d/deathland/city/c3" ]) );
	ob->reset();
}
