// File: /d/deathland/city/c7.c
// Generated by Roommaker Sat Nov 11 12:17:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人國度的主要道路");
	ob->set_long( @LONG_DESCRIPTION
矮人國度的主要道路,道路的兩旁有火把照亮著,由於矮人高超的建築技術,
這道路修築的非常筆直 , 很難相信你是處在地底下數十里的地方 .道路的東方
有一個拱門 , 由拱門過去就是矮人國度的皇宮了 .往北方則是通往矮人的村落
的小路.為了保護老弱婦孺.在到達矮人的村落時你會經過矮人的軍營.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/palace/pa_01", 
		"north" : "/d/deathland/dwarf/village_01", 
		"west" : "/d/deathland/city/c6" ]) );
	ob->reset();
}
