// File: /d/deathland/city/church.c
// Generated by Roommaker Sat Nov 11 15:06:00 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人國度的教堂");
	ob->set_long( @LONG_DESCRIPTION
一股祥和的氣氛籠罩著整個地方,教堂裡到處都是虔誠的信徒,在這麼多年
的戰亂之中, 矮人們期望他們的大神能夠解救他們脫離苦海, 因此建造了這座
雄偉的大教堂.教堂內的擺設除了一座非常巨大的神像 (statue) 外,神像前有
一個祭壇(altar),此外數張長椅被整齊排列著,好讓信徒們能專心的祈禱.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"altar" : "一個奇怪的祭壇,上面空無一物.\n", 
		"statue" : "@@look_statue" ]) );
	ob->set( "exits", ([ 
		"south" : "/d/deathland/city/c4" ]) );
	ob->set( "objects", ([ 
		"priest" : "/d/deathland/monster/priest", 
		"believer#2" : "/d/deathland/monster/believer", 
		"believer#4" : "/d/deathland/monster/believer", 
		"believer#1" : "/d/deathland/monster/believer", 
		"believer#3" : "/d/deathland/monster/believer" ]) );
	ob->reset();
}
