// File: /d/deathland/city/g7.c
// Generated by Roommaker Sat Nov 11 15:20:21 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("英雄墓場");
	ob->set_long( @LONG_DESCRIPTION
這裡是矮人英雄的墓場,墓場裡埋藏著一位縱橫沙場的英雄.這一座墓碑的碑銘上
寫著: 一位令人敬仰的無敵英雄.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/city/g6", 
		"north" : "/d/deathland/city/gb", 
		"west" : "/d/deathland/city/g8" ]) );
	ob->set( "objects", ([ 
		"guard" : "/d/deathland/monster/guard05" ]) );
	ob->set( "pre_exit_func", ([ 
		"north" : "to_north" ]) );
	ob->reset();
}
