// File: /d/deathland/city/g8.c
// Generated by Roommaker Sat Nov 11 15:23:06 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("英雄墓場");
	ob->set_long( @LONG_DESCRIPTION
這裡是矮人英雄的墓場,墓場裡埋藏著一位有著偉大探險精神的人.這一座墓碑的碑銘
上寫著: 開路的先鋒.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/city/g7", 
		"north" : "/d/deathland/city/g9" ]) );
	ob->set( "search_desc", ([ 
		"here" : "@@search_here" ]) );
	ob->reset();
}
