// File: /d/deathland/city/g9.c
// Generated by Roommaker Sat Nov 11 15:24:55 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("英雄墓場");
	ob->set_long( @LONG_DESCRIPTION
這裡是矮人英雄的墓場,墓場裡埋藏著一個悲天憫人的醫生.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/deathland/city/ga", 
		"south" : "/d/deathland/city/g8" ]) );
	ob->reset();
}
