// File: /d/deathland/city/ga.c
// Generated by Roommaker Sat Nov 11 15:25:45 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人墓場");
	ob->set_long( @LONG_DESCRIPTION
這裡是矮人國度的墓場,墓場裡埋藏著一些英勇戰死的士兵的骨骸.每一座墓碑
的底下都有一個英勇的靈魂安息著.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/city/g5", 
		"south" : "/d/deathland/city/g9" ]) );
	ob->reset();
}
