// File: /d/deathland/city/m1.c
// Generated by Roommaker Sat Nov 11 15:31:07 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人國度的市場");
	ob->set_long( @LONG_DESCRIPTION
一群矮人聚集於此,這裡是矮人國度的市場,矮人在此買賣一些日常用品,以及
一些奇奇怪怪的東西. 小販的叫賣聲不絕於耳,你期望能在此買到什麼有用的物品
嗎?或許紀念品是最好的選擇,其他的東西只是浪費你的金錢吧了.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/deathland/city/m2", 
		"north" : "/d/deathland/city/c4" ]) );
	ob->set( "objects", ([ 
		"vendor" : "/d/deathland/monster/vendor" ]) );
	ob->reset();
}
