// File: /d/deathland/city/m4.c
// Generated by Roommaker Sat Nov 11 15:34:23 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人國度的酒吧");
	ob->set_long( @LONG_DESCRIPTION
除了矮人聚集於此之外,一些外來的探險者與淘金客也聚集在這裡.這裡是矮人
國度唯一的娛樂場所,酒吧.在這裡,你能聽到各式各樣的傳聞,有些荒誕不經,有些
稀奇古怪.有些是真,有些是假,用你的智慧去分辨吧.
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/deathland/city/m2" ]) );
	ob->set( "objects", ([ 
		"bard" : "/d/deathland/monster/bard01", 
		"explorer" : "/d/deathland/monster/explorer02", 
		"barkeeper" : "/d/deathland/monster/barkeeper" ]) );
	ob->reset();
}
