// File: /d/ocean/ship_iriah.c
// Generated by Roommaker Mon Dec 27 18:39:52 1993

#include <mudlib.h>
#define SHIP_OBJ "/d/std/ocean/ship_iriah"

inherit ROOM;
string location;

void create()
{
	::create();
//	set_name( "frigate iriah", "依莉雅號帆船");
	add( "id", ({ "frigate", "iriah" }) );
	set_short("依莉雅號帆船");
	set( "long","@@query_c_long" );
	set( "light", 1 );
	set_outside( "ocean" );

	reset();
}

string query_c_long()
{
	string long;

	long = 
"你現在正站在依莉雅號帆船的甲板上，依莉雅號是一艘大型的多桅帆船，漆\n"
"成淡藍色的船身和乳白色鑲黃邊的巨帆，襯托出這艘美麗的帆船所獨有的一種高\n"
"貴氣質，據說這艘帆船是在諾頓王國的皇后依莉雅二十歲生日那天，藍沙港的居\n"
"民獻給皇后的生日禮物。\n";
	switch( location ) {
		case "Bluesand":
			long += "    依莉雅號現在正停泊在藍沙港的碼頭上。\n";
			break;
		case "Haiwei":
			long += "    依莉雅號現在正停泊在海威港的碼頭邊。\n";
			break;
		case "ocean":
		default:
			long += "    依莉雅號現在正航行在一望無際的大海上。\n";
			break;
	} 
	return long;
}

// This function sets the location of the ship.
varargs void set_location( string new_loc, string exit )
{
	location = new_loc;
	if( location=="ocean" || !exit ) {
		set( "exits", ([]) );
		SHIP_OBJ->move( "/d/std/ocean/ocean" );
	} else {
		set( "exits", ([ "out": exit ]) );
		SHIP_OBJ->move( exit );
	}
}

