// File: /d/deathland/village/v05.c
// Generated by Roommaker Thu Nov 23 21:04:30 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人村落的入口");
	ob->set_long( @LONG_DESCRIPTION
矮人的村莊.一些矮人們的小孩與老人居住在那裡.由於迷宮的保護,
這裡已經多年沒有戰爭了.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/deathland/village/v04", 
		"north" : "/d/deathland/village/v21" ]) );
	ob->set( "objects", ([ 
		"child" : "/d/deathland/monster/child" ]) );
	ob->reset();
}
