// File: /d/deathland/village/v12.c
// Generated by Roommaker Thu Nov 23 21:09:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人村落的小路");
	ob->set_long( @LONG_DESCRIPTION
你目前位於矮人的村莊的環莊道路上,這裡有著非常和平安詳的氣氛,恍佛是一個世
外桃源.這裡已經多年沒有戰爭了,矮人們的童年幾乎在此渡過 .西邊似乎是一間被廢棄
的建築物,從外表來看應該是座監牢.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/deathland/village/v11", 
		"north" : "/d/deathland/village/v13", 
		"west" : "/d/deathland/village/vr8" ]) );
	ob->set( "objects", ([ 
		"older" : "/d/deathland/monster/older" ]) );
	ob->reset();
}
