// File: /d/deathland/village/v23.c
// Generated by Roommaker Thu Nov 23 21:01:32 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人村落的廣場");
	ob->set_long( @LONG_DESCRIPTION
你目前位於矮人的村莊的大廣場上,這裡有著非常和平安詳的氣氛,矮人們經常在此地
遊玩及嬉戲.東邊有一個很大的水塘(pool),是矮人飲用水的來源 ,在水塘的中央有一個
飄浮的房子(house),你不能想像為何它能浮在空中而不掉下來.
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"house" : @LONG_TEXT
一間飄浮的房子,它有著奇怪的力量,當你注視著它的時候,你發現有一
奇異的光線從裡面射了出來.
LONG_TEXT
, 
		"pool" : "一個大水塘,由於矮人的飲用水取於此地,所以此水塘禁止游泳.\n" ]) );
	ob->set( "exits", ([ 
		"north" : "/d/deathland/village/v24", 
		"south" : "/d/deathland/village/v22", 
		"west" : "/d/deathland/village/v13" ]) );
	ob->reset();
}
