// File: /d/deathland/village/v25.c
// Generated by Roommaker Thu Nov 23 21:08:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人村落的小路");
	ob->set_long( @LONG_DESCRIPTION
你目前位於矮人的村莊的環莊道路上,這裡有著非常和平安詳的氣氛,恍佛是一個世
外桃源.這裡已經多年沒有戰爭了,矮人們的童年幾乎在此渡過.北邊是一間醫院,上面的
招牌上寫著:安琪拉(angelina)診所.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/village/v35", 
		"north" : "/d/deathland/village/vr6", 
		"west" : "/d/deathland/village/v15" ]) );
	ob->reset();
}
