// File: /d/deathland/village/v51.c
// Generated by Roommaker Thu Nov 23 21:05:52 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人村落的小路");
	ob->set_long( @LONG_DESCRIPTION
你目前位於矮人的村莊的環莊道路上,這裡有著非常和平安詳的氣氛,恍佛是一個世
外桃源.這裡已經多年沒有戰爭了,矮人們的童年幾乎在此渡過.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/deathland/village/v52", 
		"west" : "/d/deathland/village/v41" ]) );
	ob->set( "objects", ([ 
		"warrior" : "/d/deathland/monster/warrior02" ]) );
	ob->reset();
}
