// File: /d/deathland/village/v52.c
// Generated by Roommaker Thu Nov 23 21:06:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人村落的小路");
	ob->set_long( @LONG_DESCRIPTION
你目前位於矮人的村莊的環莊道路上,這裡有著非常和平安詳的氣氛,恍佛是一個世
外桃源.這裡已經多年沒有戰爭了 ,矮人們的童年幾乎在此渡過.東邊是矮人族開會的地
方,但是似乎已經很久沒有使用了.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/village/vr3", 
		"south" : "/d/deathland/village/v51", 
		"north" : "/d/deathland/village/v53" ]) );
	ob->set( "objects", ([ 
		"poet" : "/d/deathland/monster/writer" ]) );
	ob->reset();
}
