// File: /d/deathland/village/vr6.c
// Generated by Roommaker Thu Nov 23 21:14:32 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("安琪拉診所");
	ob->set_long( @LONG_DESCRIPTION
這裡躺著很多受傷的矮人士兵及戰士,充斥著藥水味及消毒劑的嗆鼻味道.而這裡的
設備似乎十分齊全,在這裡的大夫醫治之下,受傷的士兵應該很快地能回到戰場上.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/deathland/village/v25" ]) );
	ob->set( "objects", ([ 
		"doctor" : "/d/deathland/monster/doctor", 
		"soldier#3" : "/d/deathland/monster/soldier05", 
		"soldier#2" : "/d/deathland/monster/soldier05", 
		"soldier#1" : "/d/deathland/monster/soldier05" ]) );
	ob->reset();
}
