// File: /d/deathland/village/vr8.c
// Generated by Roommaker Thu Nov 23 21:09:23 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("荒廢的牢獄");
	ob->set_long( @LONG_DESCRIPTION
這裡是一座荒廢已久的牢獄,瓦礫堆積著整個地方.仔細一看有一個門通往地下,但
是那個門已經完完全全被封死了
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"door" : "除了瓦礫堆積在上面外,似乎有一股魔力封住這道門\n" ]) );
	ob->set( "exits", ([ 
		"east" : "/d/deathland/village/v12" ]) );
	ob->reset();
}
