// File: /d/eastland/mumar/kitchen.c
// Generated by Roommaker Sat Nov 25 13:52:53 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("伙房");
	ob->set_long( @LONG_DESCRIPTION
這裡是牧馬關的伙房，每天供應全關官兵營養豐富的食物，以保持體力巔峰。
這兒的牆上掛滿了鍋碗瓢盆之類的烹調器具，油膩的調理臺上則是一些用大桶子裝
的調味品。鼓風爐上的大鍋子大的嚇人，不過聞起來味道還真不錯。這兒的東邊還
有一間庫房，西邊的門外則是教場。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/mumar/vault03", 
		"west" : "/d/eastland/mumar/square06" ]) );
	ob->set( "objects", ([ 
		"cookie#2" : "/d/eastland/mumar/monster/cook_soldier", 
		"cookie#1" : "/d/eastland/mumar/monster/cook_soldier" ]) );
	ob->reset();
}
