// File: /d/eastland/mumar/ladder01.c
// Generated by Roommaker Sat Nov 25 13:50:44 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石梯");
	ob->set_long( @LONG_DESCRIPTION
這裡是城牆函洞下的一座石梯，牆上的火把正嘶嘶地燒著。一道粗糙的石梯從這
兒往上通到城牆上的走廊，東邊則可以回到城樓通道。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/mumar/road1", 
		"up" : "/d/eastland/mumar/wall01" ]) );
	ob->set( "no_monster", 1 );
	ob->reset();
}
