// File: /d/eastland/mumar/m_kitchen.c
// Generated by Roommaker Sat Nov 25 13:55:49 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("鏡中的伙房");
	ob->set_long( @LONG_DESCRIPTION
這裡是鏡中的牧馬關的伙房。原本該掛在牆上的烹調器具們散落在地上的各個
角落，除此之外，地面上都是一些東倒西歪的空桶子。四周的牆壁和調理臺上全是
一些啃□過和抓過的痕跡，看來這裡是某個貪吃的野獸的家。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/mumar/m_square" ]) );
	ob->set( "objects", ([ 
		"rat" : "/d/eastland/mumar/monster/rat" ]) );
	ob->reset();
}
