// File: /d/eastland/mumar/m_square.c
// Generated by Roommaker Sat Nov 25 13:55:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("鏡中的牧馬關教場");
	ob->set_long( @LONG_DESCRIPTION
你走進了一片很大的廣場，不過，和鏡外不同的是，這兒是一片死寂，一點生氣
都沒有，靜得連掉下一支針都聽得見。南北的關門都是緊閉，東邊的庫房門也是鎖得
死死的。黑暗的關內，只有西邊的廚房裡有一絲淡黃色的光線透出。
教場上回湯。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/eastland/mumar/m_kitchen", 
		"up" : "/d/eastland/mumar/m_stage" ]) );
	ob->reset();
}
