// File: /d/eastland/mumar/square03.c
// Generated by Roommaker Sat Nov 25 13:54:56 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("牧馬關教場");
	ob->set_long( @LONG_DESCRIPTION
你走進牧馬關教場的東南角，這兒是牧馬關的新兵教場，所有剛調到牧馬關的士
兵都必須在這裡接受三天的入營訓練，來適應這裡的作息和氣候；凡是無法完成三天
訓練的人，都將分送到別的基地。由於能在牧馬關保衛□土，是東方大國人民的光榮
，所以你所看到的每個新兵都卯上全力，期望能成為一個牧馬關戰士。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/mumar/square02", 
		"north" : "/d/eastland/mumar/square06", 
		"southeast" : "/d/eastland/mumar/stable" ]) );
	ob->set( "objects", ([ 
		"soldier#3" : "/d/eastland/mumar/monster/new_soldier", 
		"soldier#2" : "/d/eastland/mumar/monster/new_soldier", 
		"master" : "/d/eastland/mumar/monster/master", 
		"soldier#1" : "/d/eastland/mumar/monster/new_soldier" ]) );
	ob->reset();
}
