// File: /d/eastland/mumar/square04.c
// Generated by Roommaker Sat Nov 25 13:53:32 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("牧馬關教場");
	ob->set_long( @LONG_DESCRIPTION
你走進了牧馬關的士兵教場，這裡是正規士兵每日操課的地點。廣大的教場上，
這群為保國衛民而努力的戰士們，從未懈怠，不斷地練習著各種戰技和陣法變換，期
望自己能在戰場上大顯身手。士兵操練的殺聲加上城牆反射回來的迴音，震耳欲聾，
聽不慣的人還真難在這待太久。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/mumar/square05", 
		"west" : "/d/eastland/mumar/vault02", 
		"south" : "/d/eastland/mumar/square01" ]) );
	ob->set( "objects", ([ 
		"soldier#2" : "/d/eastland/mumar/monster/soldier", 
		"soldier#1" : "/d/eastland/mumar/monster/soldier" ]) );
	ob->reset();
}
