// File: /d/eastland/mumar/square05.c
// Generated by Roommaker Sat Nov 25 13:53:17 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("牧馬關教場");
	ob->set_long( @LONG_DESCRIPTION
這裡是一片很大的廣場，牧馬關的官兵就在此地接受日夜不停的嚴格訓練，廣場
四周是高聳的牧馬關城牆，使得殺氣瀰漫在整個教場上。北邊就是牧馬關的北門，南
邊則可以通往南門。你耳裡聽到的全是教頭和士兵們的嘶喊聲，在整個教場上回湯。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/mumar/square06", 
		"west" : "/d/eastland/mumar/square04", 
		"north" : "/d/eastland/mumar/north_gate", 
		"south" : "/d/eastland/mumar/square02" ]) );
	ob->reset();
}
