// File: /d/eastland/mumar/stage02.c
// Generated by Roommaker Sat Nov 25 13:51:45 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("御風樓");
	ob->set_long( @LONG_DESCRIPTION
你走到這兒，看到一座雄偉壯碩的城樓，城樓上有一塊扁額，用挺拔的字體寫著
「御風樓」。樓角的飛簷上各雕著一隻栩栩如生的麒麟。樓門前的四隻大銅柱上各以
一隻石黿為基，柱上盤著四條青龍，各自追逐著紅、藍、綠、黃四顆火球。這兒的磅
薄氣勢像個大戶人家，反倒不像是個軍事重鎮。進了門就是一道上樓的大梯，往北則
可以回到城牆的通道。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"up" : "/d/eastland/mumar/stage06", 
		"north" : "/d/eastland/mumar/wall05" ]) );
	ob->reset();
}
