// File: /d/eastland/mumar/wall05.c
// Generated by Roommaker Sat Nov 25 13:51:39 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("牧馬關城牆");
	ob->set_long( @LONG_DESCRIPTION
你走到了牧馬關的北面的城牆上，整座牧馬關也只有這兒朝北的一面才設有城垛
，滿是傷痕的城垛似乎在訴說著戰爭的殘酷。關外的黃色風景絲毫沒有生氣，有的只
是一片死寂。來往的駱駝商隊緩慢地移動，是這片沙漠中唯一的點綴。從這兒往南，
你看到一座城樓。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/mumar/stage02", 
		"west" : "/d/eastland/mumar/wall04" ]) );
	ob->reset();
}
