// File: /d/eastland/mumar/wall02.c
// Generated by Roommaker Sat Nov 25 13:51:11 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("牧馬關城牆");
	ob->set_long( @LONG_DESCRIPTION
你正站在牧馬關的城牆上，關內關外的風景在這兒可以一覽無遺。關外是一片黃色
的沙漠世界，隱約還可以看到來往的駱駝商隊，南邊則是一片綠油油的稻田，和北邊正
成了一個天地的對比。在不遠的西南邊，東方大國的重要軍經中心－若嵐城巍巍地聳立
在那兒，和這座牧馬關成犄角之勢，互相保衛著。
LONG_DESCRIPTION
	);

	ob->set_outside( "eastland" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/mumar/wall01", 
		"north" : "/d/eastland/mumar/wall03" ]) );
	ob->set( "objects", ([ 
		"soldier#3" : "/d/eastland/mumar/monster/guard_soldier", 
		"soldier#2" : "/d/eastland/mumar/monster/guard_soldier", 
		"soldier#1" : "/d/eastland/mumar/monster/guard_soldier" ]) );
	ob->reset();
}
