             牧馬關區域(地上部份)開放說明  --  作者 Stasia  at 94/10/16
             ============================
 
I. 歷史 :
　　 自古以來，牧馬隘口一直是東方大國往北交通的要道，也以此地做為和北方蠻族
　　 的一個緩衝地區。
     然而三百年前，因小型的商人衝突所引發和北方蠻族的一場戰爭使得東方大國體
     認到牧馬隘口的重要性，不僅止於交通要道，更有戰略的意義，因而指派了當代
     最偉大的營造師 -- 姜忠政在此建造了一座關口。經過歷代的補建，這座關卡已
     經固若金湯，北方蠻族也從此二百五十多年從未能進犯到牧馬關北門以南的地區
     。
II. 政府
 
     牧馬關直屬朝廷管轄，關內設節度使一名、大將軍一名分理政軍事誼。但節度使
     常因權力較大而支使大將軍的行動。
 
影響力。
III. 商店
 
   　軍事設施不設商店。
 
IV. 任務概要
 
   目前鎮內有三個任務：
   I.   搜捕逃兵  --  幫助軍師抓一個最近跑掉的小兵。
   II.  伙房  -- 伙房出現鼠賊，要幫助伙伕頭找出偷糧食的小賊。
 
V.  動物列表
 
動物名稱    檔名          等級  AC/DB  WC  傷害範圍  武器裝備   特殊能力
=========== ============= ====  ====== === ========= ========== ========
蟑螂        cockroach     1     8/0    3   1-3
伙伕        cook_soldier  3     16/6   7   2-8       W)勺子     菜渣攻擊
新兵        new_soldier   4     20/6   8   4-8       W)木刀     團體攻擊
巡邏兵      guard_soldier 4     20/6   9   4-9       W)警棍     自動攻擊
馬伕        groom         5     26/12  15  5-17                 不能殺
老兵        old_soldier   5     25/10  12  5-14      W)鈍匕首   團體攻擊
工匠        artisan       6     38/10  13  7-15      W)鐵錘     盾牌破壞
士兵        soldier       6     30/15  15  8-20      W)長戈     團體攻擊
                                                     A)青鋼鱗甲
伙伕頭      cock_master   7     35/15  20  11-26     W)平底鍋   米包攻擊
教頭        master        10    72/21  28  10-22     A)背心     團體攻擊
                                       28  10-22     A)紅短褲
庫房守衛    guard         11    60/22  30  16-38     W)長槍     防具破壞
                                                     A)青鋼鱗甲
戰馬        horse         14    75/28  43  21-41                可騎乘
大老鼠      rat           14    75/28  43  21-41                quest
力士        hercules      15    75/35  42  25-45     W)大槌頭
哈將軍      ha            16    80/40  46  23-48     W)影劍
                                                     A)方盾
                                                     A)石棉網
                                                     I)步卒兵符
哼將軍      hen           16    80/40  46  23-48     W)光刀
                                                     A)圓盾
                                                     A)貂皮
                                                     I)騎兵令牌
軍師        advisor       17    95/51  55  30-50     W)羽扇     幻雷[2]
                                                     A)綸巾     冰雹[3]
                                                     A)兩儀指環 呼喚力士
                                                     A)四象道袍
                                                     A)八卦道鞋
節度使      lee           18    100/50 75  43-65     W)尚方寶劍
                                                     A)金項鍊
                                                     A)金鏤玉衣
                                                     A)絲質手套
VI. 武器列表
 
武器名稱     檔案名稱       武器類別     WC   傷害範圍     特殊攻擊
===========  =============  ===========  ===  ===========  ===========
警棍         club           blunt        5    3-6
鐵錘         hammer         blunt        6    4-11
勺子         scoop          blunt        7    2-8
木刀         wooden_blade   long_blade   8    4-8
鈍匕首       dagger1        dagger       10   4-13
平底鍋       pan            blunt        10   6-12
長戈         javenlin       thrusting    10   5-13
長槍         lance          thrusting    13   6-14
大槌頭       hammer1        blunt        25   11-28
影劍         shadow_sword   long_blade   25   13-28        冰系
光刀         shining_blade  long_blade   25   13-28        火系
羽扇         fan            wand         35   18-27        雷系
尚方寶劍     king_sword     long_blade   30   18-33
 
VII. 防具列表
 
防具名稱   檔名           形態     質料     AC/DB    特殊效果
=========  =============  =======  =======  =======  =======================
金項鍊     amulet01       misc     light_m  0/7      fire 10
青鋼臂甲   armband01      arms     heavy_m  4/2
八卦玄鞋   boots01        feet     cloth    5/3
石棉網     cloak01        cloak    element  4/3      fire 15
貂皮       cloak02        cloak    leather  4/3      cold 15
金縷玉衣   cloth01        body     light_m  28/5     fire 10,cold 10
背心       cloth02        body     cloth    10/1
四象玄袍   cloth03        body     cloth    25/5
綸巾       hat01          head     cloth    3/2
青鋼脛甲   leggings       legs     heavy_m  6/2
青鋼鱗甲   mail01         body     heavy_m  20/0
紅短褲     pants          legs     cloth    3/0
兩儀指環   ring           finger   element  0/7
矩方盾     shield01       shield   light_m  4/2
規圓盾     shield02       shield   light_m  4/2
絲質手套   gloves01       hands    cloth    5/0
 
VIII. 物品列表
 
物品名稱   檔名         形態    特殊用途
========== ============ ======= =========
步卒兵符   mark_a       物品    過守衛
騎兵令牌   mark_c       物品    騎馬出馬房
鏡子的碎片 fragment     物品    quest用
金釦子     button       物品    quest用
