// File: /d/deathland/mine/d03.c
// Generated by Roommaker Thu Nov 23 20:21:42 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人礦坑的大洞穴");
	ob->set_long( @LONG_DESCRIPTION
一個很黑很暗的大洞穴,曾經是個含量豐富的礦坑,但是自從傳出這裡出現怪物後
就沒有什麼人敢來了.越往西走,就覺得似乎有人在窺探你的樣子.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/mine/d02", 
		"west" : "/d/deathland/mine/d04" ]) );
	ob->reset();
}
