// File: /d/deathland/mine/m43.c
// Generated by Roommaker Thu Nov 23 20:33:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人礦坑");
	ob->set_long( @LONG_DESCRIPTION
這裡是礦坑的深處.你能看到的是一個周圍的巖壁充滿著被挖掘的痕跡以及
用木頭架設著以免塌陷的巖洞.在地上有鐵軌鋪設著.專供運礦車通行使用.然而
這裡是鐵軌的盡頭.有一個奇怪的機器(machine)放在鐵軌的兩旁,用來停止運礦
車.一群辛苦的矮人礦工在此努力地開採礦石.
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"machine" : "被放在鐵軌的兩旁,可以大量地增加摩擦力.\n" ]) );
	ob->set( "direction", "machine" );
	ob->set( "exits", ([ 
		"north" : "/d/deathland/mine/m32" ]) );
	ob->reset();
}
