// File: /d/deathland/mine/m72.c
// Generated by Roommaker Thu Nov 23 20:30:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人礦坑");
	ob->set_long( @LONG_DESCRIPTION
這裡是礦坑的深處.你能看到的是一個周圍的巖壁充滿著被挖掘的痕跡以及
用木頭架設著以免塌陷的巖洞.在地上有鐵軌鋪設著.專供運礦車通行使用.你看
到鐵軌一直延伸出深淵之外.而南邊的深淵又大又深.
LONG_DESCRIPTION
	);

	ob->set( "another", "/d/deathland/holyplace/r06" );
	ob->set( "direction", "abyss" );
	ob->set( "exits", ([ 
		"north" : "/d/deathland/mine/m62" ]) );
        ob->set("objects",([
             "rat":"/d/deathland/monster/rat",
        ]) );
	ob->reset();
}
