// File: /d/deathland/mine/mine_02.c
// Generated by Roommaker Thu Nov 23 20:24:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("矮人礦坑");
	ob->set_long( @LONG_DESCRIPTION
這裡是礦坑的深處.你能看到的是一個周圍的巖壁充滿著被挖掘的痕跡以及
用木頭架設著以免塌陷的巖洞.在地上有鐵軌鋪設著.專供運礦車通行使用.你能
看到許多運礦車來來往往.
LONG_DESCRIPTION
	);

	ob->set( "direction", "south" );
	ob->set( "exits", ([ 
		"south" : "/d/deathland/mine/m01", 
		"north" : "/d/deathland/mine/mine_01" ]) );
	ob->reset();
}
