// File: /d/eastland/easta/east_nlane.c
// Generated by Roommaker Sat Nov 25 17:02:09 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("東大街");
	ob->set_long( @LONG_DESCRIPTION
你現在正位於若嵐城的東大街上，整齊的街道上鋪著青石磚，若嵐城的街道
素有整潔美觀的好評，你最好別任意製造髒亂，以免受人恥笑。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/easta/east_ent", 
		"west" : "/d/eastland/easta/east_nalley" ]) );
	ob->reset();
}
