// File: /d/eastland/easta/east_malley.c
// Generated by Roommaker Sat Nov 25 17:09:45 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("東大街");
	ob->set_long( @LONG_DESCRIPTION
你現在正位於若嵐城的東大街上，整齊的街道上鋪著青石磚，若嵐城的街道
素有整潔美觀的好評，你最好別任意製造髒亂，以免受人恥笑。在你的北邊是一
家叫做「聚寶齋」的商店，往南則是金蟾錢莊。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/east_ent", 
		"north" : "/d/eastland/easta/shop", 
		"west" : "/d/eastland/easta/palace_e", 
		"south" : "/d/eastland/easta/bank" ]) );
	ob->reset();
}
