// File: /d/eastland/easta/east_ent.c
// Generated by Roommaker Sat Nov 25 17:02:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("東大街路口");
	ob->set_long( @LONG_DESCRIPTION
你現在來到若嵐城東門內的大街，若嵐城以若嵐宮為中心，東西東北環繞著
四條大街，東大街向來以「吃」聞名，東大街北胡同還因為多得數不盡的餐館與
小吃攤，博得「百味巷」的別稱，往西是東大街的主要街道，通往若嵐宮的青龍
門，東邊則是往城外的東門。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/eastgate", 
		"north" : "/d/eastland/easta/east_nlane", 
		"south" : "/d/eastland/easta/east_slane", 
		"west" : "/d/eastland/easta/east_malley" ]) );
	ob->set( "objects", ([ 
		"vendor" : "/obj/vendor" ]) );
	ob->reset();
}
