// File: /d/eastland/easta/north_ent.c
// Generated by Roommaker Sat Nov 25 17:03:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("北大街路口");
	ob->set_long( @LONG_DESCRIPTION
你現在來到若嵐城北門內的大街，若嵐城以若嵐宮為中心，東西東北環繞著
四條大街，北大街文風鼎盛，許多書院畫坊都開在這條街上，以養士著名的「賽
孟嘗」卞大夫所出資興建的「舞墨軒」也在這條街上，北邊則是往城外的北門。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/north_elane", 
		"south" : "/d/eastland/easta/north_malley", 
		"north" : "/d/eastland/easta/northgate", 
		"west" : "/d/eastland/easta/north_wlane" ]) );
	ob->reset();
}
