// File: /d/eastland/easta/north_ealley.c
// Generated by Roommaker Sat Nov 25 17:02:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("北大街東胡同");
	ob->set_long( @LONG_DESCRIPTION
你現在正位於若嵐城的北大街上，整齊的街道上鋪著青石磚，若嵐城的街道
素有整潔美觀的好評，你最好別任意製造髒亂，以免受人恥笑。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/easta/north_elane", 
		"south" : "/d/eastland/easta/palace_ne", 
		"west" : "/d/eastland/easta/post_office" ]) );
	ob->reset();
}
