// File: /d/eastland/easta/palace_w.c
// Generated by Roommaker Sat Nov 25 17:11:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("若嵐宮白虎門");
	ob->set_long( @LONG_DESCRIPTION
你現在來到了若嵐宮西邊的玄武門，高大的宮門上面裝飾著七排拳頭大的銅
環，緊閉的宮門和高大的宮牆透出一股宮廷深深的氣氛，若嵐宮中數不進的珍奇
寶物都被嚴密地守護著。往西是寬敞的西大街，從這裡可以遠遠地望見若嵐城的
西門，沿著宮牆的青石板路往北方和南方延伸。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/easta/palace_sw", 
		"north" : "/d/eastland/easta/palace_nw", 
		"west" : "/d/eastland/easta/west_malley" ]) );
	ob->set( "objects", ([ 
		"guard#3" : "/d/eastland/easta/monster/palace_guard", 
		"guard#2" : "/d/eastland/easta/monster/palace_guard", 
		"guard#1" : "/d/eastland/easta/monster/palace_guard", 
		"guard#4" : "/d/eastland/easta/monster/palace_guard" ]) );
	ob->reset();
}
