// File: /d/eastland/easta/palace_e.c
// Generated by Roommaker Sat Nov 25 17:10:42 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("若嵐宮青龍門");
	ob->set_long( @LONG_DESCRIPTION
你現在來到了若嵐宮東邊的青龍門，高大的宮門上面裝飾著七排拳頭大的銅
環，緊閉的宮門和高大的宮牆透出一股宮廷深深的氣氛，若嵐宮中數不進的珍奇
寶物都被嚴密地守護著。往東是寬敞的東大街，從這裡可以遠遠地望見若嵐城的
東門，沿著宮牆的青石板路往北方和南方延伸。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/east_malley", 
		"south" : "/d/eastland/easta/palace_se", 
		"north" : "/d/eastland/easta/palace_ne" ]) );
	ob->set( "objects", ([ 
		"guard#3" : "/d/eastland/easta/monster/palace_guard", 
		"guard#2" : "/d/eastland/easta/monster/palace_guard", 
		"guard#1" : "/d/eastland/easta/monster/palace_guard", 
		"guard#4" : "/d/eastland/easta/monster/palace_guard" ]) );
	ob->reset();
}
