// File: /d/eastland/easta/palace_sw.c
// Generated by Roommaker Sat Nov 25 17:05:27 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("靈猿樓");
	ob->set_long( @LONG_DESCRIPTION
你現在正位於若嵐宮西南角，靈猿樓前的廣場，若嵐宮高大的宮牆往東方與
北方延伸，沿著宮牆種著一排美麗的鳳凰木，街道上鋪著整齊的青石板，廣場南
邊與西邊各有一條胡同，通往環繞若嵐城的大街。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/palace_s", 
		"south" : "/d/eastland/easta/south_walley", 
		"north" : "/d/eastland/easta/palace_w", 
		"west" : "/d/eastland/easta/west_salley" ]) );
	ob->set( "objects", ([ 
		"vistor2" : "/d/eastland/easta/monster/vistor", 
		"vistor1" : "/d/eastland/easta/monster/vistor" ]) );
	ob->reset();
}
