// File: /d/eastland/easta/palace_s.c
// Generated by Roommaker Sat Nov 25 17:10:58 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("若嵐宮朱雀門");
	ob->set_long( @LONG_DESCRIPTION
你現在來到了若嵐宮南邊的朱雀門，高大的宮門上面裝飾著七排拳頭大的銅
環，緊閉的宮門和高大的宮牆透出一股宮廷深深的氣氛，若嵐宮中數不進的珍奇
寶物都被嚴密地守護著。往南是寬敞的南大街，從這裡可以遠遠地望見若嵐城的
南門，沿著宮牆的青石板路往東方和西方延伸。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/palace_se", 
		"west" : "/d/eastland/easta/palace_sw", 
		"south" : "/d/eastland/easta/south_malley" ]) );
	ob->set( "objects", ([ 
		"guard#3" : "/d/eastland/easta/monster/palace_guard", 
		"guard#2" : "/d/eastland/easta/monster/palace_guard", 
		"guard#1" : "/d/eastland/easta/monster/palace_guard", 
		"guard#4" : "/d/eastland/easta/monster/palace_guard" ]) );
	ob->reset();
}
