// File: /d/eastland/easta/palace_se.c
// Generated by Roommaker Sat Nov 25 17:07:45 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("青鯉樓");
	ob->set_long( @LONG_DESCRIPTION
你現在來到了若嵐宮東南角，青鯉樓前的廣場，樓前用青石雕成的四十九隻
鯉魚宛如活魚一般在你的眼前遊動，映著大紅色的若嵐宮高大的宮牆，構成一幅
美妙的景象，廣場南邊和東邊的胡同通往東大街和南大街。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/east_salley", 
		"north" : "/d/eastland/easta/palace_e", 
		"south" : "/d/eastland/easta/south_ealley", 
		"west" : "/d/eastland/easta/palace_s" ]) );
	ob->set( "objects", ([ 
		"vistor2" : "/d/eastland/easta/monster/vistor", 
		"visitor1" : "/d/eastland/easta/monster/vistor" ]) );
	ob->reset();
}
