// File: /d/eastland/easta/palace_ne.c
// Generated by Roommaker Sat Nov 25 17:02:44 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("飛鴻樓");
	ob->set_long( @LONG_DESCRIPTION
你現在來到了若嵐宮東北角，飛鴻樓前的廣場，據說每年二月颳起東北風的時
候，東北風吹過飛鴻樓屋簷下的風管時，發出的聲音就如大鴻飛翔時的叫聲，不少
外地來的人都特地趕來這裡聆聽「鴻鳴」，從廣場向北是一條熱鬧的胡同，往東則
是有「百味巷」之稱的東大街北胡同。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/east_nalley", 
		"north" : "/d/eastland/easta/north_ealley", 
		"south" : "/d/eastland/easta/palace_e", 
		"west" : "/d/eastland/easta/palace_n" ]) );
	ob->set( "objects", ([ 
		"vistor2" : "/d/eastland/easta/monster/vistor", 
		"vistor1" : "/d/eastland/easta/monster/vistor" ]) );
	ob->reset();
}
