// File: /d/eastland/easta/south_malley.c
// Generated by Roommaker Sat Nov 25 17:11:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("南大街");
	ob->set_long( @LONG_DESCRIPTION
你現在正位於若嵐城的南大街上，整齊的街道上鋪著青石磚，若嵐城的街道
素有整潔美觀的好評，你最好別任意製造髒亂，以免受人恥笑。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/easta/palace_s", 
		"south" : "/d/eastland/easta/south_ent" ]) );
	ob->reset();
}
