// File: /d/eastland/easta/south_ent.c
// Generated by Roommaker Sat Nov 25 17:06:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("南大街路口");
	ob->set_long( @LONG_DESCRIPTION
你現在來到若嵐城南門內的大街，若嵐城以若嵐宮為中心，東西東北環繞著
四條大街，南大街由於正對著若嵐宮的正門朱雀門，因此有許多權貴顯要都居住
在這條街上，你的北邊不遠處是相國府，更北一點是穆將軍府，南大街的東西兩
條胡同中也住著不少大官與士紳，南邊則是往城外的南門。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/south_elane", 
		"west" : "/d/eastland/easta/south_wlane", 
		"south" : "/d/eastland/easta/southgate", 
		"north" : "/d/eastland/easta/south_malley" ]) );
	ob->reset();
}
