// File: /d/eastland/easta/southgate.c
// Generated by Roommaker Sat Nov 25 17:12:24 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("若嵐城南門");
	ob->set_long( @LONG_DESCRIPTION
這裡是若嵐城的南門，高聳的城牆和佈滿青苔的基石，古雅的城樓烘托出一股
莊嚴肅穆的氣氛，城樓上刻著「若嵐古風」四個篆字，從這裡你可以遠遠望見城中
整齊寬敞的街道，若嵐城是東方大國的首都，皇上所住的若嵐宮就位於城中心，宛
如一座小型的城市。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/9,6.east", 
		"north" : "/d/eastland/easta/south_ent" ]) );
	ob->set( "no_monster", 1 );
	ob->set( "objects", ([ 
		"guard#2" : "/d/eastland/easta/monster/cityguard", 
		"guard#1" : "/d/eastland/easta/monster/cityguard" ]) );
	ob->reset();
}
