// File: /d/eastland/easta/west_slane.c
// Generated by Roommaker Sat Nov 25 17:05:03 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("西大街");
	ob->set_long( @LONG_DESCRIPTION
你現在正位於若嵐城的西大街上，整齊的街道上鋪著青石磚，若嵐城的街道
素有整潔美觀的好評，你最好別任意製造髒亂，以免受人恥笑。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/west_salley", 
		"north" : "/d/eastland/easta/west_ent" ]) );
	ob->set( "objects", ([ 
		"vagabond#2" : "/d/eastland/easta/monster/vagabond", 
		"vagabond#1" : "/d/eastland/easta/monster/vagabond" ]) );
	ob->reset();
}
