// File: /d/eastland/easta/west_ent.c
// Generated by Roommaker Sat Nov 25 17:04:35 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("西大街路口");
	ob->set_long( @LONG_DESCRIPTION
你現在來到若嵐城西門內的大街，若嵐城以若嵐宮為中心，東西東北環繞著
四條大街，西大街上所住的居民大多屬於中下階層的農人或工人，一片平房中夾
著幾間獨門獨院的地主大宅，不過這些地主懾於布衣出身的蕭相國之威，倒也不
敢對窮人過於苛刻，往東是西大街的主要街道，西邊則是往城外的西門。
LONG_DESCRIPTION
	);

	ob->set_outside( "easta" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/easta/west_malley", 
		"south" : "/d/eastland/easta/west_slane", 
		"north" : "/d/eastland/easta/west_nlane", 
		"west" : "/d/eastland/easta/westgate" ]) );
	ob->reset();
}
