// File: /d/eastland/easta/bank.c
// Generated by Roommaker Thu Jan 27 10:10:43 1994

#include <mudlib.h>

inherit "/std/bank";
inherit "/std/exchange";
inherit ROOM;

void create()
{
	exchange::create();
	room::create();
	set_short("金蟾錢莊");
	set_long( @C_LONG_DESCRIPTION
這裡是一家頗負盛名的錢莊，老闆是若嵐城鼎鼎大名的張大財主，這家錢莊的
業務不但遍佈東方大國，連諾達尼亞和莫爾斯等地的銀行都有往來，如果你在遠風
鎮或默拉迪亞的銀行有帳戶的話，也可以在這裡存提款，或者是在這裡開戶(open)
，只要 25 枚金幣就可以將你的錢寄放在錢莊裡。錢莊裡除了存提款，也提供錢幣
的兌換服務，你可以用 convert 指令兌換身上的錢幣。
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "exits", ([ 
		"north" : "/d/eastland/easta/east_malley" ]) );
	set( "objects", (["taxman":"/d/eastland/easta/monster/taxman"]) );
	reset();
}

void init()
{
	bank::init();
	exchange::init();
}
