// File: /d/eastland/easta/herb_shop.c
// Generated by Roommaker Thu Jan 27 11:07:31 1994

#include <mudlib.h>

inherit SELLER;
inherit ROOM;

void create()
{
	::create();
	set_short("老桐閣藥鋪");
	set_long( @C_LONG_DESCRIPTION
你一走進這家藥鋪，就聞到一股濃郁的檀香，這裡是若嵐城歷史最老的一家藥
鋪，從尋常的刀傷藥膏，到難得一見的千年老參，這裡都有，這家藥鋪還有一種祖
傳的刀傷藥配方叫做「天香斷續膏」，治外傷靈驗無比，這裡所賣的藥材與價錢都
寫在一張掛在壁上的畫軸(paper)上，往東走則是南大街的東胡同。
C_LONG_DESCRIPTION
	);

	set( "item_func", ([
		"paper" : "show_menu"
	]) );
	set( "light", 1 );
	set( "exits", ([
		"east" : "/d/eastland/easta/south_ealley" ]) );
	set_inventory( ({
		({ "/obj/bandage",60,60 }),
                ({ "/d/eastland/easta/obj/plaster1", 40, 40 }),
                ({ "/d/eastland/easta/obj/white_plaster1", 40, 40 }),
		({ "/d/eastland/easta/obj/spicy_plaster", 30, 30 }),
		({ "/d/eastland/easta/obj/green_pill", 40, 40 }),
		({ "/d/eastland/easta/obj/small_pill", 30, 30 }),
		({ "/d/eastland/easta/obj/large_pill", 20, 20 }),
	}) );
	reset();
}
void reset()
{
	room::reset();
	seller::reset();
}
