// File: /d/eastland/easta/palace_nw.c
// Generated by Roommaker Sun Jan 30 05:47:16 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("黃鶴樓");
	set_long( @C_LONG_DESCRIPTION
你現在來到了若嵐宮西北角，黃鶴樓前的廣場，據說曾經有仙人乘著黃鶴來到
這座完全用大理石建成的塔樓吟詩彈琴，這裡同時也是許多文人雅士常常流連忘返
的一處名勝，黃鶴樓雲白色的形影趁著後方大紅色的若嵐宮宮牆，形成文人口中的
「若嵐紅雪」奇景。
C_LONG_DESCRIPTION
	);

	set_outside( "eastland" );
	set( "light", 1 );
	set( "exits", ([ 
		"west" : "/d/eastland/easta/west_nalley", 
		"north" : "/d/eastland/easta/north_walley", 
		"south" : "/d/eastland/easta/palace_w", 
		"east" : "/d/eastland/easta/palace_n" ]) );
	set( "objects", ([ 
		"vistor1" : "/d/eastland/easta/monster/vistor", 
		"vistor2" : "/d/eastland/easta/monster/vistor" ]) );
	reset();
#include <replace_room.h>
}
void init()
{
        if( this_player() ) this_player()->set_explore( "eastland#6" );
}
