// File: /d/eastland/easta/shop.c
// Generated by Roommaker Thu Jan 27 09:58:01 1994

#include <mudlib.h>

inherit SHOP;

void create()
{
	::create();
	set_short("聚寶齋");
	set_long( @C_LONG_DESCRIPTION
你現在走進了一家大型的商店，一塊烏黑的檀木屏風隔開入口處的兩道臺階，屏
風上三個金漆大字寫著「聚寶齋」，店裡是一個方形的賣場，兩個長相斯文的先生正
分別在左右兩個長櫃後忙著招呼客人，你可以在這裡隨意瀏覽貨物，看得中意只要向
兩位先生招呼一聲，他們就會過來，往南則是東大街的主要街道。
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "exits", ([ 
		"south" : "/d/eastland/easta/east_malley" ]) );
	set( "objects", ([
		"trashcan" : "/obj/trashcan" ]) );
	storeroom()->set( "objects", ([
		"torch#0" : "/obj/torch",
		"bandage#0" : "/obj/bandage",
		"bag#0" : "/obj/bag",
	]) );
		
	reset();
#include <replace_shop.h>
}
