// File: /d/eastland/beggar/area/church.c
// Generated by Roommaker Thu Mar 21 18:08:50 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("祠堂");
	ob->set_long( @LONG_DESCRIPTION
這是一間老舊的祠堂,因為年老未修緝, 所以看起來好像要□塌的樣子。一眼
看過去桌上有很多架子,架上供奉的多是歷代幫主和一些精忠報國之士的神主牌 。
檀香嫋嫋,誦經之聲不斷,頓時讓你想詹仰先人的風範, 因而不禁嚴肅了起來,或許
是忠義心人人有之使得你有所感觸吧。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/eastland/beggar/area/east7.c" ]) );
	ob->set( "objects", ([ 
		"old" : "/d/eastland/beggar/monster/old_garden.c", 
		"enforcer3" : "/d/eastland/beggar/monster/enforcer.c", 
		"enforcer2" : "/d/eastland/beggar/monster/enforcer.c", 
		"enforcer1" : "/d/eastland/beggar/monster/enforcer.c" ]) );
	ob->reset();
}
