// File: /d/eastland/beggar/area/cross.c
// Generated by Roommaker Mon Jul 22 17:57:56 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『薪膽村』入口處");
	ob->set_long( @LONG_DESCRIPTION
你現在來到了『薪膽村』的入口處，在路邊有一塊長滿青苔的石埤 ( stone )
，雖然上面的字跡有點模糊，但仍舊可以辨認，對於初到此地的你或許是一個很好
的指引也說不定。東、西和北邊都是村路，而南邊則是『薪膽村』的廣場，西南邊
有面山牆，牆有洞，是村的出口。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "c_item_desc", ([ 
		"stone" : @LONG_TEXT
這是一塊長滿青苔的埤,上面寫著:
                玩 ES 不要玩過火喲,小心你的功課。 
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/beggar/area/east1.c", 
		"out" : "/d/eastland/beggar/area/mroad5.c", 
		"north" : "/d/eastland/beggar/area/north1.c", 
		"south" : "/d/eastland/beggar/area/south1.c", 
		"west" : "/d/eastland/beggar/area/west1.c" ]) );
	ob->set( "objects", ([ 
		"vendor" : "/d/eastland/beggar/monster/vendor.c", 
		"fifth2" : "/d/eastland/beggar/monster/fifth.c", 
		"seventh" : "/d/eastland/beggar/monster/seventh.c" ]) );
	ob->reset();
}
