// File: /d/eastland/beggar/area/east4.c
// Generated by Roommaker Thu Mar 21 18:08:26 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("村路");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在一條由碎石子鋪成的村 路上。村路向東、西方向延伸。村路不
很大,約可容納一匹馬行駛的寬度。在路旁長著一些奇形怪狀的植物 ,那上面更開
著許多不知名的小花,小花聞起來有點淡淡的香味, 那味道說不出的使得你心曠神
怡。鳥語蛙嗚, 頓時你煩惱盡失,站在這裡真是有如仙境。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/beggar/area/east5.c", 
		"west" : "/d/eastland/beggar/area/east3.c" ]) );
	ob->reset();
}
