// File: /d/eastland/beggar/area/east8.c
// Generated by Roommaker Thu Mar 21 18:09:22 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("陰暗房間");
	ob->set_long( @LONG_DESCRIPTION
你來到了一個陰暗的房間,因為這裡長久欠缺陽光的照射,所以總有股揮之不去
的發黴味道。這裡沒什麼擺設,空洞洞的,牆壁上只有幾根快燒完的火把, 地上也沒
什腳印之類的東西,畢竟這裡很少人來。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"north" : "/d/eastland/beggar/area/east9.c" ]) );
	ob->reset();
}
