// File: /d/eastland/beggar/area/jail2.c
// Generated by Roommaker Thu Mar 21 18:10:09 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『薪膽村』監牢");
	ob->set_long( @LONG_DESCRIPTION
你現在來到了監牢的地底下一層。這裡滿地都是白森森的□骨, 角落裡有一張
釘在牆壁上的木板床。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"bed" : "一張簡簡單單的木床。\n", 
		"bone" : "幾根死人的骨頭。\n" ]) );
	ob->set( "exits", ([ 
		"up" : "/d/eastland/beggar/area/jail1.c" ]) );
	ob->set( "objects", ([ 
		"prisoner" : "/d/eastland/beggar/monster/prisoner" ]) );
	ob->reset();
}
