// File: /d/eastland/beggar/area/master_roomw.c
// Generated by Roommaker Thu Mar 21 18:11:49 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『賞善罰惡廳』");
	ob->set_long( @LONG_DESCRIPTION
這裡是『賞善罰惡廳』的左邊偏房。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/beggar/area/master_room.c" ]) );
	ob->reset();
}
