// File: /d/eastland/beggar/area/master_room.c
// Generated by Roommaker Thu Mar 21 18:11:42 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『賞善罰惡廳』大廳");
	ob->set_long( @LONG_DESCRIPTION
這裡是『賞善罰惡廳』,是丐幫用來獎勵有功份子和處罰違反幫規或者為非作
歹的幫中份子。 一進來你就可以看到一幅『關公』像和一張大紅桌子上擺著琳朗
目的家法,壁上掛著兩口鋒利的寶劍似乎警告著你不要做壞事, 否則後果不堪設想
!!大廳左側有一個樓梯可以到二樓。 
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/beggar/area/master_roome.c", 
		"out" : "/d/eastland/beggar/area/north11.c", 
		"up" : "/d/eastland/beggar/area/master_roomu.c", 
		"west" : "/d/eastland/beggar/area/master_roomw.c" ]) );
	ob->set( "objects", ([ 
		"tan_male" : "/d/eastland/beggar/monster/tan_male.c", 
		"law_master" : "/d/eastland/beggar/monster/law_master.c", 
		"tan_female" : "/d/eastland/beggar/monster/tan_female.c" ]) );
	ob->reset();
}
