// File: /d/eastland/beggar/area/master_roome.c
// Generated by Roommaker Thu Mar 21 18:11:45 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『賞善罰惡廳』");
	ob->set_long( @LONG_DESCRIPTION
這裡是『賞善罰惡廳』的右邊偏房,壁上掛著一幅畫繪形一個人形。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "c_item_desc", ([ 
		"icons" : "一幅頗舊的畫。\n" ]) );
	ob->set( "exits", ([ 
		"west" : "/d/eastland/beggar/area/master_room.c" ]) );
	ob->reset();
}
