// File: /d/eastland/beggar/area/north1.c
// Generated by Roommaker Thu Mar 21 18:10:15 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("村路");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在一條頗為寬大的村路上,約可容納兩匹馬並行。村路向南、北方
向延伸。這條村路整理得蠻乾淨的,路旁的植物修緝的很整齊,花兒欣欣向榮,比起
廣場那片光禿禿的景像自是不可而語。畢竟這條是連接幾個較大鋪子,可說是村內
最繁華的道路。雖是如此, 卻看不出任何人工刻意留下來的痕跡,這一定是出自於
某位名匠之手。在你的東邊是『吉祥』賭坊,而西邊則是一間藥鋪。    
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/beggar/area/game_room.c", 
		"west" : "/d/eastland/beggar/area/hospital.c", 
		"north" : "/d/eastland/beggar/area/north2.c", 
		"south" : "/d/eastland/beggar/area/cross.c" ]) );
	ob->reset();
}
