// File: /d/eastland/beggar/area/s4w2.c
// Generated by Roommaker Thu Mar 21 18:06:28 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『薪膽村』廣場");
	ob->set_long( @LONG_DESCRIPTION
這是一大片黃砂廣場, 因為『丐幫』弟子常在此處練武功,所以地面顯得光禿
禿的一根雜草也沒有。有時候風颳的很大挾帶著漫天的灰塵,尤其是每當南邊的高
山吹著『落山風』,真叫人眼睛睜不開。於是『丐幫』擬定做一些水土保持的工作
,但是村裡缺乏另一大片空地可以供弟子們練習, 所以每次提出做值地皮的工作就
會遭人反對, 於是乎人們還是得繼續忍受下去。東和北邊是廣場的繼續延申,西邊
是一大片樹林而南邊則是山坡。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"east" : "/d/eastland/beggar/area/s4w1.c", 
		"north" : "/d/eastland/beggar/area/s1w2.c" ]) );
	ob->reset();
}
