// File: /d/eastland/beggar/area/temp_room1.c
// Generated by Roommaker Thu Mar 21 18:09:43 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("暗房");
	ob->set_long( @LONG_DESCRIPTION
你來到一間陰暗的房間,這裡的溼氣頗重,並且有一股發黴的味道。
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"out" : "/d/eastland/beggar/area/east10.c" ]) );
	ob->set( "objects", ([ 
		"fighter" : "/d/eastland/beggar/monster/fighter.c" ]) );
	ob->reset();
}
