// File: /d/eastland/beggar/area/west6.c
// Generated by Roommaker Thu Mar 21 18:07:39 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("村路");
	ob->set_long( @LONG_DESCRIPTION
你現在正走在一條由碎石子鋪成的村 路上。村路向南、北方向延伸。村路不
很大,約可容納一匹馬行駛的寬度。在路旁長著一些奇形怪狀的植物 ,那上面更開
著許多不知名的小花,小花聞起來有點淡淡的香味, 那味道說不出的使得你心曠神
怡。鳥語蛙嗚, 頓時你煩惱盡失,站在這裡真是有如仙境。你的西邊是一個不很大
菜圃。
LONG_DESCRIPTION
	);

	ob->set_outside( "noden" );
	ob->set( "exits", ([ 
		"south" : "/d/eastland/beggar/area/west7.c", 
		"north" : "/d/eastland/beggar/area/west5.c", 
		"west" : "/d/eastland/beggar/area/farm.c" ]) );
	ob->reset();
}
