// File: /d/eastland/beggar/area/wine_shop1.c
// Generated by Roommaker Thu Mar 21 18:11:00 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『薪膽』客棧二樓");
	ob->set_long( @LONG_DESCRIPTION
這裡是『薪膽客棧』的二樓上座, 是屬較高價位的地方, 喜歡熱鬧和出手闊綽
的人都喜歡在這裡喝酒聊天。牆右角有一個樓梯可以通往一樓和三樓。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/eastland/beggar/area/wine_shop.c", 
		"up" : "/d/eastland/beggar/area/wine_shop2.c" ]) );
	ob->set( "objects", ([ 
		"waiter" : "/d/eastland/beggar/monster/waiter.c", 
		"chan_master" : "/d/eastland/beggar/monster/chan_master.c" ]) );
	ob->reset();
}
