// File: /d/eastland/beggar/area/wine_shop2.c
// Generated by Roommaker Thu Mar 21 18:11:07 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『薪膽』客棧頂樓");
	ob->set_long( @LONG_DESCRIPTION
這裡是『薪膽』客棧最高的一層樓,也是客棧最高價碼的地方。這裡通常用來
招待王公貴人或者是貴為一幫之主的地方,不是隨便就可以來的。牆右角有一個樓
梯可以下到二樓。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/eastland/beggar/area/wine_shop1.c" ]) );
	ob->set( "objects", ([ 
		"couple1" : "/d/eastland/beggar/monster/couple1.c", 
		"waiter" : "/d/eastland/beggar/monster/waiter.c", 
		"couple2" : "/d/eastland/beggar/monster/couple2.c" ]) );
	ob->reset();
}
