// File: /d/eastland/beggar/area/wine_shop.c
// Generated by Roommaker Thu Mar 21 18:10:54 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("『薪膽』客棧");
	ob->set_long( @LONG_DESCRIPTION
這裡是『薪膽村』唯一的一間客棧,往來的旅客都常常在這裡休憩。在這裡,你
或許可以打聽到各地的消息和傳言,尤其是地處偏僻的『薪膽村』,這裡就顯得更為
重要了。店小二正在忙著招呼著客人。牆右角有一個樓梯,可以上到二樓。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/eastland/beggar/area/north3.c", 
		"up" : "/d/eastland/beggar/area/wine_shop1.c" ]) );
	ob->set( "objects", ([ 
		"waiter" : "/d/eastland/beggar/monster/waiter.c" ]) );
	ob->reset();
}
