// File: /d/deathland/dwarf/batcave01.c
// Generated by Roommaker Thu Nov 23 19:40:47 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("蝙蝠洞");
	ob->set_long( @LONG_DESCRIPTION
一處蝙蝠棲息的地方,陰暗的氣息以及腐敗的味道讓人覺得很不舒服.一股令人作嘔
的風從洞的深處傳出,似乎洞的盡頭藏著一種可怕的生物.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/deathland/dwarf/river01", 
		"north" : "/d/deathland/dwarf/batcave02" ]) );
	ob->set( "objects", ([ 
		"bat" : "/d/deathland/monster/bat" ]) );
	ob->reset();
}
