// File: /d/deathland/dwarf/muse13.c
// Generated by Roommaker Thu Nov 23 20:02:13 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("一處寧靜的地方");
	ob->set_long( @LONG_DESCRIPTION
在這裡, 你只有聽到水的滴答聲, 安安靜靜的讓你有一種舒適的感覺, 好像來到
了世外桃源一樣.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/deathland/dwarf/muse23", 
		"south" : "/d/deathland/dwarf/muse12", 
		"north" : "/d/deathland/dwarf/muse14" ]) );
	ob->set( "for_guard", "shortblade" );
	ob->set( "objects", ([ 
		"guard" : "/d/deathland/monster/guard04" ]) );
	ob->reset();
}
