// File: /d/deathland/dwarf/muse53.c
// Generated by Roommaker Thu Nov 23 20:04:36 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("一處寧靜的地方");
	ob->set_long( @LONG_DESCRIPTION
在這裡, 你只有聽到水的滴答聲, 安安靜靜的讓你有一種舒適的感覺, 好像來到
了世外桃源一樣.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"south" : "/d/deathland/dwarf/muse52", 
		"north" : "/d/deathland/dwarf/muse54", 
		"west" : "/d/deathland/dwarf/muse43" ]) );
	ob->set( "for_guard", "longblade" );
	ob->set( "objects", ([ 
		"guard" : "/d/deathland/monster/guard04" ]) );
	ob->reset();
}
