// File: /d/deathland/dwarf/village_02.c
// Generated by Roommaker Thu Nov 23 19:13:40 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("通往矮人的村落的小路");
	ob->set_long( @LONG_DESCRIPTION
這小路是通往矮人的村落的唯一途徑,但是北方有一個很大的軍營.你聽到許
多的矮人士兵正在訓練的聲音.希望你沒有在矮人國度沒有作任何的壞事,否則最
好不要繼續前進.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/deathland/dwarf/village_03", 
		"south" : "/d/deathland/dwarf/village_01" ]) );
	ob->reset();
}
