// File: /d/deathland/dwarf/village_03.c
// Generated by Roommaker Thu Nov 23 19:32:37 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("軍營");
	ob->set_long( @LONG_DESCRIPTION
矮人士兵正在此地接受嚴格的訓練.為了抵抗山頂巨人的侵略,矮人族的每一
個青年都必須加入矮人軍團.因此這軍營的規模非常龐大.這裡是軍營的入口, 往
裡面看過去有好幾棟建築物(buildings).雖然這些建築物的外形看起來都一模一
樣,但是每一棟建築物都有其特別的功能.
西邊有一片很大的空地.應該是訓練戰爭技巧的地方.而在建築物的中間有條小路
穿越其中,是通往矮人的村落的唯一途徑.
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"buildings" : @LONG_TEXT
一些方方正正的建築,而這些建築似乎是一種碉堡,上面有著許許 
多多發射弓箭的地方.
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"west" : "/d/deathland/dwarf/squire", 
		"north" : "/d/deathland/dwarf/village_04", 
		"south" : "/d/deathland/dwarf/village_02" ]) );
	ob->set( "objects", ([ 
		"soldier" : "/d/deathland/monster/soldier02" ]) );
	ob->reset();
}
