// File: /d/deathland/dwarf/well08.c
// Generated by Roommaker Thu Nov 23 19:38:38 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地下河道");
	ob->set_long( @LONG_DESCRIPTION
四周到處都是青苔和一些奇怪的小蟲,而且這裡的泥土十分潮□,似乎這裡是地下
河川的河道,但是目前這河道已經乾枯了.而在這裡你看到河道已經流入更深入地下的
地方.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"northwest" : "/d/deathland/dwarf/well07" ]) );
	ob->set( "objects", ([ 
		"thief#2" : "/d/deathland/monster/thief01", 
		"thief#1" : "/d/deathland/monster/thief01" ]) );
	ob->reset();
}
