// File: /d/deathland/dwarf/well02.c
// Generated by Roommaker Thu Nov 23 19:38:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地下河道");
	ob->set_long( @LONG_DESCRIPTION
四周到處都是青苔和一些奇怪的小蟲,而且這裡的泥土十分潮□,似乎這裡是地下
河川的河道,但是目前這河道已經乾枯了.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"northwest" : "/d/deathland/dwarf/well03", 
		"southeast" : "/d/deathland/dwarf/well04" ]) );
	ob->set( "objects", ([ 
		"thief" : "/d/deathland/monster/thief01" ]) );
	ob->reset();
}
