// File: /d/deathland/dwarf/well03.c
// Generated by Roommaker Thu Nov 23 19:40:01 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地下河道");
	ob->set_long( @LONG_DESCRIPTION
四周到處都是青苔和一些奇怪的小蟲,而且這裡的泥土十分潮溼,似乎這裡是地下
河川的河道,但是目前這河道已經乾枯了.
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/deathland/dwarf/well05", 
		"southeast" : "/d/deathland/dwarf/well02" ]) );
	ob->set( "objects", ([ 
		"frog#2" : "/d/deathland/monster/frog", 
		"frog#1" : "/d/deathland/monster/frog" ]) );
	ob->reset();
}
