// File: /d/noden/hawk/crack3.c
// Generated by Roommaker Mon Dec  4 21:09:22 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
你現在來到一個狹窄的洞穴之中，洞穴的地面似乎有人工鑿過的痕跡，不過年代
已經相當久遠了，你無法確定這些痕跡是天然或人工所造成的，洞穴中的空氣相當乾
燥，一股微風從洞穴深處吹了出來。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/hawk/crack4", 
		"up" : "/d/noden/hawk/crack1" ]) );
	ob->reset();
}
