// File: /d/noden/hawk/crack1.c
// Generated by Roommaker Mon Dec  4 21:08:07 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
你現在正站在一個狹窄的洞穴中，一條恰可容納一個人通過的裂縫從外面透進
一些昏暗的光線，這個洞穴很窄，但是你發現洞穴的頂端有一塊可供攀爬的岩石突
出，只要你稍微一跳就夠得著，洞穴往下是一條更大的裂縫，裡面黑漆漆的。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"out" : "/d/noden/hawk/clearing", 
		"down" : "/d/noden/hawk/crack3", 
		"up" : "/d/noden/hawk/crack2" ]) );
	ob->set( "objects", ([ 
		"worm#1" : "/d/noden/hawk/monster/cave_worm", 
		"worm#2" : "/d/noden/hawk/monster/cave_worm" ]) );
	ob->reset();
}
