// File: /d/noden/hawk/dungeon.c
// Generated by Roommaker Mon Dec  4 21:11:04 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地牢");
	ob->set_long( @LONG_DESCRIPTION
你現在位於一個陰暗潮溼的地牢中，地上水深及膝，而且還發出惡臭，四周都是
長滿青苔(moss)的堅硬岩石，北邊的牆壁上有一個銅環(ring)嵌在你頭上約兩公尺的
地方，你聽見一陣吱吱的叫聲從西邊的牆壁(wall)後面傳出。
LONG_DESCRIPTION
	);

	ob->set( "item_desc", ([ 
		"ring" : @LONG_TEXT
這個銅環上面長滿了噁心的銅綠，看起來像是某種機關的控制開關，不過離你
太遠了，拉不到....
LONG_TEXT
, 
		"moss" : @LONG_TEXT
這些青苔不知道是什麼突變種，長得像小草一般高，有些頂端甚至還有一些像
花朵一樣的紅葉片(leaves)。
LONG_TEXT
, 
		"wall" : @LONG_TEXT
這些牆壁看起來都十分堅硬，你敲打西邊的牆壁，聲音聽起來不太一樣，也許\\\這個
方向有什麼密門或機關。
LONG_TEXT
 ]) );
	ob->reset();
}
