// File: /d/noden/hawk/altar2.c
// Generated by Roommaker Sun Jan  9 07:54:22 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	object pontiff;

	::create();
	set_short("圓形祭壇");
	set_long( @C_LONG_DESCRIPTION
你現在來到了一個圓形的大祭壇，祭壇中央有一個圓形的洞穴(pit)，在洞穴四周
散佈著六個石桌(table)，最大的一個石桌上放著一個三角錐(prymaid)，環繞著祭壇總
共有二十四根白色石柱(pillars)，祭壇的東、北、西三個方向都被極高的懸崖峭壁所
繞，往南是一片空地。
C_LONG_DESCRIPTION
	);

	set_outside( "hawk" );
	set( "item_desc", ([ 
		"table" : "這些石桌有大有小，全部都是圓形，似乎是某種魔法陣的裝置。\n", 
		"prymaid" : @LONG_TEXT
這個三角錐是透明的，但又不是水晶或玻璃做的，它的一個平面正對著東方
太陽昇起的地方，祭壇四周二十四根石柱的影子映在三角錐內部，似乎排列
成什麼符號 ....
LONG_TEXT
, 
		"pillars" : @LONG_TEXT
這些石柱都是大理石做成的，有高有低，有粗有細，不知道當初建造這些石柱
的人為什麼要把它們做成這樣，難道有什麼機關 ....
LONG_TEXT
, 
		"pit" : @LONG_TEXT
這個洞穴深不見底，跳(jump)下去不知道會有什麼後果？你似乎隱約聽到洞穴
底部傳來一陣女人哭泣的嗚咽聲。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"south" : "/d/noden/hawk/altar1" ]) );

	// pontiff is unique, one reboot one pontiff
	pontiff = new("/d/noden/hawk/monster/pontiff");
	pontiff->move(this_object());

	set( "objects", ([
		"guard#1": "/d/noden/hawk/monster/altar_guard",
		"guard#2": "/d/noden/hawk/monster/altar_guard",
		"guard#3": "/d/noden/hawk/monster/altar_guard" ]) );

	reset();
}

int clean_up()
{
	// The pontiff is unique, so don't clean up this room.
	return 0;
}

void init()
{
   if( this_player() ) this_player()->set_explore("noden#23");
}
