// File: /d/noden/hawk/altar1.c
// Generated by Roommaker Sun Jan  9 04:16:40 1994

#include <mudlib.h>

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
	set_short("祭壇入口");
	set_long( @C_LONG_DESCRIPTION
你現在來到一座圓形祭壇前的入口，這座祭壇位於群山環抱的一個谷底，四周
全都是難以攀爬的懸崖峭壁，在你的東邊有一個生鏽的鐵門，地上零零散散地有幾
個腳印(footprints)，你注意到西邊的峭壁上垂下一根繩子(rope)，繩子高高地綁
在高處一棵長在峭壁間的樹上。
C_LONG_DESCRIPTION
	);

	set_outside( "hawk" );
	set( "item_desc", ([ 
		"rope" : @LONG_TEXT
這根繩子綁在這裡似乎已經很久了，你試著拉一拉試試重量，繩子發出一陣輕微
的「啪拉」斷裂聲，為了你的安全起見，最好別試著攀爬(climb)這根繩子。
LONG_TEXT
, 
		"footprints" : @LONG_TEXT
這些腳印有兩種，一種有四根腳趾，可能還帶有爪子，你猜大概是鳥人族所留下的
，另一種腳印要比鳥人族的大得多，有三根腳趾，看不出有沒有爪子，有些腳印上
似乎還有乾掉的血跡，也許這裡鳥人族曾和某種生物發生過戰爭。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/hawk/altar2",
		"east" : "/d/noden/hawk/cave" ]) );
	set( "pre_exit_func", ([
		"north": "check_guard" ]) );
	set( "objects", ([
		"guard#1" : "/d/noden/hawk/monster/altar_guard",
		"guard#2" : "/d/noden/hawk/monster/altar_guard",
		"guard#3" : "/d/noden/hawk/monster/altar_guard",
		"guard#4" : "/d/noden/hawk/monster/altar_guard" ]) );
	create_door( "east", "west", ([
		"keyword" : ({ "rusty iron door", "iron door", "door" }),
		"name" : "rusty iron door",
		"c_name" : "生鏽鐵門",
		"c_desc" : "一扇厚重的生鏽鐵門",
		"status" : "locked",
		"lock" : "HAWK_ALTAR_ENTRANCE"
	]) );
	reset();
}

int check_guard()
{
	if( present( "altar guard" ) ) {
		write(
		"祭壇守衛擋住你的去路，說道: 任何想侵犯神聖祭壇者，格—殺—勿—論！\n"
		);	
		return 1;
	}
}
