// File: /d/noden/hawk/crack2.c
// Generated by Roommaker Sun Jan  9 03:43:35 1994

#include <mudlib.h>
#include <move.h>

inherit ROOM;

int key_present = 1;

void create()
{
	::create();
	set_short("洞穴頂端");
	set_long( @C_LONG_DESCRIPTION
你現在正站在一個洞穴頂端突出的一塊岩石上，在你的北邊有一個小洞(hole)，你
可以感覺一股新鮮的空氣隨著小洞中吹進來的涼風灌了進來，這塊突出的岩石距離地面
 不遠，從這裡跳下去應該不會受傷。
C_LONG_DESCRIPTION
	);

	set( "item_desc", ([ 
		"hole" : @LONG_TEXT
你將眼睛湊進那個小洞，發現外面是一個懸崖壁上的平臺，平臺上赫然躺著一具
白色的骷髏(skeleton)！
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"jump" : "/d/noden/hawk/crack1" ]) );
	set( "item_func", ([
		"skeleton": "look_skeleton" ]) );
	reset();
}

void look_skeleton()
{
	object key;

	if( !key_present )
		write(
		    "一具早已被風沙侵蝕得脆弱不堪的骷髏，似乎是個鳥人的骸骨。\n"
		);
	else {
		write(@ALONG
你發現骷髏的手中握著一把鐵灰色的鑰匙，你伸手一探，將鑰匙從
骷髏手中取了下來。
ALONG
		);
		key_present = 0;
		key = new( "/d/noden/hawk/obj/altar_key" );
		if( (int)key->move(this_player()) != MOVE_OK )
			key->move( this_object() );
           this_player()->set_explore("noden#24");
	}
}
