// File: /d/noden/hawk/path4.c
// Generated by Roommaker Thu Jan  6 10:55:53 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("半山腰");
	set_long( @C_LONG_DESCRIPTION
你現在來到半山腰的一處平地，這裡雖然地勢較為平坦，但是草木仍然長得並不
很高，大概是土壤貧瘠的關係，南邊的平地上有幾間獵人用的小屋，東北邊一條狹窄
的石階坡道通往山下。
C_LONG_DESCRIPTION
	);

	set_outside( "hawk" );
	set( "exits", ([ 
		"northeast" : "/d/noden/hawk/path3", 
		"south" : "/d/noden/hawk/clearing" ]) );
	reset();
#include <replace_room.h>
}
