// File: /d/noden/tomb/tomb7.c
// Generated by Roommaker Mon Dec  4 19:34:27 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("墓穴");
	ob->set_long( @LONG_DESCRIPTION
你現在來到一個佈滿蜘蛛網的通道，厚厚的灰塵與一股令人窒息的屍臭味
令你不由得捏住了鼻子，兩邊的牆上畫滿了描述戰爭的壁畫(painting)，但是
由於年代過於久遠，已經剝落了大半。
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"mark" : "這個符號和洞口的蜘蛛符號一模一樣。\n", 
		"painting" : @LONG_TEXT
這些壁畫都餳描述一場激烈的戰爭，另一邊是許多紫色皮膚的人匍匐在一個
半人半蠍的怪物面前，那隻怪物的胸前有一個蜘蛛符號(mark)。
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/tomb/tomb8", 
		"west" : "/d/noden/tomb/tomb2" ]) );
	ob->reset();
}
