// File: /d/noden/tomb/tomb9.c
// Generated by Roommaker Mon Dec  4 19:35:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("墓室");
	ob->set_long( @LONG_DESCRIPTION
你現在來到一間幽暗的墓室，在你的正上方有一個開口，像是天井的洞，不
過望出去是黑黝黝的一片，不知道上面是什麼，這裡的空氣有點潮溼，還帶著一
股動物糞便的味道，你有一種奇異的感覺，好像地板下有許多小蟲在爬行。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/tomb/tomb2", 
		"north" : "/d/noden/tomb/tomb10" ]) );
	ob->reset();
}
