// File: /d/noden/tomb/tomb8.c
// Generated by Roommaker Mon Dec  4 19:34:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("墓室");
	ob->set_long( @LONG_DESCRIPTION
你現在來到一間狹小的墓室，四周的牆壁都是用粗糙的岩石砌成的，地上
還散落著幾堆凌亂的骨頭(bones)，只有中央一具骷髏(skeleton)是完整的，
墓室的頂部似乎有一些裂縫(crack)，透出一些微光，西邊的牆上有一個出口
通往外面。
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"bones" : "這些骨頭的形狀看起來像是人類，不過大部分都被打散了。\n", 
		"crack" : "這些裂縫太窄了，而且上面佈滿了青苔，連攀登都有困難。\n", 
		"skeleton" : @LONG_TEXT
這個骷髏正躺在地板上，胸前插著一把短劍(sword)，被他的兩隻手握著，也
許是自殺死的。
LONG_TEXT
, 
		"sword" : "這是一把長滿鐵鏽的短劍，插在骷髏心臟的部位。\n" ]) );
	ob->set( "exits", ([ 
		"west" : "/d/noden/tomb/tomb7" ]) );
	ob->set( "objects", ([ 
		"girl" : "/d/noden/tomb/monster/pink_girl" ]) );
	ob->reset();
}
