// File: /d/noden/tomb/tomb5.c
// Generated by Roommaker Mon Dec  4 19:33:48 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("墓中密室");
	ob->set_long( @LONG_DESCRIPTION
你現在站在一間圓形的石室中，石室的中央擺著一個石棺(coffin)，四周都是
一些陶罐(pot)、鐵箱(box)，從地上灰塵的厚度看起來，這裡至少有幾百年沒有人
來過了。
LONG_DESCRIPTION
	);

	ob->set( "c_item_desc", ([ 
		"box" : @LONG_TEXT
這些鐵箱中裝滿了衣服、香料和一些日用品，由於年代久遠，早已腐爛成一堆
亂七八糟的東西了。
LONG_TEXT
, 
		"coffin" : @LONG_TEXT
這個石棺約有三公尺長，一公尺寬，造形像一艘獨木舟，上面畫滿了許多人物
與野獸的圖案，蓋子和石棺之間不知道用什麼東西密封著，看來是不可能打開這
個石棺了。
LONG_TEXT
, 
		"pot" : "造型古樸的陶罐，上面有一圈一圈的紋路和狩獵的圖案。\n" ]) );
	ob->set( "exits", ([ 
		"south" : "/d/noden/tomb/tomb6" ]) );
	ob->set( "objects", ([ 
		"mummy" : "/d/noden/tomb/monster/mummy" ]) );
	ob->reset();
}
