// File: /d/noden/tomb/tomb3.c
// Generated by Roommaker Sun Dec 19 20:58:59 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
  set_short("墓穴");
	set_long( @LONG_DESCRIPTION
這裡似乎是放置陪葬品的地方，不過別高興，你看到一堆箱子罐子全都翻倒
在地上，顯然這裡已經被盜墓賊蒐括過了....四周的牆壁刻著不少動物、僕人以
及房舍，這裡埋葬的大概是位有錢人，中央的地板上有一個箱子(chest)似乎沒有
被開過，這些粗心的盜墓賊竟然忘了這個箱子....。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"chest" : @LONG_TEXT
這個箱子是關著的，箱子上的鎖早已因年代久遠而鏽蝕了，應該可以輕易打開。
LONG_TEXT
 ]) );
 	set( "search_desc", ([
 		"chest" : "它是關著的。\n" ]) );
	set( "exits", ([ 
		"south" : "/d/noden/tomb/tomb2" ]) );
	set( "objects", ([
		"skeleton": "/d/noden/tomb/monster/skeleton" ]) );
	reset();
}

void init()
{
	add_action( "do_open", "open" );
}

int do_open(string arg)
{
	if( !arg || arg!="chest" )
            return notify_fail( "打開什麼？\n" );
   write(
 "你快步走向那個箱子，突然，腳底下「喀拉」一聲輕響，你腳下的地板陷了下去！\n" );
    tell_room( this_object(),
 "你聽到「喀拉」一聲，一回頭，"+this_player()->query("c_cap_name")+"已經不見了蹤影....\n",
		this_player() );
	this_player()->move_player( "/d/noden/tomb/tomb4", "SNEAK" );
    tell_room( "/d/noden/tomb/tomb4",
 "你聽到"+this_player()->query("c_cap_name")+"像小孩子一般地尖叫著——從上面掉了下來。\n",
		this_player() );
	return 1;
}

