// File: /d/noden/tomb/tomb11.c
// Generated by Roommaker Tue Oct  4 10:25:22 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("洞穴");
	set_long( @LONG_DESCRIPTION
這是一個巨大的地底洞穴，和南邊的墓室比起來，很明顯地可以看出這裡
似乎不是人工建造出來的，石壁上滿是利爪抓出來的痕跡，也許有什麼兇猛的
地底野獸常在這裡打架。
LONG_DESCRIPTION
	);

	set( "exits", ([ 
		"south" : "/d/noden/tomb/tomb10" ]) );
   set( "objects", ([
        "centipede2" : "/d/noden/tomb/monster/small_centipede",
        "centipede" : "/d/noden/tomb/monster/centipede",
        "centipede3" : "/d/noden/tomb/monster/small_centipede",
   ]) );
	reset();
}
