// File: /d/noden/tomb/tomb1.c
// Generated by Roommaker Sun Dec 19 23:26:37 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("地下石穴");
	set_long( @LONG_DESCRIPTION
你現在來到一個狹窄的地下石穴，四周的牆壁是用一些石磚砌成的，地上佈滿
灰塵，角落裡一大堆蜘蛛網，你的第六感告訴你這曾經是一個墓穴，但是現在可能
已經被一大群蜘蛛霸佔為巢穴了。
LONG_DESCRIPTION
	);

	set( "exits", ([ 
		"north" : "/d/noden/tomb/tomb2", 
		"up" : "/d/noden/13,8.noden" ]) );
	set( "objects", ([ 
		"spider#1" : "/d/noden/tomb/monster/huge_spider", 
		"spider#2" : "/d/noden/tomb/monster/huge_spider" ]) );
	reset();
#include <replace_room.h>
}

