// File: /d/noden/tomb/tomb4.c
// Generated by Roommaker Sun Dec 19 21:37:18 1993

#include <mudlib.h>

inherit ROOM;
int mark = 0;

void create()
{
	::create();
   set_short("墓中密室");
	set_long( @LONG_DESCRIPTION
你現在終於明白為什麼剛才那個箱子沒有被人打開，因為從前試著打開它的人
現在正坐在你的四周——五具白骨，他們身上的衣服早已腐爛，但是你從散落在白
骨旁邊的鏟子、鐵鉤、繩索、等各種工具可以斷定這些人是盜墓賊。不過現在你沒
空去研究這些骷髏(skeleton)，因為看目前的情形，你不久也要加入他們了。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"skeleton" : @LONG_TEXT
這些骷髏或坐或躺，顯然是餓死在這裡的，他們所帶的揹包上有不少齒痕，大概
是餓得頭昏眼花的時候拿起來亂啃的。
LONG_TEXT
,
		"corner" : @LONG_TEXT
角落裡坐著一個骷髏，你發現他的手上似乎抓著一張字條(note)。
LONG_TEXT
,
		"note" : "「...	蜘蛛記號是貝塔爾人的傳送法術標記，只要用手觸摸(touch)...」\n",
		"wall" : "這裡的牆壁又冷又硬，沒有辦法往上爬回剛才的墓室....\n" ]) );
	set( "search_desc", ([ 
		"wall" : @LONG_TEXT
你不死心地繼續搜索牆壁上任何可疑的地方，但是什麼麼也沒有發現，不...
慢著....你覺得西南邊的牆角(corner)泥土好像比較鬆軟，也許可以挖出一條
通道逃出去！
LONG_TEXT
, 
		"here" : @LONG_TEXT
你在四周的石壁上仔細地找了一遍，並沒有發現任何密門或是按鈕，不過你
可以聽到東邊的牆壁(wall)傳來陣陣水聲，不知道是否有出路....
LONG_TEXT
 ]) );
	set( "item_func", ([
		"mark" : "look_mark",
		"dirt" : "look_dirt" ]) );
	set( "objects", ([
		"dagger" : "/d/noden/tomb/obj/dagger" ]) );
	reset();
}

void init()
{
	add_action( "do_dig", "dig" );
	add_action( "do_touch", "touch" );
}

int do_dig(string arg)
{
    if( !arg || arg!="corner" ) write(
            "你用手在腳下的泥土上亂挖，不久就碰到堅硬的石頭。\n" );
	else {
            write( 
"你向牆角鬆軟的泥土(dirt)挖掘下去，「啪」一聲不知道觸動了什麼開關....。\n" );
		mark = 1;
	}
    tell_room( this_object(),
    this_player()->query("c_name") + "在地上到處亂挖,企圖找出出口。\n",
		this_player() );
	return 1;
}

void look_dirt()
{
    if( !mark ) write(
            "這些泥土潮溼中帶著一故臭味....\n" );
    else write(
             "你看到挖開泥土旁的一塊石磚上面有一個蜘蛛的記號(mark)。\n" );
}

void look_mark()
{
    if( !mark ) write( 
             "你想看什麼？\n" );
    else write(
         "一個蜘蛛形狀的記號，不知道用來幹什麼，如果這些盜墓賊還活著的話\n"
         "也許會知道....\n" );
}

int do_touch(string arg)
{
	if( !arg || !mark || arg!="mark" )
            return notify_fail( "觸摸什麼？\n" );
   write(
		"你用手觸摸蜘蛛標誌，一陣奇異的感覺從標誌上傳來，等你定下神來，發現\n"
            "周圍的景物已經變了！\n" );
	this_player()->move_player("/d/noden/tomb/tomb5", "SNEAK");
   this_player()->set_explore("noden#22");
	return 1;
}
