// File: /d/noden/tomb/tomb6.c
// Generated by Roommaker Sun Dec 19 22:55:09 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("墓中密室");
	set_long( @LONG_DESCRIPTION
這間石室比北邊的房間略小，但是佈置著許多石制的傢俱(furniture)，要不
是這裡是個墓穴，這樣的佈置可算是應有盡有，十分舒適的住所了。你注意到石室
中央的地毯(carpet)中間向下凹，可能有些古怪....。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"furniture" : "這些傢俱雖然年代久遠，但是上面都刻滿精細的花紋，看起來質地相當昂貴。\n" ]) );
	set( "item_func", ([
		"carpet": "look_carpet" ]) );
	set( "exits", ([ 
		"north" : "/d/noden/tomb/tomb5" ]) );
	set( "objects", ([
		"spider#1": "/d/noden/tomb/monster/red_spider",
		"spider#2": "/d/noden/tomb/monster/red_spider"]) );
	reset();
}

void look_carpet()
{
   write(
		"這張地毯上面繡著兩個並肩而行的獵人，手上提著....你一腳踩上地毯，卻踩了個\n"
            "空，這張地毯是個幻影！\n" );
    tell_room( this_object(),
        "你聽到"+this_player()->query("c_cap_name") + "一聲驚叫，轉過頭去人已經不見了。\n",
		this_player() );
	this_player()->move_player( "/d/noden/tomb/tomb2", "SNEAK" );
   this_player()->set_explore("noden#20");
    tell_room( "/d/noden/tomb/tomb2",
             "你聽到有人大聲驚叫，然後一個影子掉下來，差一點壓到你....\n",
		this_player() );
}
