// File: /d/noden/tomb/tomb10.c
// Generated by Roommaker Tue Oct  4 10:22:15 1994

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
   set_short("墓室");
	set_long( @LONG_DESCRIPTION
這裡是一條狹窄的通道，地上鋪滿了腐爛的葉子，一股動物糞便的味道
使你不由得捏住了鼻子，兩邊的牆壁長滿了白色的苔蘚，中間夾著幾道不知
從哪裡流下來的逕流，你注意到地上似乎有一些泥濘的腳印(footprints)，
通往南邊的房間。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"footprints" : "這些腳印印在落葉上，形狀已經十分模糊了，不知道是什麼生物留下的。\n" ]) );
	set( "exits", ([ 
		"north" : "/d/noden/tomb/tomb11", 
		"south" : "/d/noden/tomb/tomb9" ]) );
	reset();
}
