// File: /d/noden/tomb/tomb2.c
// Generated by Roommaker Wed Jan 11 11:40:52 1995

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("墓穴");
	set_long( @LONG_DESCRIPTION
你現在來到一處較為寬敞的方形石室，牆壁上有幾個斑駁鏽蝕的鐵架，上面
插著幾根早已熄滅的火把(torch)，地上積滿了厚重的灰塵，這裡的蜘蛛網(web)
幾乎蓋滿了天花板與牆角，往北是一座往下的石階，東邊和西邊原來好像有通道
，但是現在都被蜘蛛網蓋滿了，看起來充滿危險。
LONG_DESCRIPTION
	);

	set( "c_item_desc", ([ 
		"web" : @LONG_TEXT
一堆灰白色、掛滿灰塵的蜘蛛網，和你平常所見的蜘蛛網相比，這些蜘蛛網顯
然要大得多了，如果你有一把鋒利的斧頭，也許能砍(hack)出一條通路。
LONG_TEXT
, 
		"torch" : @LONG_TEXT
這些火把不知道已經熄滅了幾百年，上面不但積滿灰塵，還有許多蛀蟲的孔動
，你發現其中一根火把上的灰塵上隱隱有一個手印，難道....
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/tomb/tomb3", 
            "south" : "/d/noden/tomb/tomb1" ]) );
	set( "objects", ([ 
		"spider#3" : "/d/noden/tomb/monster/huge_spider", 
		"spider#1" : "/d/noden/tomb/monster/black_spider", 
		"spider#2" : "/d/noden/tomb/monster/black_spider" ]) );
	reset();
}

void init()
{
   add_action( "do_pull", "pull" );
   add_action( "do_hack", "hack" );
}

int do_pull(string arg)
{
   if( !arg || arg!="torch" )
   return notify_fail( "拉什麼?\n" );
   if ( !query("exits/west") ) {
      tell_object( this_player(),
     "你聽到隆的一聲, 西邊突然出現一個出口!\n" );
      set( "exits/west", "/d/noden/tomb/tomb9" );
      return 1;
   }
   tell_object( this_player(),
      "你聽到隆的一聲, 西邊的出口關上了!\n" );
   delete( "exits/west", "/d/noden/tomb/tomb9" );
   return 1;
}

int do_hack(string arg)
{
   if( !arg || arg!="web" )
   return notify_fail( "砍什麼?\n" );
   if( !present("axe", this_player()) )
   return notify_fail( "你沒有斧頭來砍。\n" );
   if( present("axe",this_player()) ) {
   tell_object( this_player(),
      "你拿起斧頭劈開蜘蛛網, 東邊的通道被你打開了!\n" );
   set( "exits/east", "/d/noden/tomb/tomb7" );
   this_player()->set_explore("noden#21");
   return 1;
   }
}

void reset()
{
        delete("exits/east");
        delete("exits/west");
        ::reset();
}
