// File: /d/noden/forest/1n.c
// Generated by Roommaker Mon Dec  4 21:15:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑森林");
	ob->set_long( @LONG_DESCRIPTION
這裡是陰森的黑森林。如它的名字一般, 在這裡的樹木枝葉異常地茂
密, 即使是正午猛烈的陽光也絲毫無法照射到這裡的地面。據傳說, 這是
由於受到魔族邪惡魔法的影響, 以致於森林中的一草一木、小動物們都變
成邪惡的黑暗生物。
LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"north", 
		"south" }) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/forest/1n1e", 
		"west" : "/d/noden/forest/1n1w", 
		"south" : "/d/noden/forest/entry", 
		"north" : "/d/noden/forest/2n" ]) );
	ob->reset();
}
