// File: /d/noden/forest/1n2e.c
// Generated by Roommaker Mon Dec  4 21:15:53 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑森林深處");
	ob->set_long( @LONG_DESCRIPTION
依然是枝葉茂密的樹木, 與不知道底有多厚的腐葉。這裡是黑森林的
深處, 一股危險的氣氛正籠罩著你的四周。
    你感覺在雜密的樹木後面, 有某些東西正在注視著你。
LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"west" }) );
	ob->set( "exits", ([ 
		"west" : "/d/noden/forest/1n1e" ]) );
	ob->set( "objects", ([ 
		"goblin2" : "/d/noden/forest/monster/goblin", 
		"goblin1" : "/d/noden/forest/monster/goblin" ]) );
	ob->reset();
}
