// File: /d/noden/forest/2n1e.c
// Generated by Roommaker Mon Dec  4 21:16:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑森林");
	ob->set_long( @LONG_DESCRIPTION
這裡是陰森的黑森林。如它的名字一般, 這個森林的樹木異常地茂密
, 使得無論多麼強烈的陽光都完全無法穿透進來。據傳說, 這是受到魔族
邪惡魔法的影響, 森林中的一草一木、小動物們都變成邪惡的黑暗生物。
    此外, 許多傳言指出此地有著前往魔族古帝國的秘密通道。
LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"south" }) );
	ob->set( "exits", ([ 
		"south" : "/d/noden/forest/1n1e", 
		"northeast" : "/d/noden/forest/3n2e" ]) );
	ob->reset();
}
