// File: /d/noden/forest/2n2w.c
// Generated by Roommaker Mon Dec  4 21:16:36 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("黑森林");
	ob->set_long( @LONG_DESCRIPTION
這裡是邪惡的黑森林, 黑暗無聲無息地籠罩著你的四周, 不祥的強大
魔力正在樹蔭下的空氣中湯漾著。恐怖、不悅的氣氛無時無刻不在, 強烈
地刺激著你的神經。在你的附近, 有些殘餘物零零落落地散成一堆, 看來
格外地噁心。
LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"southeast" }) );
	ob->set( "exits", ([ 
		"north" : "/d/noden/forest/3n2w", 
		"southeast" : "/d/noden/forest/1n1w" ]) );
	ob->set( "objects", ([ 
		"ammunt" : "/d/noden/forest/monster/ammunt" ]) );
	ob->reset();
}
