// File: /d/noden/forest/3n2e.c
// Generated by Roommaker Mon Dec  4 21:17:11 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("林中空地");
	ob->set_long( @LONG_DESCRIPTION
很難得地, 這邊竟然有一塊空地, 那些帶有邪氣的樹木完全不敢將他
們的枝葉伸進這空地一步。不過這好像不是什麼值得高興的事, 因為在空
地的中心, 長了一棵很高, 很老, 很邪惡的樹。
LONG_DESCRIPTION
	);

	ob->set( "exit_suppress", ({ 
		"southwest" }) );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/forest/2n1e" ]) );
	ob->set( "item_desc", ([ 
		"tree" : "這棵樹上下充滿著邪氣, 使你不由得擔心它什麼時候會突然向你發動\n攻擊。\n" ]) );
	ob->set( "objects", ([ 
		"reaper2" : "/d/noden/forest/monster/reaper", 
		"reaper1" : "/d/noden/forest/monster/reaper" ]) );
	ob->reset();
}
