// File: /d/noden/elf/elf/elf11.c
// Generated by Roommaker Mon Dec  4 21:41:48 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石板路");
	ob->set_long( @LONG_DESCRIPTION
這是一條用石板鋪成的路，路的兩旁是精靈屋及綠意盎然的植道樹，
石板上刻著精靈族的標幟(mark)，很有規律地向前延伸。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/elf/elf/elf5", 
		"north" : "/d/noden/elf/elf/elf16", 
		"south" : "/d/noden/elf/elf/elf15", 
		"west" : "/d/noden/elf/elf/elf18" ]) );
	ob->set( "item_desc", ([ 
		"mark" : "這標誌是一個帶著桂花冠的天馬\n" ]) );
	ob->reset();
}
