// File: /d/noden/elf/elf/elf17.c
// Generated by Roommaker Mon Dec  4 21:45:05 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("木精靈工作室");
	ob->set_long( @LONG_DESCRIPTION
"這是一個充滿木屑和雕像的房間，可能是為了通風方便，四面牆上都有巨大
的落地窗，房子的正中央放了一張很大的工作桌，桌上放著幾件未完成的作品
，左側角落放著幾支散落的酒瓶，由房子架設的情況看來，此屋子的主人必定
是一位有酒癮的工作狂。"
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"down" : "/d/noden/elf/elf/elf7" ]) );
	ob->set( "objects", ([ 
		"icers" : "/d/noden/elf/monster/wind" ]) );
	ob->reset();
}
