// File: /d/noden/elf/elf/elf8.c
// Generated by Roommaker Mon Dec  4 21:59:39 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("精靈屋");
	ob->set_long( @LONG_DESCRIPTION
這裡是精靈小屋在屋子的北方有一張用杉木製成的書桌，及一
張用石頭做的椅子，西邊是一面掛滿圖畫南面有一張鋪著繡有精靈
族圖案被子的床，南方有一個大窗戶，從窗戶望出去是一片翠綠的
草原，從微風輕送來的空氣中，傳來一股似有似無的香味，使你精
神一振。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/noden/elf/elf/elf5" ]) );
	ob->set( "objects", ([ 
		"lady1" : "/d/noden/elf/monster/lady", 
		"lady2" : "/d/noden/elf/monster/lady" ]) );
	ob->reset();
}
