// File: /d/noden/elf/elf/elf15.c
// Generated by Roommaker Mon Dec  4 21:43:54 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("精靈屋");
	ob->set_long( @LONG_DESCRIPTION
這裡是精靈小屋在屋子的北方有一張用杉木製成的書桌，
及一張用石頭做的椅子，西邊是一面掛滿圖畫南面有一張鋪
著繡有精靈族圖案被子的床，南方有一個大窗戶，從窗戶望
出去是一片翠綠的草原，從微風輕送來的空氣中，傳來一股
似有似無的香味，使你精神一振。

LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/noden/elf/elf/elf11" ]) );
	ob->set( "objects", ([ 
		"elf1" : "/d/noden/elf/monster/elf", 
		"elf2" : "/d/noden/elf/monster/elf" ]) );
	ob->reset();
}
