// File: /d/noden/elf/elf/elf43.c
// Generated by Roommaker Mon Dec  4 21:53:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞");
	ob->set_long( @LONG_DESCRIPTION
 此處是一個原始迷宮，當前次魔族入侵時，精靈們曾引誘一些魔族戰士進入此
 迷宮，從此以後每逢月圓之夜，迷宮中總是傳來陣陣淒厲的吼叫聲，精靈族人
 把此處畫為禁地，嚴禁族人進入，經過多年時光的演變，此處已變成無人的死
 域。      
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/elf/elf/elf36", 
		"west" : "/d/noden/elf/elf/elf43", 
		"north" : "/d/noden/elf/elf/elf44", 
		"south" : "/d/noden/elf/elf/elf39" ]) );
	ob->set( "objects", ([ 
		"minotajus" : "/d/noden/elf/monster/minota" ]) );
	ob->reset();
}
