// File: /d/noden/elf/elf/elf35.c
// Generated by Roommaker Mon Dec  4 21:51:20 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("地洞");
	ob->set_long( @LONG_DESCRIPTION
 往南走是一個原始迷宮，當前次魔族入侵時，精靈們曾引誘一些魔族戰士
 進入此迷宮，從此以後每逢月圓之夜，迷宮中總是傳來陣陣淒厲的吼叫聲，精
 靈族人把此處畫為禁地，嚴禁族人進入，經過多年時光的演變，此處已變成無
 人的死域。      
LONG_DESCRIPTION
	);

	ob->set( "light", 0 );
	ob->set( "exits", ([ 
		"climb" : "/d/noden/elf/elf/elf2", 
		"south" : "/d/noden/elf/elf/elf37" ]) );
	ob->reset();
}
