// File: /d/noden/elf/elf/elf20.c
// Generated by Roommaker Mon Dec  4 21:45:46 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("長老之屋");
	ob->set_long( @LONG_DESCRIPTION
這裡是精靈小屋在屋子的北方有一張用杉木製成的書桌，及一張用
石頭做的椅子，東邊是一面掛滿圖畫的牆，西面有一個大書架(bookshelf)
，同時你也看見在架子旁有幾個大木箱，南面有一張鋪著繡有精靈族圖案被
子的床，南方有一個大窗戶，從窗戶望出去是一片翠綠的草原，從微風輕送
來的空氣中，傳來一股似有似無的香味，使你精神一振。

LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/d/noden/elf/elf/elf18" ]) );
	ob->set( "objects", ([ 
		"elf elder" : "/d/noden/elf/monster/elder" ]) );
	ob->reset();
}
