// File: /d/noden/elf/elf/elf26.c
// Generated by Roommaker Mon Dec  4 21:47:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草原");
	ob->set_long( @LONG_DESCRIPTION
這裡是一望無際的大草原(plain)，你的眼前有一些草叢(bushes)肅立著，
有無數野牛腳印散落地面，遍地的青草有被撕咬過的痕跡，而草叢中時而傳
來陣陣牛鳴聲，你想這附近大概有野牛的巢穴。
LONG_DESCRIPTION
	);

	ob->set_outside( "elf_hamlet" );
	ob->set( "exits", ([ 
		"west" : "/d/noden/elf/elf/elf29", 
		"south" : "/d/noden/elf/elf/elf28", 
		"northeast" : "/d/noden/elf/elf/elf25" ]) );
	ob->set( "item_desc", ([ 
		"plain" : @LONG_TEXT
這裡長滿著青翠的小草，幾叢灌木孤獨地聳立著，雖然此處看起來
十分平靜，但是據說附近常有野獸出沒，故而此處是精靈們的狩
獵場。
LONG_TEXT
, 
		"bushes" : "這些草叢長滿荊棘你應該不能通過(pass)它\n" ]) );
	ob->set( "objects", ([ 
		"buffalo" : "/d/noden/elf/monster/buffalo" ]) );
	ob->reset();
}
