// File: /d/noden/elf/elf/elf21.c
// Generated by Roommaker Mon Dec  4 21:46:00 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草原");
	ob->set_long( @LONG_DESCRIPTION
這裡是一望無際的大草原(plain)。
LONG_DESCRIPTION
	);

	ob->set_outside( "elfhamlet" );
	ob->set( "c_item_desc", ([ 
		"plain" : @LONG_TEXT
這裡長滿著青翠的小草，幾叢灌木孤獨地聳立著，雖然此處看起來
十分平靜，但是據說附近常有野獸出沒，故而此處是精靈們的狩
獵場。
LONG_TEXT
 ]) );
	ob->set( "exits", ([ 
		"east" : "/d/noden/elf/elf/elf12", 
		"west" : "/d/noden/elf/elf/elf24" ]) );
	ob->reset();
}
