// File: /d/noden/elf/elf/elf19.c
// Generated by Roommaker Mon Dec  4 21:45:23 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("精靈屋");
	ob->set_long( @LONG_DESCRIPTION
這裡是精靈小屋在屋子的北方有一張用杉木製成的書桌，
及一張用石頭做的椅子，西邊是一面掛滿圖畫南面有一張鋪著
繡有精靈族圖案被子的床，而在空氣中傳來一股似有似無的香
味，使你精神一振。

LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/elf/elf/elf18" ]) );
	ob->set( "objects", ([ 
		"little3" : "/d/noden/elf/monster/child", 
		"little2" : "/d/noden/elf/monster/child", 
		"little1" : "/d/noden/elf/monster/child" ]) );
	ob->reset();
}
