// File: /d/noden/elf/elf/elf25.c
// Generated by Roommaker Mon Dec  4 21:46:59 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草原");
	ob->set_long( @LONG_DESCRIPTION
這裡是一望無際的大草原(plain)，呈現在你面前的是一個大池塘，池邊
長著無數的蘆葦草，同時幾株野蓮正疏落有致地散落池面，附近有很多動物
雜亂的腳印，你想此處必是動物取水的地方。
LONG_DESCRIPTION
	);

	ob->set_outside( "elf_hamlet" );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/elf/elf/elf26", 
		"east" : "/d/noden/elf/elf/elf24", 
		"west" : "/d/noden/elf/elf/elf27" ]) );
	ob->set( "item_desc", ([ 
		"plain" : @LONG_TEXT
這裡長滿著青翠的小草，幾叢灌木孤獨地聳立著，雖然此處看起來
十分平靜，但是據說附近常有野獸出沒，故而此處是精靈們的狩
獵場。
LONG_TEXT
 ]) );
	ob->reset();
}
