// File: /d/noden/elf/elf/elf4.c
// Generated by Roommaker Mon Dec  4 21:59:02 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("精靈屋");
	ob->set_long( @LONG_DESCRIPTION
這裡是精靈小屋在屋子的北方有一張用杉木製成的書桌，及
一張用石頭做的椅子，西邊是一面掛滿圖畫南面有一張鋪著繡有
精靈族圖案被子的床，而在空氣中傳來一股似有似無的香味，使
你精神一振。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"south" : "/d/noden/elf/elf/elf2.c" ]) );
	ob->set( "objects", ([ 
		"elf" : "/d/noden/elf/monster/elf" ]) );
	ob->reset();
}
