// File: /d/noden/elf/elf/elf1.c
// Generated by Roommaker Mon Dec  4 21:40:22 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("精靈村入口");
	ob->set_long( @LONG_DESCRIPTION
在你的眼前是一排排杉木製成的房屋，而村前有一個大廣場，
一群小精靈正在那裡嬉戲著，村旁是一片青翠的草原，有一
條小溪潺潺的流過，有幾隻牛羊正在溪邊淺嘗溪水，櫬著遠
方的青山，彷如一處世外桃源。
LONG_DESCRIPTION
	);

	ob->set_outside( "elfhamlet" );
	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"west" : "/d/noden/elf/elf/elf2.c", 
		"north" : "d/noden/16,18.noden" ]) );
	ob->set( "objects", ([ 
		"guard2" : "/d/noden/elf/monster/guard", 
		"guard1" : "/d/noden/elf/monster/guard" ]) );
	ob->reset();
}
