// File: /d/noden/elf/elf/elf46.c
// Generated by Roommaker Mon Dec  4 21:54:03 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草原");
	ob->set_long( @LONG_DESCRIPTION
這裡是一望無際的大草原，有無數的動物生長在這裡，有幾株矮灌木孤零零的
立著，這裡的植物都是非常適合小動物生長，有可以躲避的半人高芒草及荊棘
叢，有柔細可口的牧草，真是小動物的天堂。
LONG_DESCRIPTION
	);

	ob->set_outside( "elfhamlat" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/elf/elf/elf45", 
		"south" : "/d/noden/elf/elf/elf47.c" ]) );
	ob->set( "objects", ([ 
		"rabbit3" : "/d/noden/elf/monster/rabbit", 
		"rabbit2" : "/d/noden/elf/monster/rabbit", 
		"rabbit1" : "/d/noden/elf/monster/rabbit" ]) );
	ob->reset();
}
