// File: /d/noden/elf/elf/elf13.c
// Generated by Roommaker Mon Dec  4 21:42:14 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草原");
	ob->set_long( @LONG_DESCRIPTION
這裡是一座小山丘，由此處望去四周的風景都盡在眼底，北方的精靈村
依稀可見，西方的草原一直延伸到天際，南方的小河清澈美麗。山丘的東方
好像有一個洞穴。
LONG_DESCRIPTION
	);

	ob->set_outside( "elfhamlet" );
	ob->set( "exits", ([ 
		"west" : "/d/noden/elf/elf/elf14", 
		"north" : "/d/noden/elf/elf/elf6" ]) );
	ob->set( "item_desc", ([ 
		"plain" : @LONG_TEXT
這裡長滿著青翠的小草，幾叢灌木孤獨地聳立著，雖然此處看起來
十分平靜，但是據說附近常有野獸出沒，故而此處是精靈們的狩
獵場。
LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"wolf" : "/d/noden/monster/wolf" ]) );
	ob->reset();
}
