// File: /d/noden/elf/elf/elf29.c
// Generated by Roommaker Mon Dec  4 21:50:00 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草原");
	ob->set_long( @LONG_DESCRIPTION
這裡是大草原(plain)的盡頭，你的眼前是浩瀚的大海，而白色的沙灘上
鋪有細細的柔沙，草原緊連著沙灘，使得眼前得景色美麗如詩，有無數野牛
腳印散落地面，遍地的青草有被撕咬過的痕跡，而草叢中時而傳來陣陣牛鳴
聲，你想這附近大概有野牛的巢穴。
LONG_DESCRIPTION
	);

	ob->set_outside( "elf_hamlet" );
	ob->set( "exits", ([ 
		"east" : "/d/noden/elf/elf/elf26" ]) );
	ob->set( "item_desc", ([ 
		"plain" : @LONG_TEXT
這裡長滿著青翠的小草，幾叢灌木孤獨地聳立著，雖然此處看起來
十分平靜，但是據說附近常有野獸出沒，故而此處是精靈們的狩
獵場。
LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"buffalo2" : "/d/noden/elf/monster/buffalo", 
		"buffalo1" : "/d/noden/elf/monster/buffalo" ]) );
	ob->reset();
}
