// File: /d/noden/elf/elf/elf22.c
// Generated by Roommaker Mon Dec  4 21:46:08 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草原");
	ob->set_long( @LONG_DESCRIPTION
這裡是一望無際的大草原(plain)，有無數的動物生長在這裡，你的眼前
有一些草叢(bushes)肅立著，一條小河從草原的南方緩緩的流過
LONG_DESCRIPTION
	);

	ob->set_outside( "elfhamlet" );
	ob->set( "exits", ([ 
		"north" : "/d/noden/elf/elf/elf14", 
		"west" : "/d/noden/elf/elf/elf23" ]) );
	ob->set( "item_desc", ([ 
		"plain" : @LONG_TEXT
這裡長滿著青翠的小草，幾叢灌木孤獨地聳立著，雖然此處看起來
十分平靜，但是據說附近常有野獸出沒，故而此處是精靈們的狩
獵場。
LONG_TEXT
, 
		"bushes" : "這些草叢長滿荊棘你應該不能通過(pass)它\n" ]) );
	ob->reset();
}
