// File: /d/noden/elf/elf/elf6.c
// Generated by Roommaker Mon Dec  4 21:59:23 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("草原");
	ob->set_long( @LONG_DESCRIPTION
這裡是一望無際的大草原(plain)，有無數的動物生長在這裡，南方有一座
小山丘，西方一眼望去盡是連綿的草原，同時此地偶而傳來狼嚎聲，你想附近必
定有狼的巢穴。
LONG_DESCRIPTION
	);

	ob->set_outside( "elfhamlet" );
	ob->set( "exits", ([ 
		"southwest" : "/d/noden/elf/elf/elf14.c", 
		"west" : "/d/noden/elf/elf/elf12.c", 
		"north" : "/d/noden/elf/elf/elf3.c", 
		"south" : "/d/noden/elf/elf/elf13.c" ]) );
	ob->set( "item_desc", ([ 
		"plain" : @LONG_TEXT
這裡長滿著青翠的小草，幾叢灌木孤獨地聳立著，雖然此處看起來
十分平靜，但是據說附近常有野獸出沒，故而此處是精靈們的狩
獵場。
LONG_TEXT
 ]) );
	ob->reset();
}
