// File: /d/noden/elf/elf/elf32.c
// Generated by Roommaker Mon Dec  4 21:50:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("樹洞");
	ob->set_long( @LONG_DESCRIPTION
  這裡是一個樹洞房間，有一張大桌子擺在房子的中間，幾張椅子
  整齊的排放著，牆上有幾隻大火把，使整個房間明亮如晝。北邊有一
  間漂亮的洞中屋。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"out" : "/d/noden/elf/elf/elf31", 
		"north" : "/d/noden/elf/elf/elf33" ]) );
	ob->set( "objects", ([ 
		"guard2" : "/d/noden/elf/monster/guard", 
		"guard1" : "/d/noden/elf/monster/guard" ]) );
	ob->reset();
}
