// File: /u/l/layuter/elf/elf18.c
// Generated by Roommaker Thu Nov 18 13:33:19 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("石板路");
	set_long( @LONG_DESCRIPTION
這是一條用石板鋪成的路，路的兩旁是精靈屋及綠意盎然的植
道樹，石板上刻著精靈族的標幟(mark)，很有規律地向前延伸。在
此刻你正走到路的盡頭，在你眼前有一棵巨大的樹(tree)，高聳的
向天際拔升，在樹旁有一個豎立的招牌。
LONG_DESCRIPTION
	);
    set("item_desc",([
        "mark" : "這標誌是一個帶著桂花冠的天馬\n",
        "tree" : @TREE
  這是一棵高聳入天的樹，你注意到它有一些樹枝(branch)低垂，
  你好像可以爬上這些樹枝。
TREE
]));            
	set( "light", 1 );
	set( "exits", ([
		"south" : LELF"elf20",
		"north" : LELF"elf19",
		"east" : LELF"elf11"
	]) );
}

void init()
{
    add_action("do_climb","climb");
 }
 
int do_climb(string arg)
{ 
 if (!arg || arg!="branch") return 0;
 this_player()->move_player(LELF"elf31","SNEAK");
 tell_room(this_object(), this_player()->query("c_name")+"爬上樹枝\n",this_player());
 return 1;
 }

