// File: /u/l/layuter/elf/elf2.c
// Generated by Roommaker Thu Nov 11 16:10:41 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
        ::create();
        set_short("A empty room", "精靈村廣場");
        set_long( @LONG_DESCRIPTION
，這是一個用大理石沏成的廣場，廣場中央是一個噴水池(fountain)
，池旁是一坐巨大的雕像(statue)，天空中有幾隻和平鴿(dove)在盤旋著
，有幾棵百年老樹(tree)高大地遮蔽過往的行人。
LONG_DESCRIPTION
        );
        
    set("c_item_desc",([
       "fountain" : "這水池的水既清澈又冰涼，是精靈們的主要水源。\n",
       "dove" : "這是一種白色的鳥類，看起來十分的溫馴。\n",
       "tree" : "這樹看起來十分的高大，以你的能力似乎無法爬上去(climb)。\n",
       "statue": @STATUE
 這雕像是一座巨大的女神像，在神像的下方有一個告示版(board)，
 當你注視此神像時，你發現神像的右手好像特別乾淨。      
STATUE
,
       "hand" : "這手的位置太高，你僅能勉強的拉動它。\n",
       "board" : @BOARD
這是精靈村守護神`希納斯'的神像，她曾經幫助精靈們抵抗魔族的侵略，
因此他成為了此村的守護神。希納斯的神性是愛與和平，故而在她的感化
之下，精靈村的精靈們都有著善良的習性與好客的脾氣。
BOARD
       ]));
    set("objects",([
        "little1" : "/d/noden/elf/monster/child",
        "little2" : "/d/noden/elf/monster/child",
        "dove" : "/d/noden/elf/monster/dove",
        ]));   
        set( "light", 1 );
   set( "exits", ([
        "east" : "/d/noden/elf/elf/elf1",
        "south" : "/d/noden/elf/elf/elf3",
        "north" : "/d/noden/elf/elf/elf4",
        "west" : "/d/noden/elf/elf/elf5",
     ]) );
        reset();
}

void init()
{
    add_action("do_pull","pull");
}

int do_pull(string arg)
{  
    if( !arg || arg != "hand" ) return 0;
    tell_room(this_object(),"地板上突然出現一個地洞,"+
        this_player()->query("c_name")+"掉入洞中，而地板卻立刻恢復原狀。\n",
        this_player());
   this_player()->set_explore("noden#31");
   this_player()->move_player("/d/noden/elf/elf/elf35","SNEAK");
    return 1;
}
