// File: /u/l/layuter/elf/elf24.c
// Generated by Roommaker Sat Nov 20 04:07:52 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("地洞");
	set_long( @LONG_DESCRIPTION
 此處是一個原始迷宮，當前次魔族入侵時，精靈們曾引誘一些魔族戰士進入此
 迷宮，從此以後每逢月圓之夜，迷宮中總是傳來陣陣淒厲的吼叫聲，精靈族人
 把此處畫為禁地，嚴禁族人進入，經過多年時光的演變，此處已變成無人的死
 域。      
LONG_DESCRIPTION
	);	
	set("objects",([
	    "fighter":LMONSTER"fighter",
	    "fighter1":LMONSTER"fighter" ]));
	set( "light", 0);
	set("exits",([
	    "south" : LELF"elf38",
	    "north" : LELF"elf40",
	    "east" : LELF"elf41",
	    "west" : LELF"elf40"]));
	    reset();
}
