// File: /u/l/layuter/elf/elf24.c
// Generated by Roommaker Sat Nov 20 04:07:52 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("樹枝");
	set_long( @LONG_DESCRIPTION
你現在是位於濃密的樹叢中，從樹叢的隙縫中，你發現一個大樹洞(hole)
，好像有一些火光從其中透出。
LONG_DESCRIPTION
	);	
	set("item_desc",([
	    "hole" : "這是一個大樹洞，看起來應該有足夠的空間可以進入(enter)它。\n"]));
	set( "light", 0);
	set("exits",([
	    "down" : LELF"elf18"]));
}
void init()
{
  add_action("do_enter","enter");
  }
 
int do_enter(string arg)
{
    if(!arg || arg!="hole") return 0;
    this_player()->move_player(LELF"elf32","SNEAK");
    tell_room(this_object(),this_player()->query("c_name")+" 進入洞穴中 \n",this_player());
    return 1;
    } 
