// File: /u/l/layuter/elf/elf24.c
// Generated by Roommaker Sat Nov 20 04:07:52 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("草原");
	set_long( @LONG_DESCRIPTION
這裡是草原和森林的交界處,眼前是一片鬱郁蒼蒼的密林，林中
時而傳來鳥獸的叫聲,從此處望去林中是一片翠綠，你有想進入
森林的衝動，可惜你找不到小路可以進入。
LONG_DESCRIPTION
	);
	set("objects",([
	    "unicon" : LMONSTER"unicorn"]));	    
    set_outside("elfhamlat");
	set( "exits", ([
		"leave" : LELF"elf30"
	]) );
	reset();
}
