// File: /u/l/layuter/elf/elf24.c
// Generated by Roommaker Sat Nov 20 04:07:52 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("草原");
	set_long( @LONG_DESCRIPTION
這裡是一望無際的大草原(plain)，有無數的動物生長在這裡，你的眼前
有一些草叢(bushes)肅立著。此地有一些小灌木生長著，同時地上還有數十個
小地洞(cellar)。
LONG_DESCRIPTION
	);
    set("item_desc",([
     "cellar" : "這些地洞很小，像是土撥鼠的巢穴。\n",
     "bushes" : "這些草叢長滿雜草你應該能通過(pass)它\n",
     "plain" : @Plain
這裡長滿著青翠的小草，幾叢灌木孤獨地聳立著，雖然此處看起來
十分平靜，但是據說附近常有野獸出沒，故而此處是精靈們的狩
獵場。
Plain
      ]));
	set("exits",([
	      "north" : LELF"elf24"
	      ]));
    set_outside("elfhamlat");
	set("objects",([
          "marmot1" : LMONSTER"marmot",         
          "marmot2" : LMONSTER"marmot",
          "marmot3" : LMONSTER"marmot",
          "marmot4" : LMONSTER"marmot",
          "marmot5" : LMONSTER"marmot"
	     ]));
	reset();
}

void init()
{
  add_action("do_pass","pass");
  }
  
int do_pass(string arg)
{
   if (!arg || arg!="bushes") return 0;
   this_player()->move_player(LELF"elf45","SNEAK");
   this_player()->set_explore("noden#30");
   tell_room(this_object(),
	this_player()->query("c_name")+"進入草叢中。\n"
      ,this_player());
   return 1;
 }
