// File: /u/l/layuter/elf/elf24.c
// Generated by Roommaker Sat Nov 20 04:07:52 1993

#include "../layuter.h"

inherit ROOM;

void create()
{
	::create();
	set_short("地洞");
	set_long( @LONG_DESCRIPTION
 此處是一個原始迷宮深處的一個房間，這裡的擺設和平常人的一樣，有一個大桌子
 ，而有幾張小椅子隨處散置著，一張木床閒置在角落，但奇怪的是這間房子在四面
 牆上都有一個大窗戶，你想屋主一定是個膽小的人。 
LONG_DESCRIPTION
	);	
	set( "light", 0);
	set("exits",([
	    "south" : LELF"elf43"]));
	set("objects",([
	    "thiris" : LMONSTER"steal",
	    "fighter1": LMONSTER"fighter",
	    "fighter2": LMONSTER"fighter"]));
	 reset();
}

void init()
{
   if( this_player() ) this_player()->set_explore("noden#32");
}
