// File: /d/noden/tamumu/cave2.c
// Generated by Roommaker Mon Dec  4 19:42:09 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
這裡是一個天然的洞穴，也許該說是半天然的，巖壁上並沒有任何斧鑿的痕跡
或人工的修飾，但是在你面前的是一道石階，通往西邊。石階旁有一個石刻的奇特
雕像(statue)，看起來似乎是這裡唯一的光源。
LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"east" : "/d/noden/tamumu/cave1", 
		"west" : "/d/noden/tamumu/cave3" ]) );
	ob->set( "item_desc", ([ 
		"statue" : @LONG_TEXT
這個雕像有著人類的頭顱、獅子的身體、和一雙蝙蝠般的翅膀，它的前爪捧
著一個球形的容器，容器裡盛滿了黃色膏狀的東西，一根燈心正在容器中央
燃燒著，發出微弱的光芒。
LONG_TEXT
 ]) );
	ob->set( "objects", ([ 
		"tamumu#1" : "/d/noden/tamumu/monster/warrior", 
		"tamumu#2" : "/d/noden/tamumu/monster/warrior" ]) );
	ob->reset();
}
