// File: /d/noden/tamumu/cave5.c
// Generated by Roommaker Mon Dec  4 19:43:16 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("石室");
	ob->set_long( @LONG_DESCRIPTION
你來到一間不算太寬大的石室之中，一些石制的日用品和竹簍(basket)是這
裡唯一的擺設，南邊的一個架子上整齊地陳列著一堆....骷髏頭(skulls)！看起
來你現在所在的地方並不是很安全，最好小心一點，以免成為它們的一份子。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"north" : "/d/noden/tamumu/altar" ]) );
	ob->set( "item_desc", ([ 
		"skulls" : @LONG_TEXT
哇....二、三十個白森森的骷髏頭排在一起，有些骷髏頭上面還用刀子刻著
數字(numbers)，不知道是什麼意思？
LONG_TEXT
, 
		"basket" : @LONG_TEXT
這些竹簍大小不一，有的是圓的，有的是方的，有的背後還有用來揹負的
揹帶或繩索，不知道裡面裝了些什麼東西？
LONG_TEXT
, 
		"numbers" : @LONG_TEXT
一、二、三......二十三、二十四，總共二十四個骷髏頭，上面標示著從一
到二十四的數字。
LONG_TEXT
 ]) );
	ob->reset();
}
