// File: /d/noden/tamumu/cave7.c
// Generated by Roommaker Mon Dec  4 19:44:11 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
你進入了一個狹窄的通道，左右兩旁的石壁給人一種不尋常的壓迫感，你的
頭頂不時傳來一陣陣蝙蝠的吱吱叫聲，地上不知道為什麼溼漉漉的一片，還長著
許多不知名的青苔，你必須很小心地前進以免滑倒。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"west" : "/d/noden/tamumu/cave8", 
		"southeast" : "/d/noden/tamumu/cave6" ]) );
	ob->reset();
}
