// File: /d/noden/tamumu/cave4.c
// Generated by Roommaker Mon Dec  4 19:42:51 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("階梯");
	ob->set_long( @LONG_DESCRIPTION
你現在走上一個洞穴中的階梯，上方的巖壁低得幾乎要碰到你的頭。你發現
西邊不遠處有一個巨大的洞穴，洞穴的入口處站著兩座石雕(statue)，看起來這
裡是塔姆姆人的祭壇，建造階梯的人故意將上方的巖壁留下，使得進入祭壇的人
都必須彎著身子。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/tamumu/cave3", 
		"west" : "/d/noden/tamumu/altar" ]) );
	ob->set( "item_desc", ([ 
		"statue" : @LONG_TEXT
這兩座雕像都是人的頭顱、獅子的身體、以及一對蝙蝠般的翅膀，左邊的雕像
腳底下踩著一隻蟒蛇，右邊的雕像腳底下踩著一隻蜘蛛，看起來有說不出的詭
異。
LONG_TEXT
 ]) );
	ob->reset();
}
