// File: /d/noden/tamumu/cave1.c
// Generated by Roommaker Mon Dec  4 19:41:46 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("洞穴");
	ob->set_long( @LONG_DESCRIPTION
你進入了一個奇異的洞穴，洞穴西邊的出口被一片水幕遮住，水花濺得這裡
的地面上積了許多水窪。由於潮溼的水氣，巖壁上生滿了厚厚的青苔，洞穴往西
似乎隱隱有著火光，什麼樣的生物會居住在這個隱密的洞穴中呢？
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/11,5.noden", 
		"west" : "/d/noden/tamumu/cave2" ]) );
	ob->reset();
}
