// File: /d/noden/tamumu/cave3.c
// Generated by Roommaker Mon Dec  4 19:42:29 1995

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("階梯");
	ob->set_long( @LONG_DESCRIPTION
你現在走上一個洞穴中的階梯，你的頭幾乎要撞到上方的巖壁，不知道建造
這到階梯的人為什麼不把上方的巖壁挖高一點，你隱約聞到一骨刺鼻的燒焦味從
西邊傳來，東邊走下階梯的地方似乎有亮光。
LONG_DESCRIPTION
	);

	ob->set( "exits", ([ 
		"east" : "/d/noden/tamumu/cave2", 
		"west" : "/d/noden/tamumu/cave4" ]) );
	ob->reset();
}
