// File: /d/noden/tamumu/altar.c
// Generated by Roommaker Wed Dec 15 10:58:47 1993

#include <mudlib.h>

inherit ROOM;

void create()
{
	::create();
	set_short("塔姆姆祭壇");
	set_long( @C_LONG_DESCRIPTION
你來到一個巨大的洞穴之中，洞穴頂端不知道有什麼東西盤踞著，你只聽到
一陣陣「嗤....嗤....」的聲音從上面傳來。在你面前是一尊人形石雕(statue)
旁邊圍繞著數根黑色的石柱(pillar)，石雕前有一個血跡斑斑的平臺(plate)，
看起來塔姆姆人一定是有用活人獻祭的習慣，你最好趁他們還沒有找上你之前離
開這裡....。
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "item_desc", ([ 
		"symbols" : @LONG_TEXT
這些符號大多扭曲變形，難以辨認，不過你大約可以看出上面有代表獅子、
老鷹、蜘蛛三種生物的圖形。
LONG_TEXT
, 
		"statue" : @LONG_TEXT
這個石雕足足有三、四個人高，和前面所見到的雕像恰好相反，這座雕像有著
獅子的頭顱和人類的身體，同樣的一對蝙蝠般翅膀緊貼在石雕背後，石雕的右
手指向洞穴頂端，左手指著地上的平臺，你突然有股衝動想順著石雕的手臂(
arm)爬上洞穴頂端一探究竟。
LONG_TEXT
, 
		"pillar" : @LONG_TEXT
這些石柱或高或矮，但是清一色都黑得發亮，上面刻滿了各種詭異的符號(
symbols)與紋路。
LONG_TEXT
, 
		"plate" : @LONG_TEXT
這個平臺上血跡斑斑，連旁邊的泥土都沾著不少凝結的血塊，你懷疑這個
平臺上殺過多少個犧牲者？
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"south" : "/d/noden/tamumu/cave5", 
		"north" : "/d/noden/tamumu/cave6", 
		"east" : "/d/noden/tamumu/cave4" ]) );
	set( "objects", ([ 
		"monk#1" : "/d/noden/tamumu/monster/monk", 
		"monk#2" : "/d/noden/tamumu/monster/monk", 
		"chieftain" : "/d/noden/tamumu/monster/chieftain" ]) );
	reset();
}

void init()
{
   if( this_player() ) this_player()->set_explore("noden#13");
}
