// File: /d/noden/tamumu/cave9.c
// Generated by Roommaker Wed Dec 15 07:15:48 1993

#include <mudlib.h>

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
	set_short("洞穴盡頭");
	set_long( @C_LONG_DESCRIPTION
這裡是這個洞穴的盡頭，一張石制的桌子(table)的中央，旁邊的地上堆著
幾條鐵鏈(chain)，腐臭的味道來自你的北邊，往東是一條陰暗狹窄的通道，你
似乎聽到有人在說話，但是不知道聲音從哪裡來。
C_LONG_DESCRIPTION
	);

	set( "light", 1 );
	set( "item_desc", ([ 
		"table" : "桌上有一盞小小的油燈，正發出微弱的光線，照亮這個洞穴\n", 
		"chain" : @LONG_TEXT
這些鐵鏈上沾滿血跡，已經分辨不出它們原來是什麼樣子，光是想像這些
鐵鏈的用途就令你不寒而慄。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"north" : "/d/noden/tamumu/jail1", 
		"east" : "/d/noden/tamumu/cave8" ]) );
	set( "objects", ([
		"jailor": "/d/noden/tamumu/monster/jailor" ]) );
	create_door( "north", "south", ([
		"keyword" : ({"door", "iron door"}),
		"name" : "iron door",
		"c_name" : "鐵門",
		"c_desc" : "一扇厚實的鐵門，上面有一道凹槽",
		"status" : "locked",
		"lock" : "TAMUMU_JAIL1"
	]) );
	reset();
}
