// File: /d/noden/tamumu/cave8.c
// Generated by Roommaker Wed Dec 15 07:38:41 1993

#include <mudlib.h>

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
	set_short("洞穴");
	set_long( @C_LONG_DESCRIPTION
這裡的空氣不但潮溼，而且還隱隱夾雜著一股臭味，這使你想起遠風鎮老鐵匠
店裡的地下室，不過味道有點不同....這裡的味道好像是屍體腐敗的味道，你連呼
吸都不敢太用力，以免被這種可怕的味道嗆昏。東邊的空氣似乎比較新鮮，西邊隱
約有一些亮光。
C_LONG_DESCRIPTION
	);

	set( "exits", ([ 
		"north" : "/d/noden/tamumu/jail2", 
		"west" : "/d/noden/tamumu/cave9", 
		"east" : "/d/noden/tamumu/cave7" ]) );
	create_door( "north", "south", ([
		"keyword" : ({"door", "iron door"}),
		"name" : "iron door",
		"c_name" : "鐵門",
		"c_desc" : "一扇厚實的鐵門，上面有一道凹槽",
		"status" : "locked",
		"lock" : "TAMUMU_JAIL1"
	]) );
	reset();
}
