// File: /d/noden/tamumu/jail2.c
// Generated by Roommaker Wed Dec 15 07:48:08 1993

#include <mudlib.h>

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
	set_short("監牢");
	set_long( @C_LONG_DESCRIPTION
這裡是一間狹小的監牢，在你的頭頂正上方有一個洞穴，但是你夠不著，地
上鋪著一些稻草或是某種曬乾的植物，一些白骨(bones)和破碎的衣服(clothes)
散佈在四周，這個地方看起來很久沒有「人類」住過了，雖然好像有某種怪物居
住在這裡....。
C_LONG_DESCRIPTION
	);

	set( "item_desc", ([ 
		"clothes" : @LONG_TEXT
這些衣服碎片上面滿是血跡，它原來的主人一定是遭到了不幸——被某種怪物
活活撕裂了....。
LONG_TEXT
, 
		"bones" : "這些白骨看起來年代已經非常久遠，上面還有著不少齒痕。\n" ]) );
	set( "exits", ([ 
		"south" : "/d/noden/tamumu/cave8" ]) );
	create_door( "south", "north", ([
		"keyword" : ({"door", "iron door"}),
		"name" : "iron door",
		"c_name" : "鐵門",
		"c_desc" : "一扇厚實的鐵門，上面有一道凹槽",
		"status" : "locked",
		"lock" : "TAMUMU_JAIL1"
	]) );
	set( "objects", ([
		"flesheater": "/d/noden/tamumu/monster/flesheater" ]) );
	reset();
}

void init()
{
   if( this_player() ) this_player()->set_explore("noden#14");
}
