// File: /d/noden/tamumu/jail1.c
// Generated by Roommaker Wed Dec 15 07:38:07 1993

#include <mudlib.h>

inherit DOORS;
inherit ROOM;

void create()
{
	::create();
	set_short("監牢");
	set_long( @C_LONG_DESCRIPTION
你現在進入了一間臭到極點的監牢，到底有多臭你也說不上來，因為你的手
正不自覺地捂著鼻子，地上有幾具還沒有腐敗完的屍體(corpses)和許多白森森的
骨頭(bones)，監牢的角落裡有一張釘在牆壁上的木板床(bed)。
C_LONG_DESCRIPTION
	);

	set( "item_desc", ([ 
		"scroll" : @LONG_TEXT
羊皮紙上的字跡已經被....腐敗屍體上的殘渣蓋住了，你只能隱約地辨認出
幾個字:
    ....塗上油....獻祭....回答正確的數字....永生....疾病....
LONG_TEXT
, 
		"bed" : @LONG_TEXT
這張木板床已經腐朽得不能睡了，上面蛀蟲的孔洞和蜂窩差不多，你發現木板
床底下有幾個罐子(pots)還是完整的。
LONG_TEXT
, 
		"bones" : @LONG_TEXT
一堆零零散散的骨頭，雖然看不出是什麼生物所留下來的，但是根據你的直覺
判斷，有 99% 的機會是人類的骨頭。
LONG_TEXT
, 
		"pots" : @LONG_TEXT
這些罐子裡面裝滿了一些黏稠的液體，其中有一個罐子是空的，不過罐子裡
還殘留著一些相同的液體，你懷疑這些東西是從前的囚犯留下來的，不過這種液
體有一種香味，到像是祭典儀式中塗在犧牲身上的香油。
LONG_TEXT
, 
		"corpses" : @LONG_TEXT
惡....這大概就是臭味的來源吧，為了避免你不必要的不愉快，這具屍體的
模樣就不必描述了....慢著，你發現屍體的手中握著一張羊皮紙(scroll)。
LONG_TEXT
 ]) );
	set( "exits", ([ 
		"south" : "/d/noden/tamumu/cave9" ]) );
	set( "objects", ([
		"prisoner#1": "/d/noden/tamumu/monster/prisoner",
		"prisoner#2": "/d/noden/tamumu/monster/prisoner",
		"prisoner#3": "/d/noden/tamumu/monster/prisoner" ]) );
	create_door( "south", "north", ([
		"keyword" : ({"door", "iron door"}),
		"name" : "iron door",
		"c_name" : "鐵門",
		"c_desc" : "一扇厚實的鐵門，上面有一道凹槽",
		"status" : "locked",
		"lock" : "TAMUMU_JAIL1"
	]) );
	reset();
}
